// @ts-nocheck
// Ported from Titan Zero extension (portable-core): titan-workforce/learning/improvement-proposal-runtime.mjs
const clean=(v,max=240)=>String(v??'').trim().slice(0,max);
const list=v=>Array.isArray(v)?v:[];
const validCompany=v=>/^[A-Za-z0-9._:-]{2,128}$/.test(clean(v,128));
const clamp=(v,min=0,max=1)=>Math.max(min,Math.min(max,Number(v)||0));
const uniq=v=>[...new Set(list(v).map(x=>clean(typeof x==='string'?x:x?.id||x?.ref,300)).filter(Boolean))];
function evidenceForWorker(performance,worker_id){return list(performance?.records).filter(r=>r?.worker_id===worker_id).flatMap(r=>list(r.evidence_refs)).filter(Boolean);}
function proposal({company_id,kind,target_type,target_id,title,rationale,evidence_refs=[],confidence=0.5,priority='MEDIUM',source_refs=[]}){return {schema:'titan.workforce.improvement-proposal.v1',proposal_id:`improve:${kind.toLowerCase()}:${target_type}:${target_id}`,company_id,kind,target_type,target_id,title,rationale,evidence_refs:uniq(evidence_refs),source_refs:uniq(source_refs),confidence:Number(clamp(confidence).toFixed(4)),priority,proposal_state:'PROPOSED',requires_human_or_governed_review:true,requires_governed_proposal:true,proposal_only:true,automatic_retraining:false,automatic_production_change:false,automatic_workflow_change:false,automatic_staffing_change:false,authority_granted:false,execution_permitted:false,grants_authority:false,authority_effect:false};}
export function buildImprovementProposalSnapshot(input={},graph={},performance={},capacity={},skills={},staffing={}){
  const company_id=clean(input.company_id||graph?.company_id,128);if(!validCompany(company_id))throw new Error('improvement-company_id-required');
  if(graph?.schema!=='titan.workforce.graph.v1'||graph.company_id!==company_id)throw new Error('improvement-workforce-graph-required');
  for(const [name,snapshot,schema] of [['performance',performance,'titan.workforce.performance-outcome-evidence.v1'],['capacity',capacity,'titan.workforce.workload-capacity.v1'],['skills',skills,'titan.workforce.skill-capability-registry.v1'],['staffing',staffing,'titan.workforce.dynamic-staffing.v1']]){if(snapshot&&Object.keys(snapshot).length&&(snapshot.company_id!==company_id||snapshot.schema!==schema))throw new Error(`improvement-${name}-snapshot-invalid`);}
  const proposals=[];
  for(const w of list(performance?.worker_performance)){
    if(!w?.worker_id)continue;const ev=evidenceForWorker(performance,w.worker_id);const confidence=Number(w.confidence||0);
    if(Number(w.correction_count||0)>0)proposals.push(proposal({company_id,kind:'QUALITY_COACHING_REVIEW',target_type:'worker',target_id:w.worker_id,title:'Review recurring corrections and quality evidence',rationale:`${w.correction_count} correction/rework events are present in evidenced outcomes.`,evidence_refs:ev,confidence,priority:Number(w.correction_count)>=3?'HIGH':'MEDIUM',source_refs:['performance_outcome_evidence']}));
    if(w.quality_score!=null&&Number(w.quality_score)<0.75&&confidence>0)proposals.push(proposal({company_id,kind:'QUALITY_IMPROVEMENT_REVIEW',target_type:'worker',target_id:w.worker_id,title:'Review quality improvement opportunity',rationale:`Evidence-backed quality score ${Number(w.quality_score).toFixed(2)} is below the review threshold.`,evidence_refs:ev,confidence,priority:'MEDIUM',source_refs:['performance_outcome_evidence']}));
    if(w.on_time_rate!=null&&Number(w.on_time_rate)<0.8&&confidence>0)proposals.push(proposal({company_id,kind:'TIMELINESS_IMPROVEMENT_REVIEW',target_type:'worker',target_id:w.worker_id,title:'Review timeliness pattern',rationale:`Evidence-backed on-time rate ${Number(w.on_time_rate).toFixed(2)} is below the review threshold.`,evidence_refs:ev,confidence,priority:'MEDIUM',source_refs:['performance_outcome_evidence']}));
  }
  for(const r of list(skills?.requirements)){
    const eligible=list(r.eligible_worker_ids);if(Number(r.required_count||1)>eligible.length)proposals.push(proposal({company_id,kind:'CAPABILITY_DEVELOPMENT_REVIEW',target_type:'capability',target_id:clean(r.capability_id),title:'Review capability development or sourcing need',rationale:`Verified eligible coverage ${eligible.length} is below required coverage ${Number(r.required_count||1)}.`,evidence_refs:list(r.evidence_refs),confidence:eligible.length?0.75:0.9,priority:eligible.length?'MEDIUM':'HIGH',source_refs:['skill_capability_registry']}));
  }
  for(const w of list(capacity?.worker_capacity))if(w?.state==='OVERLOADED')proposals.push(proposal({company_id,kind:'WORKLOAD_REBALANCE_REVIEW',target_type:'worker',target_id:clean(w.worker_id),title:'Review workload rebalancing',rationale:`Worker utilization is ${Number(w.utilization||0).toFixed(2)} with ${Number(w.available_units||0).toFixed(2)} available units.`,confidence:0.9,priority:'HIGH',source_refs:['workload_capacity','dynamic_staffing']}));
  for(const g of list(staffing?.gaps))proposals.push(proposal({company_id,kind:'STAFFING_GAP_REVIEW',target_type:g.mission_team_id?'mission_team':'assignment',target_id:clean(g.mission_team_id||g.assignment_id||'unfilled'),title:'Review unresolved staffing gap',rationale:clean(g.reason||'No eligible staffing candidate is currently available.',500),confidence:0.9,priority:'HIGH',source_refs:['dynamic_staffing']}));
  const priorityRank={HIGH:3,MEDIUM:2,LOW:1};const deduped=[...new Map(proposals.map(p=>[p.proposal_id,p])).values()].sort((a,b)=>(priorityRank[b.priority]||0)-(priorityRank[a.priority]||0)||b.confidence-a.confidence||a.proposal_id.localeCompare(b.proposal_id));
  return {schema:'titan.workforce.improvement-proposals.v1',company_id,graph_revision:Number(graph.projection_revision||0),graph_cursor:graph.projection_cursor||null,proposals:deduped,summary:{proposal_count:deduped.length,high_priority:deduped.filter(p=>p.priority==='HIGH').length,quality_reviews:deduped.filter(p=>p.kind.includes('QUALITY')).length,capability_reviews:deduped.filter(p=>p.kind==='CAPABILITY_DEVELOPMENT_REVIEW').length,workload_reviews:deduped.filter(p=>p.kind==='WORKLOAD_REBALANCE_REVIEW').length,staffing_gap_reviews:deduped.filter(p=>p.kind==='STAFFING_GAP_REVIEW').length},learning_is_proposal_only:true,no_silent_retraining:true,no_silent_production_change:true,no_authority_expansion:true,authority_granted:false,execution_permitted:false,grants_authority:false,authority_effect:false,updated_at:Date.now()};
}
export function summarizeImprovementProposals(s={}){return {company_id:s.company_id,proposal_count:s.summary?.proposal_count||0,high_priority:s.summary?.high_priority||0,quality_reviews:s.summary?.quality_reviews||0,capability_reviews:s.summary?.capability_reviews||0,workload_reviews:s.summary?.workload_reviews||0,staffing_gap_reviews:s.summary?.staffing_gap_reviews||0,proposal_only:true,no_silent_retraining:true,grants_authority:false};}
