import { LICENSED_TRADE_SERVICE_CATALOGUE } from './catalogue.js';
import type { LicensedTradeKey } from './contracts.js';

export const LICENSED_TRADES_LANGUAGE_SCHEMA='titan.zero.vertical.licensed-trades.language-projection.v1' as const;
export type LicensedTradeIntent='quote_request'|'booking_request'|'urgent_attendance'|'maintenance_reminder'|'service_question'|'job_status'|'compliance_question'|'unknown';
export interface LicensedTradeLanguageInput{company_id:string;trade:LicensedTradeKey;message:string;service_key?:string;context?:{job_ref?:string;site_ref?:string;asset_ref?:string;known_answers?:Record<string,string|number|boolean>}}
const LEGACY=new Set(['tenant_id','tenant_company_id','workspace_tenant_id','tenantId','tenantCompanyId','business_id','account_id','workspace_id']);
function rejectLegacy(v:unknown,p='input'):void{if(!v||typeof v!=='object')return;if(Array.isArray(v)){v.forEach((x,i)=>rejectLegacy(x,`${p}[${i}]`));return;}for(const[k,x]of Object.entries(v as Record<string,unknown>)){if(LEGACY.has(k))throw new Error(`${p}.${k} is a legacy tenant boundary; company_id is required`);rejectLegacy(x,`${p}.${k}`);}}
function req(v:unknown,n:string){const x=String(v??'').trim();if(!x)throw new Error(`${n} is required`);return x;}
function opt(v:unknown){const x=String(v??'').trim();return x||null;}
function norm(v:unknown){return String(v??'').toLowerCase().replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();}
function serviceFor(trade:LicensedTradeKey,key?:string){if(!key)return null;const s=LICENSED_TRADE_SERVICE_CATALOGUE.find(x=>x.service_key===key);if(!s)throw new Error(`unknown licensed-trade service: ${key}`);if(s.trade!==trade)throw new Error(`service ${key} does not belong to trade ${trade}`);return s;}
function detect(text:string):LicensedTradeIntent{const t=norm(text);if(['urgent','emergency','need someone now','no power','water loss'].some(x=>t.includes(x)))return'urgent_attendance';if(['remind','next maintenance','next service','due'].some(x=>t.includes(x)))return'maintenance_reminder';if(['quote','price','cost','how much','estimate'].some(x=>t.includes(x)))return'quote_request';if(['book','booking','appointment','schedule'].some(x=>t.includes(x)))return'booking_request';if(['safe','compliant','compliance','certificate'].some(x=>t.includes(x)))return'compliance_question';if(['job','status','technician','worker'].some(x=>t.includes(x)))return'job_status';if(['include','service','what is included'].some(x=>t.includes(x)))return'service_question';return'unknown';}
function tradeLabel(t:LicensedTradeKey){return t==='hvac'?'HVAC':t==='electrical'?'Electrical':'Plumbing';}
export function buildLicensedTradeLanguageProjection(input:LicensedTradeLanguageInput){
 rejectLegacy(input);const company_id=req(input.company_id,'company_id');const message=req(input.message,'message');const service=serviceFor(input.trade,input.service_key);const intent=detect(message);const known=input.context?.known_answers??{};
 const q:{key:string;question:string;reason:string}[]=[];const add=(key:string,question:string,reason:string)=>{if(known[key]==null||known[key]==='')q.push({key,question,reason});};
 if(intent==='quote_request'||intent==='booking_request'){
  add('site_type','What type of site or property is this?','scope');
  add('asset_context','Which fixture, circuit, switchboard, HVAC unit or other asset is involved?','asset_context');
  add('scope','What work or outcome is being requested?','scope');
  if(service?.configured_policy_reference_required)add('configured_policy_reference','Which configured company policy or jurisdiction reference applies?','policy_gate');
  if(service?.qualification_tags.length)add('qualification_scope','Which configured qualification scope must the shared assignment owner verify?','qualification_gate');
 }
 const title=`${tradeLabel(input.trade)}${service?` — ${service.name}`:''}`;
 return Object.freeze({schema:LICENSED_TRADES_LANGUAGE_SCHEMA,company_id,trade:input.trade,service_key:service?.service_key??null,normalized_message:norm(message),intent,intent_is_hint:true,quote_questions:Object.freeze(q.map(x=>Object.freeze(x))),customer_summary:Object.freeze({title,intent,next_step:intent==='quote_request'?'Prepare quote inputs':intent==='urgent_attendance'?'Prepare governed attendance handoff':intent==='maintenance_reminder'?'Review maintenance reminder/rebooking context':'Clarify or route request'}),titan_go_summary:Object.freeze({job_ref:opt(input.context?.job_ref),site_ref:opt(input.context?.site_ref),asset_ref:opt(input.context?.asset_ref),trade:input.trade,service_key:service?.service_key??null,qualification_tags:Object.freeze([...(service?.qualification_tags??[])]),expected_evidence:Object.freeze([...(service?.evidence_requirements??[])]),assignment_authoritative:false,completion_authoritative:false}),owners:Object.freeze({chatbot:'shared_agent_shell_and_intent_owner',quote:'shared_quote_agent_owner',sales:'shared_sales_agent_owner',dispatch:'shared_workforce_assignment_owner',booking:'shared_booking_owner',jobs:'shared_jobs_owner',recurrence:'shared_recurrence_rebooking_owner'}),generic_classifier_replaced:false,agent_shell_replaced:false,quote_mutation_emitted:false,booking_mutation_emitted:false,dispatch_mutation_emitted:false,sales_mutation_emitted:false,customer_message_sent:false,reminder_sent:false,dispatch_permitted:false,safety_claim_authoritative:false,compliance_claim_authoritative:false,proposal_only:true,grants_authority:false,execution_permitted:false,requires_fresh_authority_evaluation:true});
}
