// @ts-nocheck
// Ported from Titan Zero extension (browser-adapter-required): cleaning-marketplace-renewal.js
// QUARANTINE: not exported to standalone runtime until browser/DOM dependencies are adapted.
(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const STORE='titanCleaningMarketplaceRenewalV1';let config={thresholds:{renewal_attention_days:60,urgent_notice_days:14}},company_id='company-default',state={items:{}},items=[],filter='all';
const key=i=>`${i.kind}:${i.id}`,daysBetween=(a,b)=>Math.ceil((b-a)/86400000),parseDate=v=>v?new Date(`${v}T00:00:00`):null;
async function company(){const x=await chrome.storage.local.get(['titanBusinessProfile']);return String(x.titanBusinessProfile?.company_id||$('grant-company')?.value||'company-default').trim()||'company-default'}
async function load(){company_id=await company();const x=await chrome.storage.local.get([STORE]);state=(x[STORE]||{})[company_id]||{company_id,items:{}};state.company_id=company_id;state.items=state.items||{};items=window.TitanCleaningMarketplaceValue?.getItems?.()||[];}
async function save(){const x=await chrome.storage.local.get([STORE]),root=x[STORE]||{};root[company_id]=state;await chrome.storage.local.set({[STORE]:root});window.dispatchEvent(new CustomEvent('titan-cleaning-marketplace-renewal-changed',{detail:{company_id,grants_authority:false}}));}
function entry(i){return state.items[key(i)]||{}}
function evaluate(i,e=entry(i),now=new Date()){
 const renewal=parseDate(e.renewal_date),end=parseDate(e.contract_end_date),notice=Number.isFinite(Number(e.cancellation_notice_days))?Math.max(0,Number(e.cancellation_notice_days)):null;
 const renewalDays=renewal?daysBetween(now,renewal):null,endDays=end?daysBetween(now,end):null,attention=config.thresholds.renewal_attention_days||60,urgent=config.thresholds.urgent_notice_days||14;
 const cancellationDeadline=renewal&&notice!==null?new Date(renewal.getTime()-notice*86400000):null,deadlineDays=cancellationDeadline?daysBetween(now,cancellationDeadline):null;
 const dueSoon=renewalDays!==null&&renewalDays<=attention,deadlineUrgent=deadlineDays!==null&&deadlineDays<=urgent;
 const hasEvidence=i.uses!==null||i.evidence!==null||i.net!==null,weak=i.unused_spend||i.low_adoption||(i.net!==null&&i.net<0),proven=!!i.proven_value,candidate=String(e.replacement_candidate||'').trim(),risk=String(e.migration_risk||'unknown');
 let recommendation='evidence_needed',reason='Record renewal/contract terms and adoption/value evidence before making a renewal decision.';
 if(proven&&!weak){recommendation='keep';reason=dueSoon?'Recorded evidence supports keeping this component; confirm renewal terms before the deadline.':'Recorded adoption and positive net value support keeping this component.'}
 if(dueSoon&&!proven){recommendation='review_renewal';reason=hasEvidence?'Renewal is approaching and current recorded evidence does not establish proven value.':'Renewal is approaching but adoption/value evidence is incomplete.'}
 if(weak&&candidate){recommendation=risk==='high'?'plan_migration':'consider_replacement';reason=risk==='high'?'Current evidence warrants review and a replacement candidate is recorded, but migration risk is high; plan and validate migration before any change.':'Current evidence warrants review and a replacement candidate is recorded; compare fit and migration requirements before deciding.'}
 else if(weak&&dueSoon){recommendation='review_renewal';reason='Renewal is approaching and current evidence shows unused spend, low adoption or negative recorded value.'}
 if(deadlineUrgent&&recommendation==='evidence_needed'){recommendation='review_renewal';reason='The recorded cancellation-notice deadline is close; review the contract and evidence now.'}
 return{recommendation,reason,renewal_days:renewalDays,contract_end_days:endDays,cancellation_deadline:cancellationDeadline?cancellationDeadline.toISOString().slice(0,10):null,cancellation_deadline_days:deadlineDays,due_soon:dueSoon,deadline_urgent:deadlineUrgent,replacement_candidate:candidate||null,migration_risk:risk,grants_authority:false,cancels_products:false,renews_products:false,purchases_replacements:false};
}
function show(i){const d=evaluate(i);return filter==='all'||filter===d.recommendation||(filter==='urgent'&&(d.deadline_urgent||d.due_soon));}
function render(){const rows=items.map(i=>({i,d:evaluate(i)})),shown=rows.filter(x=>show(x.i));$('marketplace-renewal-count').textContent=`${shown.length} shown`;$('marketplace-renewal-summary').innerHTML=[['Active tracked',rows.length],['Renewal attention',rows.filter(x=>x.d.due_soon).length],['Urgent notice windows',rows.filter(x=>x.d.deadline_urgent).length],['Consider replacement',rows.filter(x=>['consider_replacement','plan_migration'].includes(x.d.recommendation)).length],['Evidence needed',rows.filter(x=>x.d.recommendation==='evidence_needed').length]].map(([a,b])=>`<div><span>${esc(a)}</span><strong>${b}</strong></div>`).join('');
 $('marketplace-renewal-list').innerHTML=shown.length?shown.map(({i,d})=>{const e=entry(i),k=key(i);return `<article class="supply-card marketplace-renewal-card ${d.deadline_urgent?'value-warning':''}"><div class="supply-card-head"><div><div class="module-title"><strong>${esc(i.name)}</strong><span class="pill">${esc(i.kind)}</span><span class="pill ${d.recommendation==='keep'?'verified':d.deadline_urgent?'danger':'warn'}">${esc(d.recommendation.replaceAll('_',' '))}</span></div><div class="meta"><span>${esc(i.category)}</span><span>${esc(d.reason)}</span></div></div></div><div class="economics-summary"><div><strong>${d.renewal_days===null?'—':d.renewal_days}</strong><span>days to renewal</span></div><div><strong>${d.cancellation_deadline||'Not recorded'}</strong><span>cancellation deadline</span></div><div><strong>${esc(d.migration_risk)}</strong><span>migration risk</span></div><div><strong>${esc(d.replacement_candidate||'None recorded')}</strong><span>replacement candidate</span></div></div><div class="marketplace-renewal-fields"><label>Renewal date<input type="date" data-renewal-field="${esc(k)}" data-field="renewal_date" value="${esc(e.renewal_date||'')}"></label><label>Contract end date<input type="date" data-renewal-field="${esc(k)}" data-field="contract_end_date" value="${esc(e.contract_end_date||'')}"></label><label>Cancellation notice days<input type="number" min="0" step="1" data-renewal-field="${esc(k)}" data-field="cancellation_notice_days" value="${esc(e.cancellation_notice_days??'')}"></label><label>Migration risk<select data-renewal-field="${esc(k)}" data-field="migration_risk">${(config.migration_risk_levels||['unknown','low','medium','high']).map(v=>`<option value="${esc(v)}" ${String(e.migration_risk||'unknown')===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label><label>Replacement candidate<input type="text" data-renewal-field="${esc(k)}" data-field="replacement_candidate" value="${esc(e.replacement_candidate||'')}" placeholder="Company-selected alternative"></label><label class="marketplace-renewal-notes">Contract / migration notes<textarea rows="2" data-renewal-field="${esc(k)}" data-field="notes" placeholder="Contract terms, export needs, switching constraints, owner decision notes">${esc(e.notes||'')}</textarea></label></div><div class="purchase-actions"><button class="featured" data-renewal-save="${esc(k)}">Save renewal evidence</button></div></article>`}).join(''):'<div class="empty">No active Marketplace components match this renewal view.</div>';bind();}
function bind(){document.querySelectorAll('[data-renewal-save]').forEach(b=>b.onclick=async()=>{const k=b.dataset.renewalSave,e={...(state.items[k]||{})};document.querySelectorAll(`[data-renewal-field="${CSS.escape(k)}"]`).forEach(el=>{e[el.dataset.field]=el.value===''?null:(el.type==='number'?Number(el.value):el.value)});e.updated_at=new Date().toISOString();e.source='company_input';state.items[k]=e;await save();render();});}
async function init(){try{config=await (await fetch(chrome.runtime.getURL('titan-modules/cleaning-marketplace-renewal.json'))).json();if(config.schema!=='titan-cleaning-marketplace-renewal/v1')throw new Error('Marketplace renewal config is invalid');await load();render()}catch(e){$('marketplace-renewal-notice').textContent=`Marketplace renewal tracking unavailable: ${e.message}`}}
$('marketplace-renewal-filter').addEventListener('change',e=>{filter=e.target.value;render()});window.addEventListener('titan-cleaning-marketplace-value-changed',init);window.addEventListener('titan-company-changed',init);init();
window.TitanCleaningMarketplaceRenewal={evaluate,companyId:()=>company_id,getItems:()=>items.map(i=>({...i,...evaluate(i)})),grantsAuthority:false,cancelsProducts:false,renewsProducts:false,purchasesReplacements:false};
})();
