// @ts-nocheck
// Ported from Titan Zero extension (browser-adapter-required): cleaning-marketplace-value.js
// QUARANTINE: not exported to standalone runtime until browser/DOM dependencies are adapted.
(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const STORE='titanCleaningMarketplaceValueV1',SW='titanCleaningSoftwareMarketplaceV1',WF='titanCleaningWorkforceMarketplaceV1',GR='titanCleaningGrowthMarketplaceV1';
let config={thresholds:{minimum_recent_uses_for_established_adoption:3,minimum_recent_evidence_for_proven_value:1}},software={products:[]},growth={products:[]},company_id='company-default',state={items:{}},items=[],filter='all';
const num=v=>v===''||v===null||v===undefined?null:(Number.isFinite(Number(v))?Number(v):null),key=(kind,id)=>`${kind}:${id}`;
async function company(){const x=await chrome.storage.local.get(['titanBusinessProfile']);return String(x.titanBusinessProfile?.company_id||$('grant-company')?.value||'company-default').trim()||'company-default'}
async function load(){company_id=await company();const x=await chrome.storage.local.get([STORE,SW,WF,GR]);state=(x[STORE]||{})[company_id]||{company_id,items:{}};state.company_id=company_id;state.items=state.items||{};
 const active=[];const sw=(x[SW]||{})[company_id]?.products||{};for(const p of software.products)if(sw[p.id]?.status==='using')active.push({kind:'software',id:p.id,name:p.name,category:p.category,overlap_keys:[`software-category:${p.category}`],installed_at:sw[p.id]?.updated_at||sw[p.id]?.using_at||null});
 const wf=(x[WF]||{})[company_id]?.products||{};for(const p of window.TitanCleaningWorkforceProducts?.products||[])if(['purchased','installed'].includes(wf[p.id]?.status))active.push({kind:'workforce',id:p.id,name:p.name,category:p.specialty||'cleaning specialist',overlap_keys:(p.capabilities||[]).map(v=>`capability:${v}`),installed_at:wf[p.id]?.purchased_at||null});
 const gr=(x[GR]||{})[company_id]?.products||{};for(const p of growth.products)if(['installed','purchased','included'].includes(gr[p.id]?.status))active.push({kind:'growth',id:p.id,name:p.name,category:p.category,overlap_keys:(p.provides||[]).map(v=>`capability:${v}`),installed_at:gr[p.id]?.installed_at||null});
 const counts=new Map();for(const a of active)for(const o of a.overlap_keys||[])counts.set(o,(counts.get(o)||0)+1);items=active.map(a=>({...a,potential_overlap_keys:(a.overlap_keys||[]).filter(o=>(counts.get(o)||0)>1)}));}
async function save(){const x=await chrome.storage.local.get([STORE]),root=x[STORE]||{};root[company_id]=state;await chrome.storage.local.set({[STORE]:root});window.dispatchEvent(new CustomEvent('titan-cleaning-marketplace-value-changed',{detail:{company_id}}));}
function entry(i){return state.items[key(i.kind,i.id)]||{};}
function derive(i){const e=entry(i),uses=num(e.use_count_30d),ev=num(e.evidence_count_30d),cost=num(e.monthly_recurring_cost),benefit=num(e.recorded_benefit_value_30d),net=cost!==null&&benefit!==null?benefit-cost:null,adopt=config.thresholds.minimum_recent_uses_for_established_adoption||3,evidence=config.thresholds.minimum_recent_evidence_for_proven_value||1;
 const unused=cost!==null&&cost>0&&uses===0,low=uses!==null&&uses<adopt,dup=(i.potential_overlap_keys||[]).length>0,proven=net!==null&&net>0&&uses!==null&&uses>=adopt&&ev!==null&&ev>=evidence;
 let posture='evidence needed';if(unused)posture='review unused spend';else if(dup&&low)posture='review overlap & adoption';else if(proven)posture='proven recorded value';else if(low)posture='improve adoption / review fit';else if(net!==null&&net<0)posture='review recorded value';else if(uses!==null&&uses>=adopt)posture='adopted — value evidence needed';
 return{uses,evidence:ev,cost,benefit,net,unused_spend:unused,low_adoption:low,duplication_risk:dup,proven_value:proven,posture};}
function money(v){return v===null?'Not recorded':`${state.currency||'AUD'} ${Number(v).toFixed(2)}`}
function show(i){const d=derive(i);if(filter==='all')return true;if(filter==='action')return d.unused_spend||d.low_adoption||d.duplication_risk||(d.net!==null&&d.net<0);if(filter==='unused')return d.unused_spend;if(filter==='duplicate')return d.duplication_risk;if(filter==='proven')return d.proven_value;return true;}
function render(){const rows=items.map(i=>({i,d:derive(i)})),shown=rows.filter(x=>show(x.i));$('marketplace-value-count').textContent=`${shown.length} shown`;$('marketplace-value-summary').innerHTML=[['Tracked active',rows.length],['Needs review',rows.filter(x=>x.d.unused_spend||x.d.low_adoption||x.d.duplication_risk||(x.d.net!==null&&x.d.net<0)).length],['Unused spend flags',rows.filter(x=>x.d.unused_spend).length],['Potential overlaps',rows.filter(x=>x.d.duplication_risk).length],['Proven recorded value',rows.filter(x=>x.d.proven_value).length]].map(([a,b])=>`<div><span>${esc(a)}</span><strong>${b}</strong></div>`).join('');
 $('marketplace-value-list').innerHTML=shown.length?shown.map(({i,d})=>{const e=entry(i),k=key(i.kind,i.id),bad=d.unused_spend||(d.net!==null&&d.net<0);return `<article class="supply-card marketplace-value-card ${bad?'value-warning':''}"><div class="supply-card-head"><div><div class="module-title"><strong>${esc(i.name)}</strong><span class="pill">${esc(i.kind)}</span>${d.proven_value?'<span class="pill verified">PROVEN VALUE</span>':''}${d.unused_spend?'<span class="pill danger">UNUSED SPEND</span>':''}${d.duplication_risk?'<span class="pill warn">POTENTIAL OVERLAP</span>':''}</div><div class="meta"><span>${esc(i.category)}</span><span>${esc(d.posture)}</span></div></div></div><div class="economics-summary"><div><strong>${d.uses===null?'—':d.uses}</strong><span>uses / 30d</span></div><div><strong>${d.evidence===null?'—':d.evidence}</strong><span>evidence / 30d</span></div><div><strong>${esc(money(d.cost))}</strong><span>monthly recurring cost</span></div><div><strong>${esc(money(d.net))}</strong><span>recorded net value / 30d</span></div></div>${d.duplication_risk?`<div class="economics-warning">Potential structural overlap: ${esc(i.potential_overlap_keys.map(v=>v.replace(/^software-category:|^capability:/,'')).join(', '))}. This is a review signal, not proof that either component is redundant.</div>`:''}<div class="marketplace-value-fields"><label>Uses last 30 days<input type="number" min="0" step="1" data-value-field="${esc(k)}" data-field="use_count_30d" value="${esc(e.use_count_30d??'')}"></label><label>Evidence records last 30 days<input type="number" min="0" step="1" data-value-field="${esc(k)}" data-field="evidence_count_30d" value="${esc(e.evidence_count_30d??'')}"></label><label>Monthly recurring cost<input type="number" min="0" step="0.01" data-value-field="${esc(k)}" data-field="monthly_recurring_cost" value="${esc(e.monthly_recurring_cost??'')}"></label><label>Recorded benefit value (30d)<input type="number" min="0" step="0.01" data-value-field="${esc(k)}" data-field="recorded_benefit_value_30d" value="${esc(e.recorded_benefit_value_30d??'')}"></label><label>Last used<input type="date" data-value-field="${esc(k)}" data-field="last_used_at" value="${esc(e.last_used_at||'')}"></label><label class="marketplace-value-notes">Evidence / notes<textarea rows="2" data-value-field="${esc(k)}" data-field="notes" placeholder="What outcome or evidence supports keeping this component?">${esc(e.notes||'')}</textarea></label></div><div class="purchase-actions"><button class="featured" data-value-save="${esc(k)}">Save company evidence</button></div></article>`}).join(''):'<div class="empty">No active Marketplace components match this view. Mark software as using, purchase a cleaning specialist, or install a Growth Marketplace component to begin value tracking.</div>';bind();}
function bind(){document.querySelectorAll('[data-value-save]').forEach(b=>b.onclick=async()=>{const k=b.dataset.valueSave,e={...(state.items[k]||{})};document.querySelectorAll(`[data-value-field="${CSS.escape(k)}"]`).forEach(el=>{const f=el.dataset.field;e[f]=el.value===''?null:(el.type==='number'?Number(el.value):el.value)});e.updated_at=new Date().toISOString();e.source='company_input';state.items[k]=e;await save();render();});}
async function init(){try{config=await (await fetch(chrome.runtime.getURL('titan-modules/cleaning-marketplace-value.json'))).json();software=await (await fetch(chrome.runtime.getURL('titan-modules/cleaning-software-catalog.json'))).json();growth=await (await fetch(chrome.runtime.getURL('titan-modules/cleaning-growth-marketplace.json'))).json();if(config.schema!=='titan-cleaning-marketplace-value/v1')throw new Error('Marketplace value config is invalid');await load();render()}catch(e){$('marketplace-value-notice').textContent=`Marketplace value tracking unavailable: ${e.message}`}}
$('marketplace-value-filter').addEventListener('change',e=>{filter=e.target.value;render()});window.addEventListener('titan-company-changed',init);window.addEventListener('titan-marketplace-coverage-changed',init);window.addEventListener('titan-cleaning-workforce-updated',init);init();
window.TitanCleaningMarketplaceValue={derive,companyId:()=>company_id,getItems:()=>items.map(i=>({...i,...derive(i)})),grantsAuthority:false,approvesSpend:false,cancelsProducts:false,removesWorkers:false};
})();
