// @ts-nocheck
// Ported from Titan Zero extension (browser-adapter-required): diagnostics.js
// QUARANTINE: not exported to standalone runtime until browser/DOM dependencies are adapted.
const LOG_KEY='titanDiagnosticLog';
const MAX_LOG=1000;
const q=id=>document.getElementById(id);
const now=()=>new Date().toISOString();
const safe=v=>{try{return typeof v==='string'?v:JSON.stringify(v)}catch{return String(v)}};
const retention=globalThis.TitanDiagnosticRetention;
const normalizeLog=log=>retention?.pruneDiagnosticLog?retention.pruneDiagnosticLog(log,{maxEntries:MAX_LOG}):{entries:(Array.isArray(log)?log:[]).slice(-MAX_LOG),pruned:Math.max(0,(Array.isArray(log)?log.length:0)-MAX_LOG),maxEntries:MAX_LOG};
async function getLog(){const d=await chrome.storage.local.get([LOG_KEY]);return [...normalizeLog(d[LOG_KEY]).entries]}
async function addLog(level,source,message,detail={}){const current=await getLog();const entry={ts:now(),level,source,message,correlation_id:detail?.correlation_id||null,operation_id:detail?.operation_id||null,detail};const state=retention?.appendDiagnosticEntry?retention.appendDiagnosticEntry(current,entry,{maxEntries:MAX_LOG}):normalizeLog([...current,entry]);await chrome.storage.local.set({[LOG_KEY]:[...state.entries]});renderLog()}
function card(label,value,state='ok'){return `<div class="card"><span>${label}</span><strong class="${state}">${String(value)}</strong></div>`}
async function runtimeSnapshot(){
 const out={runtime:'available',manifest:chrome.runtime.getManifest().version,storage:!!chrome.storage?.local,permissions:'unknown',origins:'unknown',activeTab:'unknown',sidePanel:!!chrome.sidePanel};
 try{const p=await chrome.permissions.getAll();out.permissions=(p.permissions||[]).join(', ')||'none';out.origins=(p.origins||[]).join(', ')||'none'}catch(e){out.permissions='error: '+e.message}
 try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});out.activeTab=tab?`${tab.title||'(untitled)'} — ${tab.url||''}`:'none'}catch(e){out.activeTab='error: '+e.message}
 return out;
}

async function moduleSnapshot(){
 try{const r=await chrome.runtime.sendMessage({type:'TITAN_MODULES',action:'getDiagnostics'});return r?.ok===false?{ok:false,error:r.error}:r||{ok:false,error:'no response'}}catch(e){return {ok:false,error:e.message}}
}
async function observabilitySnapshot(){
 try{const [snapshot,recent]=await Promise.all([chrome.runtime.sendMessage({type:'TITAN_OBSERVABILITY',action:'snapshot'}),chrome.runtime.sendMessage({type:'TITAN_OBSERVABILITY',action:'recent',query:{limit:25}})]);return {snapshot:snapshot?.observability||null,recent:recent?.recent||null,error:snapshot?.ok===false?snapshot.error:null}}catch(e){return {snapshot:null,recent:null,error:e.message}}
}
async function renderObservability(){const o=await observabilitySnapshot();const s=o.snapshot||{};const components=s.components||{};q('observability-grid').innerHTML=[card('Status',o.error||s.status||'unavailable',o.error||s.status==='degraded'?'warn':'ok'),card('Company',s.company_id||'not bound',s.company_id?'ok':'warn'),card('Collectors',s.collectorCount??0),card('Persistent events',o.recent?.count??0),card('Errors observed',s.severityCounts?.error??0,(s.severityCounts?.error||0)>0?'warn':'ok'),...Object.entries(components).map(([name,value])=>card(name,value?.error||safe(value),value?.ok===false?'warn':'ok'))].join('');q('observability-events').textContent=(o.recent?.events||[]).map(e=>`[${new Date(e.observed_at).toISOString()}] ${String(e.severity||'info').toUpperCase()} ${e.component} ${e.event_type}${e.correlation_id?` · correlation ${e.correlation_id}`:''}${e.operation_id?` · operation ${e.operation_id}`:''}`).join('\n')||'No persistent observability events recorded for the active company.';return o}
async function bridgeSnapshot(){
 const s=await chrome.storage.local.get(['titanOutcomeHistory','titanSharedContext','titanZeroDemoView','titanOutcomeBridgeStatus','titanWorkFrameState','titanWorkforceRoster','titanPreferredWorker','titanServiceVertical']);
 let bg={};try{bg=await chrome.runtime.sendMessage({type:'TITAN_DIAGNOSTICS',action:'snapshot'})||{}}catch(e){bg={error:e.message}}
 return {view:s.titanZeroDemoView||'unknown',context:s.titanSharedContext?.title||'none',outcomeHistory:Array.isArray(s.titanOutcomeHistory)?s.titanOutcomeHistory.length:0,outcomeBridge:s.titanOutcomeBridgeStatus||'unknown',workFrame:s.titanWorkFrameState||'unknown',workforce:{workers:Array.isArray(s.titanWorkforceRoster)?s.titanWorkforceRoster.length:0,preferred:s.titanPreferredWorker||'auto',vertical:s.titanServiceVertical||'unknown'},background:bg};
}
async function renderHealth(){const r=await runtimeSnapshot(),b=await bridgeSnapshot(),m=await moduleSnapshot(),o=await observabilitySnapshot(),log=await getLog();const errors=log.filter(x=>x.level==='error').length,warns=log.filter(x=>x.level==='warn').length;q('error-count').textContent=errors;q('warning-count').textContent=warns;q('event-count').textContent=log.length;q('overall-health').textContent=errors?'Attention':'Healthy';q('overall-health').className=errors?'error':'ok';q('health-grid').innerHTML=[card('Extension version',r.manifest),card('Storage',r.storage?'Available':'Missing',r.storage?'ok':'error'),card('Side panel API',r.sidePanel?'Available':'Missing',r.sidePanel?'ok':'warn'),card('Background',b.background?.error?b.background.error:'Responding',b.background?.error?'error':'ok'),card('Module runtime',typeof m.error==='string'?m.error:`${m.enabled||0}/${m.total||0} enabled · ${m.blocked||0} blocked · ${Number(m.error||0)} errors · ${(m.bundles||[]).length} bundles · ${(m.contributions?.workers||0)} workers · ${(m.contributions?.verticals||0)} verticals · ${m.governance?.active||0} active grants · ${m.marketplace?.items||0} marketplace packages`,typeof m.error==='string'||Number(m.error||0)>0?'error':Number(m.blocked||0)>0?'warn':'ok'),card('Observability',o.error||o.snapshot?.status||'unavailable',o.error||o.snapshot?.status==='degraded'?'warn':'ok')].join('');q('bridge-grid').innerHTML=[card('Current view',b.view),card('Active context',b.context),card('Outcome history',b.outcomeHistory),card('Outcome bridge',safe(b.outcomeBridge),String(b.outcomeBridge).includes('fail')?'error':'ok'),card('Work frame',safe(b.workFrame)),card('Background bridge',safe(b.background)),card('Workforce',safe(b.workforce))].join('');q('runtime-grid').innerHTML=[card('Runtime',r.runtime),card('Active tab',r.activeTab),card('Permissions',r.permissions),card('Host origins',r.origins)].join('')}
async function renderLog(){const log=await getLog();const filter=q('log-filter')?.value||'all';const filtered=filter==='all'?log:log.filter(x=>x.level===filter);q('event-log').textContent=filtered.slice().reverse().map(e=>`[${e.ts}] ${e.level.toUpperCase()} ${e.source}: ${e.message}${e.detail&&Object.keys(e.detail).length?`\n  ${safe(e.detail)}`:''}`).join('\n\n')||'No diagnostic events recorded.';q('event-count').textContent=log.length;q('error-count').textContent=log.filter(x=>x.level==='error').length;q('warning-count').textContent=log.filter(x=>x.level==='warn').length}
async function runSelfTest(){const results=[];const test=async(name,fn)=>{try{const v=await fn();results.push([name,'PASS',safe(v??'OK'),'ok'])}catch(e){results.push([name,'FAIL',e.message,'error']);await addLog('error','selftest',name,{message:e.message,stack:e.stack})}};
 await test('Runtime manifest',()=>chrome.runtime.getManifest().version);
 await test('Storage write/read',async()=>{const k='titanDiagSelfTest';await chrome.storage.local.set({[k]:Date.now()});const d=await chrome.storage.local.get([k]);if(!d[k])throw Error('readback failed');await chrome.storage.local.remove([k]);return 'round-trip OK'});
 await test('Permissions',async()=>{const p=await chrome.permissions.getAll();return `${(p.permissions||[]).length} permissions`});
 await test('Active tab',async()=>{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab)throw Error('no active tab');return tab.url||tab.title||'available'});
 await test('Background messaging',async()=>{const r=await chrome.runtime.sendMessage({type:'TITAN_DIAGNOSTICS',action:'ping'});if(!r?.ok)throw Error(r?.error||'no response');return r});
 await test('Outcome bridge state',async()=>{const d=await chrome.storage.local.get(['titanOutcomeHistory','titanOutcomeBridgeStatus']);return {history:(d.titanOutcomeHistory||[]).length,status:d.titanOutcomeBridgeStatus||'not yet exercised'}});
 await test('Bridge runtime snapshot',async()=>bridgeSnapshot());
 await test('Module runtime',async()=>{const m=await chrome.runtime.sendMessage({type:'TITAN_MODULES',action:'getDiagnostics'});if(!m||m.ok===false)throw Error(m?.error||'no module response');if(m.error)throw Error(`${m.error} module errors`);return {total:m.total,enabled:m.enabled,blocked:m.blocked,bundles:m.bundles,governance:m.governance,marketplace:m.marketplace,events:m.contributions?.events||0,contributions:m.contributions,handlers:m.handlers,checks:m.checks}});
 await test('Observability runtime',async()=>{const o=await chrome.runtime.sendMessage({type:'TITAN_OBSERVABILITY',action:'snapshot'});if(!o?.ok)throw Error(o?.error||'no observability response');return {status:o.observability?.status,company_id:o.observability?.company_id,collectors:o.observability?.collectorCount,components:o.observability?.components}});
 q('selftest-results').innerHTML=results.map(([n,s,d,c])=>`<div class="card"><span>${n}</span><strong class="${c}">${s}</strong><small>${d}</small></div>`).join('');await addLog(results.some(x=>x[1]==='FAIL')?'warn':'info','selftest','Self-test completed',{results});await renderHealth();return results}
async function copyAll(){const log=await getLog();const r=await runtimeSnapshot(),b=await bridgeSnapshot();const report={generated_at:now(),extension:chrome.runtime.getManifest(),runtime:r,bridge:b,modules:await moduleSnapshot(),observability:await observabilitySnapshot(),log};const txt=JSON.stringify(report,null,2);await navigator.clipboard.writeText(txt);q('titan-copy-all').textContent='Copied';setTimeout(()=>q('titan-copy-all').textContent='Copy All',1200);await addLog('info','diagnostics','Diagnostic report copied',{entries:log.length})}
async function exportDiagnostics(){const log=await getLog();const report={generated_at:now(),runtime:await runtimeSnapshot(),bridge:await bridgeSnapshot(),modules:await moduleSnapshot(),observability:await observabilitySnapshot(),log};const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`titan-zero-diagnostics-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);await addLog('info','diagnostics','Diagnostic JSON exported',{entries:log.length})}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===`section-${b.dataset.section}`));if(b.dataset.section==='observability')void renderObservability()});
q('titan-run-self-test').onclick=runSelfTest;q('titan-copy-all').onclick=copyAll;q('titan-export-diagnostics').onclick=exportDiagnostics;q('titan-clear-log').onclick=async()=>{await chrome.storage.local.set({[LOG_KEY]:[]});await renderHealth();await renderLog()};q('log-filter').onchange=renderLog;
window.addEventListener('error',e=>addLog('error','diagnostics-page',e.message,{filename:e.filename,line:e.lineno,column:e.colno,stack:e.error?.stack}));window.addEventListener('unhandledrejection',e=>addLog('error','diagnostics-page','Unhandled promise rejection',{reason:safe(e.reason),stack:e.reason?.stack}));
renderHealth();renderLog();renderObservability();