// @ts-nocheck
// Ported from Titan Zero extension (portable-core): titan-intelligence/core/consequence-intelligence.mjs
import {verifySemanticEvidenceSeal} from './semantic-evidence.js';
import {verifyRealityProvenanceSeal} from './reality-provenance-evidence.js';
const freeze=v=>{if(v&&typeof v==='object'&&!Object.isFrozen(v)){Object.freeze(v);for(const x of Object.values(v))freeze(x)}return v};
function stable(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(stable).join(',')}]`;return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`}
async function sha(t){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
const clamp=n=>Math.max(0,Math.min(1,Number.isFinite(Number(n))?Number(n):0));
const SEV={negligible:.1,low:.25,moderate:.5,medium:.5,high:.75,critical:1}; const REV={reversible:.15,difficult:.65,hard:.75,irreversible:1,unknown:.5};
function identity(r){return [String(r?.company_id||''),String(r?.item_id||''),String(r?.revision_id||'')]}
function sameIdentity(a,b){return identity(a).every((x,i)=>x===identity(b)[i])}
function effectScore(e){const severity=SEV[String(e.severity||'moderate').toLowerCase()]??.5,likelihood=clamp(e.likelihood??.5),irreversibility=REV[String(e.reversibility||'unknown').toLowerCase()]??.5;return clamp(severity*.62+likelihood*.23+irreversibility*.15)}
export async function assessConsequences(input={}){
 const company_id=String(input.company_id||'').trim(),item_id=String(input.item_id||'').trim(),revision_id=String(input.revision_id||'').trim(); if(!company_id)throw new Error('consequence-company-id-required');if(!item_id)throw new Error('consequence-item-id-required');if(!revision_id)throw new Error('consequence-revision-id-required');
 const anchor={company_id,item_id,revision_id}; const semantic=input.semantic_evidence||null,provenance=input.provenance_evidence||null;
 if(semantic){if(!(await verifySemanticEvidenceSeal(semantic)))throw new Error('consequence-semantic-evidence-seal-invalid');if(!sameIdentity(anchor,semantic))throw new Error('consequence-semantic-evidence-identity-mismatch')}
 if(provenance){if(!(await verifyRealityProvenanceSeal(provenance)))throw new Error('consequence-provenance-evidence-seal-invalid');if(!sameIdentity(anchor,provenance))throw new Error('consequence-provenance-evidence-identity-mismatch')}
 const effects=(input.effects||[]).map((e,i)=>{const x={effect_id:e.effect_id||`effect-${i+1}`,domain:String(e.domain||'operational'),description:String(e.description||'unspecified downstream effect'),severity:String(e.severity||'moderate').toLowerCase(),likelihood:clamp(e.likelihood??.5),reversibility:String(e.reversibility||'unknown').toLowerCase(),affected_entities:[...(e.affected_entities||[])].slice(0,50),evidence_refs:[...(e.evidence_refs||[])].slice(0,50)};return {...x,consequence_score:effectScore(x)}});
 const maxScore=effects.length?Math.max(...effects.map(e=>e.consequence_score)):0; const criticalIrreversible=effects.some(e=>e.severity==='critical'&&e.reversibility==='irreversible'); const crossCompany=effects.some(e=>e.domain==='cross-company'||e.cross_company===true)||input.cross_company_effect===true;
 const provenanceUncertain=provenance?.authenticity_state==='uncertain'||(provenance&&provenance.provenance_confidence<.5); const unresolvedSemantic=Boolean(semantic?.alternatives?.length&&semantic.confidence<.6);
 let risk='low',gate='clear-for-next-intelligence-stage'; if(maxScore>=.45){risk='medium';gate='review-required'} if(maxScore>=.72){risk='high';gate='authorisation-required'} if(criticalIrreversible||crossCompany||(maxScore>=.85&&(provenanceUncertain||unresolvedSemantic))){risk='exceptional';gate='flux-consideration'}
 const payload={schema_version:1,assessment_id:input.assessment_id||crypto.randomUUID(),company_id,item_id,revision_id,proposed_state_change:structuredClone(input.proposed_state_change??input.proposed_state??null),current_state:structuredClone(input.current_state??null),effects,maximum_consequence_score:maxScore,risk_level:risk,acceptance_gate:gate,uncertainty_signals:{provenance_uncertain:provenanceUncertain,semantic_alternatives_unresolved:unresolvedSemantic},evidence_bindings:{semantic:semantic?{evidence_id:semantic.evidence_id,seal_digest:semantic.seal_digest}:null,provenance:provenance?{evidence_id:provenance.evidence_id,seal_digest:provenance.seal_digest}:null},principles:{evaluated_before_state_acceptance:true,critical_effects_not_averaged_away:true,consequence_is_forecast_not_fact:true},authority:{may_accept_state_change:false,may_approve:false,may_authorise:false,may_apply:false,next_authority:'Titan Zero processing and receiving-domain intelligence'},assessed_at:Number(input.assessed_at||Date.now())};
 const seal_digest=await sha(stable(payload));return freeze({...payload,sealed:true,seal_digest});
}
export async function verifyConsequenceSeal(r){if(!r||r.sealed!==true||!r.principles?.evaluated_before_state_acceptance)return false;const c=structuredClone(r),e=c.seal_digest;delete c.seal_digest;delete c.sealed;return e===await sha(stable(c));}
export async function assertConsequenceGateForAcceptance(r,identityInput={}){if(!(await verifyConsequenceSeal(r)))throw new Error('consequence-gate-seal-invalid');if(!sameIdentity(r,identityInput))throw new Error('consequence-gate-identity-mismatch');if(r.acceptance_gate!=='clear-for-next-intelligence-stage')throw new Error(`consequence-gate-${r.acceptance_gate}`);return true;}
