// @ts-nocheck
// Ported from Titan Zero extension (portable-core): titan-workforce/starter-agents/booking/booking-source-adapter.mjs
const text=(v,n)=>{const s=String(v??'').trim();if(!s)throw new Error(`${n}-required`);return s};
export function normalizeBookingSource(input={}){
 const company_id=text(input.company_id,'company-id'),customer_id=text(input.customer_id,'customer-id'),service_id=text(input.service_id,'service-id'),site_id=text(input.site_id,'site-id'),correlation_id=text(input.correlation_id,'correlation-id');
 if(input.quote){if(String(input.quote.company_id??company_id)!==company_id)throw new Error('cross-company-quote-denied');if(!['accepted','approved'].includes(String(input.quote.status??'').toLowerCase()))throw new Error('accepted-quote-required');return Object.freeze({schema:'titan.booking.source.v1',company_id,customer_id,service_id,site_id,correlation_id,variant:'accepted_quote',quote_id:text(input.quote.quote_id??input.quote.id,'quote-id'),price_ref:input.quote.price_ref??null,fixed_price:false,grants_authority:false});}
 const svc=input.service;if(!svc||String(svc.company_id??company_id)!==company_id)throw new Error('company-service-required');if(svc.fixed_price!==true)throw new Error('quote-or-fixed-price-service-required');if(!svc.price_ref&&!Number.isFinite(Number(svc.price)))throw new Error('fixed-price-reference-required');return Object.freeze({schema:'titan.booking.source.v1',company_id,customer_id,service_id,site_id,correlation_id,variant:'fixed_price_no_quote',quote_id:null,price_ref:svc.price_ref??{amount:Number(svc.price),currency:svc.currency??null},fixed_price:true,grants_authority:false});
}
export function bookingSourceToIntent(source,input={}){if(source?.schema!=='titan.booking.source.v1')throw new Error('booking-source-required');return Object.freeze({company_id:source.company_id,customer_id:source.customer_id,service_id:source.service_id,site_id:source.site_id,quote_id:source.quote_id,correlation_id:source.correlation_id,idempotency_key:text(input.idempotency_key,'idempotency-key'),intent_id:text(input.intent_id,'intent-id'),worker_id:input.worker_id??'booking-agent',requested_window:input.requested_window??null,source_variant:source.variant});}
