// @ts-nocheck
// Ported from Titan Zero extension (browser-adapter-required): cleaning-software-marketplace.js
// QUARANTINE: not exported to standalone runtime until browser/DOM dependencies are adapted.
(()=>{'use strict';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const STORE='titanCleaningSoftwareMarketplaceV1';let catalog={products:[],categories:[]},state={company_id:'company-default',products:{}},filters={query:'',category:'all',size:'all',preferred:false};
async function loadState(){const x=await chrome.storage.local.get(['titanBusinessProfile',STORE]);const company=String(x.titanBusinessProfile?.company_id||$('grant-company')?.value||'company-default').trim()||'company-default';const root=x[STORE]||{};state=root[company]||{company_id:company,products:{}};state.company_id=company;}
async function save(){const x=await chrome.storage.local.get([STORE]),root=x[STORE]||{};root[state.company_id]=state;await chrome.storage.local.set({[STORE]:root});}
const ps=id=>state.products[id]||{preferred:false,status:'considering',notes:''};const cat=id=>catalog.categories.find(c=>c.id===id)?.name||id;
function matches(p){const q=filters.query.toLowerCase();return(filters.category==='all'||p.category===filters.category)&&(filters.size==='all'||p.sizes.includes(filters.size))&&(!filters.preferred||ps(p.id).preferred)&&(!q||[p.name,p.vendor,p.use,cat(p.category),...(p.tags||[])].join(' ').toLowerCase().includes(q));}
function render(){const shown=catalog.products.filter(matches),saved=catalog.products.filter(p=>ps(p.id).preferred||ps(p.id).status!=='considering');$('software-result-count').textContent=`${shown.length} shown`;$('software-summary').innerHTML=[['Products',catalog.products.length],['Categories',catalog.categories.length],['Preferred',catalog.products.filter(p=>ps(p.id).preferred).length],['Using now',catalog.products.filter(p=>ps(p.id).status==='using').length],['Shortlisted',saved.length]].map(([a,b])=>`<div><span>${esc(a)}</span><strong>${b}</strong></div>`).join('');
$('software-products').innerHTML=shown.map(p=>{const s=ps(p.id);return `<article class="supply-card"><div class="supply-card-head"><div><div class="module-title"><strong>${esc(p.name)}</strong>${s.preferred?'<span class="pill verified">PREFERRED</span>':''}${s.status==='using'?'<span class="pill verified">USING</span>':''}</div><div class="meta"><span>${esc(p.vendor)}</span><span>${esc(cat(p.category))}</span><span>${esc(p.sizes.join(' · '))}</span></div></div><button class="supply-star" data-software-preferred="${esc(p.id)}">${s.preferred?'★':'☆'}</button></div><p>${esc(p.use)}</p><div class="meta"><span>${esc((p.tags||[]).join(' · '))}</span></div><div class="supply-fields"><label>Status<select data-software-status="${esc(p.id)}"><option value="considering" ${s.status==='considering'?'selected':''}>Considering</option><option value="shortlisted" ${s.status==='shortlisted'?'selected':''}>Shortlisted</option><option value="using" ${s.status==='using'?'selected':''}>Using now</option><option value="rejected" ${s.status==='rejected'?'selected':''}>Not suitable</option></select></label><label>Notes<input type="text" data-software-notes="${esc(p.id)}" value="${esc(s.notes)}" placeholder="integration, plan or reason"></label></div></article>`}).join('')||'<div class="empty">No software products match these filters.</div>';
$('software-shortlist-count').textContent=`${saved.length} saved`;$('software-shortlist').innerHTML=saved.length?saved.map(p=>{const s=ps(p.id);return `<article class="order-card"><div><div class="module-title"><strong>${esc(p.name)}</strong><span class="pill ${s.status==='using'?'verified':''}">${esc(s.status)}</span></div><div class="meta"><span>${esc(p.vendor)}</span><span>${esc(cat(p.category))}</span>${s.notes?`<span>${esc(s.notes)}</span>`:''}</div></div></article>`}).join(''):'<div class="empty">No software has been shortlisted yet.</div>';bind();}
function bind(){document.querySelectorAll('[data-software-preferred]').forEach(b=>b.onclick=async()=>{const id=b.dataset.softwarePreferred,s=ps(id);state.products[id]={...s,preferred:!s.preferred};await save();render();});document.querySelectorAll('[data-software-status]').forEach(e=>e.onchange=async()=>{const id=e.dataset.softwareStatus;state.products[id]={...ps(id),status:e.value};await save();render();});document.querySelectorAll('[data-software-notes]').forEach(e=>e.onchange=async()=>{const id=e.dataset.softwareNotes;state.products[id]={...ps(id),notes:e.value};await save();render();});}
async function init(){try{catalog=await (await fetch(chrome.runtime.getURL('titan-modules/cleaning-software-catalog.json'))).json();if(catalog.schema!=='titan-cleaning-software-catalog/v1')throw new Error('Software catalogue is invalid');await loadState();$('software-category').innerHTML='<option value="all">All categories</option>'+catalog.categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');render();}catch(e){$('software-notice').textContent=`Cleaning software marketplace unavailable: ${e.message}`;}}
$('software-search').addEventListener('input',e=>{filters.query=e.target.value;render();});$('software-category').addEventListener('change',e=>{filters.category=e.target.value;render();});$('software-business-size').addEventListener('change',e=>{filters.size=e.target.value;render();});$('software-preferred-only').addEventListener('change',e=>{filters.preferred=e.target.checked;render();});window.addEventListener('titan-company-changed',init);init();})();
