// @ts-nocheck
// Ported from Titan Zero extension (browser-adapter-required): cleaning-service-launch-planner.js
// QUARANTINE: not exported to standalone runtime until browser/DOM dependencies are adapted.
(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const STORE='titanCleaningServiceLaunchPlansV1';let config={stages:[],service_requirements:{}},company_id='company-default',state={plans:{}},opportunities=[];
const today=()=>new Date().toISOString().slice(0,10);
const planFor=id=>state.plans?.[id]||{service_line:id,owner:'',target_date:'',notes:'',checks:{},pilot_confirmed:false,quote_scope_confirmed:false,delivery_standard_confirmed:false,first_job_reference:'',first_job_completed:false,milestones:[],updated_at:null};
async function load(){const x=await chrome.storage.local.get(['titanBusinessProfile',STORE]);company_id=String(x.titanBusinessProfile?.company_id||$('grant-company')?.value||'company-default').trim()||'company-default';state=(x[STORE]||{})[company_id]||{company_id,plans:{}};opportunities=window.TitanCleaningGrowthOpportunities?.getOpportunities?.()||[];}
async function savePlan(id,patch){const x=await chrome.storage.local.get(STORE),all=x[STORE]||{},current=planFor(id),opp=opportunities.find(o=>o.service_line===id)||{service_line:id,evidence_count:0,readiness:0,missing_products:[],missing_workers:[]},before=statusFor(opp,current),candidate={...current,...patch,service_line:id,company_id},after=statusFor(opp,candidate),now=new Date().toISOString(),milestones=[...(current.milestones||[])];if(after.current!==before.current||after.percent!==before.percent)milestones.push({stage:after.current,progress:after.percent,recorded_at:now});const next={...candidate,milestones:milestones.slice(-50),updated_at:now};all[company_id]={company_id,plans:{...(state.plans||{}),[id]:next}};await chrome.storage.local.set({[STORE]:all});state=all[company_id];window.dispatchEvent(new CustomEvent('titan-cleaning-service-launch-plan-changed',{detail:{company_id,service_line:id,grants_authority:false}}));render();return next;}
const reqs=id=>config.service_requirements?.[id]||[];
function stageState(o,p){const manual=reqs(o.service_line),manualReady=manual.every(r=>p.checks?.[r.id]===true),hasEvidence=o.evidence_count>0,coverageReady=o.readiness===100,pilot=!!p.pilot_confirmed,commercialReady=!!p.quote_scope_confirmed&&!!p.delivery_standard_confirmed;return {
 opportunity_detected:hasEvidence,
 capability_review:true,
 prerequisites_ready:coverageReady,
 training_compliance_ready:manualReady,
 pilot_ready:coverageReady&&manualReady&&pilot,
 ready_to_sell:coverageReady&&manualReady&&pilot&&commercialReady,
 first_job_scheduled:coverageReady&&manualReady&&pilot&&commercialReady&&String(p.first_job_reference||'').trim().length>0,
 first_job_completed:coverageReady&&manualReady&&pilot&&commercialReady&&String(p.first_job_reference||'').trim().length>0&&!!p.first_job_completed
};}
function statusFor(o,p){const gates=stageState(o,p),stages=config.stages||[];let completed=0,current=stages[0]?.id||'';for(const s of stages){if(gates[s.id]){completed++;current=s.id}else break;}const percent=stages.length?Math.round(completed/stages.length*100):0;return {gates,completed,current,percent,next:stages[completed]?.id||null};}
function blockers(o,p){const out=[];if(o.evidence_count===0)out.push('No matching company opportunity evidence recorded.');if(o.missing_products?.length)out.push(`${o.missing_products.length} required Marketplace product${o.missing_products.length===1?'':'s'} still missing.`);if(o.missing_workers?.length)out.push(`${o.missing_workers.length} required Workforce specialist${o.missing_workers.length===1?'':'s'} still missing.`);const missingManual=reqs(o.service_line).filter(r=>p.checks?.[r.id]!==true);if(missingManual.length)out.push(`${missingManual.length} training/compliance/business prerequisite${missingManual.length===1?'':'s'} not confirmed.`);if(!p.pilot_confirmed)out.push('Pilot scope and QA process not confirmed.');if(!p.quote_scope_confirmed)out.push('Quote/scope readiness not confirmed.');if(!p.delivery_standard_confirmed)out.push('Delivery/quality standard not confirmed.');return out;}
function lineName(id){const select=$('growth-opportunity-filter');return [...(select?.options||[])].find(o=>o.value===id)?.textContent||id;}
function dueLabel(d){if(!d)return 'No target date';const delta=Math.round((new Date(`${d}T00:00:00`)-new Date(`${today()}T00:00:00`))/86400000);return delta<0?`${Math.abs(delta)} day${Math.abs(delta)===1?'':'s'} overdue`:delta===0?'Target today':`${delta} day${delta===1?'':'s'} to target`;}
function render(){opportunities=window.TitanCleaningGrowthOpportunities?.getOpportunities?.()||opportunities;let list=opportunities;const f=$('service-launch-filter')?.value||'all';if(f!=='all')list=list.filter(o=>o.service_line===f);if($('service-launch-active-only')?.checked)list=list.filter(o=>o.evidence_count>0||planFor(o.service_line).updated_at);
const tracked=list.filter(o=>planFor(o.service_line).updated_at),ready=list.filter(o=>statusFor(o,planFor(o.service_line)).gates.ready_to_sell),completed=list.filter(o=>statusFor(o,planFor(o.service_line)).gates.first_job_completed),blocked=list.filter(o=>blockers(o,planFor(o.service_line)).length>0);
$('service-launch-count').textContent=`${tracked.length} tracked plan${tracked.length===1?'':'s'}`;
$('service-launch-summary').innerHTML=`<div><strong>${tracked.length}</strong><span>Tracked launches</span></div><div><strong>${ready.length}</strong><span>Planner-ready to sell</span></div><div><strong>${completed.length}</strong><span>First jobs completed</span></div><div><strong>${blocked.length}</strong><span>Plans with blockers</span></div>`;
$('service-launch-list').innerHTML=list.length?list.map(o=>{const p=planFor(o.service_line),s=statusFor(o,p),bs=blockers(o,p),requirements=reqs(o.service_line);return `<article class="supply-card service-launch-card"><div class="supply-card-head"><div><div class="module-title"><strong>${esc(lineName(o.service_line))}</strong><span class="pill ${s.gates.ready_to_sell?'verified':s.percent?'warn':''}">${s.percent}% launch progress</span></div><div class="meta"><span>${o.readiness}% capability readiness</span><span>${o.evidence_count} demand signal${o.evidence_count===1?'':'s'}</span><span>${esc(dueLabel(p.target_date))}</span></div></div></div>
<div class="launch-stage-track">${(config.stages||[]).map(st=>`<div class="launch-stage ${s.gates[st.id]?'done':s.next===st.id?'current':''}"><span>${s.gates[st.id]?'✓':'○'}</span><div><strong>${esc(st.name)}</strong><small>${esc(st.description)}</small></div></div>`).join('')}</div>
${bs.length?`<div class="launch-blockers"><strong>Current blockers</strong>${bs.map(b=>`<span>• ${esc(b)}</span>`).join('')}</div>`:'<div class="launch-blockers clear"><strong>No known launch blockers</strong><span>Planner gates are satisfied. This does not publish or authorize the service.</span></div>'}
<div class="launch-form"><label>Launch owner<input type="text" data-launch-owner="${esc(o.service_line)}" value="${esc(p.owner||'')}" placeholder="Person or role accountable"></label><label>Target launch date<input type="date" data-launch-date="${esc(o.service_line)}" value="${esc(p.target_date||'')}"></label><label class="launch-notes">Launch notes<textarea data-launch-notes="${esc(o.service_line)}" rows="2" placeholder="Supplier, training, pilot or sales notes">${esc(p.notes||'')}</textarea></label></div>
<div class="launch-checks"><strong>Training, compliance & service prerequisites</strong>${requirements.map(r=>`<label><input type="checkbox" data-launch-check="${esc(o.service_line)}" data-check-id="${esc(r.id)}" ${p.checks?.[r.id]?'checked':''}> ${esc(r.label)} <span>${esc(r.category)}</span></label>`).join('')||'<span>No additional service-specific manual requirements configured.</span>'}</div>
<div class="launch-checks"><strong>Business launch gates</strong><label><input type="checkbox" data-launch-pilot="${esc(o.service_line)}" ${p.pilot_confirmed?'checked':''}> Pilot scope and QA process confirmed</label><label><input type="checkbox" data-launch-quote="${esc(o.service_line)}" ${p.quote_scope_confirmed?'checked':''}> Quote/scope is ready for this service</label><label><input type="checkbox" data-launch-delivery="${esc(o.service_line)}" ${p.delivery_standard_confirmed?'checked':''}> Delivery and quality standard confirmed</label></div>
<div class="launch-form"><label>First job reference<input type="text" data-launch-job="${esc(o.service_line)}" value="${esc(p.first_job_reference||'')}" placeholder="Job ID / booking reference"></label><label class="check"><input type="checkbox" data-launch-completed="${esc(o.service_line)}" ${p.first_job_completed?'checked':''} ${String(p.first_job_reference||'').trim()?'':'disabled'}> First job completed</label></div>
<div class="purchase-actions">${(o.missing_products?.length||o.missing_workers?.length)?`<button data-launch-missing="${esc(o.service_line)}">View missing Marketplace items</button>`:''}<button class="featured" data-launch-save="${esc(o.service_line)}">Save launch plan</button></div></article>`;}).join(''):'<div class="empty">No service launch plans match this view.</div>';
wire();}
function readCard(id){const checks={...planFor(id).checks};document.querySelectorAll(`[data-launch-check="${CSS.escape(id)}"]`).forEach(i=>checks[i.dataset.checkId]=i.checked);return {owner:document.querySelector(`[data-launch-owner="${CSS.escape(id)}"]`)?.value||'',target_date:document.querySelector(`[data-launch-date="${CSS.escape(id)}"]`)?.value||'',notes:document.querySelector(`[data-launch-notes="${CSS.escape(id)}"]`)?.value||'',checks,pilot_confirmed:!!document.querySelector(`[data-launch-pilot="${CSS.escape(id)}"]`)?.checked,quote_scope_confirmed:!!document.querySelector(`[data-launch-quote="${CSS.escape(id)}"]`)?.checked,delivery_standard_confirmed:!!document.querySelector(`[data-launch-delivery="${CSS.escape(id)}"]`)?.checked,first_job_reference:document.querySelector(`[data-launch-job="${CSS.escape(id)}"]`)?.value||'',first_job_completed:!!document.querySelector(`[data-launch-completed="${CSS.escape(id)}"]`)?.checked};}
function wire(){document.querySelectorAll('[data-launch-save]').forEach(b=>b.onclick=()=>savePlan(b.dataset.launchSave,readCard(b.dataset.launchSave)));document.querySelectorAll('[data-launch-missing]').forEach(b=>b.onclick=()=>{const o=opportunities.find(x=>x.service_line===b.dataset.launchMissing),id=o?.missing_products?.[0];if(id){const search=$('growth-search');const api=window.TitanCleaningGrowthMarketplace?.getProduct?.(id);if(search){search.value=api?.name||id;search.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('.growth-marketplace')?.scrollIntoView({behavior:'smooth',block:'start'});}}else document.querySelector('.cleaning-workforce-marketplace')?.scrollIntoView({behavior:'smooth',block:'start'});});}
async function init(){try{config=await fetch(chrome.runtime.getURL('titan-modules/cleaning-service-launch-plans.json')).then(r=>r.json());if(config.schema!=='titan-cleaning-service-launch-plans/v1')throw new Error('launch-plan configuration is invalid');await load();const sel=$('service-launch-filter'),opp=$('growth-opportunity-filter');if(sel&&opp)sel.innerHTML='<option value="all">All service lines</option>'+[...opp.options].filter(o=>o.value!=='all').map(o=>`<option value="${esc(o.value)}">${esc(o.textContent)}</option>`).join('');render();}catch(e){$('service-launch-notice').textContent=`Service launch planner unavailable: ${e.message}`;}}
$('service-launch-filter')?.addEventListener('change',render);$('service-launch-active-only')?.addEventListener('change',render);window.addEventListener('titan-cleaning-growth-signals-changed',async()=>{await load();render()});window.addEventListener('titan-marketplace-coverage-changed',async()=>{await load();render()});window.addEventListener('titan-company-changed',init);window.addEventListener('titan-cleaning-service-launch-plan-changed',async e=>{if(e.detail?.company_id===company_id){await load();render();}});
window.TitanCleaningServiceLaunchPlanner=Object.freeze({getPlans:()=>opportunities.map(o=>{const p=planFor(o.service_line),s=statusFor(o,p);return {service_line:o.service_line,owner:p.owner||null,target_date:p.target_date||null,updated_at:p.updated_at||null,milestones:[...(p.milestones||[])],progress:s.percent,current_stage:s.current,next_stage:s.next,ready_to_sell:!!s.gates.ready_to_sell,first_job_reference:p.first_job_reference||null,first_job_completed:!!s.gates.first_job_completed,blockers:blockers(o,p),grants_authority:false,publishes_service:false,executes_work:false};}),companyId:()=>company_id});init();})();
