// @ts-nocheck
// Ported from Titan Zero extension (browser-adapter-required): cleaning-growth-recommendations.js
// QUARANTINE: not exported to standalone runtime until browser/DOM dependencies are adapted.
(()=>{'use strict';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const SIGNAL_STORE='titanCleaningGrowthSignalsV1', GROWTH_STORE='titanCleaningGrowthMarketplaceV1', WF_STORE='titanCleaningWorkforceMarketplaceV1';
let rules={signal_types:[],rules:[]},catalog={products:[]},company_id='company-default',signals=[],growthState={products:{}},ownedWorkers=new Set(),coverage=new Set();
const norm=v=>String(v||'').trim().toLowerCase(), byId=id=>catalog.products.find(p=>p.id===id), growthStatus=id=>growthState.products?.[id]?.status||'available';
async function load(){const x=await chrome.storage.local.get(['titanBusinessProfile',SIGNAL_STORE,GROWTH_STORE,WF_STORE]);company_id=String(x.titanBusinessProfile?.company_id||$('grant-company')?.value||'company-default').trim()||'company-default';signals=((x[SIGNAL_STORE]||{})[company_id]||[]).filter(s=>s&&s.company_id===company_id);growthState=(x[GROWTH_STORE]||{})[company_id]||{company_id,products:{}};ownedWorkers=new Set();coverage=new Set();
 for(const w of window.TitanCleaningWorkforce?.specialists||[]){ownedWorkers.add(w.id);for(const c of w.capabilities||[])coverage.add(c)}
 const wf=(x[WF_STORE]||{})[company_id]?.products||{};for(const [id,s] of Object.entries(wf))if(['purchased','installed'].includes(s?.status)){ownedWorkers.add(id);const w=window.TitanCleaningWorkforceProducts?.products?.find(v=>v.id===id);for(const c of w?.capabilities||[])coverage.add(c)}
 for(const [id,s] of Object.entries(growthState.products||{}))if(['installed','purchased','included'].includes(s?.status))for(const c of byId(id)?.provides||[])coverage.add(c);
}
const productCovered=p=>!p?true:['installed','purchased','included'].includes(growthStatus(p.id))||((p.provides||[]).length>0&&(p.provides||[]).every(c=>coverage.has(c)));
const signalType=id=>rules.signal_types.find(s=>s.id===id)||{name:id,weight:1};
function evidenceText(s){return [s.subject,s.detail].filter(Boolean).join(' — ')||signalType(s.type).name}
function recommendations(){const map=new Map();for(const s of signals){const hay=norm([s.subject,s.detail,s.service_line].filter(Boolean).join(' '));if(!hay)continue;for(const r of rules.rules||[]){const hits=(r.terms||[]).filter(t=>hay.includes(norm(t)));if(!hits.length)continue;for(const id of r.products||[]){const p=byId(id);if(!p||productCovered(p)||growthStatus(id)==='not_suitable')continue;const cur=map.get(id)||{product:p,score:0,evidence:[],matches:new Set()};cur.score+=Number(signalType(s.type).weight||1)+Math.min(2,hits.length-1);cur.evidence.push(s);hits.forEach(h=>cur.matches.add(h));map.set(id,cur);}}}
 return [...map.values()].sort((a,b)=>b.score-a.score||a.product.name.localeCompare(b.product.name));}
async function persistSignals(){const x=await chrome.storage.local.get([SIGNAL_STORE]),root=x[SIGNAL_STORE]||{};root[company_id]=signals;await chrome.storage.local.set({[SIGNAL_STORE]:root});window.dispatchEvent(new CustomEvent('titan-cleaning-growth-signals-changed',{detail:{company_id}}));}
async function recordSignal(input={}){const type=String(input.type||'manual_growth_goal');if(!rules.signal_types.some(s=>s.id===type))throw new Error('unknown cleaning growth signal type');const signal={signal_id:String(input.signal_id||`growth-signal-${Date.now()}-${Math.random().toString(36).slice(2,7)}`),company_id,type,subject:String(input.subject||'').trim(),detail:String(input.detail||'').trim(),service_line:String(input.service_line||'').trim(),source:String(input.source||'manual').trim()||'manual',estimated_value:Number(input.estimated_value)>0?Number(input.estimated_value):null,currency:String(input.currency||'').trim().toUpperCase().slice(0,3),observed_at:String(input.observed_at||new Date().toISOString()),grants_authority:false};signals.unshift(signal);signals=signals.slice(0,200);await persistSignals();render();return signal;}
async function removeSignal(id){signals=signals.filter(s=>s.signal_id!==id);await persistSignals();render();}
function render(){const recs=recommendations();$('growth-rec-count').textContent=`${recs.length} gap${recs.length===1?'':'s'} detected`;$('growth-signal-count').textContent=`${signals.length} signal${signals.length===1?'':'s'}`;
 $('growth-recommendations').innerHTML=recs.length?recs.slice(0,12).map((r,i)=>`<article class="supply-card growth-rec-card"><div class="supply-card-head"><div><div class="module-title"><strong>${esc(r.product.name)}</strong><span class="pill ${i<3?'verified':''}">Score ${r.score}</span></div><div class="meta"><span>${esc(r.evidence.length)} evidence item${r.evidence.length===1?'':'s'}</span><span>Advisory only</span></div></div></div><p>${esc(r.product.summary)}</p><div class="growth-evidence"><strong>Why Titan recommends it</strong>${r.evidence.slice(0,3).map(s=>`<span>• ${esc(signalType(s.type).name)}: ${esc(evidenceText(s))}</span>`).join('')}</div><div class="purchase-actions"><button class="featured" data-rec-view="${esc(r.product.id)}">View missing product</button><button data-rec-dismiss="${esc(r.product.id)}">Mark not suitable</button></div></article>`).join(''):'<div class="empty">No evidence-backed growth gaps yet. Add a real enquiry, lost job, tender, compliance need or operating issue below. Titan will not invent recommendations without evidence.</div>';
 $('growth-signal-history').innerHTML=signals.length?signals.slice(0,30).map(s=>`<article class="order-card"><div><div class="module-title"><strong>${esc(signalType(s.type).name)}</strong><span class="pill">${esc(s.source)}</span></div><div class="meta"><span>${esc(evidenceText(s))}</span><span>${esc(new Date(s.observed_at).toLocaleDateString())}${Number(s.estimated_value)>0?` · ${esc((s.currency?s.currency+' ':'')+Number(s.estimated_value).toLocaleString())}`:''}</span></div></div><button data-signal-remove="${esc(s.signal_id)}">Remove</button></article>`).join(''):'<div class="empty">No growth signals recorded for this company.</div>';
 bind();}
function bind(){document.querySelectorAll('[data-signal-remove]').forEach(b=>b.onclick=()=>removeSignal(b.dataset.signalRemove));document.querySelectorAll('[data-rec-view]').forEach(b=>b.onclick=()=>{const q=$('growth-search');q.value=byId(b.dataset.recView)?.name||'';q.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('.growth-marketplace')?.scrollIntoView({behavior:'smooth',block:'start'});});document.querySelectorAll('[data-rec-dismiss]').forEach(b=>b.onclick=async()=>{const id=b.dataset.recDismiss,x=await chrome.storage.local.get([GROWTH_STORE]),root=x[GROWTH_STORE]||{},st=root[company_id]||{company_id,products:{}};st.products=st.products||{};st.products[id]={...(st.products[id]||{}),status:'not_suitable',recommendation_dismissed_at:new Date().toISOString()};root[company_id]=st;await chrome.storage.local.set({[GROWTH_STORE]:root});await load();render();window.dispatchEvent(new CustomEvent('titan-marketplace-coverage-changed',{detail:{company_id}}));});}
async function init(){try{[rules,catalog]=await Promise.all([fetch(chrome.runtime.getURL('titan-modules/cleaning-growth-recommendation-rules.json')).then(r=>r.json()),fetch(chrome.runtime.getURL('titan-modules/cleaning-growth-marketplace.json')).then(r=>r.json())]);if(rules.schema!=='titan-cleaning-growth-recommendation-rules/v1')throw new Error('Recommendation rules are invalid');await load();$('growth-signal-type').innerHTML=rules.signal_types.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');render();}catch(e){$('growth-rec-notice').textContent=`Growth recommendations unavailable: ${e.message}`;}}
$('growth-signal-add').addEventListener('click',async()=>{const subject=$('growth-signal-subject').value.trim(),detail=$('growth-signal-detail').value.trim();if(!subject&&!detail){$('growth-rec-notice').textContent='Add a real enquiry, opportunity, requirement or issue before recording a signal.';return;}await recordSignal({type:$('growth-signal-type').value,subject,detail,estimated_value:$('growth-signal-value')?.value,currency:$('growth-signal-currency')?.value,source:'manual'});$('growth-signal-subject').value='';$('growth-signal-detail').value='';if($('growth-signal-value'))$('growth-signal-value').value='';$('growth-rec-notice').textContent='Growth signal recorded. Recommendations recalculated from company evidence.';});
window.addEventListener('titan-company-changed',init);window.addEventListener('titan-marketplace-coverage-changed',async()=>{await load();render()});window.addEventListener('titan-cleaning-growth-signal',e=>recordSignal(e.detail||{}).catch(()=>{}));
window.TitanCleaningGrowthRecommendations=Object.freeze({recordSignal:input=>recordSignal(input),getRecommendations:()=>recommendations().map(r=>({product_id:r.product.id,score:r.score,evidence_count:r.evidence.length})),getSignals:()=>signals.map(s=>({...s})),companyId:()=>company_id});init();})();
