// @ts-nocheck
// Ported from Titan Zero extension (browser-adapter-required): cleaning-marketplace-action-queue.js
// QUARANTINE: not exported to standalone runtime until browser/DOM dependencies are adapted.
(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const STORE='titanCleaningMarketplaceActionQueueV1';let config={thresholds:{due_soon_days:14}},company_id='company-default',state={items:{},history:[]},queue=[],filter='active';
const nowDay=()=>{const d=new Date();d.setHours(0,0,0,0);return d},daysUntil=v=>{if(!v)return null;const d=new Date(`${v}T00:00:00`);return Number.isFinite(d.getTime())?Math.round((d-nowDay())/86400000):null};
async function company(){const x=await chrome.storage.local.get(['titanBusinessProfile']);return String(x.titanBusinessProfile?.company_id||$('grant-company')?.value||'company-default').trim()||'company-default'}
async function load(){company_id=await company();const x=await chrome.storage.local.get([STORE]);state=(x[STORE]||{})[company_id]||{company_id,items:{},history:[]};state.company_id=company_id;state.items=state.items||{};state.history=state.history||[];buildQueue();}
async function save(event){const x=await chrome.storage.local.get([STORE]),root=x[STORE]||{};root[company_id]=state;await chrome.storage.local.set({[STORE]:root});if(event)state.history.unshift(event);window.dispatchEvent(new CustomEvent('titan-cleaning-marketplace-action-queue-changed',{detail:{company_id,grants_authority:false}}));}
function sourceRows(){const renewal=window.TitanCleaningMarketplaceRenewal?.getItems?.()||[],groups=window.TitanCleaningMarketplaceConsolidation?.getGroups?.()||[],rows=[];
 for(const r of renewal){if(['keep','evidence_needed'].includes(r.recommendation)&&!r.urgent_notice&&!r.renewal_attention)continue;rows.push({id:`renewal:${r.kind}:${r.id}`,source:'renewal',title:r.name||r.id,subject_key:`${r.kind}:${r.id}`,recommendation:r.recommendation,reason:r.reason||'',suggested_evidence:r.recommendation==='evidence_needed'?['adoption/value evidence']:['renewal terms','decision owner'],source_due:r.notice_deadline||r.renewal_date||null,urgency:r.urgent_notice?'urgent':r.renewal_attention?'attention':'normal'});}
 for(const g of groups){if(['no_change_supported'].includes(g.recommendation))continue;rows.push({id:`consolidation:${g.overlap_key}`,source:'consolidation',title:`Overlap: ${g.label}`,subject_key:g.overlap_key,recommendation:g.recommendation,reason:g.reason||'',suggested_evidence:g.recommendation==='evidence_needed'?['adoption/value evidence']:['dependency review','export readiness','retained target'],source_due:null,urgency:g.recommendation==='plan_safe_consolidation'?'attention':'normal'});}
 return rows;}
function derive(row){const rec=state.items[row.id]||{},due=rec.due_date||row.source_due||null,du=daysUntil(due),status=rec.status||'open',completed=['decision_recorded','closed'].includes(status),overdue=!completed&&du!==null&&du<0,dueSoon=!completed&&du!==null&&du>=0&&du<=Number(config.thresholds?.due_soon_days||14);let priority=rec.priority||row.urgency||'normal';if(overdue)priority='urgent';else if(dueSoon&&priority==='normal')priority='attention';const evidence=(rec.evidence_requirements||row.suggested_evidence||[]).filter(Boolean);return{...row,...rec,due_date:due,days_until_due:du,status,priority,overdue,due_soon:dueSoon,evidence_requirements:evidence,grants_authority:false,executes_underlying_action:false};}
function buildQueue(){queue=sourceRows().map(derive).sort((a,b)=>Number(b.overdue)-Number(a.overdue)||({urgent:0,attention:1,normal:2}[a.priority]-({urgent:0,attention:1,normal:2}[b.priority]))||((a.days_until_due??99999)-(b.days_until_due??99999)));}
function visible(r){if(filter==='all')return true;if(filter==='active')return !['decision_recorded','closed'].includes(r.status);if(filter==='overdue')return r.overdue;if(filter==='waiting')return r.status==='waiting_evidence';if(filter==='completed')return ['decision_recorded','closed'].includes(r.status);return true;}
function fmtDue(r){if(!r.due_date)return'No due date';if(r.overdue)return`${r.due_date} · ${Math.abs(r.days_until_due)}d overdue`;if(r.days_until_due===0)return`${r.due_date} · due today`;return`${r.due_date} · ${r.days_until_due}d`;}
function render(){buildQueue();const shown=queue.filter(visible);$('marketplace-action-queue-count').textContent=`${shown.length} actions shown`;$('marketplace-action-queue-summary').innerHTML=[['Open',queue.filter(r=>!['decision_recorded','closed'].includes(r.status)).length],['Overdue',queue.filter(r=>r.overdue).length],['Waiting evidence',queue.filter(r=>r.status==='waiting_evidence').length],['Decision recorded',queue.filter(r=>r.status==='decision_recorded').length],['Closed',queue.filter(r=>r.status==='closed').length]].map(([a,b])=>`<div><span>${esc(a)}</span><strong>${b}</strong></div>`).join('');
 $('marketplace-action-queue-list').innerHTML=shown.length?shown.map(r=>`<article class="supply-card marketplace-action-card ${r.overdue?'value-warning':''}"><div class="supply-card-head"><div><div class="module-title"><strong>${esc(r.title)}</strong><span class="pill">${esc(r.source)}</span><span class="pill ${r.priority==='urgent'?'danger':r.priority==='attention'?'warn':'verified'}">${esc(r.priority)}</span></div><div class="meta"><span>${esc(r.recommendation.replaceAll('_',' '))}</span><span>${esc(r.reason)}</span><span>${esc(fmtDue(r))}</span></div></div></div><div class="action-queue-fields"><label>Owner<input data-action-field="${esc(r.id)}" data-field="owner" value="${esc(r.owner||'')}" placeholder="Decision owner"></label><label>Due date<input type="date" data-action-field="${esc(r.id)}" data-field="due_date" value="${esc(r.due_date||'')}"></label><label>Status<select data-action-field="${esc(r.id)}" data-field="status">${config.statuses.map(v=>`<option value="${v}" ${r.status===v?'selected':''}>${v.replaceAll('_',' ')}</option>`).join('')}</select></label><label>Priority<select data-action-field="${esc(r.id)}" data-field="priority">${config.priorities.map(v=>`<option value="${v}" ${r.priority===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Decision<select data-action-field="${esc(r.id)}" data-field="decision"><option value="">Not recorded</option>${config.decisions.map(v=>`<option value="${v}" ${r.decision===v?'selected':''}>${v.replaceAll('_',' ')}</option>`).join('')}</select></label><label class="action-evidence">Evidence requirements<input data-action-field="${esc(r.id)}" data-field="evidence_requirements_text" value="${esc((r.evidence_requirements||[]).join('; '))}" placeholder="Separate with ;"></label><label class="action-notes">Decision / evidence notes<textarea rows="2" data-action-field="${esc(r.id)}" data-field="notes">${esc(r.notes||'')}</textarea></label><button class="featured" data-action-save="${esc(r.id)}">Save review</button></div></article>`).join(''):'<div class="empty">No Marketplace review actions match this filter.</div>';bind();renderHistory();}
function renderHistory(){$('marketplace-action-history').innerHTML=state.history.length?state.history.slice(0,40).map(h=>`<div class="action-history-row"><strong>${esc(h.title)}</strong><span>${esc(h.status||'updated')} · ${esc(h.decision||'no decision')}</span><span>${esc(h.at)}</span></div>`).join(''):'<div class="empty">No completed review history yet.</div>';}
function bind(){document.querySelectorAll('[data-action-save]').forEach(b=>b.onclick=async()=>{const id=b.dataset.actionSave,row=queue.find(x=>x.id===id);if(!row)return;const prev=state.items[id]||{},rec={...prev};document.querySelectorAll(`[data-action-field="${CSS.escape(id)}"]`).forEach(el=>{let v=el.value;if(el.dataset.field==='evidence_requirements_text'){rec.evidence_requirements=String(v).split(';').map(x=>x.trim()).filter(Boolean);return;}rec[el.dataset.field]=v||null;});rec.updated_at=new Date().toISOString();rec.source='company_input';state.items[id]=rec;state.history.unshift({id:`hist-${Date.now()}-${Math.random().toString(16).slice(2)}`,action_id:id,title:row.title,status:rec.status||'open',decision:rec.decision||null,owner:rec.owner||null,at:rec.updated_at,grants_authority:false,executes_underlying_action:false});state.history=state.history.slice(0,200);await save();render();});}
async function init(){try{config=await (await fetch(chrome.runtime.getURL('titan-modules/cleaning-marketplace-action-queue.json'))).json();if(config.schema!=='titan-cleaning-marketplace-action-queue/v1')throw new Error('Marketplace action queue config is invalid');await load();render()}catch(e){$('marketplace-action-queue-notice').textContent=`Marketplace action queue unavailable: ${e.message}`}}
$('marketplace-action-queue-filter').addEventListener('change',e=>{filter=e.target.value;render()});window.addEventListener('titan-cleaning-marketplace-renewal-changed',init);window.addEventListener('titan-cleaning-marketplace-consolidation-changed',init);window.addEventListener('titan-company-changed',init);init();
window.TitanCleaningMarketplaceActionQueue={getItems:()=>queue.map(derive),companyId:()=>company_id,grantsAuthority:false,executesUnderlyingAction:false,cancelsProducts:false,renewsProducts:false,purchasesReplacements:false,migratesData:false,removesWorkers:false};
})();
