// @ts-nocheck
// Ported from Titan Zero extension (browser-adapter-required): cleaning-growth-marketplace.js
// QUARANTINE: not exported to standalone runtime until browser/DOM dependencies are adapted.
(()=>{'use strict';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const STORE='titanCleaningGrowthMarketplaceV1', WF_STORE='titanCleaningWorkforceMarketplaceV1', SW_STORE='titanCleaningSoftwareMarketplaceV1';
let catalog={products:[],categories:[]},state={company_id:'company-default',products:{}},filters={query:'',category:'all',missing:true},coverage=new Set(),ownedWorkers=new Set();
const ps=id=>state.products[id]||{status:'available',notes:''}, byId=id=>catalog.products.find(p=>p.id===id), norm=v=>String(v||'').trim().toLowerCase();
async function load(){const x=await chrome.storage.local.get(['titanBusinessProfile',STORE,WF_STORE,SW_STORE]);const company_id=String(x.titanBusinessProfile?.company_id||$('grant-company')?.value||'company-default').trim()||'company-default';state=(x[STORE]||{})[company_id]||{company_id,products:{}};state.company_id=company_id;coverage=new Set();ownedWorkers=new Set();
  for(const w of window.TitanCleaningWorkforce?.specialists||[]){ownedWorkers.add(w.id);for(const c of w.capabilities||[])coverage.add(c)}
  const wf=(x[WF_STORE]||{})[company_id]?.products||{};for(const [id,s] of Object.entries(wf))if(['purchased','installed'].includes(s?.status)){ownedWorkers.add(id);const w=window.TitanCleaningWorkforceProducts?.products?.find(v=>v.id===id);for(const c of w?.capabilities||[])coverage.add(c)}
  for(const [id,s] of Object.entries(state.products||{}))if(['installed','purchased','included'].includes(s?.status))for(const c of byId(id)?.provides||[])coverage.add(c);
  const sw=(x[SW_STORE]||{})[company_id]?.products||{};for(const [id,s] of Object.entries(sw))if(s?.status==='using')coverage.add('software:'+id);
}
async function save(){const x=await chrome.storage.local.get([STORE]),root=x[STORE]||{};root[state.company_id]=state;await chrome.storage.local.set({[STORE]:root});window.dispatchEvent(new CustomEvent('titan-marketplace-coverage-changed',{detail:{company_id:state.company_id}}));}
const fullyCovered=p=>p.category!=='crew'&&(p.provides||[]).length>0&&(p.provides||[]).every(c=>coverage.has(c));
const componentOwned=c=>c.kind==='workforce_agent'?ownedWorkers.has(c.id):['installed','purchased','included'].includes(ps(c.id).status)||fullyCovered(byId(c.id)||{});
const missingComponents=p=>(p.components||[]).filter(c=>!componentOwned(c));
const crewCovered=p=>p.category==='crew'&&(p.components||[]).length>0&&missingComponents(p).length===0;
const covered=p=>fullyCovered(p)||crewCovered(p)||['installed','purchased','included'].includes(ps(p.id).status);
const cname=id=>catalog.categories.find(c=>c.id===id)?.name||id;
function matches(p){const q=norm(filters.query);return(filters.category==='all'||p.category===filters.category)&&(!filters.missing||!covered(p))&&(!q||[p.name,p.summary,cname(p.category),...(p.tags||[]),...(p.recommended_for||[])].join(' ').toLowerCase().includes(q));}
function coverageLabel(p){if(p.category==='crew'){const miss=missingComponents(p);return miss.length?`${miss.length} missing of ${(p.components||[]).length}`:'Already complete'}return covered(p)?'Already covered':`${(p.provides||[]).length} capabilities`;}
function componentLabel(c){const p=byId(c.id);if(p)return p.name;const w=window.TitanCleaningWorkforceProducts?.products?.find(v=>v.id===c.id)||window.TitanCleaningWorkforce?.byId?.[c.id];return w?.name||c.id;}
function render(){const shown=catalog.products.filter(matches),installed=catalog.products.filter(covered),crews=catalog.products.filter(p=>p.category==='crew');$('growth-result-count').textContent=`${shown.length} available`;
 $('growth-summary').innerHTML=[['Marketplace products',catalog.products.length],['Product classes',catalog.categories.length],['Covered / installed',installed.length],['Complete crews',crews.filter(crewCovered).length],['Missing products',catalog.products.filter(p=>!covered(p)).length]].map(([a,b])=>`<div><span>${esc(a)}</span><strong>${b}</strong></div>`).join('');
 $('growth-products').innerHTML=shown.length?shown.map(p=>{const s=ps(p.id),miss=p.category==='crew'?missingComponents(p):[];const comp=p.category==='crew'?`<div class="growth-components"><strong>Bundle check</strong>${(p.components||[]).map(c=>`<span class="${componentOwned(c)?'owned':'missing'}">${componentOwned(c)?'✓':'＋'} ${esc(componentLabel(c))}</span>`).join('')}</div>`:'';return `<article class="supply-card growth-card"><div class="supply-card-head"><div><div class="module-title"><strong>${esc(p.name)}</strong><span class="pill">${esc(cname(p.category))}</span>${p.jurisdiction_aware?'<span class="pill warn">JURISDICTION-AWARE</span>':''}</div><div class="meta"><span>${esc(coverageLabel(p))}</span><span>${esc(p.commercial_model.replaceAll('_',' '))}</span><span>Risk ${esc(p.risk_ceiling)}</span></div></div></div><p>${esc(p.summary)}</p>${comp}<div class="meta"><span>${esc((p.recommended_for||[]).join(' · '))}</span></div><div class="supply-fields growth-fields"><label>Status<select data-growth-status="${esc(p.id)}"><option value="available" ${s.status==='available'?'selected':''}>Available</option><option value="shortlisted" ${s.status==='shortlisted'?'selected':''}>Shortlisted</option><option value="not_suitable" ${s.status==='not_suitable'?'selected':''}>Not suitable</option></select></label><label>Company note<input data-growth-note="${esc(p.id)}" value="${esc(s.notes||'')}" placeholder="why this business needs it"></label></div><div class="purchase-actions"><button class="featured" data-growth-install="${esc(p.id)}">${p.category==='crew'?`Install ${miss.length} missing component${miss.length===1?'':'s'}`:'Add to company'}</button></div></article>`}).join(''):'<div class="empty">Nothing missing in this view. Titan hides products whose capabilities are already covered.</div>';
 $('growth-installed-count').textContent=`${installed.length} covered`;$('growth-installed').innerHTML=installed.length?installed.map(p=>`<article class="order-card"><div><div class="module-title"><strong>${esc(p.name)}</strong><span class="pill verified">COVERED</span></div><div class="meta"><span>${esc(cname(p.category))}</span><span>${esc(ps(p.id).notes||'capability already available')}</span></div></div>${ps(p.id).status==='installed'?`<button data-growth-remove="${esc(p.id)}">Remove marketplace install</button>`:''}</article>`).join(''):'<div class="empty">No growth products are installed yet.</div>';bind();}
async function installOne(id){const p=byId(id);if(!p||covered(p))return;if(p.category==='crew'){for(const c of missingComponents(p)){if(c.kind==='marketplace_product'){const cp=byId(c.id);if(cp&&!covered(cp))state.products[c.id]={...ps(c.id),status:'installed',installed_at:new Date().toISOString(),installed_via:p.id}}else if(c.kind==='workforce_agent'){const x=await chrome.storage.local.get([WF_STORE]),root=x[WF_STORE]||{},company=root[state.company_id]||{company_id:state.company_id,products:{}};company.products=company.products||{};company.products[c.id]={...(company.products[c.id]||{}),status:'purchased',purchased_at:new Date().toISOString(),installed_via:p.id};root[state.company_id]=company;await chrome.storage.local.set({[WF_STORE]:root});ownedWorkers.add(c.id);}}state.products[id]={...ps(id),status:'installed',installed_at:new Date().toISOString()};}else state.products[id]={...ps(id),status:'installed',installed_at:new Date().toISOString()};await save();await load();render();}
function bind(){document.querySelectorAll('[data-growth-status]').forEach(e=>e.onchange=async()=>{state.products[e.dataset.growthStatus]={...ps(e.dataset.growthStatus),status:e.value};await save();render()});document.querySelectorAll('[data-growth-note]').forEach(e=>e.onchange=async()=>{state.products[e.dataset.growthNote]={...ps(e.dataset.growthNote),notes:e.value};await save()});document.querySelectorAll('[data-growth-install]').forEach(b=>b.onclick=()=>installOne(b.dataset.growthInstall));document.querySelectorAll('[data-growth-remove]').forEach(b=>b.onclick=async()=>{const id=b.dataset.growthRemove;state.products[id]={...ps(id),status:'available',removed_at:new Date().toISOString()};await save();await load();render()});}
async function init(){try{catalog=await (await fetch(chrome.runtime.getURL('titan-modules/cleaning-growth-marketplace.json'))).json();if(catalog.schema!=='titan-cleaning-growth-marketplace/v1')throw new Error('Growth catalogue is invalid');await load();$('growth-category').innerHTML='<option value="all">All product classes</option>'+catalog.categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');render()}catch(e){$('growth-notice').textContent=`Cleaning growth marketplace unavailable: ${e.message}`}}
$('growth-search').addEventListener('input',e=>{filters.query=e.target.value;render()});$('growth-category').addEventListener('change',e=>{filters.category=e.target.value;render()});$('growth-missing-only').addEventListener('change',e=>{filters.missing=e.target.checked;render()});window.addEventListener('titan-company-changed',init);window.addEventListener('titan-cleaning-workforce-updated',init);init();})();
