// @ts-nocheck
// Ported from Titan Zero extension (browser-adapter-required): cleaning-workforce-marketplace.js
// QUARANTINE: not exported to standalone runtime until browser/DOM dependencies are adapted.
(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const STORE='titanCleaningWorkforceMarketplaceV1';let state={company_id:'company-default',products:{}},filters={query:'',specialty:'all',shortlist:false},installed={ids:new Set(),names:new Set()};
const catalog=()=>window.TitanCleaningWorkforceProducts?.products||[];const norm=v=>String(v||'').replace(/\s+/g,' ').trim().toLowerCase();
async function loadState(){const x=await chrome.storage.local.get(['titanBusinessProfile',STORE]);const company=String(x.titanBusinessProfile?.company_id||$('grant-company')?.value||'company-default').trim()||'company-default';const root=x[STORE]||{};state=root[company]||{company_id:company,products:{}};state.company_id=company;}
async function save(){const x=await chrome.storage.local.get([STORE]),root=x[STORE]||{};root[state.company_id]=state;await chrome.storage.local.set({[STORE]:root});}
async function scanInstalled(){installed={ids:new Set(),names:new Set()};const add=(id,name)=>{if(id)installed.ids.add(String(id));if(name)installed.names.add(norm(name));};
  try{for(const w of window.TitanCleaningWorkforce?.specialists||[])add(w.id,w.name);for(const r of window.TitanClientWorkforce?.catalogue||[])add(r.role_definition_id,r.name);}catch{}
  try{const text=await (await fetch(chrome.runtime.getURL('titan-cleaning-workforce.js'))).text();for(const m of text.matchAll(/mk\('([^']+)','([^']+)'/g))add(m[1],m[2]);}catch{}
  try{const text=await (await fetch(chrome.runtime.getURL('titan-client-workforce.js'))).text();for(const m of text.matchAll(/"role_definition_id":"([^"]+)","name":"([^"]+)"/g))add(m[1],m[2]);}catch{}
}
const ps=id=>state.products[id]||{status:'available',notes:''};
const purchased=p=>['purchased','installed'].includes(ps(p.id).status);const duplicate=p=>installed.ids.has(p.id)||installed.names.has(norm(p.name));
function saleable(){return catalog().filter(p=>!duplicate(p)&&!purchased(p));}
function matches(p){const q=filters.query.toLowerCase();return(filters.specialty==='all'||p.specialty===filters.specialty)&&(!filters.shortlist||ps(p.id).status==='shortlisted')&&(!q||[p.name,p.purpose,p.specialty,...(p.capabilities||[]),...(p.recommended_for||[])].join(' ').toLowerCase().includes(q));}
function render(){const all=catalog(),available=saleable(),shown=available.filter(matches),bought=all.filter(p=>purchased(p));$('workforce-market-result-count').textContent=`${shown.length} available`;$('workforce-market-summary').innerHTML=[['Specialist products',all.length],['Already covered',all.filter(duplicate).length],['Available to company',available.length],['Shortlisted',available.filter(p=>ps(p.id).status==='shortlisted').length],['Purchased',bought.length]].map(([a,b])=>`<div><span>${esc(a)}</span><strong>${b}</strong></div>`).join('');
$('workforce-market-products').innerHTML=shown.length?shown.map(p=>{const s=ps(p.id);return `<article class="supply-card"><div class="supply-card-head"><div><div class="module-title"><strong>🧹 ${esc(p.name)}</strong>${s.status==='shortlisted'?'<span class="pill verified">SHORTLISTED</span>':''}</div><div class="meta"><span>${esc(p.specialty)}</span><span>${esc(p.department)}</span><span>Risk ${esc(p.risk_ceiling)}</span></div></div></div><p>${esc(p.purpose)}</p><div class="meta"><span>${esc((p.recommended_for||[]).join(' · '))}</span></div><div class="supply-fields"><label>Status<select data-workforce-market-status="${esc(p.id)}"><option value="available" ${s.status==='available'?'selected':''}>Available</option><option value="shortlisted" ${s.status==='shortlisted'?'selected':''}>Shortlisted</option><option value="not_suitable" ${s.status==='not_suitable'?'selected':''}>Not suitable</option></select></label><label>Notes<input type="text" data-workforce-market-notes="${esc(p.id)}" value="${esc(s.notes)}" placeholder="service need, customer, rollout note"></label></div><div class="purchase-actions"><button class="featured" data-workforce-market-buy="${esc(p.id)}">Mark purchased & add to workforce</button></div></article>`}).join(''):'<div class="empty">No additional cleaning specialists match these filters. Existing workforce roles are intentionally not resold.</div>';
$('workforce-market-purchased-count').textContent=`${bought.length} purchased`;$('workforce-market-purchased').innerHTML=bought.length?bought.map(p=>`<article class="order-card"><div><div class="module-title"><strong>🧹 ${esc(p.name)}</strong><span class="pill verified">IN WORKFORCE</span></div><div class="meta"><span>${esc(p.specialty)}</span><span>${esc(ps(p.id).notes||'company-scoped specialist')}</span></div></div><button data-workforce-market-remove="${esc(p.id)}">Remove from workforce</button></article>`).join(''):'<div class="empty">No marketplace cleaning specialists have been purchased for this company.</div>';bind();}
function bind(){document.querySelectorAll('[data-workforce-market-status]').forEach(e=>e.onchange=async()=>{const id=e.dataset.workforceMarketStatus;state.products[id]={...ps(id),status:e.value};await save();render();});document.querySelectorAll('[data-workforce-market-notes]').forEach(e=>e.onchange=async()=>{const id=e.dataset.workforceMarketNotes;state.products[id]={...ps(id),notes:e.value};await save();});document.querySelectorAll('[data-workforce-market-buy]').forEach(b=>b.onclick=async()=>{const id=b.dataset.workforceMarketBuy;state.products[id]={...ps(id),status:'purchased',purchased_at:new Date().toISOString()};await save();render();});document.querySelectorAll('[data-workforce-market-remove]').forEach(b=>b.onclick=async()=>{const id=b.dataset.workforceMarketRemove;state.products[id]={...ps(id),status:'available',removed_at:new Date().toISOString()};await save();render();});}
async function init(){try{await loadState();await scanInstalled();const specialties=[...new Set(catalog().map(p=>p.specialty))].sort();$('workforce-market-specialty').innerHTML='<option value="all">All specialties</option>'+specialties.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');render();}catch(e){$('workforce-market-notice').textContent=`Cleaning workforce marketplace unavailable: ${e.message}`;}}
$('workforce-market-search').addEventListener('input',e=>{filters.query=e.target.value;render();});$('workforce-market-specialty').addEventListener('change',e=>{filters.specialty=e.target.value;render();});$('workforce-market-shortlist-only').addEventListener('change',e=>{filters.shortlist=e.target.checked;render();});window.addEventListener('titan-company-changed',init);init();})();
