// @ts-nocheck
// Ported from Titan Zero extension (browser-adapter-required): cleaning-service-launch-economics.js
// QUARANTINE: not exported to standalone runtime until browser/DOM dependencies are adapted.
(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const STORE='titanCleaningLaunchEconomicsV1';let config={},company_id='company-default',state={lines:{}},rows=[];
const blank=id=>({service_line:id,currency:config.default_currency||'AUD',setup_cost:null,pilot_cost:null,monthly_fixed_cost:null,expected_job_revenue:null,expected_job_variable_cost:null,expected_jobs_per_month:null,launch_budget_cap:null,notes:'',updated_at:null});
const num=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)&&n>=0?n:null};
const fmt=(v,c='AUD')=>v===null||v===undefined?'Not supplied':new Intl.NumberFormat(undefined,{style:'currency',currency:c,maximumFractionDigits:2}).format(v);
const lineName=id=>[...($('growth-opportunity-filter')?.options||[])].find(o=>o.value===id)?.textContent||id;
function derive(x){const setup=num(x.setup_cost),pilot=num(x.pilot_cost),fixed=num(x.monthly_fixed_cost),revenue=num(x.expected_job_revenue),variable=num(x.expected_job_variable_cost),jobs=num(x.expected_jobs_per_month),cap=num(x.launch_budget_cap);const investment=[setup,pilot,fixed].some(v=>v!==null)?(setup||0)+(pilot||0)+(fixed||0):null;const margin=revenue!==null&&variable!==null?revenue-variable:null;const breakEven=investment!==null&&margin!==null&&margin>0?Math.ceil(investment/margin):null;const monthlyContribution=jobs!==null&&margin!==null?jobs*margin:null;let budget='not_set';if(cap!==null&&investment!==null)budget=investment>cap?'exceeds':'within';const complete=revenue!==null&&variable!==null&&investment!==null;return {known_launch_investment:investment,contribution_per_job:margin,break_even_jobs:breakEven,expected_monthly_contribution:monthlyContribution,budget_status:budget,inputs_complete:complete,positive_contribution:margin!==null?margin>0:null};}
async function load(){const x=await chrome.storage.local.get(['titanBusinessProfile',STORE]);company_id=String(x.titanBusinessProfile?.company_id||$('grant-company')?.value||'company-default').trim()||'company-default';state=(x[STORE]||{})[company_id]||{company_id,lines:{}};}
async function save(id,patch){const x=await chrome.storage.local.get(STORE),all=x[STORE]||{},current=state.lines?.[id]||blank(id),next={...current,...patch,service_line:id,company_id,updated_at:new Date().toISOString()};all[company_id]={company_id,lines:{...(state.lines||{}),[id]:next}};await chrome.storage.local.set({[STORE]:all});state=all[company_id];window.dispatchEvent(new CustomEvent('titan-cleaning-launch-economics-changed',{detail:{company_id,service_line:id,grants_authority:false,approves_spend:false}}));render();return next;}
function allLines(){const planner=window.TitanCleaningServiceLaunchPlanner?.getPlans?.()||[],opps=window.TitanCleaningGrowthOpportunities?.getOpportunities?.()||[],ids=[...new Set([...planner.map(p=>p.service_line),...opps.map(o=>o.service_line),...Object.keys(state.lines||{})])];return ids.map(id=>{const input={...blank(id),...(state.lines?.[id]||{})},derived=derive(input),plan=planner.find(p=>p.service_line===id)||{},opp=opps.find(o=>o.service_line===id)||{};return {...input,...derived,name:lineName(id),launch_progress:plan.progress||0,ready_to_sell:!!plan.ready_to_sell,evidence_count:opp.evidence_count||0};});}
function summary(list){const entered=list.filter(r=>r.updated_at),within=entered.filter(r=>r.budget_status==='within'),exceeds=entered.filter(r=>r.budget_status==='exceeds'),breakEven=entered.filter(r=>r.break_even_jobs!==null),positive=entered.filter(r=>r.positive_contribution===true);return {entered:entered.length,within_budget:within.length,over_budget:exceeds.length,break_even_known:breakEven.length,positive_margin:positive.length};}
function val(v){return v===null||v===undefined?'':String(v)}
function render(){rows=allLines();const mode=$('launch-economics-filter')?.value||'tracked';let list=rows;if(mode==='tracked')list=list.filter(r=>r.updated_at||r.evidence_count>0||r.launch_progress>0);if(mode==='budget')list=list.filter(r=>r.budget_status==='exceeds');if(mode==='ready')list=list.filter(r=>r.break_even_jobs!==null&&r.budget_status!=='exceeds');const s=summary(rows);if($('launch-economics-count'))$('launch-economics-count').textContent=`${s.entered} economic model${s.entered===1?'':'s'}`;if($('launch-economics-summary'))$('launch-economics-summary').innerHTML=`<div><strong>${s.entered}</strong><span>Models entered</span></div><div><strong>${s.break_even_known}</strong><span>Break-even known</span></div><div><strong>${s.positive_margin}</strong><span>Positive job margin</span></div><div><strong>${s.within_budget}</strong><span>Within budget cap</span></div><div><strong>${s.over_budget}</strong><span>Budget warnings</span></div>`;
if(!$('launch-economics-list'))return;$('launch-economics-list').innerHTML=list.length?list.map(r=>`<article class="supply-card launch-economics-card ${r.budget_status==='exceeds'?'budget-warning':''}"><div class="supply-card-head"><div><div class="module-title"><strong>${esc(r.name)}</strong><span class="pill ${r.budget_status==='exceeds'?'danger':r.break_even_jobs!==null?'verified':'warn'}">${r.budget_status==='exceeds'?'Budget warning':r.break_even_jobs!==null?'Model calculated':'Inputs needed'}</span></div><div class="meta"><span>${r.evidence_count} demand signal${r.evidence_count===1?'':'s'}</span><span>${r.launch_progress}% launch progress</span><span>${r.ready_to_sell?'Planner ready to sell':'Planner not ready to sell'}</span></div></div></div>
<div class="economics-summary"><div><strong>${esc(fmt(r.known_launch_investment,r.currency))}</strong><span>Known launch investment</span></div><div><strong>${esc(fmt(r.contribution_per_job,r.currency))}</strong><span>Contribution per job</span></div><div><strong>${r.break_even_jobs===null?'Not calculable':esc(r.break_even_jobs)}</strong><span>Break-even jobs</span></div><div><strong>${esc(fmt(r.expected_monthly_contribution,r.currency))}</strong><span>Expected monthly contribution</span></div></div>
${r.positive_contribution===false?'<div class="economics-warning">Expected job revenue does not exceed the supplied variable job cost. Break-even cannot be positive under these assumptions.</div>':''}${r.budget_status==='exceeds'?`<div class="economics-warning">Known launch investment exceeds the company-entered launch budget cap by ${esc(fmt(r.known_launch_investment-r.launch_budget_cap,r.currency))}. Titan has not approved any spending.</div>`:''}
<div class="economics-fields"><label>Currency<input data-econ-currency="${esc(r.service_line)}" value="${esc(r.currency)}" maxlength="3"></label><label>Setup cost<input type="number" min="0" step="0.01" data-econ-setup="${esc(r.service_line)}" value="${esc(val(r.setup_cost))}"></label><label>Pilot cost<input type="number" min="0" step="0.01" data-econ-pilot="${esc(r.service_line)}" value="${esc(val(r.pilot_cost))}"></label><label>Monthly fixed cost<input type="number" min="0" step="0.01" data-econ-fixed="${esc(r.service_line)}" value="${esc(val(r.monthly_fixed_cost))}"></label><label>Expected revenue / job<input type="number" min="0" step="0.01" data-econ-revenue="${esc(r.service_line)}" value="${esc(val(r.expected_job_revenue))}"></label><label>Variable cost / job<input type="number" min="0" step="0.01" data-econ-variable="${esc(r.service_line)}" value="${esc(val(r.expected_job_variable_cost))}"></label><label>Expected jobs / month<input type="number" min="0" step="1" data-econ-jobs="${esc(r.service_line)}" value="${esc(val(r.expected_jobs_per_month))}"></label><label>Launch budget cap<input type="number" min="0" step="0.01" data-econ-cap="${esc(r.service_line)}" value="${esc(val(r.launch_budget_cap))}"></label><label class="economics-notes">Assumption notes<textarea rows="2" data-econ-notes="${esc(r.service_line)}" placeholder="Source of costs, quote assumptions, pilot constraints…">${esc(r.notes||'')}</textarea></label></div><div class="purchase-actions"><button class="featured" data-econ-save="${esc(r.service_line)}">Save commercial assumptions</button></div></article>`).join(''):'<div class="empty">No launch economics match this view.</div>';
document.querySelectorAll('[data-econ-save]').forEach(b=>b.onclick=()=>{const id=b.dataset.econSave,q=s=>document.querySelector(`[${s}="${CSS.escape(id)}"]`);save(id,{currency:String(q('data-econ-currency')?.value||config.default_currency||'AUD').trim().toUpperCase().slice(0,3),setup_cost:num(q('data-econ-setup')?.value),pilot_cost:num(q('data-econ-pilot')?.value),monthly_fixed_cost:num(q('data-econ-fixed')?.value),expected_job_revenue:num(q('data-econ-revenue')?.value),expected_job_variable_cost:num(q('data-econ-variable')?.value),expected_jobs_per_month:num(q('data-econ-jobs')?.value),launch_budget_cap:num(q('data-econ-cap')?.value),notes:q('data-econ-notes')?.value||''});});}
async function init(){try{config=await fetch(chrome.runtime.getURL('titan-modules/cleaning-launch-economics.json')).then(r=>r.json());if(config.schema!=='titan-cleaning-launch-economics/v1')throw new Error('launch economics configuration is invalid');await load();render();}catch(e){if($('launch-economics-notice'))$('launch-economics-notice').textContent=`Commercial launch readiness unavailable: ${e.message}`;}}
$('launch-economics-filter')?.addEventListener('change',render);['titan-cleaning-service-launch-plan-changed','titan-cleaning-growth-signals-changed','titan-marketplace-coverage-changed'].forEach(ev=>window.addEventListener(ev,render));window.addEventListener('titan-company-changed',init);
window.TitanCleaningLaunchEconomics=Object.freeze({getModels:()=>allLines().map(r=>({...r,grants_authority:false,approves_spend:false,purchases_products:false,publishes_service:false})),getSummary:()=>summary(allLines()),derive:input=>derive(input),companyId:()=>company_id,grantsAuthority:false,approvesSpend:false});init();})();
