// @ts-nocheck
// Ported from Titan Zero extension (browser-adapter-required): cleaning-service-launch-portfolio.js
// QUARANTINE: not exported to standalone runtime until browser/DOM dependencies are adapted.
(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let config={stalled_after_days:14},company_id='company-default',rows=[];
const DAY=86400000,now=()=>Date.now(),dateOnly=v=>v?new Date(`${v}T00:00:00`).getTime():null;
const ageDays=v=>v?Math.max(0,Math.floor((now()-new Date(v).getTime())/DAY)):null;
const dueDays=v=>{const t=dateOnly(v);if(t===null)return null;return Math.ceil((t-dateOnly(new Date().toISOString().slice(0,10)))/DAY)};
const lineName=id=>[...($('growth-opportunity-filter')?.options||[])].find(o=>o.value===id)?.textContent||id;
function build(){
  const planner=window.TitanCleaningServiceLaunchPlanner,oppApi=window.TitanCleaningGrowthOpportunities;
  company_id=planner?.companyId?.()||oppApi?.companyId?.()||'company-default';
  const plans=planner?.getPlans?.()||[],opps=oppApi?.getOpportunities?.()||[],byOpp=new Map(opps.map(o=>[o.service_line,o]));
  rows=plans.map(p=>{const o=byOpp.get(p.service_line)||{},tracked=!!p.updated_at||o.evidence_count>0,age=ageDays(p.updated_at),due=dueDays(p.target_date),blocked=(p.blockers||[]).length>0,overdue=tracked&&due!==null&&due<0&&!p.first_job_completed,stalled=tracked&&!p.first_job_completed&&age!==null&&age>=Number(config.stalled_after_days||14),missingOwner=tracked&&!String(p.owner||'').trim(),missingTarget=tracked&&!p.target_date;let risk='none';if(overdue&&blocked)risk='critical';else if(overdue||stalled)risk='high';else if(blocked||missingOwner||missingTarget)risk='attention';return {...p,name:lineName(p.service_line),tracked,evidence_count:o.evidence_count||0,opportunity_value:o.total_value||0,opportunity_currency:o.currency||null,overdue,stalled,days_since_update:age,days_to_target:due,missing_owner:missingOwner,missing_target:missingTarget,risk};});
  return rows;
}
function summary(list){const tracked=list.filter(r=>r.tracked),completed=tracked.filter(r=>r.first_job_completed),ready=tracked.filter(r=>r.ready_to_sell),overdue=tracked.filter(r=>r.overdue),stalled=tracked.filter(r=>r.stalled),atRisk=tracked.filter(r=>r.risk!=='none'),owned=tracked.filter(r=>!r.missing_owner),conversion=tracked.length?Math.round(completed.length/tracked.length*100):0;return {tracked:tracked.length,ready:ready.length,completed:completed.length,overdue:overdue.length,stalled:stalled.length,at_risk:atRisk.length,owner_assigned:owned.length,first_job_conversion_percent:conversion};}
function riskLabel(r){return r==='critical'?'Critical':r==='high'?'High':r==='attention'?'Attention':'On track';}
function statusText(r){if(r.first_job_completed)return 'First job completed';if(r.ready_to_sell)return 'Ready to sell';if(r.overdue)return `${Math.abs(r.days_to_target)} day${Math.abs(r.days_to_target)===1?'':'s'} overdue`;if(r.stalled)return `No saved progress for ${r.days_since_update} days`;if(r.days_to_target===0)return 'Target today';if(r.days_to_target>0)return `${r.days_to_target} days to target`;return r.tracked?'In progress':'Not tracked';}
function render(){build();const mode=$('launch-portfolio-filter')?.value||'tracked';let list=rows;if(mode==='tracked')list=list.filter(r=>r.tracked);if(mode==='risk')list=list.filter(r=>r.tracked&&r.risk!=='none');if(mode==='overdue')list=list.filter(r=>r.overdue);if(mode==='stalled')list=list.filter(r=>r.stalled);if(mode==='ready')list=list.filter(r=>r.ready_to_sell&&!r.first_job_completed);if(mode==='completed')list=list.filter(r=>r.first_job_completed);const s=summary(rows);$('launch-portfolio-count').textContent=`${s.tracked} tracked launch${s.tracked===1?'':'es'}`;$('launch-portfolio-summary').innerHTML=`<div><strong>${s.tracked}</strong><span>Tracked</span></div><div><strong>${s.ready}</strong><span>Ready to sell</span></div><div><strong>${s.overdue}</strong><span>Overdue</span></div><div><strong>${s.stalled}</strong><span>Stalled</span></div><div><strong>${s.at_risk}</strong><span>At risk</span></div><div><strong>${s.first_job_conversion_percent}%</strong><span>First-job conversion</span></div>`;
$('launch-portfolio-list').innerHTML=list.length?list.sort((a,b)=>({critical:0,high:1,attention:2,none:3}[a.risk]-({critical:0,high:1,attention:2,none:3}[b.risk]))||b.progress-a.progress).map(r=>`<article class="portfolio-row risk-${esc(r.risk)}"><div class="portfolio-main"><div class="module-title"><strong>${esc(r.name)}</strong><span class="pill ${r.risk==='none'?'verified':r.risk==='attention'?'warn':'danger'}">${esc(riskLabel(r.risk))}</span></div><div class="meta"><span>${r.progress}% launch progress</span><span>${r.evidence_count} demand signal${r.evidence_count===1?'':'s'}</span><span>${esc(statusText(r))}</span></div></div><div class="portfolio-account"><strong>${esc(r.owner||'Unassigned')}</strong><span>${r.target_date?`Target ${esc(r.target_date)}`:'No target date'}</span></div><div class="portfolio-stage"><strong>${esc(String(r.current_stage||'').replaceAll('_',' '))}</strong><span>Next: ${esc(String(r.next_stage||'complete').replaceAll('_',' '))}</span></div><div class="portfolio-blockers"><strong>${(r.blockers||[]).length}</strong><span>blocker${(r.blockers||[]).length===1?'':'s'}</span></div><div class="portfolio-actions"><button data-portfolio-open="${esc(r.service_line)}">Open launch plan</button></div>${(r.milestones||[]).length?`<details class="portfolio-history"><summary>Milestone history (${r.milestones.length})</summary>${[...r.milestones].reverse().slice(0,8).map(m=>`<div><strong>${esc(String(m.stage||'').replaceAll('_',' '))}</strong><span>${esc(m.progress)}%</span><time>${esc(new Date(m.recorded_at).toLocaleString())}</time></div>`).join('')}</details>`:''}</article>`).join(''):'<div class="empty">No service launches match this portfolio view.</div>';
document.querySelectorAll('[data-portfolio-open]').forEach(b=>b.onclick=()=>{const sel=$('service-launch-filter');if(sel){sel.value=b.dataset.portfolioOpen;sel.dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('.service-launch-planner')?.scrollIntoView({behavior:'smooth',block:'start'});}});}
async function init(){try{config=await fetch(chrome.runtime.getURL('titan-modules/cleaning-launch-portfolio.json')).then(r=>r.json());if(config.schema!=='titan-cleaning-launch-portfolio/v1')throw new Error('portfolio configuration is invalid');render();}catch(e){if($('launch-portfolio-notice'))$('launch-portfolio-notice').textContent=`Launch portfolio unavailable: ${e.message}`;}}
$('launch-portfolio-filter')?.addEventListener('change',render);['titan-cleaning-service-launch-plan-changed','titan-cleaning-growth-signals-changed','titan-marketplace-coverage-changed'].forEach(ev=>window.addEventListener(ev,render));window.addEventListener('titan-company-changed',init);
window.TitanCleaningServiceLaunchPortfolio=Object.freeze({getPortfolio:()=>{build();return rows.map(r=>({...r,grants_authority:false,publishes_service:false,executes_work:false}));},getSummary:()=>summary(build()),companyId:()=>company_id,grantsAuthority:false});init();})();
