// @ts-nocheck
// Ported from Titan Zero extension (browser-adapter-required): cleaning-growth-opportunity-intelligence.js
// QUARANTINE: not exported to standalone runtime until browser/DOM dependencies are adapted.
(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const SIGNAL_STORE='titanCleaningGrowthSignalsV1',GROWTH_STORE='titanCleaningGrowthMarketplaceV1',WF_STORE='titanCleaningWorkforceMarketplaceV1';
let config={service_lines:[]},catalog={products:[]},company_id='company-default',signals=[],growthState={products:{}},workerProducts=[],ownedWorkers=new Set(),coverage=new Set();
const norm=v=>String(v||'').trim().toLowerCase(),product=id=>catalog.products.find(p=>p.id===id),status=id=>growthState.products?.[id]?.status||'available';
async function load(){const x=await chrome.storage.local.get(['titanBusinessProfile',SIGNAL_STORE,GROWTH_STORE,WF_STORE]);company_id=String(x.titanBusinessProfile?.company_id||$('grant-company')?.value||'company-default').trim()||'company-default';signals=((x[SIGNAL_STORE]||{})[company_id]||[]).filter(s=>s&&s.company_id===company_id);growthState=(x[GROWTH_STORE]||{})[company_id]||{company_id,products:{}};workerProducts=window.TitanCleaningWorkforceProducts?.products||[];ownedWorkers=new Set();coverage=new Set();
for(const w of window.TitanCleaningWorkforce?.specialists||[]){ownedWorkers.add(w.id);for(const c of w.capabilities||[])coverage.add(c)}
const wf=(x[WF_STORE]||{})[company_id]?.products||{};for(const [id,s] of Object.entries(wf))if(['purchased','installed'].includes(s?.status)){ownedWorkers.add(id);for(const c of workerProducts.find(v=>v.id===id)?.capabilities||[])coverage.add(c)}
for(const [id,s] of Object.entries(growthState.products||{}))if(['installed','purchased','included'].includes(s?.status))for(const c of product(id)?.provides||[])coverage.add(c);
}
const productCovered=id=>{const p=product(id);if(!p)return false;if(['installed','purchased','included'].includes(status(id)))return true;return (p.provides||[]).length>0&&(p.provides||[]).every(c=>coverage.has(c));};
const money=(value,currency)=>{if(!(Number(value)>0))return 'No value recorded';const code=String(currency||'').trim().toUpperCase();return `${code?code+' ':''}${Number(value).toLocaleString(undefined,{maximumFractionDigits:2})}`;};
function matchingSignals(line){return signals.filter(s=>{const h=norm([s.subject,s.detail,s.service_line].filter(Boolean).join(' '));return h&&(line.terms||[]).some(t=>h.includes(norm(t)));});}
function opportunity(line){const evidence=matchingSignals(line),missingProducts=(line.required_products||[]).filter(id=>!productCovered(id)),missingWorkers=(line.required_workers||[]).filter(id=>!ownedWorkers.has(id));const total=(line.required_products||[]).length+(line.required_workers||[]).length,ready=total-missingProducts.length-missingWorkers.length,readiness=total?Math.round(ready/total*100):100;
const values=evidence.filter(s=>Number(s.estimated_value)>0),explicitValue=values.reduce((a,s)=>a+Number(s.estimated_value||0),0),currencies=[...new Set(values.map(s=>String(s.currency||'').trim().toUpperCase()).filter(Boolean))],currency=currencies.length===1?currencies[0]:currencies.length>1?'MIXED':'';
const lostCount=evidence.filter(s=>s.type==='enquiry_lost').length,tenderCount=evidence.filter(s=>s.type==='tender_opportunity').length,repeat=evidence.length>=2;
const priority=Math.min(100,(evidence.length*12)+(lostCount*10)+(tenderCount*8)+Math.round((100-readiness)*0.35)+(explicitValue>0?8:0));
return {line,evidence,missingProducts,missingWorkers,total,ready,readiness,explicitValue,currency,repeat,lostCount,tenderCount,priority};}
function opportunities(){return (config.service_lines||[]).map(opportunity).sort((a,b)=>b.priority-a.priority||b.evidence.length-a.evidence.length||a.line.name.localeCompare(b.line.name));}
function workerName(id){return (window.TitanCleaningWorkforce?.specialists||[]).find(w=>w.id===id)?.name||workerProducts.find(w=>w.id===id)?.name||id;}
function render(){let list=opportunities();const f=$('growth-opportunity-filter')?.value||'all';if(f!=='all')list=list.filter(o=>o.line.id===f);if($('growth-opportunity-demand-only')?.checked)list=list.filter(o=>o.evidence.length>0);
const demand=list.filter(o=>o.evidence.length>0),ready=list.filter(o=>o.readiness===100),value=demand.reduce((a,o)=>a+o.explicitValue,0),curr=[...new Set(demand.filter(o=>o.explicitValue>0).map(o=>o.currency).filter(Boolean))];
$('growth-opportunity-count').textContent=`${demand.length} evidence-backed opportunit${demand.length===1?'y':'ies'}`;
$('growth-opportunity-summary').innerHTML=`<div><strong>${demand.length}</strong><span>Demand-backed service lines</span></div><div><strong>${ready.length}</strong><span>100% ready</span></div><div><strong>${list.filter(o=>o.repeat).length}</strong><span>Repeated demand</span></div><div><strong>${value>0?esc(money(value,curr.length===1?curr[0]:curr.length>1?'MIXED':'')):'—'}</strong><span>Recorded opportunity value only</span></div>`;
$('growth-opportunity-list').innerHTML=list.length?list.map(o=>`<article class="supply-card growth-opportunity-card"><div class="supply-card-head"><div><div class="module-title"><strong>${esc(o.line.name)}</strong><span class="pill ${o.evidence.length?'verified':''}">${o.readiness}% ready</span></div><div class="meta"><span>${o.evidence.length} signal${o.evidence.length===1?'':'s'}${o.repeat?' · repeated demand':''}</span><span>Priority ${o.priority}/100</span></div></div></div><p><strong>Recorded opportunity:</strong> ${esc(money(o.explicitValue,o.currency))}. ${o.explicitValue?'This total uses only values explicitly entered with matching evidence.':'Titan will not estimate revenue without company evidence.'}</p><div class="growth-evidence"><strong>Launch readiness</strong><span>Known components ready: ${o.ready}/${o.total}</span>${o.missingProducts.slice(0,5).map(id=>`<span>• Missing product: ${esc(product(id)?.name||id)}</span>`).join('')}${o.missingWorkers.slice(0,5).map(id=>`<span>• Missing workforce: ${esc(workerName(id))}</span>`).join('')}${!o.missingProducts.length&&!o.missingWorkers.length?'<span>• Known Marketplace and Workforce requirements are covered.</span>':''}</div><div class="growth-evidence"><strong>Demand evidence</strong>${o.evidence.length?o.evidence.slice(0,3).map(s=>`<span>• ${esc(s.subject||s.detail||s.type)}${Number(s.estimated_value)>0?` — ${esc(money(s.estimated_value,s.currency))}`:''}</span>`).join(''):'<span>• No matching company evidence recorded yet.</span>'}</div><div class="purchase-actions">${o.line.launch_product?`<button class="featured" data-opportunity-open="${esc(o.line.launch_product)}">View launch pack</button>`:''}${o.line.crew_product?`<button data-opportunity-open="${esc(o.line.crew_product)}">View crew</button>`:''}</div></article>`).join(''):'<div class="empty">No opportunities match this view.</div>';
document.querySelectorAll('[data-opportunity-open]').forEach(b=>b.onclick=()=>{const p=product(b.dataset.opportunityOpen),q=$('growth-search');if(q&&p){q.value=p.name;q.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('.growth-marketplace')?.scrollIntoView({behavior:'smooth',block:'start'});}});
}
async function init(){try{[config,catalog]=await Promise.all([fetch(chrome.runtime.getURL('titan-modules/cleaning-growth-service-lines.json')).then(r=>r.json()),fetch(chrome.runtime.getURL('titan-modules/cleaning-growth-marketplace.json')).then(r=>r.json())]);if(config.schema!=='titan-cleaning-growth-service-lines/v1')throw new Error('service-line configuration is invalid');await load();$('growth-opportunity-filter').innerHTML='<option value="all">All opportunities</option>'+config.service_lines.map(l=>`<option value="${esc(l.id)}">${esc(l.name)}</option>`).join('');render();}catch(e){$('growth-opportunity-notice').textContent=`Opportunity intelligence unavailable: ${e.message}`;}}
$('growth-opportunity-filter')?.addEventListener('change',render);$('growth-opportunity-demand-only')?.addEventListener('change',render);window.addEventListener('titan-cleaning-growth-signals-changed',async()=>{await load();render()});window.addEventListener('titan-marketplace-coverage-changed',async()=>{await load();render()});window.addEventListener('titan-company-changed',init);
window.TitanCleaningGrowthOpportunities=Object.freeze({getOpportunities:()=>opportunities().map(o=>({service_line:o.line.id,evidence_count:o.evidence.length,readiness:o.readiness,recorded_value:o.explicitValue,currency:o.currency,missing_products:[...o.missingProducts],missing_workers:[...o.missingWorkers],priority:o.priority,grants_authority:false})),companyId:()=>company_id});init();})();
