// @ts-nocheck
// Ported from Titan Zero extension (browser-adapter-required): titan-electrical-workforce.js
// QUARANTINE: not exported to standalone runtime until browser/DOM dependencies are adapted.
/* Titan Zero Electrical Vertical Workforce v1.0
 * Module-owned electrical specialists layered over internal shared Workforce agents.
 * Role identity does not confer authority. Licensed/regulatory electrical work remains gated.
 */
(() => {
  const mk=(id,name,department,purpose,capabilities,opts={})=>({
    id,roleDefinitionId:id,role_definition_id:id,name,displayName:`Electrical · ${name}`,icon:'⚡',department,
    division_key:department,purpose,description:purpose,capabilities,operational_domains:capabilities,
    autonomy:'governed',riskCeiling:opts.riskCeiling||'MEDIUM',risk_ceiling:opts.riskCeiling||'MEDIUM',
    min_business_tier:'SOLO',vertical:'electrical',verticals:['electrical'],companyBoundary:'company_id',company_boundary:'company_id',
    activationConfersAuthority:false,activation_confers_authority:false,source:'Titan Workforce Verticals · Electrical v1',
    evidenceRequired:opts.evidenceRequired||[],approvalRequiredFor:opts.approvalRequiredFor||[],licensedWork:opts.licensedWork!==false
  });

  const SPECIALISTS=[
    mk('titan.electrical.scope_assessor','Electrical Scope Assessor','sales','Define electrical job scope from customer symptoms, photos, equipment/site details, access constraints and known exclusions without treating remote observations as a field diagnosis.',['electrical_scope','photo_scope','site_details','equipment_details','access_constraints','quote_inputs'],{evidenceRequired:['customer_scope','site_or_photo_evidence'],licensedWork:false}),
    mk('titan.electrical.quote_specialist','Electrical Quote Specialist','sales','Prepare transparent electrical quote inputs, labour/material assumptions, exclusions and provisional allowances from an approved scope.',['electrical_quote','labour_estimate','materials_allowance','scope_assumptions','quote_options'],{approvalRequiredFor:['price_override','discount_outside_policy'],licensedWork:false}),
    mk('titan.electrical.fault_triage','Electrical Fault Triage Specialist','technical','Triage electrical symptoms, urgency and evidence without presenting remote reasoning as licensed field diagnosis or test results.',['electrical_fault','symptom_triage','urgency','evidence_request','job_classification'],{riskCeiling:'HIGH',licensedWork:false}),
    mk('titan.electrical.emergency_no_power','Emergency & No-Power Coordinator','operations','Coordinate no-power, burning smell, sparking, exposed-damage and urgent electrical events, prioritising safe attendance and hazard escalation.',['electrical_emergency','no_power','burning_smell','sparking','priority_dispatch','hazard_escalation'],{riskCeiling:'HIGH',evidenceRequired:['safe_customer_observation']}),
    mk('titan.electrical.switchboard','Switchboard & Protection Coordinator','work','Coordinate switchboard, breaker, RCD and protection-device scope and evidence for qualified attendance.',['switchboard','breaker','rcd','protection_device','job_scope','test_evidence'],{riskCeiling:'HIGH',evidenceRequired:['switchboard_or_fault_record']}),
    mk('titan.electrical.circuit_outlet','Circuit & Outlet Coordinator','work','Coordinate circuit, socket/outlet and local power faults with affected areas, symptoms, equipment context and field-test evidence.',['circuit','outlet','socket','power_fault','affected_area','field_test_evidence'],{riskCeiling:'HIGH',evidenceRequired:['affected_area_record']}),
    mk('titan.electrical.lighting','Lighting Coordinator','work','Scope lighting faults, replacements and additions with room/location, fitting type, controls and approved installation requirements.',['lighting','light_fixture','switch','lighting_scope','installation_inputs'],{evidenceRequired:['lighting_scope_or_photo']}),
    mk('titan.electrical.installation','Electrical Installation Coordinator','work','Plan qualified electrical installation work from approved scope, equipment requirements, circuits, access, dependencies and evidence.',['electrical_installation','new_circuit','equipment_connection','installation_plan','dependencies'],{riskCeiling:'HIGH',evidenceRequired:['approved_scope']}),
    mk('titan.electrical.quality_inspector','Electrical Quality Inspector','quality','Review approved scope, field test results, completion photos, defects, labels/certificates where applicable and unresolved issues before closure.',['electrical_qc','test_result_review','photo_qa','defect_review','completion_gate','certificate_evidence'],{riskCeiling:'HIGH',evidenceRequired:['completion_photos','field_test_result']}),
    mk('titan.electrical.parts_materials','Electrical Materials & Parts Coordinator','assets','Plan and track approved electrical materials such as cable, breakers, protection devices, outlets, fittings and consumables against scope.',['electrical_parts','materials_plan','cable','breakers','outlets','stock_check'],{licensedWork:false}),
    mk('titan.electrical.preventive_maintenance','Preventive Electrical Maintenance Coordinator','work','Plan recurring electrical inspection and preventive maintenance from assets, service history and company/customer requirements.',['preventive_electrical','maintenance_schedule','inspection_plan','service_history','recurring_service'],{licensedWork:false}),
    mk('titan.electrical.safety_compliance','Electrical Safety & Compliance Coordinator','compliance','Track licensed-electrician requirements, field isolation/verification evidence, certificates and compliance handoffs without inventing jurisdictional requirements.',['electrical_safety','licensed_worker','isolation_evidence','certificate_tracking','compliance_handoff'],{riskCeiling:'HIGH',evidenceRequired:['licensed_worker_identity','required_compliance_evidence'],licensedWork:false}),
    mk('titan.electrical.service_recovery','Electrical Service Recovery Specialist','customer','Investigate electrical complaints, compare promised scope with evidence and coordinate governed rework or customer recovery.',['electrical_complaint','scope_comparison','rework_plan','customer_recovery'],{riskCeiling:'MEDIUM',evidenceRequired:['customer_issue','original_scope','completion_evidence'],licensedWork:false}),
    mk('titan.electrical.energy_efficiency','Energy Efficiency Coordinator','environment','Identify evidence-based lighting, controls and electrical energy-efficiency opportunities from verified usage and asset information without compromising safety or compliance.',['energy_efficiency','lighting_efficiency','controls','consumption_baseline','verified_savings'],{licensedWork:false})
  ];
  const byId=Object.fromEntries(SPECIALISTS.map(x=>[x.id,x]));

  const jt=(id,label,checklist,requiredEvidence,opts={})=>({id,label,checklist,requiredEvidence,licensedWorkerRequired:opts.licensedWorkerRequired!==false,isolationVerificationRequired:opts.isolationVerificationRequired!==false});
  const JOB_TYPES={
    fault_no_power:jt('fault_no_power','Fault / no-power response',['record affected area and symptoms using safe observations only','record visible/smell/sound hazard indicators without approaching exposed live parts','prioritise qualified attendance according to risk','licensed electrician establishes safe isolation/test state in field','diagnose and perform authorised work','record field test outcome, residual risk and completion evidence'],['safe_customer_observation','licensed_attendance_evidence','field_test_result','completion_or_followup_record']),
    switchboard_protection:jt('switchboard_protection','Switchboard / protection work',['record symptoms, affected circuits and protection-device behaviour','capture safe external identifiers/photos only where appropriate','confirm approved scope and qualified attendance','licensed electrician establishes isolation/test conditions','perform authorised switchboard/protection work','record required test/certificate/completion evidence'],['fault_or_scope_record','licensed_work_evidence','field_test_result','completion_or_certificate_evidence']),
    circuit_outlet:jt('circuit_outlet','Circuit / outlet work',['record affected outlets/circuit/area and symptoms','record connected equipment context when relevant','confirm approved scope','licensed electrician isolates/tests and performs authorised work','verify field test outcome','capture completion evidence and unresolved exceptions'],['affected_area_record','licensed_work_evidence','field_test_result']),
    lighting:jt('lighting','Lighting work',['confirm room/location, fitting and control requirements','record existing condition/photo where safe','confirm approved replacement/addition scope','licensed electrician performs applicable wiring/installation work','record functional/electrical field verification','capture completion evidence'],['lighting_scope_or_photo','licensed_work_evidence','field_verification']),
    installation:jt('installation','Electrical installation',['confirm approved design/scope and equipment requirements','record site/access/dependency information','confirm materials and qualified worker readiness','licensed electrician establishes safe work/isolation conditions','perform authorised installation and required tests','record test/certificate/completion evidence and follow-up items'],['approved_scope','installation_evidence','field_test_result','completion_or_certificate_evidence']),
    preventive_maintenance:jt('preventive_maintenance','Preventive electrical maintenance',['confirm asset/circuit/equipment register and history','define inspection/service scope','identify known faults and critical dependencies','licensed electrician performs required field inspection/testing','record defects, results and recommended follow-up','schedule next review from verified outcome'],['asset_or_equipment_record','inspection_or_test_evidence','maintenance_outcome'])
  };

  const classifyJobType=outcome=>{const t=String(outcome||'').toLowerCase();if(/no power|power outage|burning smell|sparking|electrical emergency|electric shock|exposed wire/.test(t))return JOB_TYPES.fault_no_power;if(/switchboard|breaker|rcd|safety switch|protection device/.test(t))return JOB_TYPES.switchboard_protection;if(/outlet|socket|power point|circuit/.test(t))return JOB_TYPES.circuit_outlet;if(/light|lighting|downlight|luminaire/.test(t))return JOB_TYPES.lighting;if(/install|new circuit|equipment connection|upgrade/.test(t))return JOB_TYPES.installation;if(/prevent|maintenance|inspection plan|recurring/.test(t))return JOB_TYPES.preventive_maintenance;return null;};

  const RULES=[
    [/\b(quote|quotation|price|estimate).*\b(assumption|exclusion|electric|job)?/i,'titan.electrical.quote_specialist'],
    [/\b(compliance|certificate|licensed|licence|permit|isolation|inspection requirement)\b/i,'titan.electrical.safety_compliance'],
    [/\b(energy efficiency|energy saving|lighting efficiency|consumption|usage baseline)\b/i,'titan.electrical.energy_efficiency'],
    [/\b(post.?work|completion|test results?|quality|qc|defect|completion photos?)\b/i,'titan.electrical.quality_inspector'],
    [/\b(scope|site details?|assess .*job)\b|\bphotos?\b.*\b(scope|customer notes?)\b/i,'titan.electrical.scope_assessor'],
    [/\b(no power|power outage|burning smell|sparking|electrical emergency|electric shock|exposed wire)\b/i,'titan.electrical.emergency_no_power'],
    [/\b(switchboard|breaker|rcd|safety switch|protection device|tripping)\b/i,'titan.electrical.switchboard'],
    [/\b(install|installation|new circuit|equipment connection|electrical upgrade)\b/i,'titan.electrical.installation'],
    [/\b(outlet|socket|power point|circuit|dead outlet)\b/i,'titan.electrical.circuit_outlet'],
    [/\b(light|lighting|downlight|luminaire)\b/i,'titan.electrical.lighting'],
    [/\b(parts?|materials?|cable|breakers?|outlets?|fittings?|stock|order)\b/i,'titan.electrical.parts_materials'],
    [/\b(preventive|preventative|recurring|maintenance plan|scheduled maintenance)\b/i,'titan.electrical.preventive_maintenance'],
    [/\b(complaint|rework|unhappy|service recovery|failed .*repair)\b/i,'titan.electrical.service_recovery'],
    [/\b(diagnos|triage|symptom|fault)\b/i,'titan.electrical.fault_triage']
  ];
  const route=(outcome,preferredId=null)=>{if(preferredId&&byId[preferredId])return byId[preferredId];const t=String(outcome||'');for(const [re,id] of RULES)if(re.test(t))return byId[id];return byId['titan.electrical.fault_triage'];};

  const executionContract=(worker,outcome)=>{const job=classifyJobType(outcome);const evidence=[...(worker?.evidenceRequired||[]),...(job?.requiredEvidence||[])];return `ELECTRICAL WORKFORCE ASSIGNMENT\nWorker: ${worker?.name||'Electrical Worker'}\nCompany boundary: company_id\nCapabilities: ${(worker?.capabilities||[]).join(', ')}\n\nElectrical operating contract:\n- Work toward the requested operational outcome and preserve evidence.\n- Remote observations are triage/scope inputs only; they are not a substitute for licensed electrical diagnosis, isolation, testing or certification.\n- Consequential electrical work must be performed or confirmed by an appropriately licensed/authorised field worker under applicable local requirements.\n- Do not instruct an unqualified person to access switchboards, exposed conductors, live parts, perform electrical isolation, reset repeatedly tripping protection, or carry out hazardous tests.\n- Electrical isolation and test state must come from qualified field evidence where the job requires it.\n- Do not claim a repair, isolation, test, certificate, booking, purchase, message, invoice or other mutation happened without an authoritative result/receipt.\n- Do not mark work complete when required evidence, field verification, licensed-worker confirmation, isolation verification or material scope remains unresolved.\n- Escalate shock, arcing/sparking, burning smell, exposed conductors, fire/smoke, water interaction and other electrical hazards.\n${job?`- Job type: ${job.label}.\n- Checklist: ${job.checklist.join('; ')}.\n`:''}${evidence.length?`- Evidence expected: ${[...new Set(evidence)].join('; ')}.\n`:''}\nRequested outcome:\n${String(outcome||'').trim()}`;};

  const validateCompletion=({jobType,checklistCompleted=[],evidence=[],unresolved=[],licensedWorkerConfirmed=false,isolationVerified=false}={})=>{const job=JOB_TYPES[jobType];const errors=[];if(!job)errors.push('known-electrical-job-type-required');if(job&&checklistCompleted.length<job.checklist.length)errors.push('electrical-checklist-incomplete');if(job&&evidence.length<job.requiredEvidence.length)errors.push('required-evidence-missing');if(job?.licensedWorkerRequired&&!licensedWorkerConfirmed)errors.push('licensed-worker-confirmation-required');if(job?.isolationVerificationRequired&&!isolationVerified)errors.push('electrical-isolation-verification-required');if(unresolved?.length)errors.push('unresolved-electrical-exceptions');return {valid:errors.length===0,errors};};
  const buildJobPlan=({jobType,outcome='',constraints=[]}={})=>{const job=JOB_TYPES[jobType]||classifyJobType(outcome)||JOB_TYPES.fault_no_power;return {job_type:job.id,label:job.label,checklist:[...job.checklist],required_evidence:[...job.requiredEvidence],licensed_worker_required:job.licensedWorkerRequired,isolation_verification_required:job.isolationVerificationRequired,constraints:[...constraints],company_boundary:'company_id'};};

  window.TitanElectricalWorkforce={version:'1.0.0',specialists:SPECIALISTS,byId,jobTypes:JOB_TYPES,route,classifyJobType,executionContract,validateCompletion,buildJobPlan};
  try{chrome.storage.local.set({titanElectricalWorkforceVersion:'1.0.0',titanElectricalSpecialistCount:SPECIALISTS.length,titanElectricalJobTypeCount:Object.keys(JOB_TYPES).length})}catch{}
})();
