// @ts-nocheck
// Ported from Titan Zero extension (portable-core): titan-settings/control-plane/approval-policy-settings.mjs
const LEGACY_ALIASES=['tenant_id','tenant_company_id'];
export const APPROVAL_POLICY_LEVELS=Object.freeze(['runtime-default','review','approval','human-only']);
const RISK_LEVELS=Object.freeze(['none','low','medium','high','critical']);
const RANK=Object.freeze({'runtime-default':0,review:1,approval:2,'human-only':3,none:0});
function company(input){if(!input||typeof input!=='object')throw new Error('approval-policy-settings-input-required');for(const k of LEGACY_ALIASES)if(k in input)throw new Error(`legacy-company-boundary-alias-forbidden:${k}`);const id=String(input.company_id??'').trim();if(!id)throw new Error('company_id-required');return id;}
function level(v,fallback='runtime-default'){const x=String(v??fallback).trim().toLowerCase().replaceAll('_','-');if(!APPROVAL_POLICY_LEVELS.includes(x))throw new Error(`approval-policy-level-invalid:${x}`);return x;}
function stronger(a,b){return (RANK[a]??0)>=(RANK[b]??0)?a:b;}
function overrides(raw){if(raw==null)return Object.freeze({});if(typeof raw!=='object'||Array.isArray(raw))throw new Error('approval-capability-overrides-invalid');const out={};for(const [k,v] of Object.entries(raw)){const key=String(k).trim();if(key)out[key]=level(v);}return Object.freeze(out);}
export function projectApprovalPolicySettings(input){const company_id=company(input);const s=input.settings&&typeof input.settings==='object'?input.settings:{};const raw=s.approvalPolicySettings&&typeof s.approvalPolicySettings==='object'?s.approvalPolicySettings:{};const risks=raw.risk_levels&&typeof raw.risk_levels==='object'?raw.risk_levels:{};const risk_levels={};for(const r of RISK_LEVELS)risk_levels[r]=level(risks[r],'runtime-default');return Object.freeze({schema_version:'1.0',company_id,default_level:level(raw.default_level),risk_levels:Object.freeze(risk_levels),protected_actions:level(raw.protected_actions,'approval'),capability_overrides:overrides(raw.capability_overrides),require_fresh_auth:raw.require_fresh_auth===true,require_separation_of_duties:raw.require_separation_of_duties!==false,settings_can_satisfy_approval:false,settings_can_create_approval:false,settings_can_relax_runtime_requirement:false,grants_authority:false,execution_permitted:false});}
export function buildApprovalRequirementProjection(input){const company_id=company(input);const p=input.projected_settings;if(!p||p.company_id!==company_id)throw new Error('approval-policy-settings-company-mismatch');const capability=String(input.capability??'').trim();if(!capability)throw new Error('capability-required');const risk=String(input.risk??'none').trim().toLowerCase();if(!RISK_LEVELS.includes(risk))throw new Error('risk-invalid');const protected_action=input.protected_action===true;let effective=level(p.default_level);const reasons=[];const riskLevel=level(p.risk_levels?.[risk]);if(RANK[riskLevel]>RANK[effective]){effective=riskLevel;reasons.push('settings_risk_approval_floor');}if(protected_action&&RANK[p.protected_actions]>RANK[effective]){effective=p.protected_actions;reasons.push('settings_protected_action_approval_floor');}const cap=p.capability_overrides?.[capability];if(cap&&RANK[cap]>RANK[effective]){effective=cap;reasons.push('settings_capability_approval_floor');}return Object.freeze({schema_version:'1.0',company_id,capability,risk,protected_action,effective_requirement_level:effective,require_fresh_auth:p.require_fresh_auth,require_separation_of_duties:p.require_separation_of_duties,reason_codes:Object.freeze(reasons),settings_can_approve:false,settings_can_satisfy_approval:false,grants_authority:false,execution_permitted:false});}
export function evaluateApprovalPolicyRequirement(input){const company_id=company(input);const p=input.projection;const runtime=input.runtime_requirement;if(!p||p.company_id!==company_id||!runtime||String(runtime.company_id??'')!==company_id)throw new Error('approval-policy-company-mismatch');const runtimeLevel=String(runtime.requirement_level??'none').trim().toLowerCase().replaceAll('_','-');if(!(runtimeLevel in RANK))throw new Error(`runtime-requirement-level-invalid:${runtimeLevel}`);const settingsLevel=p.effective_requirement_level;const finalLevel=stronger(runtimeLevel,settingsLevel);const reasons=[...(Array.isArray(runtime.reason_codes)?runtime.reason_codes:[]),...(p.reason_codes??[])];if(finalLevel!==runtimeLevel)reasons.push('settings_increased_approval_requirement');return Object.freeze({schema_version:'1.0',company_id,capability:p.capability,runtime_requirement_level:runtimeLevel,settings_requirement_level:settingsLevel,requirement_level:finalLevel,authority_required:runtime.authority_required===true||RANK[finalLevel]>=RANK.review,require_fresh_auth:p.require_fresh_auth,require_separation_of_duties:p.require_separation_of_duties,reason_codes:Object.freeze([...new Set(reasons)]),projection_only:true,approval_satisfied:false,authority_granted:false,execution_permitted:false,settings_relaxed_runtime_requirement:false});}
