import test from 'node:test'; import assert from 'node:assert/strict'; import path from 'node:path'; import {pathToFileURL} from 'node:url';
const root=process.cwd(); const runner=await import(pathToFileURL(path.join(root,'packages/.tmp-business-workflows-build/runner-contract.js')).href); const state=await import(pathToFileURL(path.join(root,'packages/.tmp-business-workflows-build/execution-state.js')).href);
const plan=()=>runner.buildTitanBusinessWorkflowRunPlan({workflowId:'create_quote_v1',companyId:'c1',actorId:'u1',correlationId:'corr-1',idempotencyKey:'idem-1',input:{customer_id:'x'}});

test('execution state preserves correlation and idempotency across restart',()=>{const s=state.createTitanBusinessWorkflowExecutionState({plan:plan(),maxAttempts:3}); assert.equal(s.idempotency_key,'idem-1'); assert.equal(s.correlation_id,'corr-1'); assert.equal(state.assertTitanBusinessWorkflowResume(s,{companyId:'c1',correlationId:'corr-1',idempotencyKey:'idem-1'}),s);});
test('revision conflicts fail closed',()=>{const s=state.createTitanBusinessWorkflowExecutionState({plan:plan()}); assert.throws(()=>state.transitionTitanBusinessWorkflowExecutionState({state:s,expectedRevision:1,event:{eventId:'e1',type:'START'}}),/revision-conflict/);});
test('duplicate event id is deterministic no-op',()=>{let s=state.createTitanBusinessWorkflowExecutionState({plan:plan()}); s=state.transitionTitanBusinessWorkflowExecutionState({state:s,expectedRevision:0,event:{eventId:'e1',type:'START'}}); const again=state.transitionTitanBusinessWorkflowExecutionState({state:s,expectedRevision:999,event:{eventId:'e1',type:'START'}}); assert.equal(again,s);});
test('retry reuses idempotency key and respects bounded retry budget',()=>{let s=state.createTitanBusinessWorkflowExecutionState({plan:plan(),maxAttempts:2}); s=state.transitionTitanBusinessWorkflowExecutionState({state:s,expectedRevision:0,event:{eventId:'e1',type:'START'}}); s=state.transitionTitanBusinessWorkflowExecutionState({state:s,expectedRevision:1,event:{eventId:'e2',type:'RETRYABLE_FAILURE',errorCode:'timeout'}}); assert.equal(s.status,'RETRY_WAIT'); const idem=s.idempotency_key; s=state.transitionTitanBusinessWorkflowExecutionState({state:s,expectedRevision:2,event:{eventId:'e3',type:'START'}}); assert.equal(s.idempotency_key,idem); s=state.transitionTitanBusinessWorkflowExecutionState({state:s,expectedRevision:3,event:{eventId:'e4',type:'RETRYABLE_FAILURE',errorCode:'timeout'}}); assert.equal(s.status,'FAILED_FINAL'); assert.equal(s.attempt,2);});
test('resume rejects company, correlation, and idempotency drift',()=>{const s=state.createTitanBusinessWorkflowExecutionState({plan:plan()}); assert.throws(()=>state.assertTitanBusinessWorkflowResume(s,{companyId:'c2',correlationId:'corr-1',idempotencyKey:'idem-1'}),/company-mismatch/); assert.throws(()=>state.assertTitanBusinessWorkflowResume(s,{companyId:'c1',correlationId:'corr-2',idempotencyKey:'idem-1'}),/correlation-mismatch/); assert.throws(()=>state.assertTitanBusinessWorkflowResume(s,{companyId:'c1',correlationId:'corr-1',idempotencyKey:'idem-2'}),/idempotency-mismatch/);});
test('terminal success cannot be mutated by a later distinct event',()=>{let s=state.createTitanBusinessWorkflowExecutionState({plan:plan()}); s=state.transitionTitanBusinessWorkflowExecutionState({state:s,expectedRevision:0,event:{eventId:'e1',type:'START'}}); s=state.transitionTitanBusinessWorkflowExecutionState({state:s,expectedRevision:1,event:{eventId:'e2',type:'SUCCEEDED',resultRef:'quote-1'}}); assert.equal(s.status,'SUCCEEDED'); assert.equal(s.result_ref,'quote-1'); assert.throws(()=>state.transitionTitanBusinessWorkflowExecutionState({state:s,expectedRevision:2,event:{eventId:'e3',type:'FINAL_FAILURE'}}),/workflow-state-terminal/);});
