import Link from "next/link";
import styles from "../marketing.module.css";
export const metadata={title:"Cleaning Operations Assessment",description:"Review cleaning service setup, configured prices, visits, checklists and repetitive office work."};
export default function AssessmentPage(){return <main className={styles.page}>
<header className={styles.header}><Link href="/" className={styles.brand}><span>T0</span><strong>TITAN ZERO<small>CLEANING OPERATIONS ASSESSMENT</small></strong></Link><nav><Link href="/">Home</Link><Link href="/app" className={styles.cta}>Open Titan Zero →</Link></nav></header>
<section className={styles.hero}><div className={styles.heroCopy}><p className={styles.kicker}>CLEANING FIRST-RELEASE REVIEW</p><h1>Find the admin slowing down each cleaning job.</h1><p className={styles.lede}>Review how a cleaning request becomes a scoped service, a company-priced job, a scheduled visit and a recorded outcome. Start with the cleaning configuration and native field-service workflows already in Titan.</p><div className={styles.actions}><Link href="/app">Open Titan Zero</Link><a href="#assessment">What we assess</a></div></div><div className={styles.command}><div className={styles.commandTop}><span>CLEANING / REVIEW</span><i>EXAMPLE</i></div><div className={styles.chatAI}><small>START WITH</small><p>Where do service scope, configured prices, access details or completion notes have to be copied or chased?</p></div><div className={styles.cards}><article><b>01</b><span>scope service</span></article><article><b>02</b><span>plan visit</span></article><article><b>03</b><span>record outcome</span></article></div></div></section>
<section className={styles.section} id="assessment"><p className={styles.kicker}>WHAT WE ASSESS</p><h2>Follow the work from setup through the visit.</h2><div className={styles.grid}><article><span>01</span><h3>Services and scope</h3><p>Which supported cleaning services do you offer, and how are inclusions, exclusions and property details captured?</p></article><article><span>02</span><h3>Pricing and quotes</h3><p>Are fixed prices and hourly rates configured by your company, and which work must remain quote-required?</p></article><article><span>03</span><h3>Visits and recurrence</h3><p>How are service areas, working hours, recurring visits, access and team capacity coordinated?</p></article><article><span>04</span><h3>Checklists and exceptions</h3><p>Can cleaners see the visit checklist and record completion notes, photos or issues for owner review?</p></article></div></section>
<section className={styles.dark}><div><p className={styles.kicker}>USE THE EXISTING NATIVE WORKFLOW</p><h2>Keep company setup separate from business authority.</h2><p>Cleaning setup configures service types and company-provided prices. Jobs, schedules, checklists, completion, invoices and customer communication continue through their existing company-scoped and governed owners.</p></div><div className={styles.flow}><span>Service setup</span><b>→</b><span>Job scope</span><b>→</b><span>Visit</span><b>→</b><span>Checklist</span></div></section>
<section className={styles.final}><p>CLEANING FIRST. CONFIGURED BY YOUR COMPANY.</p><h2>Start with the services and operations your team is ready to deliver.</h2><Link href="/app">Enter Titan Zero →</Link></section></main>}
