export const PERSONAL_ZERO_PROTOCOL = "titan.personal-zero.v1";
export const PERSONAL_ZERO_VERSION = 1 as const;
export type PersonalZeroPrivacyClass = "personal_private" | "company_restricted" | "shareable";
export type UnderstandingStatus = "candidate" | "accepted" | "superseded" | "expired" | "deleted";
export type CognitiveEventType = "observation"|"recommendation"|"correction"|"approval"|"rejection"|"decision"|"action"|"outcome"|"prediction"|"prediction_scored"|"understanding_candidate"|"understanding_accepted"|"understanding_superseded";
export type OneIdentity=Readonly<{one_id:string;zero_id:string}>;
export type ZeroIdentity=Readonly<{zero_id:string;one_id:string;protocol:typeof PERSONAL_ZERO_PROTOCOL;created_at:number}>;
export type CompanyRelationship=Readonly<{relationship_id:string;one_id:string;zero_id:string;company_id:string;role_refs:readonly string[];capability_refs:readonly string[];authority_refs:readonly string[];data_visibility_refs:readonly string[];status:"active"|"revoked";activated_at:number;revoked_at:number|null}>;
export type EvidenceReference=Readonly<{evidence_id:string;source:string;provenance_ref:string}>;
export type UnderstandingEvidence=Readonly<{understanding_evidence_id:string;one_id:string;zero_id:string;company_id:string;relationship_id:string|null;subject:string;value:unknown;evidence:readonly EvidenceReference[];confidence:number;observed_at:number;fresh_until:number|null;privacy_class:PersonalZeroPrivacyClass;provider_egress_allowed:boolean;correction_of:string|null}>;
export type UnderstandingState=Readonly<{understanding_id:string;one_id:string;zero_id:string;company_id:string;relationship_id:string|null;subject:string;value:unknown;status:UnderstandingStatus;evidence_refs:readonly string[];confidence:number;version:number;supersedes_understanding_id:string|null;created_at:number;updated_at:number}>;
export type ExperienceRecord=Readonly<{experience_id:string;one_id:string;zero_id:string;company_id:string;relationship_id:string|null;context_refs:readonly string[];decision_ref:string|null;action_ref:string|null;expected_outcome:unknown;verified_outcome_ref:string|null;actual_outcome:unknown;unintended_effects:readonly unknown[];lesson:unknown;confidence:number;future_applicability:readonly string[];created_at:number}>;
export type PredictionCalibration=Readonly<{prediction_event_id:string;outcome_event_id:string;predicted_probability:number;actual:boolean;brier_score:number;scored_at:number;authority_neutral:true}>;
export type CrossContextShareGrant=Readonly<{grant_id:string;one_id:string;zero_id:string;source_company_id:string;source_relationship_id:string;target_company_id:string;target_relationship_id:string;subject_refs:readonly string[];purpose:string;consent_ref:string;allow_personal_private:false;expires_at:number|null;revoked_at:number|null;created_at:number;authority_neutral:true}>;
export type RetentionPolicy=Readonly<{retain_until:number|null;delete_after_expiry:boolean}>;
export type CognitiveEvent=Readonly<{event_id:string;one_id:string;zero_id:string;company_id:string;relationship_id:string|null;type:CognitiveEventType;payload:unknown;evidence_refs:readonly string[];confidence:number;privacy_class:PersonalZeroPrivacyClass;parent_event_id:string|null;correlation_id:string|null;operation_id:string|null;occurred_at:number;authority_neutral:true;execution_authority:false}>;
const cleanId=(value:unknown,field:string)=>{const out=String(value??"").trim();if(!out)throw new Error(`${field} is required`);return out};
const validConfidence=(value:unknown)=>{const out=Number(value);if(!Number.isFinite(out)||out<0||out>1)throw new Error("confidence must be between 0 and 1");return out};
export function createOneIdentity(input:{one_id:string;zero_id:string}):OneIdentity{return Object.freeze({one_id:cleanId(input.one_id,"one_id"),zero_id:cleanId(input.zero_id,"zero_id")})}
export function createZeroIdentity(input:{zero_id:string;one_id:string;created_at?:number}):ZeroIdentity{return Object.freeze({zero_id:cleanId(input.zero_id,"zero_id"),one_id:cleanId(input.one_id,"one_id"),protocol:PERSONAL_ZERO_PROTOCOL,created_at:Number(input.created_at??Date.now())})}
export function createCompanyRelationship(input:Omit<CompanyRelationship,"status"|"revoked_at"> & {status?:"active"|"revoked";revoked_at?:number|null}):CompanyRelationship{const status=input.status??"active";return Object.freeze({...input,relationship_id:cleanId(input.relationship_id,"relationship_id"),one_id:cleanId(input.one_id,"one_id"),zero_id:cleanId(input.zero_id,"zero_id"),company_id:cleanId(input.company_id,"company_id"),role_refs:Object.freeze([...input.role_refs]),capability_refs:Object.freeze([...input.capability_refs]),authority_refs:Object.freeze([...input.authority_refs]),data_visibility_refs:Object.freeze([...input.data_visibility_refs]),status,revoked_at:status==="revoked"?Number(input.revoked_at??Date.now()):null})}
export function createUnderstandingEvidence(input:UnderstandingEvidence):UnderstandingEvidence{return Object.freeze({...input,understanding_evidence_id:cleanId(input.understanding_evidence_id,"understanding_evidence_id"),one_id:cleanId(input.one_id,"one_id"),zero_id:cleanId(input.zero_id,"zero_id"),company_id:cleanId(input.company_id,"company_id"),confidence:validConfidence(input.confidence),evidence:Object.freeze([...input.evidence]),provider_egress_allowed:input.privacy_class==="personal_private"?false:Boolean(input.provider_egress_allowed)})}
export function createUnderstandingState(input:UnderstandingState):UnderstandingState{if(input.status==="accepted"&&!input.evidence_refs.length)throw new Error("accepted understanding requires evidence");return Object.freeze({...input,understanding_id:cleanId(input.understanding_id,"understanding_id"),one_id:cleanId(input.one_id,"one_id"),zero_id:cleanId(input.zero_id,"zero_id"),company_id:cleanId(input.company_id,"company_id"),confidence:validConfidence(input.confidence),evidence_refs:Object.freeze([...input.evidence_refs])})}
export function createExperienceRecord(input:ExperienceRecord):ExperienceRecord{if(input.actual_outcome!=null&&!input.verified_outcome_ref)throw new Error("actual outcome requires verified_outcome_ref");return Object.freeze({...input,experience_id:cleanId(input.experience_id,"experience_id"),one_id:cleanId(input.one_id,"one_id"),zero_id:cleanId(input.zero_id,"zero_id"),company_id:cleanId(input.company_id,"company_id"),confidence:validConfidence(input.confidence),context_refs:Object.freeze([...input.context_refs]),unintended_effects:Object.freeze([...input.unintended_effects]),future_applicability:Object.freeze([...input.future_applicability])})}
export function createCognitiveEvent(input:Omit<CognitiveEvent,"authority_neutral"|"execution_authority">):CognitiveEvent{return Object.freeze({...input,event_id:cleanId(input.event_id,"event_id"),one_id:cleanId(input.one_id,"one_id"),zero_id:cleanId(input.zero_id,"zero_id"),company_id:cleanId(input.company_id,"company_id"),confidence:validConfidence(input.confidence),evidence_refs:Object.freeze([...input.evidence_refs]),authority_neutral:true,execution_authority:false})}

export function scorePrediction(input:{prediction_event_id:string;outcome_event_id:string;predicted_probability:number;actual:boolean;scored_at?:number}):PredictionCalibration{const p=validConfidence(input.predicted_probability);const y=input.actual?1:0;return Object.freeze({...input,predicted_probability:p,brier_score:(p-y)**2,scored_at:Number(input.scored_at??Date.now()),authority_neutral:true})}
export function createCrossContextShareGrant(input:Omit<CrossContextShareGrant,"authority_neutral"|"allow_personal_private"> & {allow_personal_private?:false}):CrossContextShareGrant{if(input.source_company_id===input.target_company_id&&input.source_relationship_id===input.target_relationship_id)throw new Error("cross-context share requires distinct contexts");if(!input.subject_refs.length)throw new Error("cross-context share requires subject_refs");if(input.allow_personal_private!==undefined&&input.allow_personal_private!==false)throw new Error("personal_private cross-context sharing requires a stronger consent contract");return Object.freeze({...input,grant_id:cleanId(input.grant_id,"grant_id"),one_id:cleanId(input.one_id,"one_id"),zero_id:cleanId(input.zero_id,"zero_id"),source_company_id:cleanId(input.source_company_id,"source_company_id"),source_relationship_id:cleanId(input.source_relationship_id,"source_relationship_id"),target_company_id:cleanId(input.target_company_id,"target_company_id"),target_relationship_id:cleanId(input.target_relationship_id,"target_relationship_id"),subject_refs:Object.freeze([...input.subject_refs]),purpose:cleanId(input.purpose,"purpose"),consent_ref:cleanId(input.consent_ref,"consent_ref"),allow_personal_private:false,authority_neutral:true})}
export function isFresh(fresh_until:number|null,now=Date.now()){return fresh_until==null||fresh_until>now}
export function isRetained(policy:RetentionPolicy,now=Date.now()){return policy.retain_until==null||policy.retain_until>now}
