import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createPaymentsCommunicationsSetupAuthority} from '../titan-onboarding/runtime/payments-communications-setup.mjs';
const native=JSON.parse(fs.readFileSync(new URL('../titan-capabilities/native-contributions.json',import.meta.url)));
function db(){const m=new Map();return {async getRecord(c,l){return m.get(`${c.company_id}:${l.collection}`)||null},async putRecord(c,r){const k=`${c.company_id}:${r.collection}`,p=m.get(k),v=(p?.version||0)+1,o={...r,version:v};m.set(k,o);return o}}}
const base={payments:{methods:['payid','cash'],currency:'AUD'},communications:{channel_capability_ids:['channel.gmail','channel.whatsapp']},providers:{providerConfigs:[{providerId:'ollama',name:'Ollama',enabled:true},{providerId:'openai',name:'OpenAI',enabled:false,apiKey:'secret'}],fallbackPolicy:'manual'},notifications:{channels_by_urgency:{HIGH:['IN_APP'],CRITICAL:['IN_APP']},ack_minutes_by_urgency:{HIGH:20,CRITICAL:5}}};
test('Pass6 stores configuration only while preserving credential and authority boundaries',async()=>{const a=createPaymentsCommunicationsSetupAuthority({database:db(),nativeContributions:native,clock:()=>6});const r=await a.save({company_id:'c1'},base);assert.equal(r.ok,true);assert.equal(r.execution_permitted,false);const v=await a.read({company_id:'c1'});assert.deepEqual(v.payments.methods,['payid','cash']);assert.equal(v.payments.money_movement_permitted,false);assert.deepEqual(v.communications.map(x=>x.capability_id),['channel.gmail','channel.whatsapp']);assert.ok(v.communications.every(x=>x.send_permitted===false));assert.equal(v.providers.providers[1].has_credentials,true);assert.equal(v.providers.credentials_stored_in_onboarding,false);assert.equal(JSON.stringify(v).includes('secret'),false);assert.equal(v.notifications.automatic_dispatch,false);assert.equal(v.notifications.execution_permitted,false);});
test('Pass6 rejects cross-company and legacy boundaries',async()=>{const a=createPaymentsCommunicationsSetupAuthority({database:db(),nativeContributions:native});await assert.rejects(()=>a.save({company_id:'c1'},{...base,company_id:'c2'}),/Cross-company/);await assert.rejects(()=>a.save({company_id:'c1'},{...base,tenant_id:'x'}),/legacy company boundary/);});
test('Pass6 validates communication capabilities against existing channel catalogue',async()=>{const a=createPaymentsCommunicationsSetupAuthority({database:db(),nativeContributions:native});await assert.rejects(()=>a.save({company_id:'c1'},{...base,communications:{channel_capability_ids:['channel.fake']}}),/unknown communication capability/);});
test('Pass6 validates accepted payment methods without moving money',async()=>{const a=createPaymentsCommunicationsSetupAuthority({database:db(),nativeContributions:native});await assert.rejects(()=>a.save({company_id:'c1'},{...base,payments:{methods:['crypto']}}),/unsupported payment method/);const r=await a.save({company_id:'c1'},base);assert.equal(r.authority_granted,false);});
test('Pass6 uses optimistic revision protection',async()=>{const a=createPaymentsCommunicationsSetupAuthority({database:db(),nativeContributions:native});await a.save({company_id:'c1'},base);await assert.rejects(()=>a.save({company_id:'c1'},{...base,expected_revision:0}),/revision mismatch/);});
