// @ts-nocheck
// Ported from Titan Zero extension (portable-core): titan-workforce/staffing/dynamic-staffing-runtime.mjs
const clean=(v,max=220)=>String(v??'').trim().slice(0,max);
const list=v=>Array.isArray(v)?v:[];
const validCompany=v=>/^[A-Za-z0-9._:-]{2,128}$/.test(clean(v,128));
const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)||0));
const demandOf=a=>{for(const v of [a?.demand_units,a?.workload_units,a?.estimated_hours,a?.effort_hours,a?.estimated_effort_hours]){const n=Number(v);if(Number.isFinite(n)&&n>=0)return n;}return 1;};
function assertInputs(company_id,graph,capacity,skills){if(!validCompany(company_id))throw new Error('dynamic-staffing-company_id-required');if(graph?.schema!=='titan.workforce.graph.v1'||graph.company_id!==company_id)throw new Error('dynamic-staffing-workforce-graph-required');if(capacity?.schema!=='titan.workforce.workload-capacity.v1'||capacity.company_id!==company_id)throw new Error('dynamic-staffing-capacity-required');if(skills?.schema!=='titan.workforce.skill-capability-registry.v1'||skills.company_id!==company_id)throw new Error('dynamic-staffing-skill-registry-required');}
function eligibleMap(skills){const m=new Map();for(const r of list(skills.requirements)){m.set(clean(r.capability_id),new Set(list(r.eligible_worker_ids).map(x=>clean(x)).filter(Boolean)));}return m;}
function requiredCaps(a={}){return list(a.required_capabilities).map(r=>clean(typeof r==='string'?r:r?.capability_id||r?.id||r?.name)).filter(Boolean);}
function candidateScore(worker,reqs,eligible,pressure=1,performance=null){const cap=Math.max(0,Number(worker.available_units||0));const util=clamp(worker.utilization,0,3);let matched=0;for(const c of reqs){if(eligible.get(c)?.has(worker.worker_id))matched++;}const coverage=reqs.length?matched/reqs.length:1;const perfScore=performance&&performance.performance_score!=null?clamp(performance.performance_score,0,1):0.5;const perfConfidence=performance?clamp(performance.confidence,0,1):0;const performance_component=(perfScore-0.5)*20*perfConfidence;const score=(cap*2)+(coverage*50)+((1-Math.min(util,1))*25)+(Math.min(pressure,3)*5)+performance_component;return {score:Number(score.toFixed(4)),coverage:Number(coverage.toFixed(4)),matched,performance_score:performance?.performance_score??null,performance_confidence:performance?.confidence??0,performance_evidence_count:performance?.evidence_backed_count??0};}
export function buildDynamicStaffingSnapshot(input={},graph={},projection={},capacity={},skills={},missionTeams=[],performance=null){
  const company_id=clean(input.company_id||graph?.company_id,128);assertInputs(company_id,graph,capacity,skills);if(projection?.company_id&&projection.company_id!==company_id)throw new Error('dynamic-staffing-cross-company-projection-rejected');
  const workers=list(capacity.worker_capacity).filter(w=>w?.worker_id);const workerBy=new Map(workers.map(w=>[clean(w.worker_id),w]));const eligible=eligibleMap(skills);const performanceBy=new Map(list(performance?.worker_performance).map(w=>[clean(w.worker_id),w]));
  const assignments=list(projection.assignments).filter(a=>!a?.company_id||a.company_id===company_id);const overloaded=new Set(workers.filter(w=>w.state==='OVERLOADED').map(w=>w.worker_id));const candidates=[];const gaps=[];
  for(const a of assignments){const current=clean(a.worker_id||a.assignee_worker_id||a.actor_id);if(!current||!overloaded.has(current))continue;const reqs=requiredCaps(a);const demand=demandOf(a);const pool=workers.filter(w=>w.worker_id!==current&&Number(w.available_units||0)>0&&w.state!=='OVERLOADED').map(w=>{const s=candidateScore(w,reqs,eligible,1,performanceBy.get(w.worker_id));return {worker_id:w.worker_id,score:s.score,capability_coverage:s.coverage,matched_capabilities:s.matched,available_units:Number(w.available_units||0),utilization:Number(w.utilization||0),performance_score:s.performance_score,performance_confidence:s.performance_confidence,performance_evidence_count:s.performance_evidence_count};}).filter(x=>x.capability_coverage>=1).sort((a,b)=>b.score-a.score||a.worker_id.localeCompare(b.worker_id));
    const assignment_id=clean(a.assignment_id||a.id||a.work_item_id||a.job_id||'assignment');if(pool.length)candidates.push({kind:'ASSIGNMENT_REBALANCE_CANDIDATE',assignment_id,current_worker_id:current,demand_units:demand,required_capabilities:reqs,ranked_candidates:pool.slice(0,10),reason:'current-worker-overloaded',proposal_only:true,requires_governed_proposal:true,automatic_reassignment:false,authority_granted:false,execution_permitted:false,grants_authority:false});else gaps.push({kind:'NO_ELIGIBLE_REBALANCE_CANDIDATE',assignment_id,current_worker_id:current,required_capabilities:reqs,reason:reqs.length?'no-worker-with-capability-and-capacity':'no-worker-with-spare-capacity',grants_authority:false});
  }
  const teams=list(missionTeams).filter(t=>t?.company_id===company_id&&!['COMPLETED','DISSOLVED','FAILED'].includes(clean(t.state,40).toUpperCase()));
  for(const md of list(capacity.mission_demand).filter(m=>m?.staffing_pressure==null||Number(m.staffing_pressure)>1)){
    const team=teams.find(t=>clean(t.mission_team_id)===clean(md.mission_team_id));const members=new Set(list(team?.members).map(m=>clean(m?.worker_id||m)).filter(Boolean));const reqs=[...new Set(list(team?.required_capabilities).map(r=>clean(typeof r==='string'?r:r?.capability_id||r?.id)).filter(Boolean))];const pressure=Number(md.staffing_pressure||2);
    const pool=workers.filter(w=>!members.has(w.worker_id)&&Number(w.available_units||0)>0&&w.state!=='OVERLOADED').map(w=>{const s=candidateScore(w,reqs,eligible,pressure,performanceBy.get(w.worker_id));return {worker_id:w.worker_id,score:s.score,capability_coverage:s.coverage,available_units:Number(w.available_units||0),utilization:Number(w.utilization||0),performance_score:s.performance_score,performance_confidence:s.performance_confidence,performance_evidence_count:s.performance_evidence_count};}).filter(x=>x.capability_coverage>=1).sort((a,b)=>b.score-a.score||a.worker_id.localeCompare(b.worker_id));
    if(pool.length)candidates.push({kind:'MISSION_STAFFING_CANDIDATE',mission_team_id:clean(md.mission_team_id),staffing_pressure:md.staffing_pressure,required_capabilities:reqs,ranked_candidates:pool.slice(0,10),reason:'mission-capacity-pressure',proposal_only:true,requires_governed_proposal:true,automatic_reassignment:false,authority_granted:false,execution_permitted:false,grants_authority:false});else gaps.push({kind:'NO_ELIGIBLE_MISSION_CANDIDATE',mission_team_id:clean(md.mission_team_id),required_capabilities:reqs,reason:'no-eligible-worker-with-spare-capacity',grants_authority:false});
  }
  candidates.sort((a,b)=>(b.ranked_candidates?.[0]?.score||0)-(a.ranked_candidates?.[0]?.score||0)||clean(a.assignment_id||a.mission_team_id).localeCompare(clean(b.assignment_id||b.mission_team_id)));
  return {schema:'titan.workforce.dynamic-staffing.v1',company_id,graph_revision:Number(graph.projection_revision||0),graph_cursor:graph.projection_cursor||null,candidates,gaps,summary:{candidate_groups:candidates.length,assignment_rebalance_candidates:candidates.filter(x=>x.kind==='ASSIGNMENT_REBALANCE_CANDIDATE').length,mission_staffing_candidates:candidates.filter(x=>x.kind==='MISSION_STAFFING_CANDIDATE').length,unfilled_staffing_gaps:gaps.length},ranking_inputs:['available_capacity','verified_capability_eligibility','current_workload_pressure','mission_demand','bounded_evidence_backed_performance'],proposal_only:true,requires_governed_proposal:true,automatic_reassignment:false,automatic_staffing_change:false,staffing_candidate_is_not_authority:true,authority_granted:false,execution_permitted:false,grants_authority:false,authority_effect:false,updated_at:Date.now()};
}
export function summarizeDynamicStaffing(s={}){return {company_id:s.company_id,candidate_groups:s.summary?.candidate_groups||0,assignment_rebalance_candidates:s.summary?.assignment_rebalance_candidates||0,mission_staffing_candidates:s.summary?.mission_staffing_candidates||0,unfilled_staffing_gaps:s.summary?.unfilled_staffing_gaps||0,proposal_only:true,automatic_reassignment:false,grants_authority:false};}
