import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { ProductSafetyRegistry } from '../../titan-inventory/runtime/product-safety-registry.mjs';
const p=(key)=>({source:'test',recorded_at:'2026-09-09T01:50:00.000Z',idempotency_key:key});

test('catalogue product compatibility metadata is company scoped',()=>{const r=new ProductSafetyRegistry(); r.register({company_id:'co-a',catalog_product_id:'chem-glass',job_types:['office','regular'],tags:['glass'],provenance:p('a')}); r.register({company_id:'co-b',catalog_product_id:'chem-glass',job_types:['carpet'],provenance:p('b')}); assert.equal(r.findForJob('co-a','office').length,1); assert.equal(r.findForJob('co-b','office').length,0);});
test('supplier and supplier SKU metadata are optional and preserved when supplied',()=>{const r=new ProductSafetyRegistry(); const x=r.register({company_id:'co-a',catalog_product_id:'chem-1',supplier_id:'sup-1',supplier_sku:'SKU-9',manufacturer:'Maker',provenance:p('sup')}).record; assert.deepEqual(x.supplier,{supplier_id:'sup-1',supplier_sku:'SKU-9',manufacturer:'Maker'});});
test('missing supplier data stays null rather than invented',()=>{const r=new ProductSafetyRegistry(); const x=r.register({company_id:'co-a',catalog_product_id:'chem-1',provenance:p('none')}).record; assert.equal(x.supplier,null);});
test('SDS reference supplied is preserved and marked available',()=>{const r=new ProductSafetyRegistry(); const x=r.register({company_id:'co-a',catalog_product_id:'chem-1',sds_ref:'sds://chem-1',safety_note:'Follow current SDS.',provenance:p('sds')}).record; assert.equal(x.safety.sds_state,'SDS_REFERENCE_AVAILABLE'); assert.equal(x.safety.sds_ref,'sds://chem-1');});
test('SDS requirement in source note is surfaced without fabricating an SDS link',()=>{const r=new ProductSafetyRegistry(); const x=r.register({company_id:'co-a',catalog_product_id:'chem-oven',safety_note:'High-risk chemistry; follow SDS.',provenance:p('missing-sds')}).record; assert.equal(x.safety.sds_ref,null); assert.equal(x.safety.sds_state,'SDS_REFERENCE_REQUIRED_NOT_PROVIDED'); assert.equal(r.requiresSdsAttention('co-a').length,1);});
test('safety/product metadata never grants execution or purchasing authority',()=>{const r=new ProductSafetyRegistry(); const x=r.register({company_id:'co-a',catalog_product_id:'chem-1',provenance:p('auth')}).record; assert.deepEqual(x.authority,{purchase_authority_granted:false,execution_authority_granted:false,safety_metadata_grants_authority:false});});
test('registration replay is idempotent and cannot rewrite supplier fields',()=>{const r=new ProductSafetyRegistry(); const a={company_id:'co-a',catalog_product_id:'chem-1',supplier_id:'sup-a',provenance:p('same')}; r.register(a); const replay=r.register({...a,supplier_id:'sup-b'}); assert.equal(replay.replayed,true); assert.equal(r.get('co-a','chem-1').supplier.supplier_id,'sup-a');});
test('legacy company aliases fail closed',()=>{const r=new ProductSafetyRegistry(); assert.throws(()=>r.register({company_id:'co-a',tenant_id:'legacy',catalog_product_id:'chem-1',provenance:p('legacy')}),/legacy boundary/);});
test('current cleaning supply catalogue imports real tags/job types/safety and leaves absent SDS/supplier null',()=>{const r=new ProductSafetyRegistry(); const catalog=JSON.parse(fs.readFileSync(new URL('../../titan-modules/cleaning-supply-catalog.json', import.meta.url),'utf8')); r.importCleaningSupplyCatalog('co-a',catalog); const oven=r.get('co-a','chem-oven'); assert.ok(oven.compatibility.tags.includes('oven')); assert.ok(oven.compatibility.job_types.includes('end-of-lease')); assert.match(oven.safety.safety_note,/SDS/); assert.equal(oven.safety.sds_ref,null); assert.equal(oven.supplier,null);});
test('consumable schema remains parseable with Pass7 safety/compatibility hooks',()=>{const schema=JSON.parse(fs.readFileSync(new URL('../../titan-inventory/contracts/Consumable.schema.json',import.meta.url),'utf8')); assert.ok(schema.properties.safety); assert.ok(schema.properties.compatibility); assert.ok(schema.properties.supplier);});
