// @ts-nocheck
// Ported from Titan Zero extension (portable-core): titan-workforce/supervision/supervisor-workspace-projection.mjs
const arr=v=>Array.isArray(v)?v:[];
const clean=(v,max=240)=>String(v??'').trim().slice(0,max);
const uniq=v=>[...new Set(arr(v).map(x=>clean(x)).filter(Boolean))];
function assertCompany(record,company_id,label){if(record&&record.company_id&&record.company_id!==company_id)throw new Error(`supervisor-workspace-cross-company-${label}`);}
const workerId=n=>clean(n?.worker_id||String(n?.node_id||'').replace(/^worker:/,''));
function scopedWorkers(supervision){return new Set(uniq([supervision?.supervisor_worker_id,...arr(supervision?.scope?.scoped_worker_ids),...arr(supervision?.scope?.subordinate_worker_ids)]));}
function graphWorker(graph,id){return arr(graph?.nodes).find(n=>n?.company_id===graph.company_id&&(n?.node_id===`worker:${id}`||workerId(n)===id))||null;}
function assignmentsFor(graph,scope){const out=[];for(const e of arr(graph?.edges)){if(e?.company_id!==graph.company_id||e?.type!=='ASSIGNED_TO')continue;const wid=clean(String(e.to||'').replace(/^worker:/,''));if(!scope.has(wid))continue;out.push({assignment_id:clean(String(e.from||'').replace(/^assignment:/,'')),worker_id:wid,grants_authority:false});}return out.sort((a,b)=>a.assignment_id.localeCompare(b.assignment_id));}
function openState(v){return !['closed','resolved','complete','completed','dismissed'].includes(clean(v,60).toLowerCase());}
export function buildSupervisorWorkspaceProjection(input={}){
  const company_id=clean(input.company_id,128);if(!company_id)throw new Error('supervisor-workspace-company_id-required');
  const supervision=input.supervision;if(supervision?.schema!=='titan.workforce.supervision.v1')throw new Error('supervisor-workspace-supervision-required');assertCompany(supervision,company_id,'supervision');
  const graph=input.graph;if(graph?.schema!=='titan.workforce.graph.v1')throw new Error('supervisor-workspace-graph-required');assertCompany(graph,company_id,'graph');
  const scope=scopedWorkers(supervision);const supervisor_worker_id=clean(supervision.supervisor_worker_id);if(!scope.has(supervisor_worker_id))scope.add(supervisor_worker_id);
  for(const [label,record] of [['capacity',input.capacity],['skills',input.skills],['performance',input.performance],['staffing',input.staffing],['notifications',input.notifications]])assertCompany(record,company_id,label);
  const workers=[...scope].map(id=>{const node=graphWorker(graph,id);const cap=arr(input.capacity?.worker_capacity).find(x=>x?.worker_id===id)||null;const perf=arr(input.performance?.worker_performance).find(x=>x?.worker_id===id)||null;const skillReqs=arr(input.skills?.requirements).filter(r=>arr(r?.eligible_worker_ids).includes(id)).map(r=>clean(r?.capability_id)).filter(Boolean);return {worker_id:id,label:clean(node?.label||node?.display_name||id),is_supervisor:id===supervisor_worker_id,capacity:cap?{state:cap.state||null,utilization:Number(cap.utilization||0),available_units:Number(cap.available_units||0),assignment_count:Number(cap.assignment_count||0)}:null,performance:perf?{outcome_count:Number(perf.outcome_count||0),evidence_backed_count:Number(perf.evidence_backed_count||0),score:Number(perf.score??perf.average_score??0),confidence:Number(perf.confidence||0)}:null,eligible_capability_ids:uniq(skillReqs),grants_authority:false};}).sort((a,b)=>Number(b.is_supervisor)-Number(a.is_supervisor)||a.worker_id.localeCompare(b.worker_id));
  const mission_teams=arr(input.mission_teams).filter(t=>t?.company_id===company_id&&(t?.supervisor_worker_id===supervisor_worker_id||t?.coordinator_worker_id===supervisor_worker_id||arr(t?.members).some(m=>scope.has(clean(m?.worker_id||m))))).map(t=>({mission_team_id:clean(t.mission_team_id),mission_id:clean(t.mission_id)||null,state:clean(t.state,60)||null,supervisor_worker_id:clean(t.supervisor_worker_id)||null,coordinator_worker_id:clean(t.coordinator_worker_id)||null,grants_authority:false}));
  const escalations=[...arr(supervision.escalations).map(e=>({...e,source:'supervision'})),...arr(input.notifications?.notifications).filter(n=>openState(n?.state)&&String(n?.severity||'').toLowerCase()==='critical').map(n=>({escalation_id:clean(n.notification_id||n.id),state:n.state,severity:n.severity,source:'notification',grants_authority:false}))].filter(e=>openState(e?.state));
  const staffing=arr(input.staffing?.candidates).filter(c=>scope.has(clean(c?.worker_id||c?.source_worker_id||c?.overloaded_worker_id))||arr(c?.ranked_candidates).some(r=>scope.has(clean(r?.worker_id)))).map(c=>({...c,proposal_only:true,grants_authority:false}));
  const assignments=assignmentsFor(graph,scope);
  const overloaded=workers.filter(w=>w.capacity?.state==='OVERLOADED').length;
  return {schema:'titan.workforce.supervisor-workspace-projection.v1',company_id,supervisor_worker_id,coordination_state:clean(supervision.coordination_state,60)||null,workers,assignments,mission_teams,escalations,staffing_recommendations:staffing,summary:{worker_count:workers.length,subordinate_count:Math.max(0,workers.length-1),assignment_count:assignments.length,mission_team_count:mission_teams.length,open_escalation_count:escalations.length,overloaded_worker_count:overloaded,staffing_recommendation_count:staffing.length},read_only_projection:true,coordination_responsibility_only:true,supervisor_identity_confers_authority:false,hierarchy_confers_authority:false,proposal_only_interventions:true,automatic_execution:false,grants_authority:false,authority_effect:false};
}
export function summarizeSupervisorWorkspace(workspace={}){if(workspace?.schema!=='titan.workforce.supervisor-workspace-projection.v1')throw new Error('invalid-supervisor-workspace-projection');return {...workspace.summary,company_id:workspace.company_id,supervisor_worker_id:workspace.supervisor_worker_id,read_only_projection:true,grants_authority:false};}
