// @ts-nocheck
// Ported from Titan Zero extension (portable-core): titan-workforce/supervision/supervisor-workspace-view-model.mjs
const arr=v=>Array.isArray(v)?v:[];
const clean=(v,max=240)=>String(v??'').trim().slice(0,max);
const sevRank={critical:4,high:3,medium:2,low:1};
const byLabel=(a,b)=>String(a?.label||a?.worker_id||'').localeCompare(String(b?.label||b?.worker_id||''));
function assertWorkspace(w){if(w?.schema!=='titan.workforce.supervisor-workspace-projection.v1')throw new Error('supervisor-workspace-view-model-projection-required');if(!w.company_id)throw new Error('supervisor-workspace-view-model-company-required');}
function workerStatus(worker={}){if(worker.capacity?.state==='OVERLOADED')return 'attention';if(Number(worker.capacity?.utilization||0)>=0.85)return 'busy';if(worker.performance&&Number(worker.performance.confidence||0)<0.5)return 'review';return 'normal';}
function escalationRows(values=[]){return arr(values).map(e=>({id:clean(e.escalation_id||e.id),severity:clean(e.severity,40)||'unspecified',state:clean(e.state,40)||'open',source:clean(e.source,60)||'supervision',target_ref:clean(e.target_ref)||null,requires_governed_action:true,grants_authority:false})).sort((a,b)=>(sevRank[b.severity?.toLowerCase()]||0)-(sevRank[a.severity?.toLowerCase()]||0)||a.id.localeCompare(b.id));}
function staffingRows(values=[]){return arr(values).map((item,index)=>({recommendation_id:clean(item.recommendation_id||item.candidate_id||`staffing-${index+1}`),overloaded_worker_id:clean(item.overloaded_worker_id||item.worker_id||item.source_worker_id)||null,candidate_worker_ids:arr(item.ranked_candidates).map(x=>clean(x?.worker_id)).filter(Boolean),reason:clean(item.reason||item.rationale,320)||null,proposal_only:true,requires_governed_proposal:true,grants_authority:false}));}
export function buildSupervisorWorkspaceViewModel(workspace={}){
  assertWorkspace(workspace);
  const workers=arr(workspace.workers).slice().sort((a,b)=>Number(b.is_supervisor)-Number(a.is_supervisor)||byLabel(a,b)).map(w=>({worker_id:clean(w.worker_id),label:clean(w.label)||clean(w.worker_id),is_supervisor:Boolean(w.is_supervisor),status:workerStatus(w),capacity:w.capacity||null,performance:w.performance||null,eligible_capability_ids:arr(w.eligible_capability_ids),action_hints:[{type:'open-worker-profile',worker_id:clean(w.worker_id),execution:false,grants_authority:false}],grants_authority:false}));
  const missionTeams=arr(workspace.mission_teams).map(t=>({mission_team_id:clean(t.mission_team_id),mission_id:clean(t.mission_id)||null,state:clean(t.state,60)||null,relationship:t.supervisor_worker_id===workspace.supervisor_worker_id?'supervisor':t.coordinator_worker_id===workspace.supervisor_worker_id?'coordinator':'member-scope',grants_authority:false}));
  const escalations=escalationRows(workspace.escalations);
  const staffing=staffingRows(workspace.staffing_recommendations);
  const summary={...workspace.summary,attention_worker_count:workers.filter(w=>['attention','review'].includes(w.status)).length,busy_worker_count:workers.filter(w=>w.status==='busy').length,critical_escalation_count:escalations.filter(e=>e.severity.toLowerCase()==='critical').length};
  const health=summary.critical_escalation_count>0?'critical':summary.open_escalation_count>0||summary.overloaded_worker_count>0?'attention':'operational';
  return {schema:'titan.workforce.supervisor-workspace-view-model.v1',company_id:workspace.company_id,supervisor_worker_id:workspace.supervisor_worker_id,title:'Supervisor workspace',subtitle:`${summary.subordinate_count||0} workers · ${summary.assignment_count||0} assignments · ${summary.mission_team_count||0} mission teams`,health,summary,sections:{workers,assignments:arr(workspace.assignments),mission_teams:missionTeams,escalations,staffing_recommendations:staffing},available_intents:[{intent:'review-escalations',execution:false,requires_governed_action:true,grants_authority:false},{intent:'review-capacity',execution:false,grants_authority:false},{intent:'prepare-staffing-proposal',execution:false,requires_governed_proposal:true,grants_authority:false}],ui_integration_pending:true,read_only:true,automatic_execution:false,supervisor_identity_confers_authority:false,grants_authority:false,authority_effect:false};
}
export function summarizeSupervisorWorkspaceViewModel(vm={}){if(vm?.schema!=='titan.workforce.supervisor-workspace-view-model.v1')throw new Error('invalid-supervisor-workspace-view-model');return {company_id:vm.company_id,supervisor_worker_id:vm.supervisor_worker_id,health:vm.health,...vm.summary,ui_integration_pending:true,grants_authority:false};}
