// @ts-nocheck
// Ported from Titan Zero extension (portable-core): titan-workforce/supervision/supervisor-runtime.mjs
const clean=(v,max=180)=>String(v??'').trim().slice(0,max);
const list=v=>Array.isArray(v)?v:[];
const uniq=v=>[...new Set(list(v).map(x=>clean(x)).filter(Boolean))].sort();
const validCompany=v=>/^[A-Za-z0-9._:-]{2,128}$/.test(clean(v,128));
const workerNode=(graph,id)=>list(graph?.nodes).find(n=>n?.node_id===`worker:${clean(id)}`&&n?.company_id===graph.company_id)||null;
const edgeWorkers=(graph,type,to)=>list(graph?.edges).filter(e=>e?.company_id===graph.company_id&&e?.type===type&&e?.to===to).map(e=>clean(String(e.from||'').replace(/^worker:/,''))).filter(Boolean);
function assertGraph(graph,company_id){if(graph?.schema!=='titan.workforce.graph.v1')throw new Error('supervision-workforce-graph-required');if(graph.company_id!==company_id)throw new Error('supervision-cross-company-graph-rejected');}
function assertWorker(graph,id,label='supervisor'){if(!workerNode(graph,id))throw new Error(`supervision-${label}-worker-not-in-graph`);}
function recursiveSubordinates(graph,supervisorId){const seen=new Set(),queue=[clean(supervisorId)];while(queue.length){const current=queue.shift();for(const id of edgeWorkers(graph,'REPORTS_TO',`worker:${current}`)){if(id&&id!==supervisorId&&!seen.has(id)){seen.add(id);queue.push(id);}}}return [...seen].sort();}
function teamRefs(teams,workerId){return list(teams).filter(t=>t?.supervisor_worker_id===workerId||t?.coordinator_worker_id===workerId).map(t=>({mission_team_id:clean(t.mission_team_id),mission_id:clean(t.mission_id)||null,state:clean(t.state,40)||null,relationship:t.supervisor_worker_id===workerId?'supervisor':'coordinator',grants_authority:false})).sort((a,b)=>a.mission_team_id.localeCompare(b.mission_team_id));}
function assignmentsFor(graph,workerIds){const ids=new Set(workerIds);const edges=list(graph?.edges);const assignmentIds=new Set(edges.filter(e=>e.type==='ASSIGNED_TO'&&ids.has(clean(String(e.to||'').replace(/^worker:/,'')))).map(e=>clean(String(e.from||'').replace(/^assignment:/,''))));return [...assignmentIds].sort();}
export function deriveSupervisorScope(input={},graph={},missionTeams=[]){const company_id=clean(input.company_id,128);if(!validCompany(company_id))throw new Error('supervision-company_id-required');assertGraph(graph,company_id);const supervisor_worker_id=clean(input.supervisor_worker_id||input.manager_worker_id||input.worker_id);if(!supervisor_worker_id)throw new Error('supervision-supervisor-worker-id-required');assertWorker(graph,supervisor_worker_id);const direct=edgeWorkers(graph,'REPORTS_TO',`worker:${supervisor_worker_id}`).sort();const recursive=recursiveSubordinates(graph,supervisor_worker_id);const mission_teams=teamRefs(missionTeams,supervisor_worker_id);const scopedWorkers=uniq([supervisor_worker_id,...recursive,...list(input.additional_worker_ids)]);for(const id of scopedWorkers)assertWorker(graph,id,'scoped');return {company_id,supervisor_worker_id,direct_subordinate_worker_ids:direct,subordinate_worker_ids:recursive,scoped_worker_ids:scopedWorkers,mission_teams,assignment_ids:assignmentsFor(graph,scopedWorkers),graph_revision:Number(graph.projection_revision||0),graph_cursor:graph.projection_cursor||null,derived:true,manager_identity_confers_authority:false,supervisor_identity_confers_authority:false,grants_authority:false};}
function normalizeEscalations(values,company_id){return list(values).filter(x=>!x?.company_id||x.company_id===company_id).map((x,i)=>({escalation_id:clean(x?.escalation_id||x?.id||`escalation-${i+1}`),state:clean(x?.state||x?.status,60)||'open',severity:clean(x?.severity||x?.priority,40)||null,target_ref:clean(x?.target_ref||x?.work_item_id||x?.assignment_id,180)||null,acknowledged_at:x?.acknowledged_at||null,acknowledged_by_worker_id:clean(x?.acknowledged_by_worker_id,180)||null,grants_authority:false})).filter(x=>x.escalation_id).sort((a,b)=>a.escalation_id.localeCompare(b.escalation_id));}
export function createSupervisorCoordinationRecord(input={},graph={},missionTeams=[]){const scope=deriveSupervisorScope(input,graph,missionTeams);const now=Date.now();return {schema:'titan.workforce.supervision.v1',company_id:scope.company_id,supervisor_worker_id:scope.supervisor_worker_id,scope,coordination_state:clean(input.coordination_state,60)||'active',escalations:normalizeEscalations(input.escalations,scope.company_id),handover_history:[],created_at:now,updated_at:now,graph_revision:scope.graph_revision,graph_cursor:scope.graph_cursor,durable_authority:false,coordination_responsibility_only:true,manager_identity_confers_authority:false,supervisor_identity_confers_authority:false,handover_transfers_authority:false,grants_authority:false,authority_effect:false};}
export function refreshSupervisorCoordination(record={},input={},graph={},missionTeams=[]){if(record?.schema!=='titan.workforce.supervision.v1')throw new Error('invalid-supervision-record');if(clean(input.company_id,128)!==record.company_id)throw new Error('supervision-cross-company-refresh-rejected');const scope=deriveSupervisorScope({...input,supervisor_worker_id:record.supervisor_worker_id},graph,missionTeams);return {...record,scope,escalations:input.escalations?normalizeEscalations(input.escalations,record.company_id):record.escalations,graph_revision:scope.graph_revision,graph_cursor:scope.graph_cursor,updated_at:Date.now(),grants_authority:false,authority_effect:false};}
export function acknowledgeEscalation(record={},input={}){if(record?.schema!=='titan.workforce.supervision.v1')throw new Error('invalid-supervision-record');if(clean(input.company_id,128)!==record.company_id)throw new Error('supervision-cross-company-ack-rejected');const escalation_id=clean(input.escalation_id);if(!escalation_id)throw new Error('supervision-escalation-id-required');const idx=list(record.escalations).findIndex(x=>x.escalation_id===escalation_id);if(idx<0)throw new Error('supervision-escalation-not-in-scope');const actor=clean(input.acknowledged_by_worker_id||record.supervisor_worker_id);if(actor!==record.supervisor_worker_id&&!record.scope.scoped_worker_ids.includes(actor))throw new Error('supervision-ack-actor-out-of-scope');const escalations=record.escalations.map((x,i)=>i===idx?{...x,state:x.state==='closed'?'closed':'acknowledged',acknowledged_at:Date.now(),acknowledged_by_worker_id:actor,grants_authority:false}:x);return {...record,escalations,updated_at:Date.now(),grants_authority:false,authority_effect:false};}
export function prepareSupervisorHandover(record={},input={},graph={}){if(record?.schema!=='titan.workforce.supervision.v1')throw new Error('invalid-supervision-record');if(clean(input.company_id,128)!==record.company_id)throw new Error('supervision-cross-company-handover-rejected');assertGraph(graph,record.company_id);const to_worker_id=clean(input.to_worker_id||input.to_supervisor_worker_id);if(!to_worker_id)throw new Error('supervision-handover-target-required');assertWorker(graph,to_worker_id,'handover-target');if(to_worker_id===record.supervisor_worker_id)throw new Error('supervision-handover-target-same-worker');const ref=clean(input.handover_ref||input.evidence_ref,240);if(!ref)throw new Error('supervision-handover-evidence-required');const entry={handover_id:clean(input.handover_id,180)||`supervision-handover:${record.supervisor_worker_id}:${to_worker_id}:${Date.now()}`,from_worker_id:record.supervisor_worker_id,to_worker_id,reason:clean(input.reason,500)||null,evidence_ref:ref,prepared_at:Date.now(),coordination_responsibility_only:true,transfers_authority:false,grants_authority:false};return {...record,coordination_state:'handover_prepared',handover_history:[...list(record.handover_history),entry],updated_at:entry.prepared_at,handover_transfers_authority:false,grants_authority:false,authority_effect:false};}
export function summarizeSupervisorCoordination(record={}){return {company_id:record.company_id,supervisor_worker_id:record.supervisor_worker_id,coordination_state:record.coordination_state,subordinate_count:list(record.scope?.subordinate_worker_ids).length,mission_team_count:list(record.scope?.mission_teams).length,assignment_count:list(record.scope?.assignment_ids).length,open_escalation_count:list(record.escalations).filter(x=>!['closed','resolved'].includes(x.state)).length,handover_count:list(record.handover_history).length,graph_revision:Number(record.graph_revision||0),grants_authority:false};}
