(function attachChangeSet(global){
'use strict';
const MAX_CHANGES=2000;
function sha(value,label){if(value===undefined||value===null||value==='')return null;const text=String(value).trim().toLowerCase();if(!/^[a-f0-9]{64}$/.test(text))throw new Error(`${label} must be a valid SHA-256`);return text;}
function boundedId(value,max=240){if(value===undefined||value===null||value==='')return null;const raw=String(value).trim();const text=(global.CodeeRepositoryPolicy?.redactText?global.CodeeRepositoryPolicy.redactText(raw):raw).slice(0,max);return text||null;}
function receiptId(value){if(value===undefined||value===null||value==='')return null;const raw=String(value).trim();if(!raw||raw.length>240)throw new Error('Backup receipt id is invalid or too long');return boundedId(raw,240);}
function timestamp(value){const parsed=Date.parse(String(value||''));return Number.isFinite(parsed)?new Date(parsed).toISOString():new Date().toISOString();}
function create(input){const allowedOperations=new Set(['create','modify','delete']);const incoming=Array.isArray(input?.changes)?input.changes:[];if(incoming.length>MAX_CHANGES)throw new Error(`Change set exceeds maximum ${MAX_CHANGES} changes`);const changes=incoming.map((c,i)=>{const path=global.CodeeRepositoryPolicy.normalize(c.path);if(!path||!global.CodeeRepositoryPolicy.isInScope(c.path))throw new Error(`Change-set path is outside the governed repository scope: ${path||'[empty]'}`);const operation=String(c.operation||'modify').toLowerCase();if(!allowedOperations.has(operation))throw new Error(`Unsupported change-set operation: ${operation}`);return {id:boundedId(c.id||`change-${i+1}`,160),path,operation,beforeSha256:sha(c.beforeSha256,'beforeSha256'),afterSha256:sha(c.afterSha256,'afterSha256'),backupReceiptId:receiptId(c.backupReceiptId),verified:!!c.verified};});const counts={create:0,modify:0,delete:0,other:0};for(const c of changes)(Object.hasOwn(counts,c.operation)?counts[c.operation]++:counts.other++);return {id:boundedId(input?.id||`changeset-${Date.now()}`,240),planId:boundedId(input?.planId,240),stepId:boundedId(input?.stepId,240),createdAt:timestamp(input?.createdAt),changes,counts,allBackedUp:changes.every(c=>!!c.backupReceiptId),allVerified:changes.every(c=>c.verified)};}
function add(changeSet,change){return create({...changeSet,id:changeSet.id,changes:[...(changeSet.changes||[]),change]});}
global.CodeeChangeSet=Object.freeze({create,add,MAX_CHANGES});
})(typeof globalThis!=='undefined'?globalThis:this);
