(function attachDiffEngine(global){
'use strict';
const MAX_DIFF_CHARS=1024*1024;
const MAX_DP_CELLS=2000000;
function lines(text){const value=String(text??'');if(value.length>MAX_DIFF_CHARS)throw new Error(`Repository diff input is too large (maximum ${MAX_DIFF_CHARS} characters per side).`);const out=value.split(/\r?\n/);if(out.length&&out[out.length-1]==='')out.pop();return out;}
function diff(before,after){const a=lines(before),b=lines(after),n=a.length,m=b.length;const safeLine=value=>global.CodeeRepositoryPolicy?.redactText?global.CodeeRepositoryPolicy.redactText(String(value??'')).slice(0,2000):String(value??'').slice(0,2000);if((n+1)*(m+1)>MAX_DP_CELLS)throw new Error(`Repository diff is too large for bounded exact comparison (${n}x${m} lines).`);const dp=Array.from({length:n+1},()=>new Uint32Array(m+1));for(let i=n-1;i>=0;i--)for(let j=m-1;j>=0;j--)dp[i][j]=a[i]===b[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);let i=0,j=0;const ops=[];while(i<n&&j<m){if(a[i]===b[j]){ops.push({type:'context',line:safeLine(a[i]),before:i+1,after:j+1});i++;j++;}else if(dp[i+1][j]>=dp[i][j+1]){ops.push({type:'remove',line:safeLine(a[i]),before:i+1,after:null});i++;}else{ops.push({type:'add',line:safeLine(b[j]),before:null,after:j+1});j++;}}while(i<n){ops.push({type:'remove',line:safeLine(a[i]),before:i+1,after:null});i++;}while(j<m){ops.push({type:'add',line:safeLine(b[j]),before:null,after:j+1});j++;}const hunks=[];let current=[];let lastChange=-99;for(let k=0;k<ops.length;k++){if(ops[k].type!=='context')lastChange=k;if(k-lastChange<=3||ops.slice(k+1,k+4).some(x=>x&&x.type!=='context'))current.push(ops[k]);else if(current.length){if(current.some(x=>x.type!=='context'))hunks.push({lines:current});current=[];}}if(current.some(x=>x.type!=='context'))hunks.push({lines:current});const stats={added:ops.filter(x=>x.type==='add').length,removed:ops.filter(x=>x.type==='remove').length,unchanged:ops.filter(x=>x.type==='context').length};return {stats,hunks,changed:stats.added+stats.removed>0};}
function exactReplacement(before,find,replacement){const source=String(before??''),needle=String(find??'');if(source.length>MAX_DIFF_CHARS)throw new Error('Repository exact replacement input is too large for bounded processing.');const first=source.indexOf(needle);if(first<0)throw new Error('Exact replacement target was not found.');if(source.indexOf(needle,first+needle.length)>=0)throw new Error('Exact replacement target is ambiguous.');const after=source.slice(0,first)+String(replacement??'')+source.slice(first+needle.length);return {before:source,after,diff:diff(source,after),replacement:{offset:first,beforeBytes:needle.length,afterBytes:String(replacement??'').length}};}
global.CodeeDiffEngine=Object.freeze({diff,exactReplacement,MAX_DIFF_CHARS,MAX_DP_CELLS});
})(typeof globalThis!=='undefined'?globalThis:this);
