(function attachLaravelTracer(global){
'use strict';
const MAX_ROUTES=10000, MAX_USES=500, MAX_EVIDENCE=1000;
function isRouteFile(path){const p=global.CodeeRepositoryPolicy.normalize(path);return /^routes\/.+\.php$/i.test(p)||/^app\/Extensions\/[^/]+\/routes\/.+\.php$/i.test(p);}
function parseRoutes(snapshot){const routes=[];for(const [rawPath,raw] of Object.entries(snapshot?.files||{})){if(routes.length>=MAX_ROUTES)break;if(!global.CodeeRepositoryPolicy.isInScope(rawPath)||!isRouteFile(rawPath))continue;const path=global.CodeeRepositoryPolicy.normalize(rawPath);const text=String(raw??'');const rx=/Route::(get|post|put|patch|delete|any|match)\s*\(\s*['"]([^'"]+)['"]\s*,\s*\[\s*([A-Za-z_][\w\\]*)::class\s*,\s*['"]([^'"]+)['"]\s*\]\s*\)([^;]*);/g;let m;while(routes.length<MAX_ROUTES&&(m=rx.exec(text))){const tail=m[5]||'';const name=tail.match(/->name\(\s*['"]([^'"]+)['"]\s*\)/)?.[1]||null;routes.push({method:m[1].toUpperCase(),uri:m[2],controller:m[3].split('\\').pop(),action:m[4],name,file:path});}}return routes;}
function buildClassIndex(scoped){const index=new Map();for(const [path,raw] of scoped){const text=String(raw??'');const m=text.match(/\b(?:class|interface|trait)\s+([A-Za-z_][A-Za-z0-9_]*)/);if(!m)continue;const name=m[1];if(!index.has(name))index.set(name,[]);const rows=index.get(name);if(rows.length<20)rows.push({path:global.CodeeRepositoryPolicy.normalize(path),text});}return index;}
function trace(snapshot,input){const routes=parseRoutes(snapshot);const route=routes.find(r=>(input?.routeName&&r.name===input.routeName)||(input?.uri&&r.uri===input.uri))||null;if(!route)return {route:null,relatedFiles:[],evidence:[],truncated:false};const related=new Set([route.file]);const evidence=[];let truncated=false;const scoped=Object.entries(snapshot?.files||{}).filter(([path])=>global.CodeeRepositoryPolicy.isInScope(path));const index=buildClassIndex(scoped);const controllers=index.get(route.controller)||[];for(const controller of controllers){if(evidence.length>=MAX_EVIDENCE){truncated=true;break;}related.add(controller.path);evidence.push({kind:'controller',path:controller.path,name:route.controller});let useCount=0;for(const m of controller.text.matchAll(/\buse\s+([A-Za-z_\\][A-Za-z0-9_\\]*)\s*;/g)){if(useCount++>=MAX_USES){truncated=true;break;}const name=m[1].split('\\').pop();for(const target of index.get(name)||[]){if(evidence.length>=MAX_EVIDENCE){truncated=true;break;}related.add(target.path);evidence.push({kind:'dependency',path:target.path,name});}}}
return {route,relatedFiles:[...related].sort(),evidence,truncated:truncated||routes.length>=MAX_ROUTES};}
global.CodeeLaravelTracer=Object.freeze({parseRoutes,trace,isRouteFile,MAX_ROUTES,MAX_USES,MAX_EVIDENCE});
})(typeof globalThis!=='undefined'?globalThis:this);
