import test from 'node:test';import assert from 'node:assert/strict';import {TitanAgentRuntime,InMemoryRunStore,RuntimeEventBus,assertTransition} from '../index.mjs';
const base=()=>({company_id:'c1',actor_id:'owner',agent_id:'manager',conversation_id:'conv1',messages:[{role:'user',content:'do work'}]});
function fixture(sequence,{authority}={}){const store=new InMemoryRunStore();const bus=new RuntimeEventBus();const events=[];bus.subscribe(e=>events.push(e));let i=0;const runtime=new TitanAgentRuntime({store,eventBus:bus,modelRouter:{next:async()=>sequence[Math.min(i++,sequence.length-1)]},capabilities:{resolve:async({name})=>({name,execute:true})},authorityGateway:authority??{authorize:async()=>({status:'allowed',decision_id:'d1'}),execute:async({input})=>({output:{ok:true,input},evidence_ref:'ev1'})}});return{runtime,store,events};}
test('basic run completes and streams lifecycle',async()=>{const f=fixture([{delta:'hi',final:'done'}]);const r=await f.runtime.start(base());assert.equal(r.state,'COMPLETED');assert.equal(r.result,'done');assert.ok(f.events.some(e=>e.type==='message.delta'));assert.ok(f.events.some(e=>e.type==='run.completed'));});
test('multi-turn tool use crosses authority gateway',async()=>{const f=fixture([{tool_calls:[{id:'tc1',name:'send_message',arguments:{to:'Sarah'}}]},{final:'sent'}]);const r=await f.runtime.start(base());assert.equal(r.state,'COMPLETED');assert.ok(r.messages.some(m=>m.role==='tool'));assert.ok(f.events.some(e=>e.type==='tool.completed'));});
test('approval waits and can resume after decision changes',async()=>{let approved=false;const f=fixture([{tool_calls:[{id:'tc1',name:'schedule_change',arguments:{day:'sat'}}]},{final:'scheduled'}],{authority:{authorize:async()=>approved?{status:'allowed',decision_id:'d2'}:{status:'approval_required',decision_id:'d1'},execute:async()=>({output:'ok',evidence_ref:'ev2'})}});let r=await f.runtime.start(base());assert.equal(r.state,'WAITING_APPROVAL');approved=true;r=await f.runtime.resume({company_id:'c1',run_id:r.run_id,input:{role:'system',content:'approval granted'}});assert.equal(r.state,'COMPLETED');});
test('explicit external wait persists and resumes',async()=>{const f=fixture([{wait:{state:'WAITING_EXTERNAL',kind:'reply',correlation_id:'msg1'}},{final:'Sarah replied'}]);let r=await f.runtime.start(base());assert.equal(r.state,'WAITING_EXTERNAL');assert.equal((await f.runtime.recover())[0].run_id,r.run_id);r=await f.runtime.resume({company_id:'c1',run_id:r.run_id,input:{role:'event',content:'yes'}});assert.equal(r.state,'COMPLETED');});
test('company isolation rejects cross-company resume',async()=>{const f=fixture([{wait:{state:'WAITING_USER'}}]);const r=await f.runtime.start(base());await assert.rejects(()=>f.runtime.resume({company_id:'c2',run_id:r.run_id}),/not-found/);});
test('provider failure is explicit',async()=>{const store=new InMemoryRunStore();const runtime=new TitanAgentRuntime({store,modelRouter:{next:async()=>{throw new Error('provider-down')}}});const r=await runtime.start(base());assert.equal(r.state,'FAILED');assert.match(r.error.message,/provider-down/);});
test('tool failure is explicit',async()=>{const f=fixture([{tool_calls:[{id:'t',name:'x',arguments:{}}]}],{authority:{authorize:async()=>({status:'allowed'}),execute:async()=>{throw new Error('tool-down')}}});const r=await f.runtime.start(base());assert.equal(r.state,'FAILED');assert.match(r.error.message,/tool-down/);});
test('denied authority never executes capability',async()=>{let executed=false;const f=fixture([{tool_calls:[{id:'t',name:'x',arguments:{}}]},{final:'not executed'}],{authority:{authorize:async()=>({status:'denied'}),execute:async()=>{executed=true}}});const r=await f.runtime.start(base());assert.equal(r.state,'COMPLETED');assert.equal(executed,false);});
test('cancellation is terminal',async()=>{const f=fixture([{wait:{state:'WAITING_USER'}}]);let r=await f.runtime.start(base());r=await f.runtime.cancel({company_id:'c1',run_id:r.run_id});assert.equal(r.state,'CANCELLED');await assert.rejects(()=>f.runtime.resume({company_id:'c1',run_id:r.run_id}),/terminal/);});
test('invalid transitions fail closed',()=>assert.throws(()=>assertTransition('COMPLETED','RUNNING'),/transition-invalid/));
