import test from 'node:test';import assert from 'node:assert/strict';import {TitanAgentRuntime,InMemoryRunStore,RuntimeEventBus,assertTransition} from '../index.mjs';
const base=()=>({company_id:'c1',actor_id:'owner',agent_id:'manager',conversation_id:'conv1',messages:[{role:'user',content:'do work'}]});
function fixture(sequence,{authority}={}){const store=new InMemoryRunStore();const bus=new RuntimeEventBus();const events=[];bus.subscribe(e=>events.push(e));let i=0;const runtime=new TitanAgentRuntime({store,eventBus:bus,modelRouter:{next:async()=>sequence[Math.min(i++,sequence.length-1)]},capabilities:{resolve:async({name})=>({name,execute:true})},authorityGateway:authority??{authorize:async()=>({status:'allowed',decision_id:'d1'}),execute:async({input})=>({state:'VERIFIED',output:{ok:true,input},evidence_ref:'ev1',verified:true})}});return{runtime,store,events};}
test('basic run completes and streams lifecycle',async()=>{const f=fixture([{delta:'hi',final:'done'}]);const r=await f.runtime.start(base());assert.equal(r.state,'COMPLETED');assert.equal(r.result,'done');assert.ok(f.events.some(e=>e.type==='message.delta'));assert.ok(f.events.some(e=>e.type==='run.completed'));});
test('multi-turn tool use crosses authority gateway',async()=>{const f=fixture([{tool_calls:[{id:'tc1',name:'send_message',arguments:{to:'Sarah'}}]},{final:'sent'}]);const r=await f.runtime.start(base());assert.equal(r.state,'COMPLETED');assert.ok(r.messages.some(m=>m.role==='tool'));assert.ok(f.events.some(e=>e.type==='tool.completed'));});
test('approval waits and resumes pending call without asking model to replay it',async()=>{let approved=false,executions=0,modelCalls=0;const store=new InMemoryRunStore();const runtime=new TitanAgentRuntime({store,modelRouter:{next:async()=>{modelCalls++;return modelCalls===1?{tool_calls:[{id:'tc1',name:'schedule_change',arguments:{day:'sat'}}]}:{final:'scheduled'};}},capabilities:{resolve:async({name})=>({name})},authorityGateway:{authorize:async()=>approved?{status:'allowed',decision_id:'d2'}:{status:'approval_required',decision_id:'d1'},execute:async()=>{executions++;return{state:'VERIFIED',output:'ok',evidence_ref:'ev2',verified:true};}}});let r=await runtime.start(base());assert.equal(r.state,'WAITING_APPROVAL');approved=true;r=await runtime.resume({company_id:'c1',run_id:r.run_id,input:{role:'system',content:'approval granted'}});assert.equal(r.state,'COMPLETED');assert.equal(executions,1);assert.equal(modelCalls,2);});
test('gateway wait resumes through gateway resume with same execution rather than replay',async()=>{let executeCalls=0,resumeCalls=0;const f=fixture([{tool_calls:[{id:'pay1',name:'remote_change',arguments:{job:'j1'}}]},{final:'verified'}],{authority:{authorize:async()=>({status:'allowed',decision_id:'d1'}),execute:async()=>{executeCalls++;return{state:'WAITING_MFA',operation_id:'op1'};},resume:async({execution})=>{resumeCalls++;assert.equal(execution.operation_id,'op1');return{state:'VERIFIED',verified:true,evidence_ref:'ev3',output:{changed:true}};}}});let r=await f.runtime.start(base());assert.equal(r.state,'WAITING_MFA');r=await f.runtime.resume({company_id:'c1',run_id:r.run_id,input:{role:'event',content:'mfa-complete'}});assert.equal(r.state,'COMPLETED');assert.equal(executeCalls,1);assert.equal(resumeCalls,1);});
test('explicit external model wait persists and resumes',async()=>{const f=fixture([{wait:{state:'WAITING_EXTERNAL',kind:'reply',correlation_id:'msg1'}},{final:'Sarah replied'}]);let r=await f.runtime.start(base());assert.equal(r.state,'WAITING_EXTERNAL');assert.equal((await f.runtime.recover())[0].run_id,r.run_id);r=await f.runtime.resume({company_id:'c1',run_id:r.run_id,input:{role:'event',content:'yes'}});assert.equal(r.state,'COMPLETED');});
test('company isolation rejects cross-company resume',async()=>{const f=fixture([{wait:{state:'WAITING_USER'}}]);const r=await f.runtime.start(base());await assert.rejects(()=>f.runtime.resume({company_id:'c2',run_id:r.run_id}),/not-found/);});
test('provider failure is explicit',async()=>{const store=new InMemoryRunStore();const runtime=new TitanAgentRuntime({store,modelRouter:{next:async()=>{throw new Error('provider-down')}}});const r=await runtime.start(base());assert.equal(r.state,'FAILED');assert.match(r.error.message,/provider-down/);});
test('tool failure is explicit',async()=>{const f=fixture([{tool_calls:[{id:'t',name:'x',arguments:{}}]}],{authority:{authorize:async()=>({status:'allowed'}),execute:async()=>{throw new Error('tool-down')}}});const r=await f.runtime.start(base());assert.equal(r.state,'FAILED');assert.match(r.error.message,/tool-down/);});
test('provider acknowledgement without verification fails closed',async()=>{const f=fixture([{tool_calls:[{id:'t',name:'x',arguments:{}}]}],{authority:{authorize:async()=>({status:'allowed'}),execute:async()=>({state:'SUCCEEDED',output:'provider ack only'})}});const r=await f.runtime.start(base());assert.equal(r.state,'FAILED');assert.match(r.error.message,/unverified/);assert.equal(f.events.some(e=>e.type==='tool.completed'),false);});
test('explicit verification failure after provider success fails closed',async()=>{const f=fixture([{tool_calls:[{id:'t',name:'x',arguments:{}}]}],{authority:{authorize:async()=>({status:'allowed'}),execute:async()=>({state:'SUCCEEDED',verification:{status:'FAILED'},output:'provider ack only'})}});const r=await f.runtime.start(base());assert.equal(r.state,'FAILED');assert.match(r.error.message,/unverified/);assert.equal(f.events.some(e=>e.type==='tool.completed'),false);});
test('verified execution with evidence can continue to completion',async()=>{const f=fixture([{tool_calls:[{id:'t',name:'x',arguments:{}}]},{final:'done'}],{authority:{authorize:async()=>({status:'allowed',decision_id:'d1'}),execute:async()=>({state:'VERIFIED',verified:true,evidence_ref:'ev-verified',output:{ok:true}})}});const r=await f.runtime.start(base());assert.equal(r.state,'COMPLETED');const completed=f.events.find(e=>e.type==='tool.completed');assert.equal(completed?.verified,true);assert.equal(completed?.evidence_ref,'ev-verified');});
test('unverified consequential outcome fails closed',async()=>{const f=fixture([{tool_calls:[{id:'t',name:'x',arguments:{}}]}],{authority:{authorize:async()=>({status:'allowed'}),execute:async()=>({state:'SUCCEEDED',verified:false,output:'provider ack only'})}});const r=await f.runtime.start(base());assert.equal(r.state,'FAILED');assert.match(r.error.message,/unverified/);});
test('denied authority never executes capability',async()=>{let executed=false;const f=fixture([{tool_calls:[{id:'t',name:'x',arguments:{}}]},{final:'not executed'}],{authority:{authorize:async()=>({status:'denied'}),execute:async()=>{executed=true}}});const r=await f.runtime.start(base());assert.equal(r.state,'COMPLETED');assert.equal(executed,false);});
test('cancellation is terminal',async()=>{const f=fixture([{wait:{state:'WAITING_USER'}}]);let r=await f.runtime.start(base());r=await f.runtime.cancel({company_id:'c1',run_id:r.run_id});assert.equal(r.state,'CANCELLED');await assert.rejects(()=>f.runtime.resume({company_id:'c1',run_id:r.run_id}),/terminal/);});
test('cancellation stores bounded correlation and cannot override run identity or event state',async()=>{const f=fixture([{wait:{state:'WAITING_USER'}}]);const run=await f.runtime.start(base());await assert.rejects(()=>f.runtime.cancel({company_id:'c1',run_id:run.run_id,cancellation:{actor_id:'other',request_id:'forged'}}),/runtime-cancellation-actor-conflict/);assert.equal((await f.store.get('c1',run.run_id)).state,'WAITING_USER');const cancelled=await f.runtime.cancel({company_id:'c1',run_id:run.run_id,cancellation:{actor_id:'owner',request_id:'cancel-request',operation_id:'cancel-operation',company_id:'c2',run_id:'forged-run',type:'run.completed',state:'COMPLETED'}});assert.equal(cancelled.state,'CANCELLED');assert.equal(cancelled.cancellation.actor_id,'owner');assert.equal(cancelled.cancellation.request_id,'cancel-request');assert.equal(cancelled.cancellation.operation_id,'cancel-operation');assert.equal(cancelled.cancellation.company_id,undefined);const event=f.events.at(-1);assert.equal(event.type,'run.cancelled');assert.equal(event.state,'CANCELLED');assert.equal(event.company_id,'c1');assert.equal(event.run_id,run.run_id);assert.equal(event.actor_id,'owner');assert.equal(event.request_id,'cancel-request');});
test('invalid transitions fail closed',()=>assert.throws(()=>assertTransition('COMPLETED','RUNNING'),/transition-invalid/));
