import assert from 'node:assert/strict';
import { createChatEvent, createChatComponent } from '../src/ported/titan-runtime/interaction-engine/chat-protocol.js';
import { createChatState, applyChatEvent } from '../src/ported/titan-runtime/interaction-engine/chat-state.js';
let n=0; const test=(name,fn)=>{fn();n++;console.log('PASS',name)};
const base=()=>createChatState({conversation_id:'c1',company_id:'co1',surface:'command'});
const ev=(x={})=>createChatEvent({event_id:x.event_id??'e1',conversation_id:'c1',company_id:'co1',surface:'zero',type:x.type??'stream_delta',sequence:x.sequence,stream_id:x.stream_id??'s1',text:x.text??'Hi',stream_complete:x.stream_complete});
let s=base(); s=applyChatEvent(s,ev({sequence:1,event_id:'e1',text:'Hel'}));
test('stream delta starts progressive response',()=>assert.equal(s.streams[0].text,'Hel'));
s=applyChatEvent(s,ev({sequence:2,event_id:'e2',text:'lo'}));
test('stream deltas append in order',()=>assert.equal(s.streams[0].text,'Hello'));
const before=s; s=applyChatEvent(s,ev({sequence:2,event_id:'e2',text:'MUTATE'}));
test('duplicate event id is idempotent',()=>assert.strictEqual(s,before));
test('duplicate replay does not increment revision',()=>assert.equal(s.revision,2));
test('out of order future event fails closed',()=>assert.throws(()=>applyChatEvent(s,ev({sequence:4,event_id:'e4'})),/out-of-order/));
test('old sequence with new event id fails closed',()=>assert.throws(()=>applyChatEvent(s,ev({sequence:1,event_id:'old'})),/out-of-order/));
s=applyChatEvent(s,ev({sequence:3,event_id:'e3',text:'!',stream_complete:true}));
test('stream can be finalized',()=>assert.equal(s.streams[0].complete,true));
test('completed stream rejects further mutation',()=>assert.throws(()=>applyChatEvent(s,ev({sequence:4,event_id:'e4',text:'x'})),/already-complete/));
test('sequence alias surface canonicalizes',()=>assert.equal(s.surface,'zero'));
test('processed event history records unique accepted ids',()=>assert.deepEqual(s.processed_event_ids,['e1','e2','e3']));
test('cross company progressive event fails closed',()=>assert.throws(()=>applyChatEvent(s,createChatEvent({event_id:'x',conversation_id:'c1',company_id:'co2',surface:'zero',type:'stream_delta',sequence:4,stream_id:'s2',text:'x'})),/company-mismatch/));
test('missing stream id fails closed',()=>assert.throws(()=>applyChatEvent(base(),createChatEvent({event_id:'x2',conversation_id:'c1',company_id:'co1',surface:'zero',type:'stream_delta',sequence:1,text:'x'})),/stream-id-required/));
test('invalid sequence fails closed',()=>assert.throws(()=>applyChatEvent(base(),ev({event_id:'x3',sequence:0})),/sequence-invalid/));
let bounded=base(); for(let i=1;i<=105;i++) bounded=applyChatEvent(bounded,createChatEvent({event_id:`b${i}`,conversation_id:'c1',company_id:'co1',surface:'zero',type:'system_notice',sequence:i,text:'x'}));
test('idempotency history is bounded',()=>assert.equal(bounded.processed_event_ids.length,100));
test('stream state grants no authority',()=>assert.equal(s.authority_granted,false));
console.log(`RESULT ${n}/15 PASS`);
