import assert from 'node:assert/strict';
import { createChatEvent, createChatComponent } from '../src/ported/titan-runtime/interaction-engine/chat-protocol.js';
import { createChatState, applyChatEvent } from '../src/ported/titan-runtime/interaction-engine/chat-state.js';
let n=0; const test=(name,fn)=>{fn();n++;console.log('PASS',name)};
const component=(id,title)=>createChatComponent({component_id:id,kind:'card',props:{title},actions:[{intent:'job.open',params:{id}}]});
let state=createChatState({conversation_id:'conv',company_id:'co-1',surface:'go',components:[component('a','A'),component('b','B'),component('c','C')]});
test('state starts authority neutral',()=>assert.equal(state.authority_granted,false));
const update=createChatEvent({event_id:'e1',conversation_id:'conv',company_id:'co-1',surface:'field',type:'component_update',expected_revision:0,components:[component('b','B updated')]});
state=applyChatEvent(state,update);
test('component update patches only target',()=>assert.deepEqual(state.components.map(c=>c.props.title),['A','B updated','C']));
test('component update increments revision',()=>assert.equal(state.revision,1));
test('stale update fails closed',()=>assert.throws(()=>applyChatEvent(state,update),/stale/));
test('missing component update target fails closed',()=>assert.throws(()=>applyChatEvent(state,createChatEvent({event_id:'e2',conversation_id:'conv',company_id:'co-1',surface:'go',type:'component_update',expected_revision:1,components:[component('x','X')]})),/target-missing/));
const result=createChatEvent({event_id:'e3',conversation_id:'conv',company_id:'co-1',surface:'go',type:'action_result',expected_revision:1,result:{action_id:'act1',intent:'job.open',status:'succeeded',receipt_id:'r1',message:'Opened',token:'strip-me'}});
state=applyChatEvent(state,result);
test('action result records Command Bus receipt without authority',()=>assert.deepEqual([state.action_results[0].execution_owner,state.action_results[0].authority_granted],['command-bus',false]));
test('action result does not replace cards',()=>assert.equal(state.components.length,3));
const error=createChatEvent({event_id:'e4',conversation_id:'conv',company_id:'co-1',surface:'go',type:'error',expected_revision:2,error:{code:'downstream_timeout',message:'Try again',retryable:true,secret:'strip'}});
state=applyChatEvent(state,error);
test('error becomes bounded presentation state',()=>assert.equal(state.errors[0].code,'downstream_timeout'));
test('cross-company event fails closed',()=>assert.throws(()=>applyChatEvent(state,createChatEvent({event_id:'e5',conversation_id:'conv',company_id:'co-2',surface:'go',type:'system_notice',text:'x'})),/company-mismatch/));
test('cross-surface event fails closed',()=>assert.throws(()=>applyChatEvent(state,createChatEvent({event_id:'e6',conversation_id:'conv',company_id:'co-1',surface:'hub',type:'system_notice',text:'x'})),/surface-mismatch/));
test('cross-conversation event fails closed',()=>assert.throws(()=>applyChatEvent(state,createChatEvent({event_id:'e7',conversation_id:'other',company_id:'co-1',surface:'go',type:'system_notice',text:'x'})),/conversation-mismatch/));
test('legacy tenant authority rejected in result',()=>assert.throws(()=>createChatEvent({event_id:'e8',conversation_id:'conv',company_id:'co-1',surface:'go',type:'action_result',result:{status:'succeeded',tenant_id:'bad'}})));
test('invalid action result status fails closed',()=>assert.throws(()=>applyChatEvent(state,createChatEvent({event_id:'e9',conversation_id:'conv',company_id:'co-1',surface:'go',type:'action_result',expected_revision:3,result:{action_id:'a',intent:'x',status:'running'}})),/status-invalid/));
test('state retains max three cards',()=>assert.ok(state.components.length<=3));
console.log(`RESULT ${n}/14 PASS`);
