import test from 'node:test';import assert from 'node:assert/strict';
import {buildRoleWorkerSeparationProjection} from '../titan-workforce/roles/role-worker-separation.mjs';
import {validateRoleWorkerIntegrity} from '../titan-workforce/roles/role-worker-integrity.mjs';
import {buildRoleWorkerStaffingProjection} from '../titan-workforce/roles/role-worker-staffing-projection.mjs';
import {buildRoleWorkerChangeSet,summarizeRoleWorkerChangeSet} from '../titan-workforce/roles/role-worker-change-set.mjs';
const roles=[{role_definition_id:'role.cleaner',name:'Cleaner',company_boundary:'company_id',activation_confers_authority:false},{role_definition_id:'role.supervisor',name:'Supervisor',company_boundary:'company_id',activation_confers_authority:false}];
function staffing(roster=[],assignments=[],critical=['role.supervisor'],company_id='co-1'){const s=buildRoleWorkerSeparationProjection({company_id,role_definitions:roles,roster,assignments});const i=validateRoleWorkerIntegrity(s,{critical_role_definition_ids:critical});return buildRoleWorkerStaffingProjection(s,i,{critical_role_definition_ids:critical});}
test('detects staffing and assignment changes without applying them',()=>{const a=staffing([],[]);const b=staffing([{worker_id:'w1',role_definition_id:'role.cleaner'}],[{assignment_id:'a1',worker_id:'w1',role_definition_id:'role.cleaner'}]);const c=buildRoleWorkerChangeSet(a,b);assert.equal(c.summary.changed,true);assert.equal(c.summary.role_changes,1);assert.equal(c.summary.worker_changes,1);assert.equal(c.applies_mutations,false);assert.equal(c.creates_assignments,false);});
test('tracks worker role changes explicitly',()=>{const a=staffing([{worker_id:'w1',role_definition_id:'role.cleaner'}]);const b=staffing([{worker_id:'w1',role_definition_ids:['role.cleaner','role.supervisor']}]);const c=buildRoleWorkerChangeSet(a,b);const w=c.worker_changes[0];assert.deepEqual(w.role_delta.added,['role.supervisor']);assert.deepEqual(w.role_delta.removed,[]);assert.equal(w.grants_authority,false);});
test('tracks newly critical unstaffed and resolved critical roles',()=>{const a=staffing([],[],[]);const b=staffing([],[],['role.supervisor']);const c=buildRoleWorkerChangeSet(a,b);assert.deepEqual(c.critical_unstaffed_delta.added,['role.supervisor']);const d=staffing([{worker_id:'s1',role_definition_id:'role.supervisor'}],[],['role.supervisor']);const e=buildRoleWorkerChangeSet(b,d);assert.deepEqual(e.critical_unstaffed_delta.resolved,['role.supervisor']);});
test('no-op comparison stays empty and authority neutral',()=>{const a=staffing([{worker_id:'w1',role_definition_id:'role.cleaner'}]);const c=buildRoleWorkerChangeSet(a,structuredClone(a));assert.equal(c.summary.changed,false);assert.equal(c.role_changes.length,0);assert.equal(c.worker_changes.length,0);const s=summarizeRoleWorkerChangeSet(c);assert.equal(s.read_only,true);assert.equal(s.grants_authority,false);});
test('cross-company comparison fails closed',()=>{const a=staffing([],[],[],'co-1'),b=staffing([],[],[],'co-2');assert.throws(()=>buildRoleWorkerChangeSet(a,b),/company-mismatch/);});
