import test from 'node:test';
import assert from 'node:assert/strict';
import {buildResolvedServiceHandoff,buildResolvedServiceHandoffDedupeKey,MemoryResolvedServiceHandoffLedger} from '../titan-workforce/customer-care/resolved-service-handoff.mjs';

const baseCase=(overrides={})=>({company_id:'co-1',case_id:'case-1',customer_id:'cust-1',job_id:'job-1',location_id:'loc-1',invoice_id:'inv-1',state:'RESOLVED',sentiment:'POSITIVE',issue_class:'QUALITY',evidence_refs:['ev-case'],authority_granted:false,execution_permitted:false,...overrides});
const refs={customer_record:{company_id:'co-1',customer_id:'cust-1'},job_record:{company_id:'co-1',job_id:'job-1'},location_record:{company_id:'co-1',location_id:'loc-1'},invoice_record:{company_id:'co-1',invoice_id:'inv-1'}};

test('resolved Jobs follow-up is structured, evidence-backed and authority neutral',()=>{const h=buildResolvedServiceHandoff({company_id:'co-1',case_record:baseCase(),target:'jobs',reason:'REWORK_REVIEW',evidence_refs:['ev-extra'],...refs});assert.equal(h.target,'jobs');assert.equal(h.source_records_authoritative,true);assert.equal(h.overwrite_source_records,false);assert.equal(h.direct_mutation,false);assert.equal(h.authority_granted,false);assert.equal(h.execution_permitted,false);assert.deepEqual(h.evidence_refs,['ev-case','ev-extra']);});
test('Rebooking handoff requires satisfactory resolved outcome',()=>{assert.throws(()=>buildResolvedServiceHandoff({company_id:'co-1',case_record:baseCase(),target:'rebooking',reason:'SATISFIED_REPEAT_OPPORTUNITY',outcome_satisfactory:false,...refs}),/satisfactory-outcome-required/);const h=buildResolvedServiceHandoff({company_id:'co-1',case_record:baseCase(),target:'rebooking',reason:'SATISFIED_REPEAT_OPPORTUNITY',outcome_satisfactory:true,...refs});assert.equal(h.target,'rebooking');});
test('Sales expansion handoff requires satisfactory resolved outcome',()=>{const h=buildResolvedServiceHandoff({company_id:'co-1',case_record:baseCase(),target:'sales',reason:'EXPANSION_SIGNAL',outcome_satisfactory:true,...refs});assert.equal(h.target,'sales');assert.equal(h.downstream_action_completed,false);});
test('negative sentiment blocks rebooking and sales even when resolved',()=>{for(const target of ['rebooking','sales'])assert.throws(()=>buildResolvedServiceHandoff({company_id:'co-1',case_record:baseCase({sentiment:'NEGATIVE'}),target,reason:target==='sales'?'EXPANSION_SIGNAL':'SATISFIED_REPEAT_OPPORTUNITY',outcome_satisfactory:true,...refs}),/satisfactory-outcome-required/);});
test('unresolved source case cannot hand off downstream',()=>{assert.throws(()=>buildResolvedServiceHandoff({company_id:'co-1',case_record:baseCase({state:'TRIAGED'}),target:'jobs',reason:'REWORK_REVIEW',...refs}),/case-not-resolved/);});
test('target reason must remain inside existing Customer Care contract',()=>{assert.throws(()=>buildResolvedServiceHandoff({company_id:'co-1',case_record:baseCase(),target:'jobs',reason:'EXPANSION_SIGNAL',...refs}),/reason-invalid/);});
test('cross-company linked records fail closed',()=>{assert.throws(()=>buildResolvedServiceHandoff({company_id:'co-1',case_record:baseCase(),target:'jobs',reason:'REWORK_REVIEW',...refs,job_record:{company_id:'co-2',job_id:'job-1'}}),/cross-company-job/);});
test('linked record ID mismatch fails closed',()=>{assert.throws(()=>buildResolvedServiceHandoff({company_id:'co-1',case_record:baseCase(),target:'jobs',reason:'REWORK_REVIEW',...refs,invoice_record:{company_id:'co-1',invoice_id:'other'}}),/invoice-id-mismatch/);});
test('legacy tenant boundary fields are rejected',()=>{assert.throws(()=>buildResolvedServiceHandoff({company_id:'co-1',tenant_company_id:'legacy',case_record:baseCase(),target:'jobs',reason:'REWORK_REVIEW',...refs}),/legacy-company-boundary/);});
test('authority-bearing case is rejected',()=>{assert.throws(()=>buildResolvedServiceHandoff({company_id:'co-1',case_record:baseCase({authority_granted:true}),target:'jobs',reason:'REWORK_REVIEW',...refs}),/authority-bearing-case-forbidden/);});
test('evidence is mandatory for resolved-service handoff',()=>{assert.throws(()=>buildResolvedServiceHandoff({company_id:'co-1',case_record:baseCase({evidence_refs:[]}),target:'jobs',reason:'REWORK_REVIEW',...refs}),/evidence-required/);});
test('dedupe key is deterministic and company/case/target/reason scoped',()=>{const a=buildResolvedServiceHandoffDedupeKey({company_id:'co-1',case_id:'case-1',target:'jobs',reason:'REWORK_REVIEW'});const b=buildResolvedServiceHandoffDedupeKey({company_id:'co-1',case_id:'case-1',target:'jobs',reason:'REWORK_REVIEW'});assert.equal(a,b);assert.match(a,/co-1:case-1:jobs:REWORK_REVIEW/);});
test('memory ledger suppresses duplicate downstream handoff',()=>{const ledger=new MemoryResolvedServiceHandoffLedger();const h=buildResolvedServiceHandoff({company_id:'co-1',case_record:baseCase(),target:'jobs',reason:'REWORK_REVIEW',...refs});assert.equal(ledger.record(h).duplicate,false);assert.equal(ledger.record(h).duplicate,true);});
test('generic Customer Care handoff remains nested and authority neutral',()=>{const h=buildResolvedServiceHandoff({company_id:'co-1',case_record:baseCase(),target:'sales',reason:'EXPANSION_SIGNAL',outcome_satisfactory:true,...refs});assert.equal(h.generic_handoff.schema,'titan.workforce.customer-care.handoff.v1');assert.equal(h.generic_handoff.authority_granted,false);assert.equal(h.generic_handoff.execution_permitted,false);});
