import test from 'node:test';
import assert from 'node:assert/strict';
import {createCompatBootstrap,COMPAT_BOOTSTRAP_SCHEMA} from '../titan-runtime/compat-decomposition/compat-bootstrap.mjs';
const registry={translation:{kind:'module',path:'translation.mjs',startup_required:false,company_scoped:false},docs:{kind:'module',path:'docs.mjs',startup_required:false,company_scoped:true}};
test('bootstrap install preserves a stable global contract without eager feature loading',()=>{let loads=0;const globalTarget={};const b=createCompatBootstrap({registry,globalTarget,moduleLoader:async()=>{loads++;return{}},resolveUrl:x=>x});assert.equal(b.schema,COMPAT_BOOTSTRAP_SCHEMA);b.install();assert.equal(globalTarget.TitanCompatBootstrap,b);assert.equal(loads,0);assert.equal(b.describe('translation').loaded,false);assert.equal(b.install(),b);assert.equal(loads,0);});
test('first use lazily loads and caches an optional feature',async()=>{let loads=0;const b=createCompatBootstrap({registry,moduleLoader:async()=>{loads++;return{ok:true}},resolveUrl:x=>x});const a=await b.load('translation');const c=await b.load('translation');assert.equal(loads,1);assert.equal(a.value.ok,true);assert.equal(c.value.ok,true);assert.equal(a.state.authority_neutral,true);});
test('company scoped optional features preserve company_id and reject legacy tenant authority',async()=>{const b=createCompatBootstrap({registry,moduleLoader:async()=>({}),resolveUrl:x=>x});await assert.rejects(b.load('docs'),/company_id_required/);await assert.rejects(b.load('docs',{company_id:'c1',tenant_id:'legacy'}),/legacy_tenant_authority_rejected/);const r=await b.load('docs',{company_id:'c1'});assert.equal(r.company_id,'c1');assert.equal(r.state.loading_confers_authority,false);});
test('event bridge registers once and routes first-use loading through bootstrap',async()=>{const handlers=new Map();let loads=0;const eventTarget={addEventListener:(n,h)=>handlers.set(n,h),removeEventListener:n=>handlers.delete(n)};const b=createCompatBootstrap({registry,eventTarget,moduleLoader:async()=>{loads++;return{ok:true}},resolveUrl:x=>x});assert.equal(b.registerEvent('translation','titan:compat:translation'),true);assert.equal(b.registerEvent('translation','titan:compat:translation'),false);await handlers.get('titan:compat:translation')({detail:{}});assert.equal(loads,1);b.uninstall();assert.equal(handlers.size,0);});
test('failed optional loads remain retryable and do not poison bootstrap',async()=>{let attempts=0;const b=createCompatBootstrap({registry,moduleLoader:async()=>{attempts++;if(attempts===1)throw new Error('offline');return{ok:true}},resolveUrl:x=>x});await assert.rejects(b.load('translation'),/offline/);const r=await b.load('translation');assert.equal(attempts,2);assert.equal(r.value.ok,true);});
