import test from 'node:test';
import assert from 'node:assert/strict';
import {createCompatBootstrap} from '../titan-runtime/compat-decomposition/compat-bootstrap.mjs';
import {createCompatDocumentEvidenceChunk,COMPAT_DOCUMENT_EVIDENCE_CHUNK_SCHEMA} from '../titan-runtime/compat-decomposition/chunks/document-evidence.mjs';
import {createCompatBrowserSessionChunk,COMPAT_BROWSER_SESSION_CHUNK_SCHEMA} from '../titan-runtime/compat-decomposition/chunks/browser-session.mjs';

test('document and browser-session domains are lazy company-scoped bootstrap features',async()=>{let loads=0;const paths=[];const b=createCompatBootstrap({moduleLoader:async url=>{loads++;paths.push(url);return{ok:true}},resolveUrl:x=>x});assert.equal(loads,0);await assert.rejects(b.loadDocumentEvidence(),/company_id_required/);await assert.rejects(b.loadBrowserSession(),/company_id_required/);assert.equal(loads,0);const d=await b.loadDocumentEvidence({company_id:'c1'});const s=await b.loadBrowserSession({company_id:'c1'});assert.equal(loads,2);assert.deepEqual(paths,['../compat-decomposition/chunks/document-evidence.mjs','../compat-decomposition/chunks/browser-session.mjs']);assert.equal(d.company_id,'c1');assert.equal(s.company_id,'c1');assert.equal(d.state.authority_neutral,true);assert.equal(s.state.loading_confers_authority,false);});

test('document chunk reuses canonical page-evidence contract and rejects cross-company evidence',()=>{const d=createCompatDocumentEvidenceChunk({company_id:'c1'});assert.equal(d.schema,COMPAT_DOCUMENT_EVIDENCE_CHUNK_SCHEMA);const e=d.capture({url:'https://example.test',title:'Example',company_id:'c1',evidence_id:'e1'});assert.equal(e.schema,'titan.page-evidence.v1');assert.equal(e.company_id,'c1');assert.equal(e.authority_neutral,true);assert.throws(()=>d.capture({url:'https://example.test',company_id:'c2'}),/cross-company-page-evidence/);assert.equal(d.loading_confers_authority,false);});

test('browser-session chunk reuses canonical registry and preserves company boundary',()=>{const s=createCompatBrowserSessionChunk({company_id:'c1'});assert.equal(s.schema,COMPAT_BROWSER_SESSION_CHUNK_SCHEMA);const r=s.upsert({session_id:'s1',company_id:'c1',tabs:[{tab_id:7,url:'https://example.test'}]});assert.equal(r.schema,'titan.browser-session.v1');assert.equal(r.company_id,'c1');assert.equal(r.authority_neutral,true);assert.equal(s.get('s1'),r);assert.equal(s.list().length,1);assert.throws(()=>s.upsert({session_id:'s2',company_id:'c2'}),/cross-company-browser-session/);assert.equal(s.remove('s1'),true);});

test('additional feature loads dedupe independently and do not force translation or each other',async()=>{let loads=0;let release;const gate=new Promise(r=>release=r);const b=createCompatBootstrap({moduleLoader:async url=>{loads++;await gate;return{url}},resolveUrl:x=>x});const a=b.loadDocumentEvidence({company_id:'c1'});const b2=b.loadDocumentEvidence({company_id:'c1'});release();const [x,y]=await Promise.all([a,b2]);assert.equal(loads,1);assert.equal(x.value,y.value);assert.equal(b.describe('translation').loaded,false);assert.equal(b.describe('browserSession').loaded,false);});

test('failed document chunk load remains retryable and does not poison browser-session loading',async()=>{let attempts=0;const b=createCompatBootstrap({moduleLoader:async url=>{if(url.includes('document-evidence')){attempts++;if(attempts===1)throw new Error('offline');}return{url}},resolveUrl:x=>x});await assert.rejects(b.loadDocumentEvidence({company_id:'c1'}),/offline/);const s=await b.loadBrowserSession({company_id:'c1'});assert.match(s.value.url,/browser-session/);const d=await b.loadDocumentEvidence({company_id:'c1'});assert.match(d.value.url,/document-evidence/);assert.equal(attempts,2);});

test('legacy tenant aliases remain rejected for newly extracted company-scoped domains',async()=>{const b=createCompatBootstrap({moduleLoader:async()=>({}),resolveUrl:x=>x});await assert.rejects(b.loadDocumentEvidence({company_id:'c1',tenant_id:'legacy'}),/legacy_tenant_authority_rejected/);await assert.rejects(b.loadBrowserSession({company_id:'c1',tenant_company_id:'legacy'}),/legacy_tenant_authority_rejected/);});
