import test from 'node:test';
import assert from 'node:assert/strict';
import {buildRebookingRetentionAnalytics} from '../titan-workforce/starter-agents/rebooking/rebooking-retention-analytics.mjs';
const ev=(type,date='2026-08-01',over={})=>({company_id:'c1',customer_id:'u1',event_id:`${type}-${date}-${over.customer_id||'u1'}`,type,event_date:date,...over});
const build=(events=[],over={})=>buildRebookingRetentionAnalytics({company_id:'c1',as_of_date:'2026-09-09',dormancy_threshold_days:30,events,...over});
test('empty analytics is deterministic zero state',()=>{const r=build();assert.equal(r.counts.events,0);assert.equal(r.rates.rebooking_per_completed_service_pct,0)});
test('counts completed and rebooked events',()=>{const r=build([ev('SERVICE_COMPLETED'),ev('REBOOKED','2026-08-10')]);assert.equal(r.counts.completed_services,1);assert.equal(r.counts.rebooked,1);assert.equal(r.rates.rebooking_per_completed_service_pct,100)});
test('counts reactivations',()=>assert.equal(build([ev('SERVICE_COMPLETED','2026-06-01'),ev('REACTIVATED','2026-09-01')]).counts.reactivated,1));
test('counts recurring conversions',()=>assert.equal(build([ev('REBOOKED'),ev('RECURRING_CONVERSION','2026-08-02')]).rates.recurring_conversion_per_rebooked_pct,100));
test('decline rate is descriptive',()=>assert.equal(build([ev('OUTREACH_SENT'),ev('REBOOKING_DECLINED','2026-08-02')]).rates.decline_per_outreach_pct,100));
test('dormancy derived from last completed date',()=>{const r=build([ev('SERVICE_COMPLETED','2026-07-01')]);assert.equal(r.customers[0].dormant,true);assert.equal(r.customers[0].dormancy_days,70)});
test('recent completion is not dormant',()=>assert.equal(build([ev('SERVICE_COMPLETED','2026-09-01')]).customers[0].dormant,false));
test('latest completion date wins',()=>{const r=build([ev('SERVICE_COMPLETED','2026-06-01'),ev('SERVICE_COMPLETED','2026-09-01')]);assert.equal(r.customers[0].last_completed_date,'2026-09-01')});
test('multiple customers isolated in rows',()=>{const r=build([ev('SERVICE_COMPLETED','2026-08-01',{customer_id:'u2'}),ev('REBOOKED','2026-08-02',{customer_id:'u1'})]);assert.deepEqual(r.customers.map(x=>x.customer_id),['u1','u2'])});
test('opt out observed but does not infer action eligibility',()=>{const r=build([ev('OPTED_OUT')]);assert.equal(r.customers[0].opted_out,true);assert.equal(r.customers[0].eligible_for_action,null)});
test('analytics never infers consent',()=>assert.equal(build([ev('SERVICE_COMPLETED')]).customers[0].consent_status_not_inferred,true));
test('analytics never infers authority',()=>assert.equal(build([ev('SERVICE_COMPLETED')]).customers[0].authority_status_not_inferred,true));
test('analytics may not trigger outreach',()=>assert.equal(build([ev('SERVICE_COMPLETED')]).interpretation.may_trigger_outreach,false));
test('analytics may not create booking',()=>assert.equal(build([ev('SERVICE_COMPLETED')]).creates_booking,false));
test('analytics may not create schedule',()=>assert.equal(build([ev('SERVICE_COMPLETED')]).creates_schedule,false));
test('analytics may not override suppression',()=>assert.equal(build([ev('SERVICE_COMPLETED')]).interpretation.may_override_suppression,false));
test('analytics may not change consent',()=>assert.equal(build([ev('SERVICE_COMPLETED')]).changes_consent,false));
test('analytics grants no authority',()=>assert.equal(build([ev('SERVICE_COMPLETED')]).grants_authority,false));
test('analytics execution is prohibited',()=>assert.equal(build([ev('SERVICE_COMPLETED')]).execution_permitted,false));
test('cross-company event rejected',()=>assert.throws(()=>build([ev('SERVICE_COMPLETED','2026-08-01',{company_id:'c2'})]),/cross-company analytics event/));
test('legacy boundary rejected',()=>assert.throws(()=>build([],{tenant_company_id:'x'}),/legacy company boundary rejected/));
test('future event rejected',()=>assert.throws(()=>build([ev('SERVICE_COMPLETED','2026-10-01')]),/future analytics event rejected/));
test('unsupported event type rejected',()=>assert.throws(()=>build([ev('RANDOM')]),/unsupported analytics event type/));
test('invalid dormancy threshold rejected',()=>assert.throws(()=>build([],{dormancy_threshold_days:0}),/invalid dormancy_threshold_days/));
test('evidence refs retained and deduplicated',()=>{const r=build([ev('SERVICE_COMPLETED')],{evidence_refs:['z','z']});assert.deepEqual(r.evidence_refs,[ev('SERVICE_COMPLETED').event_id,'z'].sort())});
test('deterministic replay identical',()=>{const input=[ev('SERVICE_COMPLETED'),ev('REBOOKED','2026-08-02')];assert.deepEqual(build(input),build(input))});
test('identity is not authority',()=>assert.equal(build([ev('SERVICE_COMPLETED')]).identity_is_authority,false));
test('analytics explicitly descriptive not authoritative',()=>assert.equal(build([ev('SERVICE_COMPLETED')]).interpretation.descriptive_not_authoritative,true));
