import test from 'node:test';
import assert from 'node:assert/strict';
import { projectPaymentMonitoring, buildPaymentReconciliationProposal, buildPaymentReminderProposal, buildCollectionsHandoff } from '../titan-workforce/starter-agents/invoicing/payment-monitoring.mjs';

const company_id='co-1';
const invoice={company_id,invoice_ref:'inv-1',currency:'AUD',total_minor:'10000',status:'sent',due_at:'2026-09-01T00:00:00Z'};
function monitor(extra={}) { return projectPaymentMonitoring({company_id,invoice:{...invoice,...extra.invoice},payments:extra.payments??[],as_of:extra.as_of??'2026-09-08T00:00:00Z'}); }
const reconcileTool={capability:'finance.payment.reconcile',provider_ref:'Titan Finance',verified:true,command_bus_required:true};
const reminderTool={capability:'crm.invoice.reminder.send',provider_ref:'Titan CRM / Titan Connect',verified:true,command_bus_required:true};

test('read-only monitoring derives unpaid overdue state with no authority',()=>{const m=monitor();assert.equal(m.observed.balance_due_minor,'10000');assert.equal(m.observed.overdue,true);assert.equal(m.observed.days_overdue,7);assert.equal(m.authority.execution_permitted,false);assert.equal(m.authority.collections_authority,false);});
test('verified settled payments derive partial and paid states exactly',()=>{const p={company_id,payment_ref:'pay-1',currency:'AUD',amount_minor:'4000',status:'settled',verified:true};const partial=monitor({payments:[p]});assert.equal(partial.observed.payment_state,'partial');assert.equal(partial.observed.balance_due_minor,'6000');const paid=monitor({payments:[p,{...p,payment_ref:'pay-2',amount_minor:'6000'}]});assert.equal(paid.observed.payment_state,'paid');assert.equal(paid.observed.balance_due_minor,'0');});
test('overpayment is represented without mutating canonical payment state',()=>{const m=monitor({payments:[{company_id,payment_ref:'p',currency:'AUD',amount_minor:'12000',status:'cleared',verified:true}]});assert.equal(m.observed.payment_state,'overpaid');assert.equal(m.observed.balance_due_minor,'-2000');assert.equal(m.authority.canonical_payment_mutation_permitted,false);});
test('unverified payment remains a blocker and is not counted',()=>{const m=monitor({payments:[{company_id,payment_ref:'p',currency:'AUD',amount_minor:'10000',status:'settled',verified:false}]});assert.equal(m.observed.verified_paid_minor,'0');assert.ok(m.blockers.includes('unverified_payment_record'));});
test('cross-company payment fails closed',()=>{assert.throws(()=>monitor({payments:[{company_id:'co-2',payment_ref:'p',currency:'AUD',amount_minor:'1000',status:'settled',verified:true}]}),/company_boundary_mismatch/);});
test('reconciliation requires verified user-governed Titan tool and stays proposal-only',()=>{const m=monitor();const r=buildPaymentReconciliationProposal({company_id,monitoring:m,unmatched_payment:{company_id,payment_ref:'bank-1',currency:'AUD',amount_minor:'10000',verified:true},tool:reconcileTool});assert.equal(r.capability,'finance.payment.reconcile');assert.equal(r.governance.user_only_workflow_observed,true);assert.equal(r.authority.execution_permitted,false);assert.throws(()=>buildPaymentReconciliationProposal({company_id,monitoring:m,unmatched_payment:{company_id,payment_ref:'bank-1',currency:'AUD',amount_minor:'10000',verified:true},tool:{...reconcileTool,verified:false}}),/tool_not_verified/);});
test('safe overdue reminder uses governed capability and contains no collections action',()=>{const m=monitor();const r=buildPaymentReminderProposal({company_id,monitoring:m,recipient:{recipient_ref:'email-1',channel:'email',safely_resolved:true},tool:reminderTool});assert.equal(r.capability,'crm.invoice.reminder.send');assert.equal(r.collections.escalation_included,false);assert.equal(r.collections.threats_or_penalties_included,false);assert.equal(r.authority.execution_permitted,false);});
test('reminders reject paid closed and not-overdue invoices',()=>{const recipient={recipient_ref:'email-1',channel:'email',safely_resolved:true};const paid=monitor({invoice:{status:'paid'},payments:[{company_id,payment_ref:'p',currency:'AUD',amount_minor:'10000',status:'settled',verified:true}]});assert.throws(()=>buildPaymentReminderProposal({company_id,monitoring:paid,recipient,tool:reminderTool}),/closed_invoice_reminder_blocked|paid_invoice_reminder_blocked/);const future=monitor({invoice:{due_at:'2026-09-10T00:00:00Z'}});assert.throws(()=>buildPaymentReminderProposal({company_id,monitoring:future,recipient,tool:reminderTool}),/invoice_not_overdue/);});
test('reminder requires safe recipient and enforces cadence',()=>{const m=monitor();assert.throws(()=>buildPaymentReminderProposal({company_id,monitoring:m,recipient:{recipient_ref:'email-1',channel:'email',safely_resolved:false},tool:reminderTool}),/safely_resolved_recipient_required/);assert.throws(()=>buildPaymentReminderProposal({company_id,monitoring:m,recipient:{recipient_ref:'email-1',channel:'email',safely_resolved:true},tool:reminderTool,prior_reminders:[{company_id,invoice_ref:'inv-1',status:'sent',occurred_at:'2026-09-07T00:00:00Z'}],cadence:{minimum_days_between_reminders:3}}),/reminder_cadence_not_elapsed/);});
test('collections is a handoff only with no payment-plan penalty or collection authority',()=>{const h=buildCollectionsHandoff(monitor());assert.equal(h.worker_can_collect,false);assert.equal(h.worker_can_commit_payment_plan,false);assert.equal(h.worker_can_add_penalty_or_late_fee,false);assert.equal(h.authority.collections_authority,false);});
