import test from "node:test";
import assert from "node:assert/strict";
import {buildDeterministicDueDateCandidate as build} from "../titan-workforce/starter-agents/rebooking/rebooking-due-date-candidates.mjs";
const base={company_id:"c1",customer_id:"u1",service_id:"svc1",opportunity_id:"rebook:c1:u1:svc1:e1",timezone:"Australia/Melbourne",completed_date:"2026-01-31",as_of_date:"2026-09-08"};
test("configured interval wins",()=>{const r=build({...base,configured_interval:{value:2,unit:"MONTHS",evidence_ref:"cfg"},prior_cadence:{value:14,unit:"DAYS"}});assert.equal(r.due_date,"2026-03-31");assert.equal(r.derivation,"CONFIGURED_INTERVAL")});
test("prior cadence used without authoritative interval",()=>{const r=build({...base,prior_cadence:{value:14,unit:"DAYS",evidence_ref:"prev"}});assert.equal(r.due_date,"2026-02-14");assert.equal(r.derivation,"VERIFIED_PRIOR_CADENCE")});
test("history median gap is deterministic",()=>{const r=build({...base,completed_date:"2026-03-01",service_history:[{company_id:"c1",completed_date:"2026-01-01",evidence_ref:"h1"},{company_id:"c1",completed_date:"2026-01-31",evidence_ref:"h2"},{company_id:"c1",completed_date:"2026-03-01",evidence_ref:"h3"}]});assert.equal(r.interval.value,30);assert.equal(r.derivation,"MEDIAN_HISTORY_GAP_DAYS");assert.equal(r.due_date,"2026-03-31")});
test("service default fallback",()=>{const r=build({...base,service_type_default_interval:{value:4,unit:"WEEKS"}});assert.equal(r.due_date,"2026-02-28");assert.equal(r.derivation,"SERVICE_TYPE_DEFAULT")});
test("insufficient evidence needs review and does not invoke model",()=>{const r=build(base);assert.equal(r.state,"NEEDS_REVIEW");assert.equal(r.model_suggestion_allowed,false);assert.equal(r.due_date,null)});
test("month end clamps safely",()=>assert.equal(build({...base,configured_interval:{value:1,unit:"MONTHS"}}).due_date,"2026-02-28"));
test("leap year clamps safely",()=>assert.equal(build({...base,completed_date:"2024-01-31",as_of_date:"2026-09-08",configured_interval:{value:1,unit:"MONTHS"}}).due_date,"2024-02-29"));
test("timezone metadata retained without instant arithmetic",()=>{const r=build({...base,completed_date:"2026-10-04",as_of_date:"2026-10-04",configured_interval:{value:7,unit:"DAYS"}});assert.equal(r.timezone,"Australia/Melbourne");assert.equal(r.due_date,"2026-10-11")});
test("cross-company history rejected",()=>assert.throws(()=>build({...base,service_history:[{company_id:"c2",completed_date:"2025-12-01"},{company_id:"c2",completed_date:"2026-01-01"},{company_id:"c2",completed_date:"2026-01-31"}]}),/cross-company/));
test("legacy boundary rejected",()=>assert.throws(()=>build({...base,tenant_company_id:"x"}),/legacy company boundary/));
test("never creates schedule booking or authority",()=>{const r=build({...base,configured_interval:{value:30,unit:"DAYS"}});assert.equal(r.creates_schedule,false);assert.equal(r.creates_booking,false);assert.equal(r.execution_permitted,false);assert.equal(r.grants_authority,false)});
test("replay is identical",()=>{const x={...base,configured_interval:{value:30,unit:"DAYS",evidence_ref:"cfg"}};assert.deepEqual(build(x),build(x))});
test("conflicting authoritative intervals fail closed",()=>assert.throws(()=>build({...base,configured_interval:{value:30,unit:"DAYS"},canonical_recurrence_interval:{value:4,unit:"WEEKS"}}),/conflicting authoritative intervals/));
test("future completion rejected",()=>assert.throws(()=>build({...base,completed_date:"2026-10-01",as_of_date:"2026-09-08",configured_interval:{value:1,unit:"MONTHS"}}),/future completed_date/));
test("provenance evidence refs retained",()=>{const r=build({...base,configured_interval:{value:30,unit:"DAYS",evidence_ref:"cfg:1"}});assert.deepEqual(r.evidence_refs,["cfg:1"])});
