import test from 'node:test';
import assert from 'node:assert/strict';
import { buildInvoiceCorrectionProposal, validateInvoiceCorrectionReceipt, correctionProposalToContractPatch } from '../titan-workforce/starter-agents/invoicing/invoice-corrections.mjs';
import { calculateExactInvoice } from '../titan-workforce/starter-agents/invoicing/exact-money.mjs';

const company_id = 'co-1';
const issued = { company_id, invoice_ref:'inv-1', status:'issued', currency:'AUD', total_minor:'10000', external_reference:'crm-inv-1' };
const tool = (action, capability='verified.finance.correction') => ({ action, capability, provider_ref:'Titan CRM revenue document authority', verified:true, command_bus_required:true });
const reason = { reason_code:'billing_error', reason_ref:'case-123' };
function exact() { return calculateExactInvoice({ company_id, currency:'AUD', line_items:[{line_ref:'l1',pricing_source_ref:'p1',quantity:'1',unit_amount_minor:'9000'}], tax:{mode:'exclusive',rate_bps:'1000'}, provenance:{pricing_source_refs:['p1'],tax_basis_ref:'gst-1',quote_or_contract_ref:'q1',actuals_ref:'a1'} }); }

test('draft cancellation is proposal-only and preserves original record',()=>{const p=buildInvoiceCorrectionProposal({company_id,action:'cancel_draft',invoice:{...issued,status:'draft'},...reason,tool:tool('cancel_draft')});assert.equal(p.source_invoice.immutable_source_record,true);assert.equal(p.governance.original_invoice_delete_permitted,false);assert.equal(p.authority.execution_permitted,false);});
test('issued invoice cannot use draft cancellation',()=>{assert.throws(()=>buildInvoiceCorrectionProposal({company_id,action:'cancel_draft',invoice:issued,...reason,tool:tool('cancel_draft')}),/draft_cancellation_requires_draft_invoice/);});
test('void of issued invoice requires explicit audit reason and verified governed tool',()=>{const p=buildInvoiceCorrectionProposal({company_id,action:'void_issued',invoice:issued,...reason,tool:tool('void_issued')});assert.equal(p.linkage.source_invoice_ref,'inv-1');assert.equal(p.governance.command_bus_required,true);assert.throws(()=>buildInvoiceCorrectionProposal({company_id,action:'void_issued',invoice:issued,reason_code:'x',reason_ref:'r',tool:{...tool('void_issued'),verified:false}}),/tool_not_verified/);});
test('credit is exact minor units linked to source and never executes refund',()=>{const p=buildInvoiceCorrectionProposal({company_id,action:'credit',invoice:issued,...reason,tool:tool('credit'),credit:{amount_minor:'2500',credit_basis_ref:'credit-policy-1',refund_requested:true}});assert.equal(p.credit.amount_minor,'2500');assert.equal(p.linkage.credit_applies_to_invoice_ref,'inv-1');assert.equal(p.credit.refund_execution_included,false);assert.equal(p.authority.refund_execution_permitted,false);});
test('credit cannot exceed original invoice total or use float money',()=>{assert.throws(()=>buildInvoiceCorrectionProposal({company_id,action:'credit',invoice:issued,...reason,tool:tool('credit'),credit:{amount_minor:'10001',credit_basis_ref:'b'}}),/credit_exceeds/);assert.throws(()=>buildInvoiceCorrectionProposal({company_id,action:'credit',invoice:issued,...reason,tool:tool('credit'),credit:{amount_minor:25.5,credit_basis_ref:'b'}}),/safe integer|integer string/);});
test('reissue requires a new invoice ref and certified replacement calculation',()=>{const p=buildInvoiceCorrectionProposal({company_id,action:'reissue',invoice:issued,...reason,tool:tool('reissue','crm.invoice.create'),replacement_exact_money:exact(),replacement_invoice_ref:'inv-2'});assert.equal(p.linkage.predecessor_invoice_ref,'inv-1');assert.equal(p.linkage.replacement_invoice_ref,'inv-2');assert.equal(p.replacement.exact_money_certified,true);assert.throws(()=>buildInvoiceCorrectionProposal({company_id,action:'reissue',invoice:issued,...reason,tool:tool('reissue'),replacement_exact_money:exact(),replacement_invoice_ref:'inv-1'}),/must_be_new_record/);});
test('cross-company invoice and replacement calculations fail closed',()=>{assert.throws(()=>buildInvoiceCorrectionProposal({company_id,action:'void_issued',invoice:{...issued,company_id:'co-2'},...reason,tool:tool('void_issued')}),/company_boundary_mismatch/);const x=exact();x.company_id='co-2';assert.throws(()=>buildInvoiceCorrectionProposal({company_id,action:'reissue',invoice:issued,...reason,tool:tool('reissue'),replacement_exact_money:x,replacement_invoice_ref:'inv-2'}),/company_boundary_mismatch/);});
test('successful correction operation is idempotently duplicate-blocked',()=>{const first=buildInvoiceCorrectionProposal({company_id,action:'void_issued',invoice:issued,...reason,tool:tool('void_issued')});assert.throws(()=>buildInvoiceCorrectionProposal({company_id,action:'void_issued',invoice:issued,...reason,tool:tool('void_issued'),prior_corrections:[{company_id,operation_id:first.operation_id,status:'executed'}]}),/duplicate_successful_correction_blocked/);});
test('receipt must preserve operation linkage and correction-specific references',()=>{const credit=buildInvoiceCorrectionProposal({company_id,action:'credit',invoice:issued,...reason,tool:tool('credit'),credit:{amount_minor:'1000',credit_basis_ref:'b'}});assert.throws(()=>validateInvoiceCorrectionReceipt(credit,{company_id,operation_id:credit.operation_id,receipt_ref:'r1',status:'executed'}),/credit_note_ref_required/);const r=validateInvoiceCorrectionReceipt(credit,{company_id,operation_id:credit.operation_id,receipt_ref:'r1',status:'executed',credit_note_ref:'cn-1'});assert.equal(r.credit_note_ref,'cn-1');assert.equal(r.authority.execution_permitted,false);});
test('contract patch marks correction_required without granting mutation authority',()=>{const p=buildInvoiceCorrectionProposal({company_id,action:'void_issued',invoice:issued,...reason,tool:tool('void_issued')});const patch=correctionProposalToContractPatch(p);assert.equal(patch.lifecycle_state,'exception');assert.equal(patch.exception.code,'correction_required');assert.equal(patch.authority.execution_permitted,false);assert.equal(patch.authority.destructive_invoice_mutation_permitted,false);});
