import test from 'node:test';import assert from 'node:assert/strict';
import {evaluateInvoiceReadiness} from '../titan-workforce/starter-agents/invoicing/invoice-readiness.mjs';
import {calculateExactInvoice} from '../titan-workforce/starter-agents/invoicing/exact-money.mjs';
import {evaluateInvoiceReviewGate} from '../titan-workforce/starter-agents/invoicing/invoice-review-gates.mjs';
import {buildInvoiceIssueSendProposal,evaluateInvoiceIssueSendDispatch,recordInvoiceIssueSendReceipt} from '../titan-workforce/starter-agents/invoicing/invoice-issue-send.mjs';
import {projectPaymentMonitoring} from '../titan-workforce/starter-agents/invoicing/payment-monitoring.mjs';
import {buildInvoiceCorrectionProposal} from '../titan-workforce/starter-agents/invoicing/invoice-corrections.mjs';
import {certifyInvoicingFinancialIntegrity} from '../titan-workforce/starter-agents/invoicing/financial-integrity-certification.mjs';
const c='co-1';
const readyInput=()=>({company_id:c,job:{company_id:c,job_ref:'j1',status:'completed',completion_ref:'done1',request_invoice:true,evidence_attachment_refs:['e1']},commercial_terms:{company_id:c,accepted:true,accepted_terms_ref:'terms1',quote_or_contract_ref:'q1',unapproved_variation_refs:[]},actuals:{company_id:c,actual_time_ref:'t1',actual_materials_ref:'m0',actuals_ref:'a1'},evidence:{company_id:c,required:true,attachment_refs:['e1'],unresolved_issue_refs:[]},tax:{company_id:c,tax_basis_ref:'tax1'},pricing:{company_id:c,currency:'AUD',pricing_source_refs:['p1']},as_of:'2026-09-08T00:00:00Z'});
const exact=(amount='10000',rate='1000')=>calculateExactInvoice({company_id:c,currency:'AUD',line_items:[{line_ref:'l1',pricing_source_ref:'p1',quantity:'1',unit_amount_minor:amount}],tax:{mode:'exclusive',rate_bps:rate},provenance:{pricing_source_refs:['p1'],tax_basis_ref:'tax1',quote_or_contract_ref:'q1',actuals_ref:'a1'}});
const tools={invoice:{capability:'crm.invoice.create',provider_ref:'Titan CRM',verified:true,command_bus_required:true},send:{capability:'crm.invoice.send',provider_ref:'Titan Connect',verified:true,command_bus_required:true}};
function sendProposal(ex=exact(),gate=evaluateInvoiceReviewGate({company_id:c,exact_money_result:ex,policy:{allowed_tax_modes:['exclusive'],allowed_tax_rate_bps:['1000']}})){return buildInvoiceIssueSendProposal({company_id:c,contract:{schema:'titan.workforce.starter.invoicing.contract.v1',company_id:c,invoice_ref:'inv-1',blockers:[]},readiness:{schema:'titan.workforce.starter.invoicing.readiness.v1',company_id:c,ready:true},exact_money:ex,review_gate:gate,canonical_invoice:{company_id:c,invoice_ref:'inv-1'},delivery:{recipient_ref:'email1',channel:'email'},tools});}

test('exact-money supports values beyond JS safe integer without float loss',()=>{const r=exact('900719925474099300000');assert.equal(r.totals.total_minor,'990791918021509230000');assert.equal(r.arithmetic.binary_float_used,false);});
test('half-up tax rounding is deterministic at minor-unit boundary',()=>{const r=exact('333','150');assert.equal(r.totals.tax_minor,'5');assert.equal(r.totals.total_minor,'338');});
test('duplicate line references and fractional numeric money fail closed',()=>{assert.throws(()=>calculateExactInvoice({company_id:c,currency:'AUD',line_items:[{line_ref:'x',pricing_source_ref:'p',quantity:'1',unit_amount_minor:'10'},{line_ref:'x',pricing_source_ref:'p',quantity:'1',unit_amount_minor:'10'}],tax:{mode:'zero'},provenance:{pricing_source_refs:['p'],tax_basis_ref:'z'}}),/duplicate_line_ref/);assert.throws(()=>exact(10.25),/safe integer|integer string/);});
test('stale completed job is still blocked from invoice readiness',()=>{const i=readyInput();i.job.stale=true;const r=evaluateInvoiceReadiness(i);assert.equal(r.ready,false);assert.ok(r.blockers.includes('stale_job_state'));});
test('quote variance without explicit threshold forces review',()=>{const r=exact();const g=evaluateInvoiceReviewGate({company_id:c,exact_money_result:r,quoted_total_minor:'11000',policy:{allowed_tax_modes:['exclusive'],allowed_tax_rate_bps:['1000']}});assert.equal(g.review_required,true);assert.ok(g.review.reasons.includes('quote_variance_policy_missing'));});
test('unexpected tax mode or rate requires review rather than silent issue',()=>{const r=exact('10000','1250');const g=evaluateInvoiceReviewGate({company_id:c,exact_money_result:r,policy:{allowed_tax_modes:['exclusive'],allowed_tax_rate_bps:['1000']}});assert.equal(g.review_required,true);assert.ok(g.review.reasons.includes('unusual_or_overridden_tax'));});
test('successful send receipt blocks duplicate while failed receipt remains retry-safe',()=>{const p=sendProposal();const auth={company_id:c,verified:true,status:'approved',receipt_ref:'auth1'};const failed=recordInvoiceIssueSendReceipt(p,{company_id:c,operation_id:p.identity.operation_id,idempotency_key:p.identity.idempotency_key,external_reference_key:p.identity.external_reference_key,status:'failed',receipt_ref:'rf',provider_ref:'Titan Connect'});assert.equal(evaluateInvoiceIssueSendDispatch(p,{company_id:c,authority_receipt:auth,existing_receipts:[failed]}).allowed,true);const sent={...failed,status:'sent'};assert.equal(evaluateInvoiceIssueSendDispatch(p,{company_id:c,authority_receipt:auth,existing_receipts:[sent]}).reason,'duplicate_send_prevented');});
test('partial exact payment and overpayment never mutate canonical payment authority',()=>{const invoice={company_id:c,invoice_ref:'inv-1',currency:'AUD',total_minor:'11000',status:'sent',due_at:'2026-09-01T00:00:00Z'};const partial=projectPaymentMonitoring({company_id:c,invoice,payments:[{company_id:c,payment_ref:'p1',currency:'AUD',amount_minor:'4000',status:'settled',verified:true}],as_of:'2026-09-08T00:00:00Z'});assert.equal(partial.observed.balance_due_minor,'7000');const over=projectPaymentMonitoring({company_id:c,invoice,payments:[{company_id:c,payment_ref:'p1',currency:'AUD',amount_minor:'12000',status:'settled',verified:true}],as_of:'2026-09-08T00:00:00Z'});assert.equal(over.observed.balance_due_minor,'-1000');assert.equal(over.authority.canonical_payment_mutation_permitted,false);});
test('cross-company data fails closed across readiness payment and certification layers',()=>{const i=readyInput();i.tax.company_id='co-2';assert.deepEqual(evaluateInvoiceReadiness(i).blockers,['company_boundary_mismatch']);assert.throws(()=>projectPaymentMonitoring({company_id:c,invoice:{company_id:'co-2',invoice_ref:'i',currency:'AUD',total_minor:'1',status:'sent'}}),/company_boundary_mismatch/);assert.throws(()=>certifyInvoicingFinancialIntegrity({company_id:c,exact_money_result:{...exact(),company_id:'co-2'}}),/company_boundary_mismatch/);});
test('credit correction cannot exceed invoice and cannot imply refund authority',()=>{const tool={action:'credit',capability:'verified.finance.correction',provider_ref:'Titan CRM',verified:true,command_bus_required:true};assert.throws(()=>buildInvoiceCorrectionProposal({company_id:c,action:'credit',invoice:{company_id:c,invoice_ref:'inv-1',status:'issued',currency:'AUD',total_minor:'11000'},reason_code:'error',reason_ref:'case1',tool,credit:{amount_minor:'11001',credit_basis_ref:'b'}}),/credit_exceeds/);const p=buildInvoiceCorrectionProposal({company_id:c,action:'credit',invoice:{company_id:c,invoice_ref:'inv-1',status:'issued',currency:'AUD',total_minor:'11000'},reason_code:'error',reason_ref:'case1',tool,credit:{amount_minor:'1000',credit_basis_ref:'b',refund_requested:true}});assert.equal(p.authority.refund_execution_permitted,false);});
test('financial-integrity certification passes an intact cross-module snapshot and grants no authority',()=>{const r=evaluateInvoiceReadiness(readyInput());const x=exact();const g=evaluateInvoiceReviewGate({company_id:c,exact_money_result:x,policy:{allowed_tax_modes:['exclusive'],allowed_tax_rate_bps:['1000']}});const s=sendProposal(x,g);const m=projectPaymentMonitoring({company_id:c,invoice:{company_id:c,invoice_ref:'inv-1',currency:'AUD',total_minor:x.totals.total_minor,status:'sent',due_at:'2026-09-30T00:00:00Z'},payments:[],as_of:'2026-09-08T00:00:00Z'});const cert=certifyInvoicingFinancialIntegrity({company_id:c,readiness:r,exact_money_result:x,review_gate:g,issue_send_proposal:s,payment_monitoring:m});assert.equal(cert.certified,true);assert.deepEqual(cert.blocking_invariants,[]);assert.equal(cert.authority.execution_permitted,false);});
test('financial-integrity certification exposes tampered invariant instead of certifying it',()=>{const x=exact();x.reconciliation.subtotal_discount_tax_matches_total=false;const cert=certifyInvoicingFinancialIntegrity({company_id:c,exact_money_result:x});assert.equal(cert.certified,false);assert.ok(cert.blocking_invariants.includes('exact_money_reconciled'));});
