import test from 'node:test';import assert from 'node:assert/strict';
import {buildRebookingSettingsPolicy,evaluateRebookingAutoProposal} from '../titan-workforce/starter-agents/rebooking/rebooking-settings-policy.mjs';
const base=()=>({company_id:'c1',revision:3,provenance:{producer:'settings-ui',evidence_refs:['e2','e1','e1']},cadence:{default_interval:{value:4,unit:'WEEKS'}},dormancy:{threshold_days:90},outreach:{channels:['EMAIL','SMS','EMAIL'],quiet_hours:{start:'20:00',end:'08:00'},frequency_caps:{max_7d:1,max_30d:3}},suppression:{block_open_complaint:true,block_service_recovery:true,block_active_booking:true},auto_proposal:{enabled:true,recurring_score_threshold:70,reactivation_score_threshold:75},incentive:{enabled:true,max_discount_percent:15,requires_explicit_approval:true}});
test('builds deterministic governed settings',()=>{assert.deepEqual(buildRebookingSettingsPolicy(base()),buildRebookingSettingsPolicy(base()))});
test('company boundary retained',()=>assert.equal(buildRebookingSettingsPolicy(base()).company_id,'c1'));
test('legacy boundary rejected',()=>assert.throws(()=>buildRebookingSettingsPolicy({...base(),tenant_company_id:'x'})));
test('provenance required',()=>{const x=base();delete x.provenance.producer;assert.throws(()=>buildRebookingSettingsPolicy(x))});
test('revision required',()=>{const x=base();x.revision=-1;assert.throws(()=>buildRebookingSettingsPolicy(x))});
test('cadence interval validated',()=>{const x=base();x.cadence.default_interval.unit='HOURS';assert.throws(()=>buildRebookingSettingsPolicy(x))});
test('dormancy validated',()=>{const x=base();x.dormancy.threshold_days=0;assert.throws(()=>buildRebookingSettingsPolicy(x))});
test('channels deduplicated',()=>assert.deepEqual(buildRebookingSettingsPolicy(base()).configured.outreach.channels,['EMAIL','SMS']));
test('unsupported channel rejected',()=>{const x=base();x.outreach.channels=['FAX'];assert.throws(()=>buildRebookingSettingsPolicy(x))});
test('quiet hours validated',()=>{const x=base();x.outreach.quiet_hours.start='25:00';assert.throws(()=>buildRebookingSettingsPolicy(x))});
test('frequency caps validated',()=>{const x=base();x.outreach.frequency_caps={max_7d:5,max_30d:2};assert.throws(()=>buildRebookingSettingsPolicy(x))});
test('consent always required',()=>assert.equal(buildRebookingSettingsPolicy(base()).configured.outreach.consent_required,true));
test('opt out always dominates',()=>assert.equal(buildRebookingSettingsPolicy(base()).configured.outreach.opt_out_dominates,true));
test('suppression cannot be overridden',()=>assert.equal(buildRebookingSettingsPolicy(base()).configured.suppression.consent_and_opt_out_non_overridable,true));
test('auto proposal stays proposal only',()=>assert.equal(buildRebookingSettingsPolicy(base()).configured.auto_proposal.proposal_only,true));
test('auto proposal requires human review',()=>assert.equal(buildRebookingSettingsPolicy(base()).configured.auto_proposal.human_review_required,true));
test('incentive requires explicit approval',()=>{const x=base();x.incentive.requires_explicit_approval=false;assert.throws(()=>buildRebookingSettingsPolicy(x))});
test('incentive cannot self authorize',()=>assert.equal(buildRebookingSettingsPolicy(base()).configured.incentive.may_not_self_authorize,true));
test('settings are not authority',()=>assert.equal(buildRebookingSettingsPolicy(base()).governance.settings_are_policy_not_authority,true));
test('settings cannot execute',()=>assert.equal(buildRebookingSettingsPolicy(base()).execution_permitted,false));
test('settings cannot create booking or schedule',()=>{const p=buildRebookingSettingsPolicy(base());assert.equal(p.creates_booking,false);assert.equal(p.creates_schedule,false)});
test('evidence refs sorted and deduped',()=>assert.deepEqual(buildRebookingSettingsPolicy(base()).provenance.evidence_refs,['e1','e2']));
test('recurring threshold produces review only',()=>{const p=buildRebookingSettingsPolicy(base());const r=evaluateRebookingAutoProposal(p,{company_id:'c1',type:'RECURRING',score:70,consent_known:true,consent_permitted:true,opted_out:false,suppressed:false});assert.equal(r.state,'PROPOSAL_REVIEW_READY');assert.equal(r.execution_permitted,false)});
test('below threshold not ready',()=>{const p=buildRebookingSettingsPolicy(base());assert.equal(evaluateRebookingAutoProposal(p,{company_id:'c1',type:'RECURRING',score:69,consent_known:true,consent_permitted:true}).state,'NOT_READY')});
test('reactivation threshold independent',()=>{const p=buildRebookingSettingsPolicy(base());assert.equal(evaluateRebookingAutoProposal(p,{company_id:'c1',type:'REACTIVATION',score:74,consent_known:true,consent_permitted:true}).state,'NOT_READY')});
test('unknown consent blocks auto proposal',()=>{const p=buildRebookingSettingsPolicy(base());assert.ok(evaluateRebookingAutoProposal(p,{company_id:'c1',type:'RECURRING',score:100,consent_known:false,consent_permitted:true}).blockers.includes('CONSENT_UNKNOWN'))});
test('opt out blocks auto proposal regardless of score',()=>{const p=buildRebookingSettingsPolicy(base());assert.ok(evaluateRebookingAutoProposal(p,{company_id:'c1',type:'RECURRING',score:100,consent_known:true,consent_permitted:true,opted_out:true}).blockers.includes('OPTED_OUT'))});
test('suppression blocks auto proposal regardless of score',()=>{const p=buildRebookingSettingsPolicy(base());assert.ok(evaluateRebookingAutoProposal(p,{company_id:'c1',type:'RECURRING',score:100,consent_known:true,consent_permitted:true,suppressed:true}).blockers.includes('SUPPRESSED'))});
test('cross-company evaluation rejected',()=>{const p=buildRebookingSettingsPolicy(base());assert.throws(()=>evaluateRebookingAutoProposal(p,{company_id:'c2',type:'RECURRING',score:100}))});
test('legacy boundary evaluation rejected',()=>{const p=buildRebookingSettingsPolicy(base());assert.throws(()=>evaluateRebookingAutoProposal(p,{company_id:'c1',tenant_id:'x',type:'RECURRING',score:100}))});
test('disabled auto proposal blocks',()=>{const x=base();x.auto_proposal.enabled=false;const p=buildRebookingSettingsPolicy(x);assert.ok(evaluateRebookingAutoProposal(p,{company_id:'c1',type:'RECURRING',score:100,consent_known:true,consent_permitted:true}).blockers.includes('AUTO_PROPOSAL_DISABLED'))});
