import test from 'node:test';
import assert from 'node:assert/strict';
import {buildRebookingOpportunity} from '../titan-workforce/starter-agents/rebooking/rebooking-contract.mjs';
import {buildDeterministicDueDateCandidate} from '../titan-workforce/starter-agents/rebooking/rebooking-due-date-candidates.mjs';
import {scoreRebookingRecommendation} from '../titan-workforce/starter-agents/rebooking/rebooking-recommendation-scoring.mjs';
import {buildGovernedRebookingOutreach} from '../titan-workforce/starter-agents/rebooking/rebooking-governed-outreach.mjs';
import {buildRebookingResponseHandoff} from '../titan-workforce/starter-agents/rebooking/rebooking-response-handoff.mjs';
import {buildRebookingRecurringLifecycle} from '../titan-workforce/starter-agents/rebooking/rebooking-recurring-lifecycle.mjs';
import {buildRebookingRetentionAnalytics} from '../titan-workforce/starter-agents/rebooking/rebooking-retention-analytics.mjs';
import {buildRebookingSettingsPolicy,evaluateRebookingAutoProposal} from '../titan-workforce/starter-agents/rebooking/rebooking-settings-policy.mjs';

const company='c1';
const opportunity=(over={})=>buildRebookingOpportunity({company_id:company,customer_id:'u1',service_id:'svc1',source_event_id:'ev1',source_type:'COMPLETED_SERVICE',consent:{known:true,permitted:true,evidence_id:'consent1'},...over});
const recommended=(over={})=>{const o=opportunity(over.opportunity||{});const due=buildDeterministicDueDateCandidate({company_id:company,customer_id:o.customer_id,service_id:o.service_id,opportunity_id:o.opportunity_id,timezone:'Australia/Melbourne',completed_date:'2026-08-01',as_of_date:'2026-09-09',configured_interval:{value:30,unit:'DAYS',evidence_ref:'cad1'},...(over.due||{})});return scoreRebookingRecommendation({company_id:company,opportunity:o,due_date_candidate:due,as_of_date:'2026-09-09',last_completed_date:'2026-08-01',dormancy_threshold_days:90,service_history_count:4,prior_completed_services:4,customer_signal:{recurring_interest:true},...(over.score||{})})};
const authOut=(over={})=>({company_id:company,granted:true,scope:'rebooking.outreach.dispatch',checked_at:'2026-09-09T00:00:00Z',max_age_seconds:300,evidence_ref:'auth-out',...over});
const outreachBase=(over={})=>({company_id:company,customer_id:'u1',recommendation:recommended(),channel:'SMS',timezone:'Australia/Melbourne',as_of_datetime:'2026-09-09T00:00:00Z',duplicate_key:'dk1',consent:{known:true,permitted:true,opted_out:false,evidence_id:'consent1',allowed_channels:['SMS']},authority_check:authOut(),frequency_caps:{max_per_7_days:5,max_per_30_days:10},...over});
const schedule=(over={})=>({company_id:company,schedule_id:'sch1',customer_id:'u1',service_id:'svc1',timezone:'Australia/Melbourne',state:'ACTIVE',next_due_date:'2026-09-15',...over});
const intent=(action,over={})=>({company_id:company,schedule_id:'sch1',intent_id:`intent-${action}`,action,verified:true,producer:'verified-customer-intent',evidence_ref:'intent-e1',...over});
const authLife=(action,over={})=>({company_id:company,granted:true,scope:action==='GENERATE_NEXT'?'rebooking.recurring.generate':'rebooking.recurring.lifecycle',checked_at:'2026-09-09T00:00:00Z',max_age_seconds:300,evidence_ref:'auth-life',...over});
const life=(action,over={})=>buildRebookingRecurringLifecycle({company_id:company,as_of_datetime:'2026-09-09T00:00:00Z',recurring_schedule:schedule(),lifecycle_intent:intent(action),authority_check:authLife(action),...over});
const policy=(over={})=>buildRebookingSettingsPolicy({company_id:company,revision:1,provenance:{producer:'settings-ui',evidence_refs:['s1']},cadence:{default_interval:{value:4,unit:'WEEKS'}},dormancy:{threshold_days:90},outreach:{channels:['SMS','EMAIL'],quiet_hours:{start:'20:00',end:'08:00'},frequency_caps:{max_7d:1,max_30d:3}},suppression:{block_open_complaint:true,block_service_recovery:true,block_active_booking:true},auto_proposal:{enabled:true,recurring_score_threshold:70,reactivation_score_threshold:75},incentive:{enabled:false,max_discount_percent:0,requires_explicit_approval:true},...over});

// Duplicate and recurrence lifecycle hardening.
test('duplicate pending recurring instance is suppressed',()=>{const r=life('GENERATE_NEXT',{existing_instances:[{company_id:company,schedule_id:'sch1',due_date:'2026-09-15',state:'PENDING'}]});assert.equal(r.state,'NOOP_IDEMPOTENT');assert.ok(r.reasons.includes('DUPLICATE_INSTANCE_SUPPRESSED'))});
test('duplicate completed recurring instance is suppressed',()=>{const r=life('GENERATE_NEXT',{existing_instances:[{company_id:company,schedule_id:'sch1',due_date:'2026-09-15',state:'COMPLETED'}]});assert.equal(r.state,'NOOP_IDEMPOTENT')});
test('paused recurrence cannot generate despite valid authority',()=>{const r=buildRebookingRecurringLifecycle({company_id:company,as_of_datetime:'2026-09-09T00:00:00Z',recurring_schedule:schedule({state:'PAUSED'}),lifecycle_intent:intent('GENERATE_NEXT'),authority_check:authLife('GENERATE_NEXT')});assert.equal(r.state,'REVIEW');assert.ok(r.reasons.includes('SCHEDULE_PAUSED'))});
test('cancelled recurrence cannot resume despite valid authority',()=>{const r=buildRebookingRecurringLifecycle({company_id:company,as_of_datetime:'2026-09-09T00:00:00Z',recurring_schedule:schedule({state:'CANCELLED'}),lifecycle_intent:intent('RESUME'),authority_check:authLife('RESUME')});assert.equal(r.state,'REVIEW');assert.ok(r.reasons.includes('CANCELLED_SCHEDULE_IMMUTABLE'))});
test('cancel is idempotent when already cancelled',()=>{const r=buildRebookingRecurringLifecycle({company_id:company,as_of_datetime:'2026-09-09T00:00:00Z',recurring_schedule:schedule({state:'CANCELLED'}),lifecycle_intent:intent('CANCEL'),authority_check:authLife('CANCEL')});assert.equal(r.state,'NOOP_IDEMPOTENT')});
test('skip does not create a job',()=>{const r=life('SKIP');assert.equal(r.creates_job,false);assert.equal(r.execution_permitted,false)});
test('stale lifecycle authority never becomes handoff ready',()=>{const r=life('GENERATE_NEXT',{authority_check:authLife('GENERATE_NEXT',{checked_at:'2026-09-08T00:00:00Z'})});assert.equal(r.state,'REVIEW');assert.ok(r.reasons.includes('AUTHORITY_STALE'))});
test('wrong lifecycle authority scope never becomes handoff ready',()=>{const r=life('PAUSE',{authority_check:authLife('PAUSE',{scope:'rebooking.outreach.dispatch'})});assert.equal(r.state,'REVIEW');assert.ok(r.reasons.includes('AUTHORITY_SCOPE_MISMATCH'))});
test('cross-company duplicate evidence fails closed',()=>assert.throws(()=>life('GENERATE_NEXT',{existing_instances:[{company_id:'c2',schedule_id:'sch1',due_date:'2026-09-15',state:'GENERATED'}]}),/cross-company existing instance/));

// Cadence changes remain proposals and cannot mutate recurrence.
test('change-frequency response stays scheduling review proposal',()=>{const o=opportunity();const r=buildRebookingResponseHandoff({company_id:company,opportunity:o,response_event:{company_id:company,opportunity_id:o.opportunity_id,response_id:'r1',source_message_id:'m1',responded_at:'2026-09-09T01:00:00Z',producer:'sms-inbound',verified:true,response_type:'CHANGE_FREQUENCY',frequency:{value:6,unit:'WEEKS'}}});assert.equal(r.state,'SCHEDULING_REVIEW_READY');assert.equal(r.scheduling_handoff.mutates_schedule,false);assert.equal(r.creates_schedule,false)});
test('invalid cadence change unit fails closed',()=>{const o=opportunity();assert.throws(()=>buildRebookingResponseHandoff({company_id:company,opportunity:o,response_event:{company_id:company,opportunity_id:o.opportunity_id,response_id:'r1',source_message_id:'m1',responded_at:'2026-09-09T01:00:00Z',producer:'sms-inbound',verified:true,response_type:'CHANGE_FREQUENCY',frequency:{value:1,unit:'HOURS'}}}),/unsupported frequency unit/)});
test('customer YES never directly books',()=>{const o=opportunity();const r=buildRebookingResponseHandoff({company_id:company,opportunity:o,response_event:{company_id:company,opportunity_id:o.opportunity_id,response_id:'r2',source_message_id:'m2',responded_at:'2026-09-09T01:00:00Z',producer:'sms-inbound',verified:true,response_type:'YES'}});assert.equal(r.state,'BOOKING_REVIEW_READY');assert.equal(r.creates_booking,false);assert.equal(r.booking_handoff.execution_permitted,false)});
test('duplicate YES response is suppressed before booking handoff',()=>{const o=opportunity();const r=buildRebookingResponseHandoff({company_id:company,opportunity:o,response_history:[{company_id:company,response_id:'r3'}],response_event:{company_id:company,opportunity_id:o.opportunity_id,response_id:'r3',source_message_id:'m3',responded_at:'2026-09-09T01:00:00Z',producer:'sms-inbound',verified:true,response_type:'YES'}});assert.equal(r.state,'DUPLICATE_SUPPRESSED');assert.equal(r.booking_handoff,null)});
test('decline remains current-opportunity scoped',()=>{const o=opportunity();const r=buildRebookingResponseHandoff({company_id:company,opportunity:o,response_event:{company_id:company,opportunity_id:o.opportunity_id,response_id:'r4',source_message_id:'m4',responded_at:'2026-09-09T01:00:00Z',producer:'sms-inbound',verified:true,response_type:'NO'}});assert.equal(r.state,'DECLINED');assert.equal(r.decline.scope,'CURRENT_REBOOKING_OPPORTUNITY');assert.equal(r.decline.permanent_suppression,false)});
test('explicit opt out requests canonical consent update but cannot change consent',()=>{const o=opportunity();const r=buildRebookingResponseHandoff({company_id:company,opportunity:o,response_event:{company_id:company,opportunity_id:o.opportunity_id,response_id:'r5',source_message_id:'m5',responded_at:'2026-09-09T01:00:00Z',producer:'sms-inbound',verified:true,response_type:'NO',opt_out:true}});assert.equal(r.state,'DECLINED_OPT_OUT_REVIEW');assert.equal(r.consent_effect.requires_canonical_consent_update,true);assert.equal(r.changes_consent,false)});

// Outreach, provider boundary, consent, caps, and DST.
test('provider dispatch is only a handoff, never a send',()=>{const r=buildGovernedRebookingOutreach(outreachBase());assert.equal(r.state,'READY_FOR_DISPATCH_HANDOFF');assert.equal(r.dispatch_handoff.provider_owned,true);assert.equal(r.sends_outreach,false)});
test('missing provider execution capability cannot be invented by rebooking',()=>{const r=buildGovernedRebookingOutreach(outreachBase());assert.equal(r.execution_permitted,false);assert.equal(r.dispatch_handoff.requires_provider_idempotency,true)});
test('opted-out customer is suppressed even with fresh authority',()=>{const r=buildGovernedRebookingOutreach(outreachBase({consent:{known:true,permitted:true,opted_out:true,evidence_id:'optout'}}));assert.equal(r.state,'SUPPRESSED');assert.ok(r.reasons.includes('OPTED_OUT'))});
test('declined recommendation cannot be forced by fresh authority',()=>{const rec=recommended();const r=buildGovernedRebookingOutreach(outreachBase({recommendation:{...rec,state:'REVIEW',recommendation:'NONE'}}));assert.equal(r.state,'SUPPRESSED');assert.ok(r.reasons.includes('RECOMMENDATION_NOT_ELIGIBLE'))});
test('duplicate outreach remains suppressed with relaxed caps',()=>{const r=buildGovernedRebookingOutreach(outreachBase({outreach_history:[{company_id:company,customer_id:'u1',channel:'SMS',sent_at:'2026-08-01T00:00:00Z',duplicate_key:'dk1'}],frequency_caps:{max_per_7_days:99,max_per_30_days:99}}));assert.equal(r.state,'SUPPRESSED');assert.ok(r.reasons.includes('DUPLICATE_OUTREACH_SUPPRESSED'))});
test('cross-company outreach history fails closed even if unrelated customer',()=>assert.throws(()=>buildGovernedRebookingOutreach(outreachBase({outreach_history:[{company_id:'c2',customer_id:'other',channel:'SMS',sent_at:'2026-09-08T00:00:00Z',duplicate_key:'x'}]})),/cross-company outreach history/));
test('DST spring-forward quiet hours use Melbourne local time',()=>{const r=buildGovernedRebookingOutreach(outreachBase({as_of_datetime:'2026-10-03T16:30:00Z',authority_check:authOut({checked_at:'2026-10-03T16:29:00Z'}),quiet_hours:{enabled:true,start:'20:00',end:'08:00'}}));assert.equal(r.state,'SUPPRESSED');assert.ok(r.reasons.includes('QUIET_HOURS_ACTIVE'))});
test('DST fall-back quiet hours use Melbourne local time',()=>{const r=buildGovernedRebookingOutreach(outreachBase({as_of_datetime:'2026-04-04T15:30:00Z',authority_check:authOut({checked_at:'2026-04-04T15:29:00Z'}),quiet_hours:{enabled:true,start:'20:00',end:'08:00'}}));assert.equal(r.state,'SUPPRESSED');assert.ok(r.reasons.includes('QUIET_HOURS_ACTIVE'))});
test('stale outreach authority cannot dispatch',()=>{const r=buildGovernedRebookingOutreach(outreachBase({authority_check:authOut({checked_at:'2026-09-08T23:00:00Z'})}));assert.equal(r.state,'AWAITING_FRESH_AUTHORITY');assert.equal(r.dispatch_handoff.channel_dispatch_permitted,false)});

// History and stale evidence hardening.
test('future service history is rejected as stale-invalid evidence',()=>assert.throws(()=>buildDeterministicDueDateCandidate({company_id:company,customer_id:'u1',service_id:'svc1',opportunity_id:'o1',timezone:'Australia/Melbourne',completed_date:'2026-08-01',as_of_date:'2026-09-09',service_history:[{company_id:company,completed_date:'2026-01-01'},{company_id:company,completed_date:'2026-06-01'},{company_id:company,completed_date:'2026-08-02'}]}),/future service history date rejected/));
test('old history can inform cadence but never creates schedule',()=>{const r=buildDeterministicDueDateCandidate({company_id:company,customer_id:'u1',service_id:'svc1',opportunity_id:'o1',timezone:'Australia/Melbourne',completed_date:'2026-08-01',as_of_date:'2026-09-09',service_history:[{company_id:company,completed_date:'2026-02-01'},{company_id:company,completed_date:'2026-04-01'},{company_id:company,completed_date:'2026-06-01'}]});assert.equal(r.state,'CANDIDATE');assert.equal(r.creates_schedule,false);assert.equal(r.execution_permitted,false)});
test('future analytics event fails closed',()=>assert.throws(()=>buildRebookingRetentionAnalytics({company_id:company,as_of_date:'2026-09-09',dormancy_threshold_days:90,events:[{company_id:company,customer_id:'u1',type:'SERVICE_COMPLETED',event_date:'2026-09-10'}]}),/future analytics event rejected/));
test('analytics stale history remains descriptive, never actionable',()=>{const r=buildRebookingRetentionAnalytics({company_id:company,as_of_date:'2026-09-09',dormancy_threshold_days:90,events:[{company_id:company,customer_id:'u1',type:'SERVICE_COMPLETED',event_date:'2025-01-01'}]});assert.equal(r.customers[0].dormant,true);assert.equal(r.customers[0].eligible_for_action,null);assert.equal(r.interpretation.may_trigger_outreach,false)});

// Settings and authority dominance.
test('100 score cannot bypass opt out in settings evaluation',()=>{const p=policy();const r=evaluateRebookingAutoProposal(p,{company_id:company,type:'RECURRING',score:100,consent_known:true,consent_permitted:true,opted_out:true,suppressed:false});assert.ok(r.blockers.includes('OPTED_OUT'));assert.notEqual(r.state,'PROPOSAL_REVIEW_READY')});
test('100 score cannot bypass suppression in settings evaluation',()=>{const p=policy();const r=evaluateRebookingAutoProposal(p,{company_id:company,type:'REACTIVATION',score:100,consent_known:true,consent_permitted:true,suppressed:true});assert.ok(r.blockers.includes('SUPPRESSED'));assert.notEqual(r.state,'PROPOSAL_REVIEW_READY')});
test('auto proposal threshold creates review only not execution',()=>{const p=policy();const r=evaluateRebookingAutoProposal(p,{company_id:company,type:'RECURRING',score:100,consent_known:true,consent_permitted:true});assert.equal(r.state,'PROPOSAL_REVIEW_READY');assert.equal(r.execution_permitted,false);assert.equal(r.grants_authority,false)});
test('settings cannot make incentive self-authorizing',()=>{const p=policy({incentive:{enabled:true,max_discount_percent:20,requires_explicit_approval:true}});assert.equal(p.configured.incentive.may_not_self_authorize,true);assert.equal(p.governance.settings_are_policy_not_authority,true)});
test('cross-company settings evaluation fails closed',()=>{const p=policy();assert.throws(()=>evaluateRebookingAutoProposal(p,{company_id:'c2',type:'RECURRING',score:100,consent_known:true,consent_permitted:true}),/cross-company/)});

// End-to-end invariant checks.
test('rebooking chain never converts identity into authority',()=>{const o=opportunity();const rec=recommended();const out=buildGovernedRebookingOutreach(outreachBase({recommendation:rec}));const lifeResult=life('GENERATE_NEXT');for(const x of [o,rec,out,lifeResult])assert.equal(x.identity_is_authority,false)});
test('rebooking chain never directly executes protected action',()=>{const o=opportunity();const rec=recommended();const out=buildGovernedRebookingOutreach(outreachBase({recommendation:rec}));const lifeResult=life('GENERATE_NEXT');for(const x of [o,rec,out,lifeResult])assert.equal(x.execution_permitted,false)});
test('adversarial replay remains deterministic',()=>{const a=life('GENERATE_NEXT',{holidays:[{company_id:company,date:'2026-09-15'}],availability:[{company_id:company,date:'2026-09-18',available:true}]}),b=life('GENERATE_NEXT',{holidays:[{company_id:company,date:'2026-09-15'}],availability:[{company_id:company,date:'2026-09-18',available:true}]});assert.deepEqual(a,b)});
