import test from 'node:test'; import assert from 'node:assert/strict';
import {evaluateInvoiceReadiness} from '../titan-workforce/starter-agents/invoicing/invoice-readiness.mjs';
import {calculateExactInvoice} from '../titan-workforce/starter-agents/invoicing/exact-money.mjs';
import {evaluateInvoiceReviewGate} from '../titan-workforce/starter-agents/invoicing/invoice-review-gates.mjs';
import {buildInvoiceIssueSendProposal} from '../titan-workforce/starter-agents/invoicing/invoice-issue-send.mjs';
import {projectPaymentMonitoring} from '../titan-workforce/starter-agents/invoicing/payment-monitoring.mjs';
import {certifyInvoicingFinancialIntegrity} from '../titan-workforce/starter-agents/invoicing/financial-integrity-certification.mjs';
import {buildJobsToInvoiceTrigger,buildCustomerCareInvoiceIssuedHandoff,buildRebookingPaidHandoff,certifyInvoicingIntegration} from '../titan-workforce/starter-agents/invoicing/invoicing-integration-handoffs.mjs';
const c='co-final';
function readiness(){return evaluateInvoiceReadiness({company_id:c,job:{company_id:c,job_ref:'job-1',status:'completed',completion_ref:'done-1',request_invoice:true,evidence_attachment_refs:['e1']},commercial_terms:{company_id:c,accepted:true,accepted_terms_ref:'terms',quote_or_contract_ref:'q1',unapproved_variation_refs:[]},actuals:{company_id:c,actual_time_ref:'t1',actual_materials_ref:'m0',actuals_ref:'a1'},evidence:{company_id:c,required:true,attachment_refs:['e1'],unresolved_issue_refs:[]},tax:{company_id:c,tax_basis_ref:'tax'},pricing:{company_id:c,currency:'AUD',pricing_source_refs:['p1']},as_of:'2026-09-08T00:00:00Z'});}
function exact(){return calculateExactInvoice({company_id:c,currency:'AUD',line_items:[{line_ref:'l1',pricing_source_ref:'p1',quantity:'1',unit_amount_minor:'10000'}],tax:{mode:'exclusive',rate_bps:'1000'},provenance:{pricing_source_refs:['p1'],tax_basis_ref:'tax',quote_or_contract_ref:'q1',actuals_ref:'a1'}});}
function financial(){const r=readiness(),x=exact(),g=evaluateInvoiceReviewGate({company_id:c,exact_money_result:x,policy:{allowed_tax_modes:['exclusive'],allowed_tax_rate_bps:['1000']}});const s=buildInvoiceIssueSendProposal({company_id:c,contract:{schema:'titan.workforce.starter.invoicing.contract.v1',company_id:c,invoice_ref:'inv-1',blockers:[]},readiness:r,exact_money:x,review_gate:g,canonical_invoice:{company_id:c,invoice_ref:'inv-1'},delivery:{recipient_ref:'cust-email',channel:'email'},tools:{invoice:{capability:'crm.invoice.create',provider_ref:'Titan CRM',verified:true,command_bus_required:true},send:{capability:'crm.invoice.send',provider_ref:'Titan Connect',verified:true,command_bus_required:true}}});const m=projectPaymentMonitoring({company_id:c,invoice:{company_id:c,invoice_ref:'inv-1',currency:'AUD',total_minor:x.totals.total_minor,status:'sent',due_at:'2026-09-30T00:00:00Z'},payments:[],as_of:'2026-09-08T00:00:00Z'});return certifyInvoicingFinancialIntegrity({company_id:c,readiness:r,exact_money_result:x,review_gate:g,issue_send_proposal:s,payment_monitoring:m});}

test('verified Titan Field completion becomes proposal-only Jobs→Invoice trigger',()=>{const r=readiness();const h=buildJobsToInvoiceTrigger({company_id:c,source_event:{company_id:c,type:'job.completed',source_owner:'Titan Field',verified:true,event_ref:'ev-job-1',job_ref:'job-1'},job:{company_id:c,job_ref:'job-1',status:'completed',request_invoice:true},readiness:r});assert.equal(h.target.proposal_only,true);assert.equal(h.authority.execution_permitted,false);});
test('Jobs trigger rejects unverified or wrong-owner completion events',()=>{const r=readiness();const base={company_id:c,type:'job.completed',source_owner:'Titan Field',verified:true,event_ref:'e',job_ref:'job-1'};const job={company_id:c,job_ref:'job-1',status:'completed',request_invoice:true};assert.throws(()=>buildJobsToInvoiceTrigger({company_id:c,source_event:{...base,verified:false},job,readiness:r}),/verified_job/);assert.throws(()=>buildJobsToInvoiceTrigger({company_id:c,source_event:{...base,source_owner:'Other'},job,readiness:r}),/source_owner/);});
test('Jobs trigger requires certified invoice readiness',()=>{assert.throws(()=>buildJobsToInvoiceTrigger({company_id:c,source_event:{company_id:c,type:'job.completed',source_owner:'Titan Field',verified:true,event_ref:'e',job_ref:'job-1'},job:{company_id:c,job_ref:'job-1',status:'completed',request_invoice:true},readiness:{schema:'titan.workforce.starter.invoicing.readiness.v1',company_id:c,ready:false}}),/readiness/);});
test('verified Titan CRM issued invoice produces Customer Care-compatible proposal-only source event',()=>{const h=buildCustomerCareInvoiceIssuedHandoff({company_id:c,invoice:{company_id:c,invoice_ref:'inv-1',status:'issued',verified:true,source_owner:'Titan CRM'},customer_ref:'cust-1',job_ref:'job-1'});assert.equal(h.source_event.type,'invoice.issued');assert.equal(h.source_event.verified,true);assert.equal(h.source_event.source_owner,'Titan CRM');assert.equal(h.authority.outreach_permitted,false);});
test('Customer Care handoff rejects unverified and cross-company invoice truth',()=>{assert.throws(()=>buildCustomerCareInvoiceIssuedHandoff({company_id:c,invoice:{company_id:c,invoice_ref:'i',status:'issued',verified:false,source_owner:'Titan CRM'},customer_ref:'c'}),/verified/);assert.throws(()=>buildCustomerCareInvoiceIssuedHandoff({company_id:c,invoice:{company_id:'other',invoice_ref:'i',status:'issued',verified:true,source_owner:'Titan CRM'},customer_ref:'c'}),/company_boundary/);});
test('fully paid completed work produces Rebooking opportunity input with no outreach or booking authority',()=>{const m=projectPaymentMonitoring({company_id:c,invoice:{company_id:c,invoice_ref:'inv-1',currency:'AUD',total_minor:'11000',status:'sent'},payments:[{company_id:c,payment_ref:'p1',currency:'AUD',amount_minor:'11000',status:'settled',verified:true}]});const h=buildRebookingPaidHandoff({company_id:c,invoice:{company_id:c,invoice_ref:'inv-1',status:'paid',verified:true,source_owner:'Titan CRM'},payment_monitoring:m,job:{company_id:c,job_ref:'job-1',status:'completed'},customer_ref:'cust-1',service_ref:'cleaning'});assert.equal(h.target.consent_required_downstream,true);assert.equal(h.authority.outreach_permitted,false);assert.equal(h.authority.booking_execution_permitted,false);});
test('Rebooking handoff suppresses partial/unpaid invoices',()=>{const m=projectPaymentMonitoring({company_id:c,invoice:{company_id:c,invoice_ref:'inv-1',currency:'AUD',total_minor:'11000',status:'sent'},payments:[{company_id:c,payment_ref:'p1',currency:'AUD',amount_minor:'1000',status:'settled',verified:true}]});assert.throws(()=>buildRebookingPaidHandoff({company_id:c,invoice:{company_id:c,invoice_ref:'inv-1',status:'sent',verified:true,source_owner:'Titan CRM'},payment_monitoring:m,job:{company_id:c,job_ref:'job-1',status:'completed'},customer_ref:'cust',service_ref:'clean'}),/fully_paid/);});
test('all integration identities are deterministic and company isolated',()=>{const r=readiness();const args={company_id:c,source_event:{company_id:c,type:'job.completed',source_owner:'Titan Field',verified:true,event_ref:'e',job_ref:'job-1'},job:{company_id:c,job_ref:'job-1',status:'completed',request_invoice:true},readiness:r};assert.equal(buildJobsToInvoiceTrigger(args).identity.idempotency_key,buildJobsToInvoiceTrigger(args).identity.idempotency_key);assert.throws(()=>buildJobsToInvoiceTrigger({...args,company_id:'other'}),/company_boundary/);});
test('final integration certification can certify Invoicing side while honestly leaving unfinished downstream agents pending',()=>{const r=readiness();const jobs=buildJobsToInvoiceTrigger({company_id:c,source_event:{company_id:c,type:'job.completed',source_owner:'Titan Field',verified:true,event_ref:'e',job_ref:'job-1'},job:{company_id:c,job_ref:'job-1',status:'completed',request_invoice:true},readiness:r});const care=buildCustomerCareInvoiceIssuedHandoff({company_id:c,invoice:{company_id:c,invoice_ref:'inv-1',status:'issued',verified:true,source_owner:'Titan CRM'},customer_ref:'cust',job_ref:'job-1'});const m=projectPaymentMonitoring({company_id:c,invoice:{company_id:c,invoice_ref:'inv-1',currency:'AUD',total_minor:'11000',status:'sent'},payments:[{company_id:c,payment_ref:'p1',currency:'AUD',amount_minor:'11000',status:'settled',verified:true}]});const reb=buildRebookingPaidHandoff({company_id:c,invoice:{company_id:c,invoice_ref:'inv-1',status:'paid',verified:true,source_owner:'Titan CRM'},payment_monitoring:m,job:{company_id:c,job_ref:'job-1',status:'completed'},customer_ref:'cust',service_ref:'clean'});const cert=certifyInvoicingIntegration({company_id:c,jobs_trigger:jobs,customer_care_handoff:care,rebooking_handoff:reb,financial_certification:financial(),downstream_status:{jobs:'ready_for_manager_merge',customer_care:'in_progress',rebooking:'in_progress'}});assert.equal(cert.invoicing_side_certified,true);assert.equal(cert.downstream_acceptance.end_to_end_downstream_certified,false);assert.equal(cert.authority.execution_permitted,false);});
test('final certification fails closed if any handoff carries wrong company',()=>{const r=readiness();const jobs=buildJobsToInvoiceTrigger({company_id:c,source_event:{company_id:c,type:'job.completed',source_owner:'Titan Field',verified:true,event_ref:'e',job_ref:'job-1'},job:{company_id:c,job_ref:'job-1',status:'completed',request_invoice:true},readiness:r});assert.throws(()=>certifyInvoicingIntegration({company_id:c,jobs_trigger:{...jobs,company_id:'other'},financial_certification:financial()}),/company_boundary/);});
