import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createBusinessDatabase } from '../titan-local/storage/business-database.mjs';
import { createCleaningServiceSetupAuthority, resolveCanonicalCleaningJobTypes } from '../titan-onboarding/runtime/cleaning-service-setup.mjs';

const bundle = JSON.parse(fs.readFileSync(new URL('../titan-modules/bundles/cleaning-workforce.bundle.json', import.meta.url), 'utf8'));
function memoryAdapter(){const stores=new Map();const gs=n=>{if(!stores.has(n))stores.set(n,new Map());return stores.get(n)};return{async transaction(_n,_m,work){const tx={async get(s,k){return structuredClone(gs(s).get(JSON.stringify(k))??null)},async put(s,v){gs(s).set(JSON.stringify(v.pk),structuredClone(v));return structuredClone(v)},async getAllByIndex(){return[]}};return work(tx)}}}
function build(){const database=createBusinessDatabase({adapter:memoryAdapter(),clock:()=>1234});return createCleaningServiceSetupAuthority({database,cleaningBundle:bundle,clock:()=>1234})}

test('Pass4 consumes the existing seven canonical cleaning job types without copying a new catalogue',()=>{const rows=resolveCanonicalCleaningJobTypes(bundle);assert.equal(rows.length,7);assert.deepEqual(rows.map(x=>x.id),['domestic_recurring','deep_clean','bond_end_of_lease','airbnb_turnover','commercial','move_in','office']);assert.ok(rows.every(x=>x.checklist.length>=6));});
test('Pass4 persists company-scoped job type, pricing and checklist selections',async()=>{const a=build();const r=await a.save({company_id:'co-a'},{selections:[{job_type_id:'domestic_recurring',pricing:{mode:'fixed',fixed_price:145,currency:'aud'},checklist_selection:[0,1,4]},{job_type_id:'office',pricing:{mode:'hourly',hourly_rate:65,minimum_charge:130}}]});assert.equal(r.revision,1);const v=await a.read({company_id:'co-a'});assert.equal(v.selections.length,2);assert.equal(v.selections[0].pricing.currency,'AUD');assert.deepEqual(v.selections[0].checklist_items,['Confirm agreed rooms and exclusions','Kitchen surfaces and sink','Vacuum and mop agreed floors']);assert.equal(v.selections[1].checklist_items.length,7);});
test('Pass4 rejects unknown or duplicate job types',async()=>{const a=build();await assert.rejects(()=>a.save({company_id:'co-a'},{selections:[{job_type_id:'made_up',pricing:{mode:'fixed',fixed_price:1}}]}),/unknown cleaning job type/);await assert.rejects(()=>a.save({company_id:'co-a'},{selections:[{job_type_id:'office',pricing:{mode:'fixed',fixed_price:1}},{job_type_id:'office',pricing:{mode:'fixed',fixed_price:2}}]}),/duplicate cleaning job type/);});
test('Pass4 validates pricing modes and required inputs',async()=>{const a=build();await assert.rejects(()=>a.save({company_id:'co-a'},{selections:[{job_type_id:'office',pricing:{mode:'fixed'}}]}),/fixed_price is required/);await assert.rejects(()=>a.save({company_id:'co-a'},{selections:[{job_type_id:'office',pricing:{mode:'hourly',hourly_rate:-1}}]}),/non-negative/);await assert.rejects(()=>a.save({company_id:'co-a'},{selections:[{job_type_id:'office',pricing:{mode:'weird'}}]}),/unsupported pricing mode/);});
test('Pass4 checklist selection can only select canonical checklist indexes',async()=>{const a=build();await assert.rejects(()=>a.save({company_id:'co-a'},{selections:[{job_type_id:'office',pricing:{mode:'quote_required'},checklist_selection:[999]}]}),/outside canonical checklist/);});
test('Pass4 is isolated by company and protected by optimistic revision',async()=>{const a=build();await a.save({company_id:'co-a'},{selections:[{job_type_id:'office',pricing:{mode:'quote_required'}}]});assert.equal((await a.read({company_id:'co-b'})).selections.length,0);await assert.rejects(()=>a.save({company_id:'co-a'},{expected_revision:0,selections:[{job_type_id:'office',pricing:{mode:'quote_required'}}]}),/revision mismatch/);});
test('Pass4 rejects legacy tenant aliases and cross-company payloads',async()=>{const a=build();await assert.rejects(()=>a.read({company_id:'co-a',tenant_id:'x'}),/legacy tenant boundary/);await assert.rejects(()=>a.save({company_id:'co-a'},{company_id:'co-b',selections:[{job_type_id:'office',pricing:{mode:'quote_required'}}]}),/Cross-company/);});
test('Pass4 never grants execution authority',async()=>{const a=build();const s=await a.save({company_id:'co-a',authority_grants:['all']},{selections:[{job_type_id:'office',pricing:{mode:'quote_required'}}]});const v=await a.read({company_id:'co-a'});for(const x of [a,s,v]){assert.equal(x.grants_authority,false);if('authority_granted'in x)assert.equal(x.authority_granted,false);if('execution_permitted'in x)assert.equal(x.execution_permitted,false)}});
