import test from 'node:test';import assert from 'node:assert/strict';
import {createOnboardingImportStagingAuthority,validateOnboardingImport} from '../titan-onboarding/runtime/import-staging.mjs';
function db(){const m=new Map();const key=(c,l)=>`${c.company_id}:${l.collection}:${l.record_id}`;return {async getRecord(c,l){return m.get(key(c,l))||null},async putRecord(c,r){const k=key(c,r),p=m.get(k),v=(p?.version||0)+1,o={...r,version:v};m.set(k,o);return o},async deleteRecord(c,l){return m.delete(key(c,l))}}}
const good={company_id:'c1',customers:[{external_id:'cust-1',customer_type:'individual',display_name:'Alex Smith',email:'alex@example.com',phone:'0400000000',street:'1 Main St',suburb:'Melbourne',state:'VIC',postcode:'3000'}],jobs:[{external_id:'job-1',customer_external_id:'cust-1',service_id:'clean-standard',address:'1 Main St',scheduled_start:'2026-09-20T09:00:00+10:00',scheduled_end:'2026-09-20T11:00:00+10:00',worker_ids:[],price:180}],history:[{external_id:'hist-1',occurred_at:'2025-01-02T00:00:00Z',event_type:'job_completed',subject_type:'job',subject_ref:'job-old-1',summary:'Historical completion'}]};
test('Pass7 validates customer/job/history rows against canonical target requirements',()=>{const v=validateOnboardingImport(good);assert.equal(v.summary.ready_to_stage,true);assert.equal(v.datasets.customers[0].target.capability,'crm.customer.create');assert.equal(v.datasets.jobs[0].target.capability,'crm.work_order.create');assert.equal(v.datasets.history[0].target.capability,null);assert.equal(v.governance.live_mutation_permitted,false);});
test('Pass7 rejects invalid and duplicate rows before staging',()=>{const bad={...good,customers:[good.customers[0],good.customers[0]],jobs:[{price:-1}]};const v=validateOnboardingImport(bad);assert.equal(v.summary.ready_to_stage,false);assert.ok(v.summary.invalid_count>=2);assert.ok(v.datasets.customers[1].errors.includes('duplicate_row'));});
test('Pass7 stages idempotently without applying live CRM mutations',async()=>{const a=createOnboardingImportStagingAuthority({database:db(),clock:()=>7});const first=await a.stage({company_id:'c1'},good);assert.equal(first.status,'STAGED');assert.equal(first.live_mutation_permitted,false);const second=await a.stage({company_id:'c1'},{...good,import_id:first.import_id});assert.equal(second.idempotent,true);const view=await a.inspect({company_id:'c1'},first.import_id);assert.equal(view.datasets.customers[0].target.capability,'crm.customer.create');assert.equal(view.authority_granted,false);});
test('Pass7 supports rollback-safe discard of staging only',async()=>{const a=createOnboardingImportStagingAuthority({database:db()});const r=await a.stage({company_id:'c1'},good);const d=await a.discard({company_id:'c1'},r.import_id);assert.equal(d.discarded,true);assert.equal(d.live_records_affected,0);assert.equal(await a.inspect({company_id:'c1'},r.import_id),null);});
test('Pass7 rejects cross-company and legacy company boundaries',async()=>{const a=createOnboardingImportStagingAuthority({database:db()});await assert.rejects(()=>a.stage({company_id:'c1'},{...good,company_id:'c2'}),/Cross-company/);await assert.rejects(()=>a.stage({company_id:'c1'},{...good,tenant_id:'legacy'}),/legacy company boundary/);});
test('Pass7 refuses reuse of import_id with a different payload',async()=>{const a=createOnboardingImportStagingAuthority({database:db()});await a.stage({company_id:'c1'},{...good,import_id:'fixed'});await assert.rejects(()=>a.stage({company_id:'c1'},{...good,import_id:'fixed',customers:[{...good.customers[0],display_name:'Different'}]}),/different payload/);});
