import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createBusinessDatabase } from '../titan-local/storage/business-database.mjs';
import { createWorkforceSetupAuthority } from '../titan-onboarding/runtime/workforce-setup.mjs';

const catalogue = JSON.parse(fs.readFileSync(new URL('../titan-workforce/catalogue/installed-client-workforce-master.json',import.meta.url),'utf8'));
const roles = catalogue.roles.slice(0,3).map(x=>x.role_definition_id);
function memoryAdapter(){const stores=new Map();const gs=n=>{if(!stores.has(n))stores.set(n,new Map());return stores.get(n)};return{async transaction(_n,_m,work){const tx={async get(s,k){return structuredClone(gs(s).get(JSON.stringify(k))??null)},async put(s,v){gs(s).set(JSON.stringify(v.pk),structuredClone(v));return structuredClone(v)},async getAllByIndex(){return[]}};return work(tx)}}}
function build(){const database=createBusinessDatabase({adapter:memoryAdapter(),clock:()=>5555});return createWorkforceSetupAuthority({database,workforceCatalogue:catalogue,clock:()=>5555})}
function input(){return{role_selections:[{role_definition_id:roles[0],target_worker_count:1},{role_definition_id:roles[1],target_worker_count:2}],availability:{timezone:'Australia/Melbourne',weekly:{monday:[{start:'08:00',end:'12:00'},{start:'13:00',end:'17:00'}],tuesday:[{start:'09:00',end:'17:00'}]}},escalation_defaults:[{severity:'high',target_role_definition_ids:[roles[0]],response_target_minutes:30},{severity:'critical',target_role_definition_ids:[roles[0],roles[1]],response_target_minutes:10}]}}

test('Pass5 exposes the existing canonical workforce catalogue without copying a replacement',async()=>{const a=build();const v=await a.read({company_id:'co-a'});assert.equal(v.available_roles.length,catalogue.total_master_roles);assert.equal(v.available_roles[0].role_definition_id,catalogue.roles[0].role_definition_id);assert.equal(v.configuration_only,true)});
test('Pass5 persists role references, availability planning and escalation defaults by company',async()=>{const a=build();const s=await a.save({company_id:'co-a'},input());assert.equal(s.revision,1);const v=await a.read({company_id:'co-a'});assert.equal(v.role_selections.length,2);assert.equal(v.availability.timezone,'Australia/Melbourne');assert.equal(v.availability.weekly.monday.length,2);assert.equal(v.escalation_defaults[0].severity,'high')});
test('Pass5 rejects unknown and duplicate workforce role references',async()=>{const a=build();const x=input();x.role_selections=[{role_definition_id:'missing.role'}];await assert.rejects(()=>a.save({company_id:'co-a'},x),/unknown workforce role/);const y=input();y.role_selections=[{role_definition_id:roles[0]},{role_definition_id:roles[0]}];await assert.rejects(()=>a.save({company_id:'co-a'},y),/duplicate workforce role/)});
test('Pass5 validates weekly availability windows and overlap',async()=>{const a=build();const x=input();x.availability.weekly.monday=[{start:'13:00',end:'12:00'}];await assert.rejects(()=>a.save({company_id:'co-a'},x),/end must be after start/);const y=input();y.availability.weekly.monday=[{start:'08:00',end:'12:00'},{start:'11:00',end:'13:00'}];await assert.rejects(()=>a.save({company_id:'co-a'},y),/overlap/)});
test('Pass5 escalation defaults must target enabled canonical roles',async()=>{const a=build();const x=input();x.escalation_defaults=[{severity:'high',target_role_definition_ids:[roles[2]]}];await assert.rejects(()=>a.save({company_id:'co-a'},x),/must be enabled/);const y=input();y.escalation_defaults=[{severity:'extreme',target_role_definition_ids:[roles[0]]}];await assert.rejects(()=>a.save({company_id:'co-a'},y),/unsupported escalation severity/)});
test('Pass5 is company isolated and optimistic-revision protected',async()=>{const a=build();await a.save({company_id:'co-a'},input());assert.equal((await a.read({company_id:'co-b'})).role_selections.length,0);await assert.rejects(()=>a.save({company_id:'co-a'},{...input(),expected_revision:0}),/revision mismatch/)});
test('Pass5 rejects legacy tenant aliases and cross-company payloads',async()=>{const a=build();await assert.rejects(()=>a.read({company_id:'co-a',tenant_id:'legacy'}),/legacy tenant boundary/);await assert.rejects(()=>a.save({company_id:'co-a'},{...input(),company_id:'co-b'}),/Cross-company/)});
test('Pass5 configuration can never activate workers, execute schedules/escalations or grant authority',async()=>{const a=build();const s=await a.save({company_id:'co-a',authority_grants:['all']},input());const v=await a.read({company_id:'co-a'});for(const x of [a,s,v]){assert.equal(x.grants_authority,false);if('role_activation_permitted'in x)assert.equal(x.role_activation_permitted,false);if('worker_creation_permitted'in x)assert.equal(x.worker_creation_permitted,false);if('execution_permitted'in x)assert.equal(x.execution_permitted,false)}assert.ok(v.role_selections.every(x=>x.workers_created===false));assert.ok(v.escalation_defaults.every(x=>x.automatic_execution===false))});
