// @ts-nocheck
// Ported from Titan Zero extension (portable-core): titan-workforce/starter-agents/jobs/jobs-field-context.mjs
const clean=v=>typeof v==='string'?v.trim():'';const list=v=>Array.isArray(v)?v:[];const uniq=v=>[...new Set(v)];
const LEGACY=['tenant_id','tenantId','tenant_company_id'];
function company(input){for(const k of LEGACY)if(input?.[k]!=null)throw new Error(`jobs-field-context-legacy-tenant-forbidden:${k}`);const c=clean(input?.company_id);if(!c)throw new Error('jobs-field-context-company-id-required');return c;}
function assertScoped(company_id,rows,label){for(const row of list(rows))if(row?.company_id&&clean(row.company_id)!==company_id)throw new Error(`jobs-field-context-cross-company:${label}`);}
const ROLE_VISIBILITY=Object.freeze({field_worker:['tasks','checklist','site_instructions','hazards','equipment','materials'],supervisor:['tasks','checklist','site_instructions','hazards','equipment','materials','internal_notes','estimated_minutes'],manager:['tasks','checklist','site_instructions','hazards','equipment','materials','internal_notes','estimated_minutes','cost_context'],owner:['tasks','checklist','site_instructions','hazards','equipment','materials','internal_notes','estimated_minutes','cost_context']});
export function buildJobFieldContext(input={}){
 const company_id=company(input),role=clean(input.role)||'field_worker';if(!ROLE_VISIBILITY[role])throw new Error(`jobs-field-context-role-unsupported:${role}`);
 const job=input.job||{};if(job.company_id&&clean(job.company_id)!==company_id)throw new Error('jobs-field-context-cross-company:job');
 for(const k of ['tasks','hazards','equipment','materials'])assertScoped(company_id,input[k],k);
 const base={tasks:list(input.tasks).map(x=>({task_id:clean(x.task_id),title:clean(x.title),required:x.required!==false,status:clean(x.status)||'pending'})),checklist:list(input.checklist).map(x=>({item_id:clean(x.item_id),label:clean(x.label),required:x.required!==false,completed:x.completed===true})),site_instructions:clean(input.site_instructions||job.site_instructions)||null,hazards:list(input.hazards).map(x=>({hazard_id:clean(x.hazard_id),summary:clean(x.summary),control:clean(x.control),severity:clean(x.severity)||null})),equipment:list(input.equipment).map(x=>({asset_id:clean(x.asset_id),name:clean(x.name),required:x.required!==false,status:clean(x.status)||null})),materials:list(input.materials).map(x=>({material_id:clean(x.material_id),name:clean(x.name),quantity:Number(x.quantity||0),unit:clean(x.unit)||null})),internal_notes:clean(input.internal_notes)||null,estimated_minutes:Number(input.estimated_minutes||0)||null,cost_context:input.cost_context??null};
 const visible=new Set(ROLE_VISIBILITY[role]);const context={};for(const [k,v] of Object.entries(base))if(visible.has(k))context[k]=v;
 return {schema:'titan.zero.jobs.field-context.v1',company_id,job_id:clean(job.job_id||input.job_id),role,visibility:[...visible],context,required_task_ids:base.tasks.filter(x=>x.required).map(x=>x.task_id).filter(Boolean),required_checklist_item_ids:base.checklist.filter(x=>x.required).map(x=>x.item_id).filter(Boolean),hazard_ack_required:base.hazards.length>0,authority_granted:false,execution_permitted:false};
}
export function missingOperationalPrerequisites(snapshot={}){const c=snapshot.context||{};const missing=[];for(const t of list(c.tasks))if(t.required&&t.status==='pending')missing.push(`task:${t.task_id}`);for(const x of list(c.checklist))if(x.required&&!x.completed)missing.push(`checklist:${x.item_id}`);for(const e of list(c.equipment))if(e.required&&['unavailable','failed','blocked'].includes(e.status))missing.push(`equipment:${e.asset_id}`);return uniq(missing);}
