// @ts-nocheck
// Ported from Titan Zero extension (ui-or-browser-adaptation): titan-workforce/starter-agents/jobs/jobs-exception-runtime.mjs
// QUARANTINE: not exported to standalone runtime until browser/DOM dependencies are adapted.
const clean=v=>typeof v==='string'?v.trim():'';const list=v=>Array.isArray(v)?v:[];const LEGACY=['tenant_id','tenantId','tenant_company_id'];
function ctx(input){for(const k of LEGACY)if(input?.[k]!=null)throw new Error(`jobs-exception-legacy-tenant-forbidden:${k}`);const company_id=clean(input?.company_id),job_id=clean(input?.job_id);if(!company_id)throw new Error('jobs-exception-company-id-required');if(!job_id)throw new Error('jobs-exception-job-id-required');return {company_id,job_id};}
export const JOB_EXCEPTION_TYPES=Object.freeze(['blocked','damage','safety','access','customer_change','scope_change','equipment_failure','material_shortage','rework','cancellation']);
const ESCALATION={safety:'IMMEDIATE_SUPERVISOR_AND_AUTHORITY_REVIEW',damage:'SUPERVISOR_REVIEW',scope_change:'VARIATION_APPROVAL',customer_change:'VARIATION_APPROVAL',rework:'QUALITY_REVIEW',cancellation:'MANAGER_REVIEW',blocked:'SUPERVISOR_REVIEW',access:'DISPATCH_REVIEW',equipment_failure:'DISPATCH_REVIEW',material_shortage:'DISPATCH_REVIEW'};
export function classifyJobException(input={}){const c=ctx(input),type=clean(input.type);if(!JOB_EXCEPTION_TYPES.includes(type))throw new Error(`jobs-exception-type-invalid:${type}`);const evidence_refs=list(input.evidence_refs).map(clean).filter(Boolean);const cost_impact=Number(input.cost_impact||0),time_impact_minutes=Number(input.time_impact_minutes||0);const requires_customer_approval=['scope_change','customer_change'].includes(type)&&(cost_impact>0||input.customer_visible_change===true);const requires_authority_review=true;const blocks_completion=!['rework'].includes(type)||input.rework_resolved!==true;return {schema:'titan.zero.jobs.exception.v1',...c,exception_id:clean(input.exception_id)||`${c.job_id}:${type}:${clean(input.operation_id)||'pending'}`,type,summary:clean(input.summary)||null,evidence_refs,cost_impact,time_impact_minutes,severity:clean(input.severity)||'medium',escalation:ESCALATION[type],requires_customer_approval,requires_authority_review,blocks_completion,status:'OPEN',authority_granted:false,execution_permitted:false};}
export function planExceptionResolution(exception={},input={}){const c=ctx(exception);if(input.company_id&&clean(input.company_id)!==c.company_id)throw new Error('jobs-exception-cross-company-resolution');const action=clean(input.action);const allowed={blocked:['resume','reassign','cancel'],damage:['document','escalate','rework'],safety:['escalate','stop_work'],access:['reschedule','reassign','cancel'],customer_change:['variation_review','reject_change'],scope_change:['variation_review','reject_change'],equipment_failure:['replace_equipment','reschedule'],material_shortage:['supply_request','reschedule'],rework:['start_rework','complete_rework'],cancellation:['approve_cancel','reject_cancel']}[exception.type]||[];if(!allowed.includes(action))return {schema:'titan.zero.jobs.exception-resolution.v1',...c,exception_id:exception.exception_id,status:'DENIED',reason:'ACTION_NOT_ALLOWED',authority_granted:false,execution_permitted:false};if(input.authority_verified!==true)return {schema:'titan.zero.jobs.exception-resolution.v1',...c,exception_id:exception.exception_id,status:'DENIED',reason:'AUTHORITY_REQUIRED',authority_granted:false,execution_permitted:false};if(exception.requires_customer_approval&&input.customer_approval_verified!==true&&action==='variation_review')return {schema:'titan.zero.jobs.exception-resolution.v1',...c,exception_id:exception.exception_id,status:'DENIED',reason:'CUSTOMER_APPROVAL_REQUIRED',authority_granted:false,execution_permitted:false};return {schema:'titan.zero.jobs.exception-resolution.v1',...c,exception_id:exception.exception_id,status:'READY',action,authority_granted:false,execution_permitted:false,proposal_only:true,requires_command_bus:true,next_job_state:action==='resume'||action==='start_rework'?'started':action==='reschedule'?'assigned':action==='approve_cancel'?'closed':null};}
export function canSilentlyCompleteWithExceptions(exceptions=[]){return list(exceptions).every(x=>x?.status==='RESOLVED'&&x?.blocks_completion!==true);}
