import test from 'node:test';import assert from 'node:assert/strict';
import {buildRevenueJourneyCorrelation} from '../../titan-revenue-journey/revenue-journey-correlation.mjs';import {buildInvoicePaymentLifecycleObservation,assertInvoicePaymentReplay} from '../../titan-revenue-journey/revenue-invoice-payment-lifecycle.mjs';
const correlation=buildRevenueJourneyCorrelation({company_id:'c1',revenue_journey_id:'revj:c1:x',job_id:'j1',provenance:{producer:'t'}});const p={producer:'finance-sync',source_event_id:'e1',observed_at:'2026-09-09T01:00:00Z'};const base={company_id:'c1',correlation,invoice_id:'i1',invoice_state:'issued',amount_total:100,amount_paid:0,amount_refunded:0,provenance:p,evidence:['invoice:i1']};
test('invoice binds to same journey without granting authority',()=>{const x=buildInvoicePaymentLifecycleObservation(base);assert.equal(x.correlation.entities.invoice_id,'i1');assert.equal(x.governance.execution_permitted,false);assert.equal(x.governance.may_move_money,false)});
test('partial payment remains outstanding and needs reconciliation',()=>{const x=buildInvoicePaymentLifecycleObservation({...base,invoice_state:'partially_paid',payment_id:'p1',payment_state:'partial',amount_paid:40,evidence:['invoice:i1','payment:p1']});assert.equal(x.amounts.outstanding,60);assert.equal(x.review.reconciliation_required,true);assert.equal(x.semantics.partial_payment_does_not_mean_settled,true)});
test('settled payment can show zero outstanding but is evidence not authority',()=>{const x=buildInvoicePaymentLifecycleObservation({...base,invoice_state:'paid',payment_id:'p1',payment_state:'settled',amount_paid:100,evidence:['payment:p1']});assert.equal(x.amounts.outstanding,0);assert.equal(x.review.reconciliation_required,false);assert.equal(x.semantics.invoice_paid_state_is_evidence_not_authority,true)});
test('failed payment does not void invoice',()=>{const x=buildInvoicePaymentLifecycleObservation({...base,payment_id:'p1',payment_state:'failed',evidence:['payment:p1']});assert.equal(x.review.failure_review_required,true);assert.equal(x.semantics.failed_payment_does_not_void_invoice,true)});
test('partial refund restores outstanding balance and requires refund review',()=>{const x=buildInvoicePaymentLifecycleObservation({...base,invoice_state:'paid',payment_id:'p1',payment_state:'partially_refunded',amount_paid:100,amount_refunded:25,evidence:['refund:r1']});assert.equal(x.amounts.outstanding,25);assert.equal(x.review.refund_review_required,true);assert.equal(x.governance.may_refund,false)});
test('full refund never executes money movement',()=>{const x=buildInvoicePaymentLifecycleObservation({...base,invoice_state:'paid',payment_id:'p1',payment_state:'refunded',amount_paid:100,amount_refunded:100,evidence:['refund:r2']});assert.equal(x.semantics.refund_state_does_not_execute_refund,true);assert.equal(x.governance.may_move_money,false)});
test('dispute requires review',()=>{const x=buildInvoicePaymentLifecycleObservation({...base,invoice_state:'disputed',payment_id:'p1',payment_state:'disputed',evidence:['dispute:d1']});assert.equal(x.review.failure_review_required,true)});
test('cross company correlation fails closed',()=>assert.throws(()=>buildInvoicePaymentLifecycleObservation({...base,company_id:'c2'}),/cross-company-correlation/));
test('cross company entity metadata fails closed',()=>{assert.throws(()=>buildInvoicePaymentLifecycleObservation({...base,invoice_company_id:'c2'}),/cross-company-invoice/);assert.throws(()=>buildInvoicePaymentLifecycleObservation({...base,payment_id:'p1',payment_state:'pending',payment_company_id:'c2'}),/cross-company-payment/)});
test('invalid financial arithmetic fails closed',()=>{assert.throws(()=>buildInvoicePaymentLifecycleObservation({...base,amount_paid:101}),/paid-exceeds-total/);assert.throws(()=>buildInvoicePaymentLifecycleObservation({...base,amount_paid:20,amount_refunded:21}),/refund-exceeds-paid/)});
test('payment state requires payment id',()=>assert.throws(()=>buildInvoicePaymentLifecycleObservation({...base,payment_state:'failed'}),/payment-id-required/));
test('deterministic replay',()=>{const a=buildInvoicePaymentLifecycleObservation(base),b=buildInvoicePaymentLifecycleObservation(base);assert.equal(assertInvoicePaymentReplay(a,b),true);assert.equal(a.idempotency_key,b.idempotency_key)});
test('source event changes replay key',()=>assert.notEqual(buildInvoicePaymentLifecycleObservation(base).idempotency_key,buildInvoicePaymentLifecycleObservation({...base,provenance:{...p,source_event_id:'e2'}}).idempotency_key));
test('legacy boundaries, provenance and evidence fail closed',()=>{assert.throws(()=>buildInvoicePaymentLifecycleObservation({...base,tenant_id:'x'}),/legacy-company-boundary/);assert.throws(()=>buildInvoicePaymentLifecycleObservation({...base,provenance:{producer:'x'}}),/provenance-required/);assert.throws(()=>buildInvoicePaymentLifecycleObservation({...base,evidence:[]}),/evidence-required/)})
