import test from 'node:test';import assert from 'node:assert/strict';
import {buildRevenueJourneyCorrelation} from '../../packages/.tmp-revenue-journey-build/revenue-journey-correlation.js';
import {buildRevenueContinuationLifecycle} from '../../packages/.tmp-revenue-journey-build/revenue-continuation-lifecycle.js';
import {buildRevenueContinuationEvidence} from '../../packages/.tmp-revenue-journey-build/continuation-evidence.js';
const corr=buildRevenueJourneyCorrelation({company_id:'c1',revenue_journey_id:'revj:c1:parent',payment_id:'p1',provenance:{producer:'test'}});
const provenance={producer:'continuation-sync',source_event_id:'e1',observed_at:'2026-09-13T02:00:00Z'};
const life=(event_type='customer_yes')=>buildRevenueContinuationLifecycle({company_id:'c1',kind:'repeat_service',repeat_id:'r1',event_type,correlation:corr,customer_id:'cust1',customer_explicit:event_type==='customer_yes',verified_intent:event_type==='customer_yes',provenance,evidence:['job:j1','invoice:i1']});
test('verified rebooking intent proposes one candidate but never creates it',()=>{const x=buildRevenueContinuationEvidence({company_id:'c1',customer_ref:'crm:customer:cust1',opportunity:'REBOOKING',lifecycle:life()});assert.match(x.candidate_revenue_journey_id,/^revj:c1:/);assert.equal(x.governance.may_create_customer_journey,false);assert.equal(x.duplicate_control.authoritative_duplicate_check_required,true)});
test('existing journey suppresses duplicate rebooking candidate',()=>{const l=life();const x=buildRevenueContinuationEvidence({company_id:'c1',customer_ref:'crm:customer:cust1',opportunity:'REBOOKING',lifecycle:l,existing_journey_id:l.candidate_revenue_journey_id});assert.equal(x.candidate_revenue_journey_id,null);assert.equal(x.duplicate_control.candidate_suppressed,true)});
test('recurring service frequency change remains schedule-review evidence only',()=>{const x=buildRevenueContinuationEvidence({company_id:'c1',customer_ref:'crm:customer:cust1',opportunity:'RECURRING_SERVICE',recurring_ref:'schedule:rec1',lifecycle:life('frequency_change')});assert.equal(x.candidate_revenue_journey_id,null);assert.equal(x.governance.may_create_schedule,false);assert.equal(x.handoff.target,'recurrence_review')});
test('review opportunity never creates a customer journey or sends outreach',()=>{const x=buildRevenueContinuationEvidence({company_id:'c1',customer_ref:'crm:customer:cust1',opportunity:'REVIEW',review_ref:'review-opportunity:1',lifecycle:life('opportunity_detected')});assert.equal(x.candidate_revenue_journey_id,null);assert.equal(x.governance.may_send_review_request,false);assert.equal(x.semantics.review_does_not_create_journey,true)});
test('retention signal remains evidence only',()=>{const x=buildRevenueContinuationEvidence({company_id:'c1',customer_ref:'crm:customer:cust1',opportunity:'RETENTION',retention_ref:'retention:signal:1',lifecycle:life('recommendation_ready')});assert.equal(x.governance.may_send_retention_outreach,false);assert.equal(x.semantics.retention_signal_does_not_create_journey,true)});
test('cross-company, legacy aliases and conflicting existing journey fail closed',()=>{const l=life();assert.throws(()=>buildRevenueContinuationEvidence({company_id:'c2',customer_ref:'x',opportunity:'REBOOKING',lifecycle:l}),/cross-company/);assert.throws(()=>buildRevenueContinuationEvidence({company_id:'c1',account_id:'legacy',customer_ref:'x',opportunity:'REBOOKING',lifecycle:l}),/legacy-company/);assert.throws(()=>buildRevenueContinuationEvidence({company_id:'c1',customer_ref:'x',opportunity:'REBOOKING',lifecycle:l,existing_journey_id:'revj:c1:other'}),/existing-journey-conflict/)})
