import SectionLabel from '../components/SectionLabel'
import CTASection from '../components/CTASection'
const principles=[
['🏗️','Business first','Start with how the company actually operates, not with a demand that it migrate into one vendor application.'],
['🧩','Keep + fill','Retain useful systems, connect them, then add Titan Zero software where genuine operational gaps remain.'],
['🛡️','Governed intelligence','Recommendations, predictions and intelligence do not automatically become execution authority.'],
['🔒','Privacy & locality','Use device, customer-hosted, BYO-cloud or Titan-managed options according to the workload and business requirements.'],
['💰','Cost sovereignty','Support customer-owned keys, provider choice, local/private models and customer-controlled compute where appropriate.'],
['🌱','Environmental systems','Make environmental evidence, assessment, auditing and improvement part of the operating system rather than a disconnected report.'],
]
export default function About(){return <><section className="pt-32 pb-16 px-6 text-center"><div className="max-w-6xl mx-auto"><SectionLabel>About Titan Zero Field Services</SectionLabel><h1 className="text-4xl sm:text-6xl font-extrabold mb-5">The business is the system.<br/><span className="text-nx-purple-light">Technology should fit around it.</span></h1><p className="text-lg text-nx-muted max-w-3xl mx-auto">Titan Zero Field Services is a managed Advanced Intelligence system for service businesses. It combines the software a business already relies on, additional Titan Zero capabilities where gaps exist, and a managed intelligence workforce configured around the operation.</p></div></section><section className="px-6 pb-24"><div className="max-w-6xl mx-auto"><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{principles.map(([i,t,d])=><div key={t} className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="text-2xl mb-3">{i}</div><h2 className="font-bold mb-2">{t}</h2><p className="text-sm text-nx-muted leading-relaxed">{d}</p></div>)}</div><div className="mt-14 bg-nx-surface border border-nx-border rounded-2xl p-8"><h2 className="text-2xl font-bold mb-3">One Field Services core, specialised by industry</h2><p className="text-nx-muted leading-relaxed">Cleaning, landscaping, pools, pressure washing, pest control, window cleaning, property maintenance and mobile services share a common operational spine, but each has different knowledge, workflows, objects, risks and customer expectations. Titan Zero keeps the common architecture while configuring the system for each industry.</p></div></div></section><CTASection/></>}