import SectionLabel from '../components/SectionLabel'
import CTASection from '../components/CTASection'
const principles=[
['👤','One + Zero + Team','The person remains One. Their Zero develops persistent working understanding, while specialist capabilities and people form the team around the work.'],
['🧠','Understanding is not authority','Zero can learn, remember, predict and improve without silently gaining permission to act.'],
['🏗️','Business first','Start with how the company actually operates, not with a demand that it migrate into one vendor application.'],
['🧩','Keep + fill','Retain useful systems, connect them, then add Titan Zero software where genuine operational gaps remain.'],
['🛡️','Governed intelligence','Recommendations, predictions and intelligence do not automatically become execution authority.'],
['🔒','Privacy & locality','Use device, customer-hosted, BYO-cloud or Titan-managed options according to the workload and business requirements.'],
['💰','Cost sovereignty','Support customer-owned keys, provider choice, local/private models and customer-controlled compute where appropriate.'],
['🌱','Environmental systems','Make environmental evidence, assessment, auditing and improvement part of the operating system rather than a disconnected report.'],
]
export default function About(){return <><section className="pt-32 pb-16 px-6 text-center"><div className="max-w-6xl mx-auto"><SectionLabel>About Titan Zero Field Services</SectionLabel><h1 className="text-4xl sm:text-6xl font-extrabold mb-5">The business is the system.<br/><span className="text-nx-purple-light">Technology should fit around it.</span></h1><p className="text-lg text-nx-muted max-w-3xl mx-auto">Titan Zero Field Services gives each owner or authorised person a digital working intelligence — their Zero — that progressively understands their role and business, coordinates specialist capabilities and works across the systems the business already relies on. Titan implements and manages the intelligence system around the operation.</p></div></section><section className="px-6 pb-24"><div className="max-w-6xl mx-auto"><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{principles.map(([i,t,d])=><div key={t} className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="text-2xl mb-3">{i}</div><h2 className="font-bold mb-2">{t}</h2><p className="text-sm text-nx-muted leading-relaxed">{d}</p></div>)}</div><div className="mt-14 grid lg:grid-cols-3 gap-5"><div className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="text-xs font-bold text-nx-purple-light mb-2">ONE</div><h2 className="text-xl font-bold mb-2">Human principal</h2><p className="text-sm text-nx-muted">Responsibility, judgement, values, relationships and authority remain human.</p></div><div className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="text-xs font-bold text-nx-purple-light mb-2">ZERO</div><h2 className="text-xl font-bold mb-2">Working intelligence</h2><p className="text-sm text-nx-muted">Persistent understanding, memory, investigation, coordination and learning around the person and business.</p></div><div className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="text-xs font-bold text-nx-purple-light mb-2">TEAM</div><h2 className="text-xl font-bold mb-2">Specialist capability</h2><p className="text-sm text-nx-muted">AI capabilities and people coordinated through Zero rather than exposed as another layer of tools to manage.</p></div></div><div className="mt-5 bg-nx-surface border border-nx-border rounded-2xl p-8"><h2 className="text-2xl font-bold mb-3">One Field Services core, specialised by industry</h2><p className="text-nx-muted leading-relaxed">Cleaning, landscaping, pools, pressure washing, pest control, window cleaning, property maintenance and mobile services share a common operational spine, but each has different knowledge, workflows, objects, risks and customer expectations. Titan Zero keeps the common architecture while configuring the system for each industry.</p></div></div></section><CTASection/></>}