import SectionLabel from '../components/SectionLabel'
import CTASection from '../components/CTASection'
const apps=[
['Command','For owners and managers',['Your Zero','business control','workforce','decisions','communications','systems','approvals','intelligence'],'Instead of opening five applications to understand one problem, ask Zero.'],
['Go','For your team in the field',['current work','schedules','communications','procedures','job knowledge','equipment information','maps','visual guidance','evidence capture'],"A worker shouldn't need to know where every piece of company knowledge lives. They should be able to ask."],
['Hub','For your customers',['questions','services','support','account information','bookings','work review','communication','relevant actions'],"Customers shouldn't have to understand your internal systems either."]
]
export default function Apps(){return <><section className="pt-32 pb-16 px-6 text-center"><div className="max-w-5xl mx-auto"><SectionLabel>Titan Zero Apps</SectionLabel><h1 className="text-4xl sm:text-6xl font-extrabold mb-5">Your Zero and business intelligence <span className="text-nx-purple-light">where the work happens.</span></h1><p className="text-lg text-nx-muted max-w-3xl mx-auto">Command, Go and Hub give owners, workers and customers focused experiences around the same governed Titan Zero environment.</p></div></section>
<section className="px-6 pb-24"><div className="max-w-6xl mx-auto grid lg:grid-cols-3 gap-5">{apps.map(([name,who,items,close])=><article key={name} className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="text-xs uppercase tracking-widest text-nx-purple-light mb-2">{who}</div><h2 className="text-3xl font-extrabold mb-5">Titan Zero {name}</h2><div className="flex flex-wrap gap-2 mb-6">{items.map(x=><span key={x} className="bg-nx-bg border border-nx-border rounded-lg px-3 py-2 text-xs">{x}</span>)}</div><p className="text-sm text-nx-muted leading-relaxed">{close}</p></article>)}</div></section>
<CTASection title="One business. Focused experiences." subtitle="Command for owners, Go for field teams and Hub for customers — connected through Titan Zero."/></>}