import SectionLabel from '../components/SectionLabel'
import CTASection from '../components/CTASection'
const items=[
['Privacy first','Architecture choices start with minimising unnecessary movement and exposure of business data.'],
['Device first','Where practical, intelligence and data processing can run on customer-controlled devices rather than requiring every task to leave the business.'],
['Private models','Customer-hosted and private LLM options can keep sensitive knowledge closer to the organisation and support private RAG over authorised business knowledge.'],
['Edge node network','Customer-controlled computers and devices can participate as governed edge nodes, bringing compute and intelligence closer to the work.'],
['Bring your own AI and API keys','Where supported, businesses can use their own provider accounts and keys instead of being permanently locked to a Titan-funded provider.'],
['Provider choice','Device, customer-hosted, BYO cloud and Titan-managed options can be selected according to the workload, privacy requirements and operating model.'],
]
export default function Architecture(){return <><section className="pt-32 pb-16 px-6 text-center"><div className="max-w-5xl mx-auto"><SectionLabel>Privacy & Architecture</SectionLabel><h1 className="text-4xl sm:text-6xl font-extrabold mb-5">Your intelligence system should work <span className="text-nx-purple-light">for your business — not trap it.</span></h1><p className="text-lg text-nx-muted max-w-3xl mx-auto">Titan Zero is designed around privacy, locality and customer choice: use existing systems, add missing software, run appropriate workloads on devices or customer-controlled infrastructure, and choose the AI providers that fit the job.</p></div></section><section className="px-6 pb-24"><div className="max-w-6xl mx-auto grid md:grid-cols-2 lg:grid-cols-3 gap-5">{items.map(([t,d])=><div key={t} className="bg-nx-surface border border-nx-border rounded-2xl p-7"><h2 className="text-lg font-bold mb-2">{t}</h2><p className="text-sm text-nx-muted leading-relaxed">{d}</p></div>)}</div><div className="max-w-6xl mx-auto mt-10 bg-nx-surface border border-nx-border rounded-2xl p-8"><h2 className="text-2xl font-bold mb-3">A governed edge fabric, not an uncontrolled device mesh.</h2><p className="text-sm text-nx-muted leading-relaxed mb-5">Titan Zero can use customer-controlled computers and devices as edge nodes for suitable workloads, including private knowledge retrieval and local model execution. Participation does not itself grant access or execution authority.</p><div className="grid md:grid-cols-3 gap-4"><div className="bg-nx-bg border border-nx-border rounded-xl p-5"><h3 className="font-bold mb-2">Authorised context</h3><p className="text-sm text-nx-muted">Nodes receive only the business context, knowledge and capability scope authorised for the workload.</p></div><div className="bg-nx-bg border border-nx-border rounded-xl p-5"><h3 className="font-bold mb-2">Local where practical</h3><p className="text-sm text-nx-muted">Private RAG, local models and customer-owned compute can keep suitable processing closer to the business.</p></div><div className="bg-nx-bg border border-nx-border rounded-xl p-5"><h3 className="font-bold mb-2">Governed execution</h3><p className="text-sm text-nx-muted">Intelligence, registration or node availability never automatically confers permission to execute business actions.</p></div></div><p className="text-xs text-nx-muted2 mt-5">In multi-company environments, company_id is the canonical tenant boundary before authorised knowledge, data access or execution is resolved.</p></div>
<div className="max-w-6xl mx-auto mt-10 grid lg:grid-cols-2 gap-5">
<div className="bg-nx-surface border border-nx-border rounded-2xl p-8"><h2 className="text-2xl font-bold mb-3">Your Zero can remain private.</h2><p className="text-sm text-nx-muted leading-relaxed mb-4">Zero may accumulate useful context about how you and the business work. Titan Zero is designed so suitable knowledge and intelligence can remain on customer-controlled infrastructure, use private retrieval, or run through local models where appropriate.</p><p className="text-sm text-nx-muted leading-relaxed">Local does not mean isolated. When external intelligence is genuinely useful, the system can use an approved external model or service for the appropriate task without requiring every workload to use the same provider.</p></div>
<div className="bg-nx-surface border border-nx-border rounded-2xl p-8"><h2 className="text-2xl font-bold mb-3">A distributed Zero, not a single box.</h2><p className="text-sm text-nx-muted leading-relaxed mb-4">Suitable parts of Titan Zero can operate across customer-controlled devices and infrastructure so intelligence can move closer to the work while remaining governed as one system.</p><p className="text-sm text-nx-muted leading-relaxed">A device joining the runtime does not inherit unrestricted business access. Identity, company scope, authorised context, capability and execution authority remain separate concerns.</p></div>
</div></section><CTASection title="Keep control of where intelligence runs." subtitle="Locality and provider choices can be matched to the workload instead of forcing one architecture on every business."/></>}