import SectionLabel from '../components/SectionLabel'
import { Link } from 'react-router-dom'
const cycle=['Discover','Configure','Verify','Observe','Rediscover','Compare','Diagnose','Preview','Approve','Reconfigure','Verify','Measure','Learn','Repeat']
const areas=[
{title:'Your Zero',status:'Core model',items:['One + Zero + Team','Persistent working understanding','Corrections and experience','Outcome learning and reassessment']},
{title:'Business Reality',status:'Continuous context',items:['Evidence-backed business facts','Meaningful change detection','Uncertainty and contradiction','Knowledge and provenance']},
{title:'Managed System',status:'Service model',items:['Existing systems first','Integration before replacement','Titan software fills genuine gaps','Ongoing management and improvement']},
{title:'Trust & Authority',status:'Governed progression',items:['Observe → Recommend → Prepare → Ask & Execute','Bounded trusted automation where appropriate','System eligibility + human delegation + current acceptance','Authority can be reduced or revoked']},
{title:'Sovereign Intelligence',status:'Architecture',items:['Device-first and privacy-first options','Private/local models and private retrieval','Customer-controlled infrastructure','BYO providers and keys where supported']},
{title:'Measured Experience',status:'Learning loop',items:['Baseline and expected outcome','Observed real-world outcome','Unintended effects','Experience feeds future reassessment']},
]
export default function Changelog(){return <><section className="pt-32 pb-16 px-6 text-center"><div className="max-w-7xl mx-auto"><SectionLabel>System Evolution</SectionLabel><h1 className="text-4xl sm:text-6xl font-extrabold mb-4">Titan Zero evolves <span className="text-nx-purple-light">with the business.</span></h1><p className="text-lg text-nx-muted max-w-3xl mx-auto">This is not a conventional software changelog. Titan Zero is designed as a continuously evolving intelligence system: understanding changes, the business changes, outcomes arrive and the system reassesses what should happen next.</p></div></section>
<section className="px-6 pb-16"><div className="max-w-6xl mx-auto"><div className="bg-nx-surface border border-nx-border rounded-2xl p-7"><SectionLabel>Evolution Loop</SectionLabel><div className="flex flex-wrap gap-2 mt-4">{cycle.map((x,i)=><span key={i} className="bg-nx-bg border border-nx-border rounded-lg px-3 py-2 text-xs font-semibold">{x}</span>)}</div><p className="text-sm text-nx-muted mt-5">Important reconfiguration remains governed. Continuous learning does not mean silent permission to change consequential business behaviour.</p></div></div></section>
<section className="px-6 pb-24"><div className="max-w-6xl mx-auto grid md:grid-cols-2 lg:grid-cols-3 gap-5">{areas.map(m=><div key={m.title} className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="flex flex-wrap justify-between gap-3 mb-5"><h2 className="text-xl font-bold">{m.title}</h2><span className="text-xs text-nx-purple-light bg-nx-purple-glow rounded-full px-3 py-1">{m.status}</span></div><div className="space-y-2">{m.items.map(x=><p key={x} className="text-sm text-nx-muted">✓ {x}</p>)}</div></div>)}</div><div className="max-w-5xl mx-auto mt-10 text-center"><p className="text-sm text-nx-muted">Explore <Link to="/your-zero" className="text-nx-purple-light">Your Zero</Link>, <Link to="/continuous-evolution" className="text-nx-purple-light">Continuous Evolution</Link>, <Link to="/fully-managed" className="text-nx-purple-light">Trust & Authority</Link> and <Link to="/measured-outcomes" className="text-nx-purple-light">Measured Outcomes</Link>.</p></div></section></>}