import SectionLabel from '../components/SectionLabel'
import { Link } from 'react-router-dom'
const milestones=[
{title:'Managed System',status:'Current direction',items:['Existing-system integration as the starting point','Titan Zero software fills genuine capability gaps','Managed Advanced Intelligence workforce configured around the business','Ongoing management and improvement rather than DIY AI configuration']},
{title:'Field Services Industry Systems',status:'Available marketing architecture',items:['Cleaning','Landscaping & Lawn Care','Pool Service','Pressure Washing','Pest Control','Window Cleaning','Property Maintenance','Mobile Services']},
{title:'Sovereign Intelligence Architecture',status:'Platform direction',items:['Device-first and privacy-first options','Private/local LLM and private knowledge retrieval options','Customer-controlled edge node architecture','BYO AI/API provider keys where supported','Device, customer-hosted, BYO-cloud and Titan-managed locality choices']},
{title:'Governed Workforce',status:'Platform direction',items:['Intelligence does not automatically confer execution authority','Company-scoped permissions and authority boundaries','Human review for configured consequential actions','Auditable operational decisions and system actions']},
{title:'Environmental Systems',status:'Cross-vertical capability',items:['Environmental assessment workflows','Environmental auditing and evidence','Compliance and improvement actions','Qualified environmental-scientist involvement where professional judgement or sign-off is required']},
]
export default function Changelog(){return <><section className="pt-32 pb-16 px-6 text-center"><div className="max-w-7xl mx-auto"><SectionLabel>System Evolution</SectionLabel><h1 className="text-4xl sm:text-6xl font-extrabold mb-4">What Titan Zero Field Services <span className="text-nx-purple-light">is becoming.</span></h1><p className="text-lg text-nx-muted max-w-3xl mx-auto">This page replaces the inherited donor-product release claims with the actual Titan Zero product direction. It describes architecture and capability direction rather than promising that every item is enabled in every customer deployment.</p></div></section><section className="px-6 pb-24"><div className="max-w-4xl mx-auto space-y-6">{milestones.map(m=><div key={m.title} className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="flex flex-wrap justify-between gap-3 mb-5"><h2 className="text-xl font-bold">{m.title}</h2><span className="text-xs text-nx-purple-light bg-nx-purple-glow rounded-full px-3 py-1">{m.status}</span></div><div className="space-y-2">{m.items.map(x=><p key={x} className="text-sm text-nx-muted">✓ {x}</p>)}</div></div>)}</div><div className="max-w-4xl mx-auto mt-10 text-center"><p className="text-sm text-nx-muted">Explore the <Link to="/fully-managed" className="text-nx-purple-light">Fully Managed model</Link>, <Link to="/privacy-architecture" className="text-nx-purple-light">privacy architecture</Link> and <Link to="/industries" className="text-nx-purple-light">industry systems</Link>.</p></div></section></>}