import SectionLabel from '../components/SectionLabel'
import CTASection from '../components/CTASection'
const rows=[
['Starting point','Replace or centralise work in the vendor platform','Keep useful systems; integrate them and fill genuine software gaps'],
['Primary interface','Users operate the vendor application and its features','Each account holder can work with their own Zero while specialist capabilities and systems operate behind it'],
['AI model','Features or assistants inside a product','A persistent personal digital working intelligence that can coordinate different authorised models, systems and specialist capabilities'],
['Implementation','Customer configures the product','Titan Zero assesses, implements, configures and manages the system'],
['Data locality','Typically vendor/cloud architecture','Device, customer-hosted, BYO cloud or Titan-managed options where supported'],
['Models & keys','Usually vendor-selected/bundled','Private/local models and BYO provider/API keys where supported'],
['Lock-in','Value concentrated inside one vendor application','Designed for portability, provider choice and use of existing systems'],
['Environmental capability','Usually separate from field-service software','Environmental assessment, audit and improvement workflows can be integrated'],
['Learning','Product configuration and assistant history','Each Zero can learn from that person’s corrections, changing role and experience while shared business outcomes remain separately governed'],
['Decision support','Often a feature-specific assistant or report','Evidence, uncertainty, investigation and multiple reasoning perspectives can inform consequential decisions'],
['Automation trust','Automation permissions are commonly configured as product settings','Capability-specific progression from observation to bounded automation; intelligence and permission remain separate'],
['Software gaps','Usually solved by adding another product or module','Titan Zero can add missing interfaces or software while retaining useful existing systems'],
['Measurement','Feature usage and workflow completion are common operational measures','Baseline, expected outcome and actual outcome can be compared so the system learns from results'],
['Operating model','Customer operates and maintains the software configuration','Titan Zero manages the intelligence environment behind personal Zeros for owners, staff and customers'],
]
export default function Compare(){return <><section className="pt-32 pb-16 px-6 text-center"><div className="max-w-5xl mx-auto"><SectionLabel>Compare the Model</SectionLabel><h1 className="text-4xl sm:text-6xl font-extrabold mb-5">Not just another field-service SaaS <span className="text-nx-purple-light">with AI added.</span></h1><p className="text-lg text-nx-muted max-w-3xl mx-auto">Titan Zero takes a different architectural and service approach. The comparison below describes operating models rather than claiming every competitor implements every characteristic.</p></div></section><section className="px-6 pb-24"><div className="max-w-6xl mx-auto overflow-x-auto border border-nx-border rounded-2xl"><table className="w-full text-left"><thead className="bg-nx-surface"><tr><th className="p-5">Area</th><th className="p-5">Typical software-first approach</th><th className="p-5 text-nx-purple-light">Titan Zero approach</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]} className="border-t border-nx-border"><th className="p-5 text-sm">{r[0]}</th><td className="p-5 text-sm text-nx-muted">{r[1]}</td><td className="p-5 text-sm text-nx-muted">{r[2]}</td></tr>)}</tbody></table></div></section><section className="px-6 pb-24"><div className="max-w-6xl mx-auto bg-nx-surface border border-nx-border rounded-2xl p-8"><SectionLabel>The structural difference</SectionLabel><h2 className="text-3xl font-extrabold mb-4">The user is not an account inside the AI. The AI is organised around the person.</h2><p className="text-nx-muted leading-relaxed">Titan Zero separates the human account holder (One), that person's persistent Zero, shared business reality and governed authority. That allows an owner, worker and customer to participate in the same connected business without pretending they are the same user, sharing one assistant memory or receiving the same permissions.</p></div></section>
<CTASection title="Keep what works. Add what is missing. Manage it as one system." subtitle="That is the core difference behind Titan Zero."/></>}