import SectionLabel from '../components/SectionLabel'
import CTASection from '../components/CTASection'
const options=[
['BYO API keys','Use supported provider accounts directly so usage can be visible under your own account and pricing relationship.'],
['BYO AI keys','Choose supported AI providers instead of being permanently tied to one bundled model vendor.'],
['Local and private LLMs','Suitable workloads can use customer-controlled models, reducing dependency on per-request cloud inference and supporting privacy-sensitive work.'],
['Use the compute you own','Customer-controlled edge devices can contribute compute where appropriate instead of every workload requiring a separately metered cloud service.'],
['Pay for management and outcomes','Titan Zero can separate the value of implementation and management from third-party usage costs, making the cost structure easier to understand.'],
['Avoid forced replacement','Keeping useful existing systems can avoid unnecessary migration and replacement costs; Titan Zero fills genuine gaps rather than replacing software merely to create lock-in.'],
]
export default function CostSovereignty(){return <><section className="pt-32 pb-16 px-6 text-center"><div className="max-w-5xl mx-auto"><SectionLabel>Cost Sovereignty</SectionLabel><h1 className="text-4xl sm:text-6xl font-extrabold mb-5">More control over <span className="text-nx-purple-light">what your intelligence actually costs.</span></h1><p className="text-lg text-nx-muted max-w-3xl mx-auto">AI costs do not have to disappear inside a black-box subscription. Titan Zero is designed to support your own keys, your own provider relationships, private/local models and customer-controlled compute where appropriate.</p></div></section><section className="px-6 pb-24"><div className="max-w-6xl mx-auto grid md:grid-cols-2 lg:grid-cols-3 gap-5">{options.map(([t,d])=><div key={t} className="bg-nx-surface border border-nx-border rounded-2xl p-7"><h2 className="text-lg font-bold mb-2">{t}</h2><p className="text-sm text-nx-muted leading-relaxed">{d}</p></div>)}</div><div className="max-w-6xl mx-auto mt-10 grid md:grid-cols-3 gap-5"><div className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="text-xs font-bold text-nx-purple-light mb-2">01 · CUSTOMER CONTROLLED</div><h2 className="font-bold mb-2">Your accounts and compute</h2><p className="text-sm text-nx-muted">Use supported provider accounts, API keys, local models, customer-hosted infrastructure and owned edge compute where those choices fit the workload.</p></div><div className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="text-xs font-bold text-nx-purple-light mb-2">02 · TITAN MANAGED</div><h2 className="font-bold mb-2">Management separated from usage</h2><p className="text-sm text-nx-muted">Titan Zero implementation and ongoing management can be priced separately from third-party model, messaging, telephony, storage or infrastructure usage.</p></div><div className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="text-xs font-bold text-nx-purple-light mb-2">03 · OPTIONAL SERVICES</div><h2 className="font-bold mb-2">Add managed infrastructure when useful</h2><p className="text-sm text-nx-muted">Titan-managed providers or infrastructure can be selected where they improve the operating model; they are not intended to become a hidden prerequisite for every deployment.</p></div></div><p className="max-w-4xl mx-auto text-xs text-nx-muted2 mt-8 text-center">Actual costs depend on workload, provider, model, infrastructure and the services selected. Local or BYO options can change the cost structure but do not guarantee a specific saving.</p></section><CTASection title="Choose the cost model that fits the business." subtitle="Titan Zero is designed to reduce unnecessary lock-in while keeping managed implementation and support."/></>}