import { useState } from 'react'
import { ChevronDown } from 'lucide-react'
import SectionLabel from '../components/SectionLabel'
import CTASection from '../components/CTASection'

const faqs=[
{q:'What does fully managed mean?',a:'Titan Zero assesses the business, integrates systems worth keeping, fills genuine software gaps, configures the Advanced Intelligence workforce, establishes governance and review boundaries, and continues managing and improving the system with the business.'},
{q:'Do I have to replace my existing field-service software?',a:'No. Titan Zero is designed to keep useful systems where they fit. We integrate around them and can add Titan Zero software or interfaces where an operational gap remains.'},
{q:'Is Titan Zero just an AI chatbot?',a:'No. Chat, voice and camera are interaction surfaces. Behind them, Titan Zero coordinates authorised workforce capabilities, business knowledge, integrations, software functions, governance and operational workflows.'},
{q:'Can Titan Zero use private or local AI models?',a:'The architecture supports device, customer-hosted, BYO-cloud and Titan-managed approaches where suitable. Private/local LLMs and private retrieval over authorised business knowledge can be used for appropriate workloads.'},
{q:'Can I use my own AI or API keys?',a:'Where a provider or integration supports it, Titan Zero is designed to allow customer-owned provider accounts and keys rather than requiring every usage cost to be hidden inside one bundled subscription.'},
{q:'What Field Services industries are supported?',a:'The Field Services site currently includes dedicated systems for cleaning, landscaping and lawn care, pool service, pressure washing, pest control, window cleaning, property maintenance and mobile service businesses.'},
{q:'How is authority controlled?',a:'An intelligence result, recommendation or prediction does not automatically grant permission to execute. Consequential actions can be governed by company authority, permissions, review points and configured autonomy.'},
{q:'What are Environmental Systems?',a:'Titan Zero can connect environmental assessment, auditing, evidence, compliance and improvement workflows to business operations. Where professional environmental judgement or sign-off is required, work can be performed or reviewed by appropriately qualified environmental scientists.'},
{q:'How is Titan Zero different from normal field-service SaaS?',a:'Traditional products generally concentrate the business inside the vendor application. Titan Zero starts from the business itself: keep useful systems, connect them, add missing software, configure a managed intelligence workforce, and choose appropriate privacy, locality and provider options.'},
{q:'Does local AI always cost less?',a:'Not necessarily. Cost depends on workload, hardware, provider, model and management requirements. Local models, customer-owned compute and BYO keys can change the cost structure and reduce some third-party usage, but Titan Zero does not promise a fixed saving.'},
]
function FAQItem({q,a}){const[open,setOpen]=useState(false);const id=`faq-${q.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}`;return <div className={`border border-nx-border rounded-xl overflow-hidden ${open?'border-nx-purple/50':''}`}><button className="w-full flex items-center justify-between gap-4 px-6 py-4 text-left" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls={id}><span className="text-sm font-semibold">{q}</span><ChevronDown size={16} aria-hidden="true" className={`text-nx-muted transition-transform ${open?'rotate-180':''}`}/></button>{open&&<div id={id} className="px-6 pb-5"><p className="text-sm text-nx-muted leading-relaxed">{a}</p></div>}</div>}
export default function FAQ(){return <><section className="pt-32 pb-16 px-6 text-center"><div className="max-w-7xl mx-auto"><SectionLabel>FAQ</SectionLabel><h1 className="text-4xl sm:text-5xl font-extrabold mb-4">Understand the <span className="text-nx-purple-light">Titan Zero model.</span></h1><p className="text-lg text-nx-muted max-w-2xl mx-auto">How the managed workforce, existing-system integration, software gap filling, privacy architecture and cost model work.</p></div></section><section className="px-6 pb-24"><div className="max-w-3xl mx-auto space-y-3">{faqs.map(f=><FAQItem key={f.q}{...f}/>)}</div></section><CTASection/></>}