import { Check } from 'lucide-react'
import SectionLabel from '../components/SectionLabel'
import FadeIn from '../components/FadeIn'
import CTASection from '../components/CTASection'

const showcaseFeatures=[
{number:'01',label:'Managed Workforce',title:'Customer & Reception Workforce',tagline:'Enquiries keep moving while your team is doing the work.',desc:'Configure authorised workforce capabilities around calls, messages, enquiries, qualification, bookings, reminders and follow-up — connected to the systems and business rules you choose.',points:['Works across authorised customer channels','Uses business knowledge and customer context','Escalates exceptions and consequential decisions','Can operate through chat, voice and generated interfaces']},
{number:'02',label:'Operations',title:'Scheduling & Field Coordination',tagline:'Keep the operating day connected.',desc:'Coordinate recurring work, locations, teams, job context, changes and next actions while retaining existing scheduling or field systems where they still fit.',points:['Recurring and one-off work context','Field team and location awareness','Exception and change handling','Human review and authority boundaries']},
{number:'03',label:'Interface',title:'Chat, Voice & Camera',tagline:'Work with the system in the way the job demands.',desc:'Titan Zero is designed around conversational and visual interaction rather than forcing every task through an administration dashboard.',points:['Chat for instructions and operational questions','Voice for hands-busy field workflows','Camera for authorised visual evidence and context','Generated interfaces when structured interaction is better']},
{number:'04',label:'System Architecture',title:'Integration + Software Gap Filling',tagline:'Keep what works. Build what is missing.',desc:'Titan Zero connects useful existing systems and can add Titan Zero software, interfaces and workflows where the business has a genuine operational gap.',points:['Existing-system integration','Titan Zero software for missing capability','Governed business actions through shared contracts','No forced replacement merely to create lock-in']},
]
const capabilities=[
['📞','Reception & communications','Enquiries, qualification, booking, reminders, updates and customer follow-up.'],
['📅','Scheduling & coordination','Recurring work, teams, locations, exceptions and operational next actions.'],
['🧠','Business intelligence','Briefings, exceptions, recommendations and decision support from authorised information.'],
['📋','Quotes & proposals','Prepare structured work from customer, property, job history and approved business knowledge for review.'],
['🗺️','Field operations','Bring job, customer, location, knowledge and change context closer to field teams.'],
['📸','Evidence & visual workflows','Connect authorised photos, documents, notes and camera input to the relevant operational record.'],
['💬','Customer care','Keep service communication, issues, feedback, repeat work and retention workflows moving.'],
['💰','Billing workflow','Move authorised completed work toward invoicing and payment through selected business systems.'],
['🔌','Integrations','Connect existing CRM, calendar, phone, messaging, accounting and operational software where supported.'],
['🧩','Gap-filling software','Add Titan Zero capabilities when the existing stack does not provide the required business function.'],
['🔒','Private intelligence options','Use device, customer-hosted, BYO-cloud or Titan-managed model options where appropriate.'],
['🌱','Environmental systems','Connect environmental assessment, audit, evidence and improvement workflows to operations.'],
]
export default function Features(){return <><section className="pt-32 pb-16 px-6 text-center"><div className="max-w-7xl mx-auto"><SectionLabel>Capabilities</SectionLabel><h1 className="text-4xl sm:text-6xl font-extrabold mb-4">More than field-service software.<br/><span className="text-nx-purple-light">A managed operating system around the business.</span></h1><p className="text-lg text-nx-muted max-w-3xl mx-auto">Titan Zero combines managed workforce capabilities, existing-system integration and additional software where gaps remain. The exact system is configured around the business rather than sold as a fixed list of AI tricks.</p></div></section>
{showcaseFeatures.map((s,i)=><section key={s.number} className="py-20 px-6 border-t border-nx-border"><div className="max-w-7xl mx-auto grid lg:grid-cols-2 gap-14 items-center"><FadeIn className={i%2?'lg:order-2':''}><div className="text-xs font-bold text-nx-purple-light mb-3">{s.number} · {s.label}</div><h2 className="text-3xl sm:text-4xl font-extrabold mb-2">{s.title}</h2><p className="text-nx-purple-light text-sm italic mb-4">{s.tagline}</p><p className="text-nx-muted leading-relaxed mb-6">{s.desc}</p><div className="space-y-3">{s.points.map(p=><div key={p} className="flex gap-3"><Check size={16} className="text-nx-green mt-0.5"/><p className="text-sm text-nx-muted">{p}</p></div>)}</div></FadeIn><FadeIn className={i%2?'lg:order-1':''}><div className="bg-nx-surface border border-nx-border rounded-2xl p-7"><p className="text-xs uppercase tracking-widest text-nx-muted2 mb-5">Managed system</p><div className="space-y-3">{['Business context','Authorised knowledge','Workforce capability','Integration / Titan software','Governance & review','Operational outcome'].map((x,n)=><div key={x} className="bg-nx-bg border border-nx-border rounded-xl p-3 flex gap-3"><span className="text-xs font-bold text-nx-purple-light">0{n+1}</span><span className="text-sm">{x}</span></div>)}</div></div></FadeIn></div></section>)}
<section className="py-20 px-6 border-t border-nx-border"><div className="max-w-7xl mx-auto"><div className="text-center mb-12"><SectionLabel>Connected Capabilities</SectionLabel><h2 className="text-4xl font-extrabold mb-3">Configure the system the business needs.</h2><p className="text-nx-muted max-w-2xl mx-auto">Capabilities share context and governance instead of becoming another collection of disconnected point tools.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{capabilities.map(([icon,t,d],i)=><FadeIn key={t} delay={i*35}><div className="bg-nx-surface border border-nx-border rounded-2xl p-6 h-full"><div className="text-2xl mb-3">{icon}</div><h3 className="font-bold mb-2">{t}</h3><p className="text-sm text-nx-muted leading-relaxed">{d}</p></div></FadeIn>)}</div></div></section>
<CTASection title="Build the capability around your operation." subtitle="Keep the software that earns its place, fill the gaps, and manage the resulting system as one Titan Zero environment."/></>}