import SectionLabel from '../components/SectionLabel'
import CTASection from '../components/CTASection'
const known=['what is known','what has been observed','what has been confirmed','what is inferred','what is uncertain','what is contradicted by other evidence']
const perspectives=['agreement','disagreement','missing evidence','alternative explanations','possible consequences','hidden assumptions','shared blind spots']
export default function IntelligenceDecisions(){return <><section className="pt-32 pb-16 px-6 text-center"><div className="max-w-5xl mx-auto"><SectionLabel>Intelligence & Decisions</SectionLabel><h1 className="text-4xl sm:text-6xl font-extrabold mb-5">From information <span className="text-nx-purple-light">to better decisions.</span></h1><p className="text-lg text-nx-muted max-w-3xl mx-auto">A person's Zero can help turn authorised information into useful decisions for that person — while keeping personal understanding, shared business reality, evidence, uncertainty and authority distinct.</p></div></section>
<section className="px-6 pb-24"><div className="max-w-6xl mx-auto"><div className="bg-nx-surface border border-nx-border rounded-2xl p-8 text-center font-bold text-lg">Discover → Understand → Diagnose → Recommend → Decide → Act → Measure → Learn</div></div></section>
<section className="py-20 px-6 border-y border-nx-border"><div className="max-w-6xl mx-auto grid lg:grid-cols-2 gap-12"><div><SectionLabel>Evidence</SectionLabel><h2 className="text-4xl font-extrabold mb-4">It can say, “I don't know.”</h2><p className="text-nx-muted leading-relaxed">AI shouldn't have to pretend. When there isn't enough reliable information, the right answer may be: <strong className="text-nx-text">We don't know yet.</strong> Titan can investigate further rather than confidently inventing an answer.</p></div><div className="space-y-3">{known.map(x=><div key={x} className="bg-nx-surface border border-nx-border rounded-xl p-4 capitalize">{x}</div>)}</div></div></section>
<section className="py-20 px-6"><div className="max-w-6xl mx-auto"><SectionLabel>Multiple perspectives</SectionLabel><h2 className="text-4xl font-extrabold mb-4">Important decisions can get more than one opinion.</h2><p className="text-nx-muted max-w-3xl mb-8">For complex or high-consequence decisions, Titan can use multiple reasoning perspectives rather than trusting the first answer from one model.</p><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{perspectives.map(x=><div key={x} className="bg-nx-surface border border-nx-border rounded-xl p-5 capitalize">{x}</div>)}</div><div className="mt-8 bg-nx-surface border border-nx-border rounded-2xl p-7"><p className="text-lg font-bold">Are they agreeing because the evidence is strong — or because they're all looking at the same incomplete information?</p></div></div></section>
<section className="py-20 px-6 border-t border-nx-border"><div className="max-w-6xl mx-auto"><SectionLabel>Context follows One</SectionLabel><h2 className="text-4xl font-extrabold mb-5">The same business can produce different useful answers for different people.</h2><div className="grid md:grid-cols-3 gap-4"><div className="bg-nx-surface border border-nx-border rounded-2xl p-6"><h3 className="font-bold mb-2">Owner or manager</h3><p className="text-sm text-nx-muted">May need business-wide operational evidence, trade-offs, risks and decisions within their authority.</p></div><div className="bg-nx-surface border border-nx-border rounded-2xl p-6"><h3 className="font-bold mb-2">Staff member</h3><p className="text-sm text-nx-muted">May need the information, instructions and decisions relevant to their work without receiving unrelated business or personal context.</p></div><div className="bg-nx-surface border border-nx-border rounded-2xl p-6"><h3 className="font-bold mb-2">Customer</h3><p className="text-sm text-nx-muted">May need clear choices and evidence about their own services, account and relationship without exposure to internal business reasoning.</p></div></div></div></section>
<section className="py-20 px-6 border-y border-nx-border"><div className="max-w-5xl mx-auto"><h2 className="text-4xl font-extrabold mb-4">A decision is not permission.</h2><p className="text-lg text-nx-muted">Titan can prepare recommendations, alternatives, evidence, uncertainty and likely consequences. Completing that reasoning does not itself grant permission to execute. Actions still pass through the applicable risk, governance, trust and authority controls.</p></div></section>
<CTASection title="Better intelligence should produce better questions, not false certainty." subtitle="Titan investigates evidence, preserves uncertainty and keeps decisions separate from permission to act."/></>}