import SectionLabel from '../components/SectionLabel'
import CTASection from '../components/CTASection'

const steps = [
  ['Assess', 'We map your workflows, existing software, information flows, pain points and operating constraints.'],
  ['Integrate', 'We connect Titan Zero to the systems worth keeping instead of forcing a rip-and-replace migration.'],
  ['Fill the gaps', 'Where the business is missing software, interfaces or workflow capability, Titan Zero can add the extra software needed around the existing stack.'],
  ['Configure the workforce', 'We configure specialised Advanced Intelligence workers, knowledge, permissions, review points and operating rules for your business.'],
  ['Operate and improve', 'We manage, monitor, maintain and improve the system as the business, software and workflows change.'],
]
export default function ManagedSystem(){return <><section className="pt-32 pb-16 px-6 text-center"><div className="max-w-5xl mx-auto"><SectionLabel>Fully Managed</SectionLabel><h1 className="text-4xl sm:text-6xl font-extrabold mb-5">You run the business.<br/><span className="text-nx-purple-light">We manage the intelligence system.</span></h1><p className="text-lg text-nx-muted max-w-3xl mx-auto">Titan Zero is not a box of AI tools you are expected to configure yourself. We implement a managed Advanced Intelligence workforce around your business, keep the systems that already work, fill software gaps where needed, and manage the resulting system with you.</p></div></section><section className="px-6 pb-24"><div className="max-w-5xl mx-auto grid md:grid-cols-2 gap-5">{steps.map(([t,d],i)=><div key={t} className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="text-xs text-nx-purple-light font-bold mb-2">0{i+1}</div><h2 className="text-xl font-bold mb-2">{t}</h2><p className="text-sm text-nx-muted leading-relaxed">{d}</p></div>)}</div></section><CTASection title="Employ an intelligence workforce without becoming an AI engineer." subtitle="Titan Zero handles implementation, integration, configuration and ongoing management around your business."/></>}