import SectionLabel from '../components/SectionLabel'
import CTASection from '../components/CTASection'
import { appRoutes } from '../config'

const scopeFactors=[
['Operating complexity','How many workflows, teams, locations and service lines need to be coordinated.'],
['Existing systems','What should be retained, integrated, improved or replaced with Titan Zero capability.'],
['Workforce scope','The reception, operations, customer, finance, intelligence and specialist capabilities being commissioned.'],
['Integration depth','The number and complexity of authorised systems, data sources, communications and operational connections.'],
['Infrastructure & privacy','Local/private models, edge nodes, customer-hosted services and other sovereignty requirements.'],
['Specialist services','Environmental assessment, resource optimisation, formulation or other professional work included in scope.'],
]
export default function Pricing(){return <><section className="pt-32 pb-14 px-6 text-center"><div className="max-w-6xl mx-auto"><SectionLabel>Investment</SectionLabel><h1 className="text-4xl sm:text-6xl font-extrabold mb-5">A custom operating system needs <span className="text-nx-purple-light">custom pricing.</span></h1><p className="text-lg text-nx-muted max-w-3xl mx-auto">Titan Zero is not sold as a fixed software seat or agent bundle. We investigate the business, design the operating system, integrate what should stay, fill genuine software gaps and commission the workforce around the operation.</p></div></section>
<section className="px-6 pb-16"><div className="max-w-5xl mx-auto bg-nx-surface border border-nx-purple/40 rounded-2xl p-8 text-center"><SectionLabel>Budgeting guide</SectionLabel><div className="text-5xl sm:text-6xl font-black gradient-text">~1–1.5%</div><h2 className="text-2xl font-bold mt-2">of annual business revenue as an initial planning range</h2><p className="text-sm text-nx-muted max-w-3xl mx-auto mt-4">This is a ballpark guide, not a revenue-share fee or fixed formula. Actual pricing is determined by scope and complexity after assessment.</p><div className="mt-7 grid sm:grid-cols-3 gap-3 text-left"><div className="bg-nx-bg border border-nx-border rounded-xl p-4"><p className="text-xs text-nx-muted2">$1M business</p><p className="font-bold">~$830–$1,250/mo</p></div><div className="bg-nx-bg border border-nx-border rounded-xl p-4"><p className="text-xs text-nx-muted2">$3M business</p><p className="font-bold">~$2,500–$3,750/mo</p></div><div className="bg-nx-bg border border-nx-border rounded-xl p-4"><p className="text-xs text-nx-muted2">$10M business</p><p className="font-bold">~$8,300–$12,500/mo</p></div></div></div></section>
<section className="px-6 pb-20"><div className="max-w-6xl mx-auto"><div className="text-center mb-10"><SectionLabel>What determines your proposal?</SectionLabel><h2 className="text-4xl font-extrabold">We price the system we actually have to manage.</h2></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{scopeFactors.map(([t,d])=><div key={t} className="bg-nx-surface border border-nx-border rounded-2xl p-6"><h3 className="font-bold mb-2">{t}</h3><p className="text-sm text-nx-muted leading-relaxed">{d}</p></div>)}</div></div></section>
<section className="py-20 px-6 border-y border-nx-border"><div className="max-w-6xl mx-auto"><div className="text-center mb-10"><SectionLabel>Launch offer</SectionLabel><h2 className="text-4xl sm:text-5xl font-extrabold">Reduce the cost while we establish the value.</h2><p className="text-nx-muted max-w-3xl mx-auto mt-3">Eligible launch customers who accept their proposal within 15 days receive free setup plus progressive introductory pricing.</p></div><div className="grid md:grid-cols-3 gap-5"><div className="bg-nx-surface border border-nx-purple/40 rounded-2xl p-7"><div className="text-xs font-bold text-nx-purple-light">MONTHS 1–3</div><div className="text-4xl font-black mt-2">50%</div><p className="text-sm text-nx-muted mt-2">of the agreed normal monthly management fee.</p></div><div className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="text-xs font-bold text-nx-purple-light">MONTHS 4–6</div><div className="text-4xl font-black mt-2">75%</div><p className="text-sm text-nx-muted mt-2">of the agreed normal monthly management fee.</p></div><div className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="text-xs font-bold text-nx-purple-light">MONTH 7+</div><div className="text-4xl font-black mt-2">100%</div><p className="text-sm text-nx-muted mt-2">normal agreed rate once the commissioning period is complete.</p></div></div><div className="mt-5 bg-nx-surface border border-nx-border rounded-2xl p-6 text-center"><strong className="text-nx-green">Setup: FREE under the launch offer.</strong><p className="text-xs text-nx-muted mt-2">Eligibility, scope, introductory rates, exit terms and any third-party costs are documented in the customer proposal and agreement.</p></div></div></section>
<section className="py-20 px-6"><div className="max-w-5xl mx-auto text-center"><SectionLabel>Measured value</SectionLabel><h2 className="text-3xl font-extrabold mb-4">The estimate starts the conversation. Measurement determines the result.</h2><p className="text-nx-muted">Titan Zero establishes an operating baseline and measures actual outcomes across revenue, cost, recovered time, cash and resources. Opportunity percentages and budgeting examples are estimates rather than guaranteed savings or returns.</p></div></section>
<CTASection title="Get a scoped Titan Zero proposal." subtitle="We assess the operation first, then define the system, expected opportunity and investment around the business." buttonText="Sign Up" buttonHref={appRoutes.signup} showDemo={false}/></>}