import SectionLabel from '../components/SectionLabel'
import CTASection from '../components/CTASection'
import { appRoutes } from '../config'

const tiers=[
{tier:'Tier 1',name:'Solo / Small',revenue:'$400k–$1.5M annual revenue',full:'$1,600–$2,500/mo',offer:'$800–$1,250/mo',setup:'Normally $6,000',opportunity:'Indicative value opportunity: $70k–$100k'},
{tier:'Tier 2',name:'Growing Operations',revenue:'$1.5M–$5M annual revenue',full:'$5,000–$7,000/mo',offer:'$2,500–$3,500/mo',setup:'Normally $12,000',opportunity:'Indicative value opportunity: $300k–$400k'},
{tier:'Tier 3',name:'Established Operations',revenue:'$5M–$20M annual revenue',full:'$12,000–$18,000/mo',offer:'$6,000–$9,000/mo',setup:'Normally $18,000',opportunity:'Indicative value opportunity: $750k–$1.1M'},
{tier:'Tier 4',name:'Enterprise',revenue:'$20M–$100M+ annual revenue',full:'$30,000–$50,000/mo',offer:'$15,000–$25,000/mo',setup:'Normally $25,000',opportunity:'Indicative value opportunity: $2M–$6M'},
]
const included=['Managed Advanced Intelligence workforce','Discovery and operating-system assessment','Existing-system integration','Titan Zero software to fill agreed gaps','Configured governance and authority controls','Monthly value measurement across revenue, cost, time, cash and resources','Privacy/locality architecture options','Environmental and resource intelligence']
export default function Pricing(){return <><section className="pt-32 pb-14 px-6 text-center"><div className="max-w-6xl mx-auto"><SectionLabel>Launch Offer & Pricing</SectionLabel><div className="inline-block mb-5 bg-nx-purple-glow border border-nx-purple/30 rounded-full px-5 py-2 text-sm font-bold text-nx-purple-light">Launch offer · sign up within 15 days of joining</div><h1 className="text-4xl sm:text-6xl font-extrabold mb-5"><span className="text-nx-purple-light">Free setup.</span><br/>50% off the ongoing monthly fee.</h1><p className="text-lg text-nx-muted max-w-3xl mx-auto">For eligible launch customers who sign up within 15 days of joining the program, Titan Zero waives the standard setup fee and discounts the ongoing monthly management fee by 50%. The offer is documented in the customer agreement before work begins.</p></div></section>
<section className="px-6 pb-16"><div className="max-w-6xl mx-auto bg-nx-surface border border-nx-purple/40 rounded-2xl p-7"><div className="grid md:grid-cols-3 gap-6 text-center"><div><div className="text-3xl font-black">FREE</div><p className="text-sm text-nx-muted mt-1">setup under launch offer</p></div><div><div className="text-3xl font-black">50% OFF</div><p className="text-sm text-nx-muted mt-1">ongoing monthly management fee</p></div><div><div className="text-3xl font-black">15 DAYS</div><p className="text-sm text-nx-muted mt-1">to accept after joining</p></div></div></div></section>
<section className="px-6 pb-24"><div className="max-w-7xl mx-auto"><div className="text-center mb-10"><SectionLabel>Business-size pricing</SectionLabel><h2 className="text-4xl font-extrabold">Launch pricing by operating scale.</h2><p className="text-sm text-nx-muted max-w-3xl mx-auto mt-3">Ranges provide an initial guide. Final scope depends on complexity, integrations, workforce configuration, infrastructure and agreed software gaps.</p></div><div className="grid md:grid-cols-2 gap-5">{tiers.map(t=><div key={t.tier} className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="text-xs font-bold text-nx-purple-light">{t.tier}</div><h3 className="text-2xl font-bold mt-1">{t.name}</h3><p className="text-sm text-nx-muted mb-6">{t.revenue}</p><div className="grid sm:grid-cols-2 gap-4"><div className="bg-nx-bg border border-nx-border rounded-xl p-4"><p className="text-xs text-nx-muted2">Standard ongoing rate</p><p className="font-bold mt-1">{t.full}</p></div><div className="bg-nx-bg border border-nx-purple/40 rounded-xl p-4"><p className="text-xs text-nx-purple-light">15-day launch offer</p><p className="font-bold mt-1">{t.offer}</p></div></div><p className="text-sm mt-5"><span className="line-through text-nx-muted2">{t.setup}</span> <strong className="text-nx-green">→ Free setup</strong></p><p className="text-xs text-nx-muted mt-3">{t.opportunity} — planning estimate only; actual measured value varies by business.</p></div>)}</div></div></section>
<section className="py-20 px-6 border-y border-nx-border"><div className="max-w-7xl mx-auto"><div className="text-center mb-10"><SectionLabel>Included</SectionLabel><h2 className="text-4xl font-extrabold">The fee is for a managed operating system, not another login.</h2></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{included.map(x=><div key={x} className="bg-nx-surface border border-nx-border rounded-xl p-5 text-sm">{x}</div>)}</div></div></section>
<section className="py-20 px-6"><div className="max-w-6xl mx-auto grid lg:grid-cols-2 gap-6"><div className="bg-nx-surface border border-nx-border rounded-2xl p-7"><SectionLabel>Value measurement</SectionLabel><h2 className="text-2xl font-bold mb-3">Measure before making stronger claims.</h2><p className="text-sm text-nx-muted leading-relaxed">Titan Zero establishes a baseline and reports measured value across revenue creation, cost reduction, recovered time, accelerated cash and resource/environmental improvement. Indicative opportunity ranges are estimates, not guaranteed customer returns.</p></div><div className="bg-nx-surface border border-nx-border rounded-2xl p-7"><SectionLabel>Ownership & third-party costs</SectionLabel><h2 className="text-2xl font-bold mb-3">Keep control of the underlying system.</h2><p className="text-sm text-nx-muted leading-relaxed">Customer data and customer-controlled infrastructure remain under the agreed ownership model. BYO provider/API keys, private/local models and customer-controlled compute can be used where supported. Third-party communications, payments, cloud, model or other usage charges depend on the selected services and are not represented here as universally free.</p></div></div></section>
<CTASection title="Join the launch offer." subtitle="Eligible customers who sign up within 15 days receive free setup and 50% off the ongoing monthly management fee." buttonText="Sign Up" buttonHref={appRoutes.signup} showDemo={false}/></>}