import SectionLabel from '../components/SectionLabel'
import CTASection from '../components/CTASection'
import { appRoutes } from '../config'

const scopeFactors=[
['Operating complexity','How many workflows, teams, locations and service lines need to be coordinated.'],
['Existing systems','What should be retained, integrated, improved or replaced with Titan Zero capability.'],
['Your Zero & workforce scope','The working intelligence, reception, operations, customer, finance, intelligence and specialist capabilities being commissioned.'],
['Integration depth','The number and complexity of authorised systems, data sources, communications and operational connections.'],
['Infrastructure & privacy','Private knowledge, local models, distributed runtime nodes, customer-hosted services and other sovereignty requirements.'],
['Specialist services','Environmental assessment, resource optimisation, formulation or other professional work included in scope.'],
]
export default function Pricing(){return <><section className="pt-32 pb-14 px-6 text-center"><div className="max-w-6xl mx-auto"><SectionLabel>Investment</SectionLabel><h1 className="text-4xl sm:text-6xl font-extrabold mb-5">A custom operating system needs <span className="text-nx-purple-light">custom pricing.</span></h1><p className="text-lg text-nx-muted max-w-3xl mx-auto">Titan Zero is not sold as a fixed software seat or agent bundle. We investigate the business, implement Your Zero, connect what should stay, fill genuine capability gaps, configure the specialist team and manage the intelligence system around the operation.</p></div></section>
<section className="px-6 pb-16"><div className="max-w-6xl mx-auto"><div className="text-center mb-10"><SectionLabel>Example systems</SectionLabel><h2 className="text-4xl font-extrabold">What might a Titan Zero engagement look like?</h2><p className="text-sm text-nx-muted max-w-3xl mx-auto mt-3">These examples show indicative system scope and monthly management pricing. They are examples only — the actual proposal is built after we assess the business.</p></div><div className="grid lg:grid-cols-3 gap-5">
{[
{business:'Local cleaning business',detail:'~$400k annual revenue · owner + small field team',price:'$400–$500 / month',services:['Business, role & workflow discovery','Your Zero and private business knowledge setup','Reception and missed-enquiry follow-up','Booking and recurring-service support','Customer reminders and rebooking','Quote and admin workflow support','Private business knowledge setup','Monthly value and resource report']},
{business:'Growing cleaning operation',detail:'~$1M annual revenue · multiple crews and recurring accounts',price:'$850–$1,250 / month',services:['Operations, systems and Zero discovery','Your Zero and managed specialist team','Reception, lead qualification and follow-up','Scheduling and team coordination','Quote, invoice and collection workflows','Customer retention and reactivation','Inventory and procurement intelligence','Environmental/resource assessment','Monthly value measurement']},
{business:'Established service company',detail:'~$5M annual revenue · multi-team operation with several systems',price:'$4,000–$6,000 / month',services:['Full business and intelligence-system investigation','Your Zero and specialist workforce configuration','Multi-system integration and gap analysis','Managed reception and operations workforce','Scheduling, field and customer coordination','Finance/admin workflow automation','Private/local intelligence architecture','Environmental and resource optimisation','Governance, measurement and ongoing improvement']}
].map(x=><div key={x.business} className="bg-nx-surface border border-nx-border rounded-2xl p-7 flex flex-col"><div><h3 className="text-xl font-bold">{x.business}</h3><p className="text-xs text-nx-muted mt-1 mb-5">{x.detail}</p><div className="text-3xl font-black text-nx-purple-light mb-1">{x.price}</div><p className="text-xs text-nx-muted2 mb-6">indicative ongoing management</p></div><div className="space-y-3 flex-1">{x.services.map(s=><p key={s} className="text-sm text-nx-muted">✓ {s}</p>)}</div></div>)}
</div><p className="text-xs text-nx-muted text-center mt-5">Illustrative Australian-dollar pricing. Complexity, locations, integration requirements, infrastructure and specialist services can move the final proposal above or below these examples.</p></div></section>
<section className="px-6 pb-20"><div className="max-w-6xl mx-auto"><div className="text-center mb-10"><SectionLabel>What determines your proposal?</SectionLabel><h2 className="text-4xl font-extrabold">We price the system we actually have to manage.</h2></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{scopeFactors.map(([t,d])=><div key={t} className="bg-nx-surface border border-nx-border rounded-2xl p-6"><h3 className="font-bold mb-2">{t}</h3><p className="text-sm text-nx-muted leading-relaxed">{d}</p></div>)}</div></div></section>
<section className="py-20 px-6 border-y border-nx-border"><div className="max-w-6xl mx-auto"><div className="text-center mb-10"><SectionLabel>Launch offer</SectionLabel><h2 className="text-4xl sm:text-5xl font-extrabold">Reduce the cost while we establish the value.</h2><p className="text-nx-muted max-w-3xl mx-auto mt-3">Eligible launch customers who accept their proposal within 15 days receive free setup plus progressive introductory pricing.</p></div><div className="grid md:grid-cols-3 gap-5"><div className="bg-nx-surface border border-nx-purple/40 rounded-2xl p-7"><div className="text-xs font-bold text-nx-purple-light">MONTHS 1–3</div><div className="text-4xl font-black mt-2">50%</div><p className="text-sm text-nx-muted mt-2">of the agreed normal monthly management fee.</p></div><div className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="text-xs font-bold text-nx-purple-light">MONTHS 4–6</div><div className="text-4xl font-black mt-2">75%</div><p className="text-sm text-nx-muted mt-2">of the agreed normal monthly management fee.</p></div><div className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="text-xs font-bold text-nx-purple-light">MONTH 7+</div><div className="text-4xl font-black mt-2">100%</div><p className="text-sm text-nx-muted mt-2">normal agreed rate once the commissioning period is complete.</p></div></div><div className="mt-5 bg-nx-surface border border-nx-border rounded-2xl p-6 text-center"><strong className="text-nx-green">Setup: FREE under the launch offer.</strong><p className="text-xs text-nx-muted mt-2">Eligibility, scope, introductory rates, exit terms and any third-party costs are documented in the customer proposal and agreement.</p></div></div></section>
<section className="py-20 px-6"><div className="max-w-5xl mx-auto text-center"><SectionLabel>Measured value</SectionLabel><h2 className="text-3xl font-extrabold mb-4">The estimate starts the conversation. Measurement determines the result.</h2><p className="text-nx-muted">Titan Zero establishes an operating baseline and measures actual outcomes across revenue, cost, recovered time, cash and resources. Opportunity percentages and budgeting examples are estimates rather than guaranteed savings or returns.</p></div></section>
<CTASection title="Get a scoped Titan Zero proposal." subtitle="We assess the operation first, then define Your Zero, the specialist team, integrations, expected opportunity and investment around the business." buttonText="Sign Up" buttonHref={appRoutes.signup} showDemo={false}/></>}