import SectionLabel from '../components/SectionLabel'
import CTASection from '../components/CTASection'

const understands=['how your business works',"what you're responsible for",'how you like things done','what matters to you','your customers','your team','your systems','your processes','your priorities','your decisions','what has worked before',"what hasn't",'what needs your attention right now']
const learns=['the decisions you make','the corrections you give it','the outcomes of previous work','changes in your business','the systems you use','the knowledge you provide','the results the business actually achieves']

export default function YourZero(){return <><section className="pt-32 pb-20 px-6 text-center"><div className="max-w-5xl mx-auto"><SectionLabel>Meet Your Zero</SectionLabel><h1 className="text-4xl sm:text-6xl font-extrabold mb-5">Your business. <span className="text-nx-purple-light">Your Zero.</span> Your team.</h1><p className="text-xl text-nx-muted max-w-3xl mx-auto">Titan Zero gives you a digital working intelligence that learns your business, works alongside you and coordinates an AI workforce to help run it.</p><p className="mt-6 font-bold">One + Zero + Team.</p></div></section>
<section className="py-20 px-6 border-y border-nx-border"><div className="max-w-6xl mx-auto grid lg:grid-cols-2 gap-12"><div><h2 className="text-4xl font-extrabold mb-5">Imagine having someone beside you who increasingly understands your business.</h2><p className="text-nx-muted leading-relaxed">You are <strong className="text-nx-text">One</strong>. Zero is your digital working intelligence. Behind Zero can be an entire team of specialist capabilities working for your business.</p></div><div className="grid sm:grid-cols-2 gap-3">{understands.map(x=><div key={x} className="bg-nx-surface border border-nx-border rounded-xl p-4 text-sm">{x}</div>)}</div></div></section>
<section className="py-20 px-6"><div className="max-w-6xl mx-auto"><SectionLabel>More than a chatbot</SectionLabel><h2 className="text-4xl font-extrabold mb-5">The goal is to give you less to operate yourself.</h2><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{[['Before you start working','Identify what needs attention.'],["While you're working",'Find information, prepare decisions and help complete tasks.'],['Around your work','Coordinate systems and specialist capabilities.'],['For you','Handle appropriate work where you have chosen to delegate authority.']].map(([t,d])=><div key={t} className="bg-nx-surface border border-nx-border rounded-2xl p-6"><h3 className="font-bold mb-2">{t}</h3><p className="text-sm text-nx-muted">{d}</p></div>)}</div></div></section>
<section className="py-20 px-6 border-y border-nx-border"><div className="max-w-6xl mx-auto grid lg:grid-cols-2 gap-12"><div><SectionLabel>Continuous understanding</SectionLabel><h2 className="text-4xl font-extrabold mb-4">Your Zero gets better by working with you.</h2><p className="text-nx-muted leading-relaxed mb-5">Titan Zero isn't designed around one giant setup questionnaire that becomes outdated. Your business, customers, staff, systems, priorities and responsibilities change, so Zero keeps learning.</p><p className="text-nx-muted leading-relaxed">Over time, Zero should need less explanation because it develops more context. That accumulated understanding becomes part of the value of your Titan Zero system.</p></div><div className="space-y-3">{learns.map(x=><div key={x} className="bg-nx-surface border border-nx-border rounded-xl p-4 text-sm">{x}</div>)}</div></div></section>
<section className="py-20 px-6"><div className="max-w-5xl mx-auto"><SectionLabel>Experience</SectionLabel><h2 className="text-4xl font-extrabold mb-5">It learns outcomes, not just habits.</h2><p className="text-lg text-nx-muted mb-8">If you normally solve a problem one way but it consistently produces poor results, Zero shouldn't simply learn that as the right way to work. Titan can compare what we knew, what we decided, what we did, what we expected and what actually happened.</p><div className="bg-nx-surface border border-nx-border rounded-2xl p-8 text-center font-bold text-lg">What we knew → what we decided → what we did → what we expected → what actually happened.</div><h3 className="text-2xl font-bold mt-10 mb-3">Correct Zero and it learns.</h3><p className="text-nx-muted">When Zero gets something wrong, your correction can become evidence that improves its understanding. If circumstances later change, Titan can reassess what it previously learned rather than assuming every old rule remains true forever.</p></div></section>
<section className="py-20 px-6 border-y border-nx-border"><div className="max-w-5xl mx-auto text-center"><SectionLabel>Human authority</SectionLabel><h2 className="text-4xl font-extrabold mb-5">Zero can become more capable without silently becoming more powerful.</h2><p className="text-lg text-nx-muted mb-7">Learning is not authority. Confidence is not authority. Prediction is not authority. Being right before is not authority. Titan separates how intelligent Zero becomes from what Zero is allowed to do.</p><p className="text-2xl font-bold">You remain One.</p></div></section>
<CTASection title="You are One. This is your Zero." subtitle="We implement your Zero, build the team around it and manage the intelligence. You run your business."/></>}