export type StandardKind="STANDARD"|"POLICY"|"SOP"|"REQUIREMENT";
export type StandardStatus="DRAFT"|"REVIEW"|"APPROVED"|"EFFECTIVE"|"SUPERSEDED"|"RETIRED";
export type CredentialStatus="DECLARED"|"EVIDENCE_SUBMITTED"|"PENDING_VERIFICATION"|"VERIFIED"|"REJECTED"|"EXPIRING"|"EXPIRED"|"SUSPENDED"|"REVOKED";
export type StandardRecord=Readonly<{standard_id:string;company_id:string;kind:StandardKind;title:string;version:number;status:StandardStatus;effective_from?:string;effective_until?:string;applies_to:Readonly<{roles?:readonly string[];capabilities?:readonly string[];locations?:readonly string[];jurisdiction?:string}>;source_refs:readonly string[];evidence_refs:readonly string[];provenance_ref:string;authorityGranted:false}>;
export type TrainingRequirement=Readonly<{requirement_id:string;company_id:string;standard_id:string;role?:string;capability?:string;validity_days?:number;assessment_required:boolean;evidence_refs:readonly string[];authorityGranted:false}>;
export type CredentialRecord=Readonly<{credential_id:string;company_id:string;subject_id:string;credential_type:string;issuer:string;effective_at:string;expires_at?:string;status:CredentialStatus;evidence_refs:readonly string[];verification_ref?:string;provenance_ref:string;authorityGranted:false}>;
export type StandardDeviation=Readonly<{deviation_id:string;company_id:string;standard_id:string;reason:string;decision:"REQUESTED"|"APPROVED"|"REJECTED"|"EXPIRED";expires_at?:string;evidence_refs:readonly string[];provenance_ref:string;authorityGranted:false}>;
function req(v:string,n:string){if(!v.trim())throw new Error(`${n}-required`)}
function company(v:string){req(v,"company_id")}
export function createStandard(input:Omit<StandardRecord,"version"|"status"|"authorityGranted">):StandardRecord{company(input.company_id);req(input.standard_id,"standard_id");req(input.provenance_ref,"provenance_ref");if(!input.source_refs.length)throw new Error("source-ref-required");return Object.freeze({...input,version:1,status:"DRAFT" as const,authorityGranted:false as const})}
export function transitionStandard(record:StandardRecord,status:StandardStatus,effective_from?:string):StandardRecord{const allowed:Record<StandardStatus,StandardStatus[]>={DRAFT:["REVIEW","RETIRED"],REVIEW:["APPROVED","DRAFT"],APPROVED:["EFFECTIVE","RETIRED"],EFFECTIVE:["SUPERSEDED","RETIRED"],SUPERSEDED:["RETIRED"],RETIRED:[]};if(!allowed[record.status].includes(status))throw new Error("standard-transition-invalid");if(status==="EFFECTIVE"&&!effective_from)throw new Error("effective-date-required");return Object.freeze({...record,status,version:record.version+1,effective_from:effective_from??record.effective_from})}
export function resolveEffectiveStandard(records:readonly StandardRecord[],company_id:string,at:string):StandardRecord{company(company_id);const time=Date.parse(at);const candidates=records.filter(r=>r.company_id===company_id&&r.status==="EFFECTIVE"&&(!r.effective_from||Date.parse(r.effective_from)<=time)&&(!r.effective_until||Date.parse(r.effective_until)>=time)).sort((a,b)=>b.version-a.version);if(!candidates[0])throw new Error("effective-standard-not-found");return candidates[0]}
export function createTrainingRequirement(input:Omit<TrainingRequirement,"authorityGranted">):TrainingRequirement{company(input.company_id);req(input.standard_id,"standard_id");return Object.freeze({...input,authorityGranted:false as const})}
export function projectCredentialStatus(record:CredentialRecord,now:string):CredentialStatus{if(record.status!=="VERIFIED")return record.status;if(!record.expires_at)return record.status;const remaining=Date.parse(record.expires_at)-Date.parse(now);return remaining<0?"EXPIRED":remaining<30*86400000?"EXPIRING":"VERIFIED"}
export function createDeviation(input:Omit<StandardDeviation,"authorityGranted">):StandardDeviation{company(input.company_id);req(input.reason,"deviation-reason");req(input.provenance_ref,"provenance_ref");return Object.freeze({...input,authorityGranted:false as const})}
