export type ConnectorHealth="UNKNOWN"|"HEALTHY"|"DEGRADED"|"UNAVAILABLE"|"REVOKED";
export type ConnectorState="REGISTERED"|"ACTIVE"|"PAUSED"|"RECOVERING"|"RETIRED";
export type Connector=Readonly<{connector_id:string;company_id:string;provider:string;capability_ids:readonly string[];credential_ref:string;health:ConnectorHealth;state:ConnectorState;revision:number;authorityGranted:false}>;
export type ConnectorReceipt=Readonly<{receipt_id:string;connector_id:string;company_id:string;capability_id:string;status:"ACCEPTED"|"REJECTED"|"DEGRADED";idempotency_key:string;provider_ref?:string;authorityGranted:false}>;
function req(v:string,n:string){if(!v.trim())throw new Error(`${n}-required`)}
export function registerConnector(input:Omit<Connector,"health"|"state"|"revision"|"authorityGranted">):Connector{req(input.connector_id,"connector_id");req(input.company_id,"company_id");req(input.provider,"provider");req(input.credential_ref,"credential_ref");if(!input.capability_ids.length)throw new Error("capability-required");return Object.freeze({...input,health:"UNKNOWN" as const,state:"REGISTERED" as const,revision:1,authorityGranted:false as const})}
export function activateConnector(connector:Connector,health:ConnectorHealth):Connector{if(connector.state!=="REGISTERED"&&connector.state!=="RECOVERING")throw new Error("connector-activation-invalid");if(health!=="HEALTHY"&&health!=="DEGRADED")throw new Error("connector-health-invalid");return Object.freeze({...connector,state:"ACTIVE" as const,health,revision:connector.revision+1})}
export function issueConnectorReceipt(connector:Connector,company_id:string,capability_id:string,idempotency_key:string,status:ConnectorReceipt["status"],provider_ref?:string):ConnectorReceipt{req(company_id,"company_id");req(capability_id,"capability_id");req(idempotency_key,"idempotency_key");if(company_id!==connector.company_id||!connector.capability_ids.includes(capability_id))throw new Error("connector-capability-denied");if(connector.state!=="ACTIVE")throw new Error("connector-not-active");return Object.freeze({receipt_id:`${connector.connector_id}:${idempotency_key}`,connector_id:connector.connector_id,company_id:connector.company_id,capability_id,status,idempotency_key,provider_ref,authorityGranted:false as const})}

