export type FoundryArtifact={schema:"titan.foundry-artifact.v1";artifact_id:string;company_id:string;source_ref:string;source_hash:string;artifact_hash:string;version:number;state:"preview"|"verified"|"published"|"retired";deployment_ref:string|null;rollback_artifact_id:string|null;created_at:string};
const req=(v:unknown,n:string)=>{const x=String(v??"").trim();if(!x)throw new Error(`${n}-required`);return x;};
export function createFoundryArtifact(input:{artifact_id:string;company_id:string;source_ref:string;source_hash:string;artifact_hash:string;version:number;state?:FoundryArtifact["state"];deployment_ref?:string|null;rollback_artifact_id?:string|null;created_at?:string}):FoundryArtifact{
 const created_at=input.created_at??new Date().toISOString(); if(!Number.isFinite(Date.parse(created_at)))throw new Error("created_at-invalid"); if(!Number.isInteger(input.version)||input.version<1)throw new Error("version-invalid"); const state=input.state??"preview";
 if(state==="published"&&(!input.deployment_ref||!input.rollback_artifact_id))throw new Error("published-artifact-provenance-required");
 return Object.freeze({schema:"titan.foundry-artifact.v1",artifact_id:req(input.artifact_id,"artifact_id"),company_id:req(input.company_id,"company_id"),source_ref:req(input.source_ref,"source_ref"),source_hash:req(input.source_hash,"source_hash"),artifact_hash:req(input.artifact_hash,"artifact_hash"),version:input.version,state,deployment_ref:input.deployment_ref??null,rollback_artifact_id:input.rollback_artifact_id??null,created_at});
}
export function verifyFoundryArtifact(artifact:FoundryArtifact,input:{company_id:string;source_hash:string;artifact_hash:string}):FoundryArtifact{if(artifact.company_id!==req(input.company_id,"company_id"))throw new Error("artifact-company-mismatch");if(artifact.source_hash!==req(input.source_hash,"source_hash"))throw new Error("source-hash-mismatch");if(artifact.artifact_hash!==req(input.artifact_hash,"artifact_hash"))throw new Error("artifact-hash-mismatch");return Object.freeze({...artifact,state:"verified"});}
export function assertFoundryRollback(artifact:FoundryArtifact,rollback:FoundryArtifact){if(artifact.company_id!==rollback.company_id)throw new Error("rollback-company-mismatch");if(artifact.rollback_artifact_id!==rollback.artifact_id)throw new Error("rollback-target-mismatch");if(rollback.state!=="published")throw new Error("rollback-target-not-published");return true;}
