// @ts-nocheck
// Ported from Titan Zero extension (portable-core): titan-workforce/starter-agents/booking/booking-hold-service.mjs
import {assertFreshSlot} from './availability-service.js';
const text=(v,n)=>{const s=String(v??'').trim();if(!s)throw new Error(`${n}-required`);return s};
export class MemoryBookingHoldStore{constructor(){this.map=new Map()} key(c,h){return `${c}::${h}`} async get(c,h){return this.map.get(this.key(c,h))??null} async compareAndSet(c,h,expectedRevision,next){const k=this.key(c,h),cur=this.map.get(k)??null,rev=cur?.revision??0;if(rev!==expectedRevision)return false;this.map.set(k,Object.freeze({...next,revision:rev+1}));return true}}
export async function createBookingHold(input={},ports={}){
 const store=ports.store;if(!store?.compareAndSet)throw new Error('booking-hold-store-required');const company_id=text(input.company_id,'company-id');const hold_id=text(input.hold_id,'hold-id');const proposal_id=text(input.proposal_id,'proposal-id');const slot=assertFreshSlot(input.slot,input.now);if(slot.company_id!==company_id)throw new Error('cross-company-slot-denied');const expires_at=new Date(Math.min(Date.parse(slot.expires_at),Date.parse(input.expires_at??slot.expires_at))).toISOString();const hold={schema:'titan.booking.hold.v1',company_id,hold_id,proposal_id,provider_slot_id:slot.provider_slot_id,provider_revision:slot.provider_revision,state:'held',expires_at,correlation_id:text(input.correlation_id,'correlation-id'),grants_authority:false,direct_mutation:false};const ok=await store.compareAndSet(company_id,hold_id,0,hold);if(!ok)return{ok:false,state:'conflict',reason:'hold-already-exists'};return{ok:true,hold:await store.get(company_id,hold_id)}}
export async function acceptBookingHold(input={},ports={}){const store=ports.store;if(!store?.get||!store?.compareAndSet)throw new Error('booking-hold-store-required');const c=text(input.company_id,'company-id'),h=text(input.hold_id,'hold-id'),cur=await store.get(c,h);if(!cur)return{ok:false,state:'conflict',reason:'hold-not-found'};if(Date.parse(cur.expires_at)<=Date.parse(input.now??new Date().toISOString()))return{ok:false,state:'expired',reason:'hold-expired'};if(cur.state!=='held')return{ok:false,state:'conflict',reason:`hold-state-${cur.state}`};const next={...cur,state:'accepted',accepted_at:input.now??new Date().toISOString()};const ok=await store.compareAndSet(c,h,cur.revision,next);return ok?{ok:true,hold:await store.get(c,h)}:{ok:false,state:'conflict',reason:'hold-revision-conflict'}}
export async function expireBookingHold(input={},ports={}){const store=ports.store;const c=text(input.company_id,'company-id'),h=text(input.hold_id,'hold-id'),cur=await store.get(c,h);if(!cur)return{ok:false,state:'missing'};if(cur.state!=='held')return{ok:false,state:cur.state};const now=input.now??new Date().toISOString();if(Date.parse(cur.expires_at)>Date.parse(now))return{ok:false,state:'not_expired'};const ok=await store.compareAndSet(c,h,cur.revision,{...cur,state:'expired',expired_at:now});return{ok,state:ok?'expired':'conflict'}}
