// @ts-nocheck
// Ported from Titan Zero extension (portable-core): titan-workforce/starter-agents/booking/booking-confirmation-service.mjs
const text=(v,n)=>{const s=String(v??'').trim();if(!s)throw new Error(`${n}-required`);return s};
export class MemoryBookingOperationStore{constructor(){this.map=new Map()}key(c,k){return `${c}::${k}`}async get(c,k){return this.map.get(this.key(c,k))??null}async putIfAbsent(c,k,v){const x=this.key(c,k);if(this.map.has(x))return false;this.map.set(x,Object.freeze({...v}));return true}async update(c,k,v){const x=this.key(c,k);if(!this.map.has(x))throw new Error('operation-not-found');this.map.set(x,Object.freeze({...v}));return this.map.get(x)}}
export async function confirmBooking(input={},ports={}){
 const company_id=text(input.company_id,'company-id'),idempotency_key=text(input.idempotency_key,'idempotency-key'),intent_id=text(input.intent_id,'intent-id'),correlation_id=text(input.correlation_id,'correlation-id');const store=ports.operationStore;if(!store?.get||!store?.putIfAbsent||!store?.update)throw new Error('booking-operation-store-required');
 const prior=await store.get(company_id,idempotency_key);if(prior?.state==='completed')return Object.freeze({ok:true,state:'confirmed',replayed:true,booking_ref:prior.booking_ref,receipt_id:prior.receipt_id});if(prior&&['dispatching','delivery_unknown'].includes(prior.state))return Object.freeze({ok:false,state:'delivery_unknown',reason:'reconcile_before_retry',replayed:true});
 if(input.hold?.company_id!==company_id||input.hold?.state!=='accepted')throw new Error('accepted-company-hold-required');if(typeof ports.revalidateSlot!=='function'||typeof ports.executeGoverned!=='function'||typeof ports.verifyBooking!=='function')throw new Error('booking-confirmation-ports-required');
 const current=await ports.revalidateSlot({company_id,hold:input.hold,correlation_id});if(!current?.ok)return Object.freeze({ok:false,state:'conflict',reason:current?.reason??'slot_revalidation_failed'});
 const operation={schema:'titan.booking.operation.v1',company_id,idempotency_key,intent_id,correlation_id,state:'dispatching',provider_slot_id:input.hold.provider_slot_id,provider_revision:input.hold.provider_revision,grants_authority:false,automatic_effect_replay:false};if(!await store.putIfAbsent(company_id,idempotency_key,operation))return confirmBooking(input,ports);
 let receipt;try{receipt=await ports.executeGoverned({company_id,capability:'crm.appointment.create',idempotency_key,correlation_id,intent_id,provider_slot_id:input.hold.provider_slot_id,provider_revision:input.hold.provider_revision,requires_authority_decision:true,requires_authoritative_receipt:true});}catch(e){await store.update(company_id,idempotency_key,{...operation,state:'delivery_unknown',error:String(e?.message??e)});return Object.freeze({ok:false,state:'delivery_unknown',reason:'execution_uncertain'});}
 if(!receipt?.ok||!receipt.receipt_id||String(receipt.company_id??company_id)!==company_id||String(receipt.idempotency_key??idempotency_key)!==idempotency_key){await store.update(company_id,idempotency_key,{...operation,state:'delivery_unknown',receipt:receipt??null});return Object.freeze({ok:false,state:'delivery_unknown',reason:'invalid_or_missing_receipt'});}
 const verified=await ports.verifyBooking({company_id,intent_id,correlation_id,idempotency_key,receipt});if(!verified?.ok||!verified.booking_ref){await store.update(company_id,idempotency_key,{...operation,state:'verification_failed',receipt_id:receipt.receipt_id});return Object.freeze({ok:false,state:'conflict',reason:'post_action_verification_failed'});}
 const done=await store.update(company_id,idempotency_key,{...operation,state:'completed',receipt_id:receipt.receipt_id,booking_ref:verified.booking_ref,completed_at:input.now??new Date().toISOString()});return Object.freeze({ok:true,state:'confirmed',replayed:false,booking_ref:done.booking_ref,receipt_id:done.receipt_id});
}
