import { z } from "zod";
import { titanAutonomyModes, titanCapabilities, titanTrustStates } from "./contracts";
const agentClass=z.enum(["worker","specialist","manager","orchestrator"]); const autonomyMode=z.enum(titanAutonomyModes);
const delegationNode=z.object({agent_id:z.string().min(1),class:agentClass,display_name:z.string().optional(),responsibility:z.string().optional()});
const operation=z.enum(["query","prepare","confirm","create","update","cancel","authority_status","request_autonomy","upgrade_options"]);
const uiCard=z.object({id:z.string().min(1),kind:z.enum(["customer","booking","job","quote","invoice","message","status","approval","workforce","autonomy","upgrade"]),title:z.string(),subtitle:z.string().optional(),fields:z.array(z.object({label:z.string(),value:z.string()})).optional(),actions:z.array(z.object({id:z.string(),label:z.string(),capability:z.enum(titanCapabilities),operation,payload:z.record(z.unknown()).optional()})).optional()});
const gateState=z.enum(["approved","pending","denied"]);
const authority=z.object({responsibility_scope:z.string().optional(),desired_mode:autonomyMode.optional(),earned_mode:autonomyMode.optional(),effective_mode:autonomyMode,entitlement_ceiling:autonomyMode.optional(),trust_state:z.enum(titanTrustStates).optional(),plan_locked:z.boolean().optional(),next_eligible_mode:autonomyMode.optional(),handshake:z.object({platform:gateState,user:gateState,assurance:gateState,hierarchy_gates:z.array(z.object({agent_id:z.string(),class:agentClass,state:gateState})).optional()}).optional(),reason_codes:z.array(z.string()).optional()});
export const titanReceiptSchema=z.object({receipt_id:z.string().min(1),trace_id:z.string().min(1),correlation_id:z.string().optional(),causation_id:z.string().optional(),capability:z.enum(titanCapabilities),status:z.enum(["requires_backend_binding","requires_approval","accepted","completed","rejected","plan_locked"]),authority_path:z.literal("risk>shield>governance>autonomy>command_bus"),message:z.string(),cards:z.array(uiCard).optional(),workforce:z.object({active_agent:delegationNode.optional(),delegation_chain:z.array(delegationNode).optional(),authority:authority.optional(),approval:z.object({required:z.boolean(),reason:z.string().optional(),gate_count:z.number().int().nonnegative().optional()}).optional(),outcome:z.object({status:z.enum(["pending","verified","failed","recovered"]),summary:z.string().optional(),verified:z.boolean().optional(),evidence_refs:z.array(z.string()).optional()}).optional(),execution:z.object({correlation_id:z.string().min(1),causation_id:z.string().optional(),idempotency_key:z.string().optional(),event_ids:z.array(z.string()).optional(),recovery:z.object({available:z.boolean(),rewind_ref:z.string().optional(),status:z.enum(["not_required","available","requested","completed","failed"]).optional()}).optional()}).optional()}).optional(),requires_approval:z.boolean().optional(),approval_token:z.string().optional()});
