import test from 'node:test';
import assert from 'node:assert/strict';
import {buildCleaningE2eCertification,CLEANING_VERTICAL_REFERENCE_BLUEPRINT,CLEANING_E2E_CERTIFICATION_SCHEMA} from '../.cleaning-test-dist/verticals/cleaning/blueprint.js';
import {buildCleaningLanguageProjection} from '../.cleaning-test-dist/verticals/cleaning/language.js';
import {buildCleaningCommercialRecurringContract} from '../.cleaning-test-dist/verticals/cleaning/contracts.js';

const refs={onboarding:'on-1',lead:'lead-1',quote:'q-1',booking:'b-1',schedule:'s-1',job:'j-1',evidence:'ev-1',qa:'qa-1',invoice:'i-1',payment:'p-1',rebooking:'rb-1'};
const base={company_id:'co-1',scenario:'residential',service_id:'regular_clean',refs,offline_sync_state:'SYNCED',qa_outcome:'PASS',unresolved_rework_count:0};

test('Pass10 certifies complete residential cleaning lifecycle as projection only',()=>{const r=buildCleaningE2eCertification(base);assert.equal(r.schema,CLEANING_E2E_CERTIFICATION_SCHEMA);assert.equal(r.certified,true);assert.deepEqual(r.blockers,[]);assert.equal(r.execution_permitted,false);});
test('reference blueprint covers onboarding through rebooking with shared owners',()=>{const ids=CLEANING_VERTICAL_REFERENCE_BLUEPRINT.stages.map(x=>x.id);assert.deepEqual(ids,['onboarding','lead_intake','quote','booking','recurring_schedule','workforce_assignment','job_execution','evidence','qa_rework','invoice','payment','rebooking']);assert.equal(CLEANING_VERTICAL_REFERENCE_BLUEPRINT.owner_transfer_permitted,false);});
test('missing lifecycle handoff refs fail closed',()=>{const r=buildCleaningE2eCertification({...base,refs:{...refs,payment:undefined}});assert.equal(r.certified,false);assert.ok(r.blockers.includes('MISSING_PAYMENT_REF'));});
test('cross-company stage evidence fails closed',()=>{const r=buildCleaningE2eCertification({...base,stage_company_ids:{job_execution:'co-2'}});assert.equal(r.certified,false);assert.ok(r.blockers.includes('CROSS_COMPANY:job_execution'));});
test('offline conflict blocks certification',()=>{const r=buildCleaningE2eCertification({...base,offline_sync_state:'CONFLICT'});assert.equal(r.certified,false);assert.ok(r.blockers.includes('OFFLINE_SYNC_CONFLICT'));});
test('QA rework and escalation block downstream certification readiness',()=>{const rw=buildCleaningE2eCertification({...base,qa_outcome:'REWORK_REQUIRED',unresolved_rework_count:1});assert.equal(rw.certified,false);assert.ok(rw.blockers.includes('UNRESOLVED_REWORK'));const es=buildCleaningE2eCertification({...base,qa_outcome:'ESCALATION_REQUIRED'});assert.ok(es.blockers.includes('QA_ESCALATION_REQUIRED'));});
test('commercial recurring scenario requires governed commercial contract reference',()=>{const no=buildCleaningE2eCertification({...base,scenario:'commercial',service_id:'office_clean',recurring:true});assert.ok(no.blockers.includes('COMMERCIAL_CONTRACT_REF_REQUIRED'));const contract=buildCleaningCommercialRecurringContract({company_id:'co-1',contract_ref:'c1',customer_ref:'cu1',service_id:'commercial_standard',frequency:'weekly',schedule_source_ref:'s-1',sla_window:{start:'18:00',end:'22:00'},sites:[{site_ref:'site-1'}]});const yes=buildCleaningE2eCertification({...base,scenario:'commercial',service_id:'office_clean',recurring:true,commercial_contract_ref:contract.contract_ref});assert.equal(yes.certified,true);});
test('quote language remains shared-agent hint inside certified flow',()=>{const lang=buildCleaningLanguageProjection({company_id:'co-1',message:'quote for a fortnightly office clean',service_id:'office_clean',context:{recurring:true}});assert.equal(lang.intent,'quote_request');assert.equal(lang.quote_mutation_emitted,false);const r=buildCleaningE2eCertification({...base,scenario:'commercial',service_id:'office_clean',recurring:true,commercial_contract_ref:'c1'});assert.equal(r.owners.quote,'shared_quote_agent_owner');});
test('invoice payment and rebooking remain readiness handoffs, never mutations',()=>{const r=buildCleaningE2eCertification(base);assert.equal(r.handoffs.invoice_ready,true);assert.equal(r.handoffs.payment_reconciliation_ready,true);assert.equal(r.handoffs.rebooking_context_ready,true);assert.equal(r.invoice_mutation_emitted,false);assert.equal(r.payment_mutation_emitted,false);assert.equal(r.rebooking_action_emitted,false);});
test('no stage can auto assign execute pay rebook or grant authority',()=>{const r=buildCleaningE2eCertification(base);assert.equal(r.assignment_mutation_emitted,false);assert.equal(r.job_mutation_emitted,false);assert.equal(r.booking_mutation_emitted,false);assert.equal(r.schedule_mutation_emitted,false);assert.equal(r.grants_authority,false);assert.equal(r.execution_permitted,false);assert.equal(CLEANING_VERTICAL_REFERENCE_BLUEPRINT.automatic_assignment_permitted,false);assert.equal(CLEANING_VERTICAL_REFERENCE_BLUEPRINT.automatic_payment_permitted,false);assert.equal(CLEANING_VERTICAL_REFERENCE_BLUEPRINT.automatic_rebooking_permitted,false);});
test('legacy tenant aliases and malformed numeric state fail closed',()=>{assert.throws(()=>buildCleaningE2eCertification({...base,tenant_id:'bad'}),/legacy tenant/);assert.throws(()=>buildCleaningE2eCertification({...base,unresolved_rework_count:-1}),/non-negative integer/);});
