import test from "node:test";
import assert from "node:assert/strict";
import {createMemoryStorageAdapter,createCompanyRepository} from "../.test-dist/storage/index.js";
import {createOfflineSyncCoordinator} from "../.test-dist/offline/index.js";

const ctx=(company_id="company-a")=>({company_id,actor_id:"sync",operation_id:"sync-test"});
function setup(){let now=1000;const repository=createCompanyRepository({adapter:createMemoryStorageAdapter(),clock:()=>now});const sync=createOfflineSyncCoordinator({repository,clock:()=>now});return{sync,setNow:v=>{now=v}};}

test("snapshot is company scoped and authority neutral",async()=>{const{sync}=setup();await sync.writeLocal(ctx(),{module_id:"crm",collection:"jobs",record_id:"j1",revision:1,data:{status:"open"}});const s=await sync.snapshot(ctx(),{module_id:"crm",collection:"jobs"});assert.equal(s.records.length,1);assert.equal(s.company_id,"company-a");assert.equal(s.grants_authority,false);});
test("clean local record accepts newer remote revision",async()=>{const{sync}=setup();await sync.applyPull(ctx(),{module_id:"crm",collection:"jobs",generation:1,cursor:"c1",records:[{record_id:"j1",revision:1,data:{status:"open"}}]});const r=await sync.applyPull(ctx(),{module_id:"crm",collection:"jobs",generation:2,cursor:"c2",records:[{record_id:"j1",revision:2,data:{status:"done"}}]});assert.equal(r.results[0].status,"remote_applied");});
test("dirty local plus newer remote produces explicit conflict",async()=>{const{sync}=setup();await sync.writeLocal(ctx(),{module_id:"crm",collection:"jobs",record_id:"j1",revision:2,data:{status:"local"}});const r=await sync.applyPull(ctx(),{module_id:"crm",collection:"jobs",generation:1,records:[{record_id:"j1",revision:3,data:{status:"remote"}}]});assert.equal(r.status,"conflicts");assert.equal((await sync.listConflicts(ctx())).length,1);});
test("stale remote revision never overwrites local",async()=>{const{sync}=setup();await sync.writeLocal(ctx(),{module_id:"crm",collection:"jobs",record_id:"j1",revision:5,data:{status:"local"}});const r=await sync.applyPull(ctx(),{module_id:"crm",collection:"jobs",generation:1,records:[{record_id:"j1",revision:4,data:{status:"old"}}]});assert.equal(r.results[0].status,"remote_stale");});
test("same revision divergent payload conflicts",async()=>{const{sync}=setup();await sync.applyPull(ctx(),{module_id:"crm",collection:"jobs",generation:1,records:[{record_id:"j1",revision:2,data:{status:"a"}}]});const r=await sync.applyPull(ctx(),{module_id:"crm",collection:"jobs",generation:2,records:[{record_id:"j1",revision:2,data:{status:"b"}}]});assert.equal(r.results[0].status,"conflict");});
test("older sync generation is rejected without applying records",async()=>{const{sync}=setup();await sync.applyPull(ctx(),{module_id:"crm",collection:"jobs",generation:3,cursor:"new",records:[]});const r=await sync.applyPull(ctx(),{module_id:"crm",collection:"jobs",generation:2,cursor:"old",records:[{record_id:"j1",revision:1,data:{status:"old"}}]});assert.equal(r.status,"stale_generation");const s=await sync.snapshot(ctx(),{module_id:"crm",collection:"jobs"});assert.equal(s.records.length,0);});
test("duplicate record in one pull fails closed",async()=>{const{sync}=setup();await assert.rejects(()=>sync.applyPull(ctx(),{module_id:"crm",collection:"jobs",generation:1,records:[{record_id:"j1",revision:1,data:{}},{record_id:"j1",revision:1,data:{}}]}),/duplicate remote record/);});
test("cross-company and legacy payloads fail closed",async()=>{const{sync}=setup();await assert.rejects(()=>sync.applyPull(ctx(),{company_id:"company-b",module_id:"crm",collection:"jobs",generation:1,records:[]}),/cross-company/i);await assert.rejects(()=>sync.applyPull(ctx(),{module_id:"crm",collection:"jobs",generation:1,records:[{record_id:"j1",revision:1,data:{tenant_id:"legacy"}}]}),/legacy/i);});
test("sync cursor/generation survive coordinator recreation on same repository",async()=>{const adapter=createMemoryStorageAdapter();const repository=createCompanyRepository({adapter,clock:()=>1000});const first=createOfflineSyncCoordinator({repository,clock:()=>1000});await first.applyPull(ctx(),{module_id:"crm",collection:"jobs",generation:7,cursor:"cursor-7",records:[]});const second=createOfflineSyncCoordinator({repository,clock:()=>2000});const state=await second.readState(ctx(),"crm","jobs");assert.equal(state.generation,7);assert.equal(state.cursor,"cursor-7");});
test("sync descriptor keeps local primary and server non-authoritative",()=>{const{sync}=setup();assert.equal(sync.descriptor.local_primary,true);assert.equal(sync.descriptor.server_grants_authority,false);assert.equal(sync.descriptor.identity_grants_authority,false);});
