import test from "node:test";import assert from "node:assert/strict";import{buildTitanCustomerCarePlan}from"../.test-dist/workforce-native/index.js";
test("Customer Care reads canonical customer job and invoice truth",()=>{assert.equal(buildTitanCustomerCarePlan({companyId:"c1",action:"get_customer",customerId:"cu1"}).operation.path,"/api/v1/clients/:id");assert.equal(buildTitanCustomerCarePlan({companyId:"c1",action:"get_project",projectId:"j1"}).operation.path,"/api/v1/jobs/:id");assert.equal(buildTitanCustomerCarePlan({companyId:"c1",action:"get_invoice",invoiceId:"i1"}).operation.path,"/api/v1/invoices/:id");});
test("Customer Care records service issues in canonical property issue lifecycle",()=>{const p=buildTitanCustomerCarePlan({companyId:"c1",action:"record_property_issue",propertyId:"p1",traceId:"t1",payload:{title:"Missed room",description:"Bathroom missed",severity:"major"}});assert.equal(p.operation.id,"property_issues.create");assert.equal(p.body.title,"Missed room");assert.equal(p.body.severity,"major");assert.equal(p.authority.execution_permitted,false);});
test("Customer Care resolves existing canonical service issue without inventing a case database",()=>{const p=buildTitanCustomerCarePlan({companyId:"c1",action:"resolve_property_issue",propertyId:"p1",issueId:"x1",payload:{resolved_note:"Rework completed"}});assert.equal(p.operation.id,"property_issues.update");assert.equal(p.issue_id,"x1");assert.equal(p.body.status,"resolved");});
test("Customer Care creates authority neutral case projections",()=>{const p=buildTitanCustomerCarePlan({companyId:"c1",action:"create_case_projection",customerId:"cu1",payload:{issue_class:"QUALITY",sentiment:"NEGATIVE",severity:"HIGH"}});assert.equal(p.projection.company_id,"c1");assert.equal(p.projection.state,"OPEN");assert.equal(p.projection.authority_granted,false);});
test("Customer Care triage escalates safety and privacy without granting execution",()=>{const p=buildTitanCustomerCarePlan({companyId:"c1",action:"triage_case",payload:{case_record:{customer_id:"cu1",state:"OPEN",issue_class:"SAFETY",severity:"MEDIUM"},triage:{signals:{active_safety_hazard:true}}}});assert.equal(p.projection.escalation_required,true);assert.ok(p.projection.routes.includes("governance"));assert.equal(p.projection.execution_permitted,false);});
test("Customer Care human review remains approval-only",()=>{const p=buildTitanCustomerCarePlan({companyId:"c1",actorId:"worker1",action:"create_human_review",payload:{case_record:{case_id:"case1",customer_id:"cu1",state:"TRIAGED",issue_class:"QUALITY",severity:"HIGH"},proposal:{proposal_type:"REFUND_REVIEW"}}});assert.equal(p.projection.execution_permitted,false);assert.equal(p.projection.execution_authorization_required,true);});
test("Customer Care rejects unsafe identifiers and legacy tenant aliases",()=>{assert.throws(()=>buildTitanCustomerCarePlan({companyId:"c1",action:"get_customer",customerId:"../bad"}),/customer-care-customer-id-required/);assert.throws(()=>buildTitanCustomerCarePlan({companyId:"c1",action:"create_case_projection",customerId:"cu1",payload:{tenant_id:"x"}}),/legacy-company-boundary/);});

test("Customer Care suppresses public review requests while dissatisfaction remains unresolved",()=>{const p=buildTitanCustomerCarePlan({companyId:"c1",action:"assess_review_eligibility",customerId:"cu1",projectId:"j1",payload:{case_record:{company_id:"c1",customer_id:"cu1",job_id:"j1",state:"TRIAGED",issue_class:"QUALITY",sentiment:"NEGATIVE"},customer_id:"cu1",job_id:"j1",outcome_record:{verified:true,company_id:"c1",customer_id:"cu1",job_id:"j1",status:"SATISFIED"},customer_care_cases:[{company_id:"c1",customer_id:"cu1",job_id:"j1",case_id:"case1",state:"TRIAGED",issue_class:"QUALITY",sentiment:"NEGATIVE"}],contact_preferences:{status:"GRANTED",allowed_channels:["sms"]},channel:"sms"}});assert.equal(p.projection.public.eligible,false);assert.equal(p.projection.public.status,"SUPPRESSED_DISSATISFACTION");});
test("Customer Care rejects cross-company projected records instead of rewriting them",()=>{assert.throws(()=>buildTitanCustomerCarePlan({companyId:"c1",action:"triage_case",payload:{case_record:{company_id:"c2",customer_id:"cu1",state:"OPEN",issue_class:"QUALITY",severity:"LOW"},triage:{}}}),/cross-company-customer-care-projection-rejected/);});
