"use client";
import styles from "./BuilderStudio.module.css";
type Row=Record<string,unknown>;
type Field={key:string;kind?:"text"|"select"|"number";options?:string[]};
const base:Record<string,Field[]>={items:[{key:"title"},{key:"status"},{key:"time"},{key:"assignee"},{key:"amount"}],messages:[{key:"author"},{key:"text"},{key:"direction",kind:"select",options:["inbound","outbound","system"]},{key:"status",kind:"select",options:["draft","sent","delivered","read"]},{key:"time"}],suggestions:[{key:"label"},{key:"value"}],fields:[{key:"name"},{key:"label"},{key:"type",kind:"select",options:["text","email","number","date","select","checkbox","textarea"]},{key:"hint"},{key:"required",kind:"select",options:["false","true"]}],steps:[{key:"title"},{key:"description"}],columns:[{key:"title"},{key:"status"},{key:"limit",kind:"number"}],tasks:[{key:"title"},{key:"status"},{key:"assignee"}],series:[{key:"label"},{key:"value",kind:"number"}],data:[{key:"label"},{key:"value",kind:"number"}],segments:[{key:"label"},{key:"value",kind:"number"}],options:[{key:"label"},{key:"value"}],errors:[{key:"field"},{key:"message"}],attachments:[{key:"name"},{key:"url"}]};
function objectify(v:unknown):Row[]{if(!Array.isArray(v))return [];return v.map(x=>x&&typeof x==="object"&&!Array.isArray(x)?{...(x as Row)}:{label:String(x),value:x});}
function schema(componentType:string,propKey:string):Field[]{if(propKey==="items"&&/(job|schedule|booking)/i.test(componentType))return [{key:"title"},{key:"status",kind:"select",options:["new","scheduled","en-route","active","complete","cancelled"]},{key:"time"},{key:"assignee"},{key:"customer"}];if(propKey==="series"||propKey==="data")return [{key:"label"},{key:"value",kind:"number"},{key:"series"}];return base[propKey]??[{key:"label"},{key:"value"}];}
export function StructuredPropEditor({componentType,propKey,value,onChange}:{componentType:string;propKey:string;value:unknown;onChange:(v:unknown)=>void}){
 const rows=objectify(value),fields=schema(componentType,propKey); const emit=(x:Row[])=>onChange(x);
 const set=(i:number,k:string,v:string)=>emit(rows.map((r,n)=>n===i?{...r,[k]:v}:r)); const remove=(i:number)=>emit(rows.filter((_,n)=>n!==i));
 const move=(i:number,d:number)=>{const n=i+d;if(n<0||n>=rows.length)return;const x=[...rows];[x[i],x[n]]=[x[n]!,x[i]!];emit(x)};
 const setCards=(i:number,cards:Row[])=>emit(rows.map((r,n)=>n===i?{...r,cards}:r));
 return <div className={styles.structuredEditor}>{rows.map((row,i)=><div className={styles.structuredRow} key={i}><div className={styles.structuredHeader}><strong>{propKey.replace(/s$/,'')} {i+1}</strong><span><button type="button" onClick={()=>move(i,-1)}>↑</button><button type="button" onClick={()=>move(i,1)}>↓</button><button type="button" onClick={()=>remove(i)}>×</button></span></div>{fields.map(f=><label key={f.key}>{f.key.replace(/([A-Z])/g," $1")}{f.kind==="select"?<select value={String(row[f.key]??"")} onChange={e=>set(i,f.key,e.target.value)}>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:<input type={f.kind==="number"?"number":"text"} value={String(row[f.key]??"")} onChange={e=>set(i,f.key,e.target.value)}/>}</label>)}{propKey==="columns"&&<div><strong>Cards</strong><StructuredPropEditor componentType="kanban-card" propKey="tasks" value={row.cards??[]} onChange={cards=>setCards(i,objectify(cards))}/></div>}</div>)}<button type="button" className="btn btn-sm" onClick={()=>emit([...rows,Object.fromEntries(fields.map(f=>[f.key,""]))])}>+ Add {propKey.replace(/s$/,'')}</button></div>;
}
