-- Pass 23: MySQL/MariaDB parity for immutable capture evidence.
CREATE TABLE IF NOT EXISTS capture_evidence (
  id CHAR(36) PRIMARY KEY,
  account_id CHAR(36) NOT NULL,
  created_by CHAR(36) NOT NULL,
  captured_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  source VARCHAR(32) NOT NULL,
  audio_filename VARCHAR(255) NULL,
  audio_original_name VARCHAR(255) NULL,
  audio_mime_type VARCHAR(128) NULL,
  audio_size_bytes INT NULL,
  photo_filename VARCHAR(255) NULL,
  photo_original_name VARCHAR(255) NULL,
  photo_mime_type VARCHAR(128) NULL,
  photo_size_bytes INT NULL,
  transcript LONGTEXT NULL,
  processing_state VARCHAR(32) NOT NULL DEFAULT 'pending',
  proposed_title VARCHAR(500) NULL,
  proposed_due_at DATETIME(3) NULL,
  proposed_span TEXT NULL,
  confidence VARCHAR(16) NULL,
  suggested_entity_type VARCHAR(32) NULL,
  suggested_entity_id CHAR(36) NULL,
  snoozed_at DATETIME(3) NULL,
  snooze_count INT NOT NULL DEFAULT 0,
  confirmed_at DATETIME(3) NULL,
  dismissed_at DATETIME(3) NULL,
  processing_error TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_capture_evidence_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
  CONSTRAINT fk_capture_evidence_user FOREIGN KEY (created_by) REFERENCES users(id),
  INDEX idx_capture_evidence_account_state (account_id, processing_state, captured_at),
  INDEX idx_capture_evidence_account_captured (account_id, captured_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
