-- Agent 4 Local Pass 03: portable intake invite persistence.
-- IDs/tokens and expiry are generated by application code so PostgreSQL UUID/
-- interval defaults are not required by the MySQL/MariaDB deployment.
CREATE TABLE IF NOT EXISTS intake_invites (
  id CHAR(36) NOT NULL,
  account_id CHAR(36) NOT NULL,
  booking_request_id CHAR(36) NULL,
  token CHAR(36) NOT NULL,
  lead_name VARCHAR(200) NOT NULL,
  lead_email VARCHAR(320) NOT NULL,
  lead_phone VARCHAR(50) NULL,
  expires_at DATETIME(3) NOT NULL,
  used_at DATETIME(3) NULL,
  delivery_method VARCHAR(16) NOT NULL DEFAULT 'email',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_intake_invites_token (token),
  KEY idx_intake_invites_booking (account_id, booking_request_id),
  KEY idx_intake_invites_active (token, used_at, expires_at),
  CONSTRAINT fk_intake_invites_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
  CONSTRAINT fk_intake_invites_booking FOREIGN KEY (booking_request_id) REFERENCES booking_requests(id) ON DELETE CASCADE,
  CONSTRAINT chk_intake_invites_delivery CHECK (delivery_method IN ('email','sms'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
