// @ts-nocheck
// Ported from Titan Zero extension (portable-core): titan-capabilities/contributions/registry.mjs
const LEGACY_COMPANY_KEYS=Object.freeze(['tenant_id','tenant_company_id','tenant_company','tenant','tenantCompanyId','organisation_id','organization_id','workspace_tenant_id']);
export const CONTRIBUTION_KINDS=Object.freeze(['runtime','capability','provider','presentation','visual','event','command','query','projection','adapter','observer']);
const KINDS=new Set(CONTRIBUTION_KINDS); const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const text=(v,f)=>{const x=String(v??'').trim();if(!x)throw new TypeError(`${f}-required`);return x};
const list=v=>Object.freeze([...new Set((Array.isArray(v)?v:(v==null?[]:[v])).map(x=>String(x??'').trim()).filter(Boolean))]);
function rejectLegacy(value,path='contribution'){if(!value||typeof value!=='object')return;if(Array.isArray(value)){value.forEach((x,i)=>rejectLegacy(x,`${path}[${i}]`));return;}for(const [k,v] of Object.entries(value)){if(LEGACY_COMPANY_KEYS.includes(k))throw new Error(`legacy-company-boundary:${path}.${k}`);rejectLegacy(v,`${path}.${k}`)}}
function companyId(raw,expected){const supplied=String(raw?.company_id??'').trim(),required=String(expected??'').trim();if(!supplied&&!required)throw new Error('company_id-required');if(supplied&&required&&supplied!==required)throw new Error('cross-company-contribution');return supplied||required}
export function normalizeContribution(raw,{company_id:expectedCompanyId=null}={}){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new TypeError('contribution-required');rejectLegacy(raw);const company_id=companyId(raw,expectedCompanyId);const kind=text(raw.kind,'kind').toLowerCase();if(!KINDS.has(kind))throw new TypeError(`unsupported-contribution-kind:${kind}`);return Object.freeze({schema:'titan.contribution.v2',company_id,id:text(raw.id??raw.contribution_id,'id'),kind,provider_id:text(raw.provider_id??raw.source_id??'titan.native','provider_id'),priority:Number.isFinite(Number(raw.priority))?Number(raw.priority):0,operations:list(raw.operations),capabilities:list(raw.capabilities),permissions:list(raw.permissions).map(x=>x.toLowerCase()),offline_support:Boolean(raw.offline_support??raw.offline??false),enabled:raw.enabled!==false,metadata:Object.freeze(clone(raw.metadata??{})),payload:Object.freeze(clone(raw.payload??{})),authority_neutral:true,activation_confers_authority:false});}
export class ContributionRegistry{#company_id;#records=new Map();constructor({company_id}={}){this.#company_id=companyId({company_id});}get company_id(){return this.#company_id}register(raw){const r=normalizeContribution(raw,{company_id:this.#company_id}),key=`${r.kind}::${r.provider_id}::${r.id}`;if(this.#records.has(key))throw new Error(`contribution-already-registered:${key}`);this.#records.set(key,r);return r}registerMany(items=[]){return Object.freeze(items.map(x=>this.register(x)))}unregisterProvider(provider){const id=text(provider,'provider_id');let n=0;for(const [k,r] of this.#records)if(r.provider_id===id){this.#records.delete(k);n++}return n}discover({kind=null,id=null,provider_id=null,operation=null,capability=null,offline_only=false,permission=null,enabled_only=true}={}){const k=kind?text(kind,'kind').toLowerCase():null;if(k&&!KINDS.has(k))throw new TypeError(`unsupported-contribution-kind:${k}`);const a=[...this.#records.values()].filter(r=>(!k||r.kind===k)&&(!id||r.id===id)&&(!provider_id||r.provider_id===provider_id)&&(!operation||r.operations.includes(operation))&&(!capability||r.capabilities.includes(capability))&&(!offline_only||r.offline_support)&&(!permission||r.permissions.includes(String(permission).toLowerCase()))&&(!enabled_only||r.enabled));a.sort((x,y)=>Number(y.offline_support)-Number(x.offline_support)||y.priority-x.priority||x.kind.localeCompare(y.kind)||x.provider_id.localeCompare(y.provider_id)||x.id.localeCompare(y.id));return Object.freeze(a)}snapshot(){return Object.freeze({schema:'titan.contribution-registry.v2',company_id:this.#company_id,count:this.#records.size,authority:{registration_grants_authority:false,activation_confers_authority:false},contributions:this.discover({enabled_only:false}).map(clone)})}}
export const createContributionRegistry=context=>new ContributionRegistry(context);
