// @ts-nocheck
import { assertCanonicalCompanyId, rejectLegacyTenantAuthorityDeep } from '../boundary.js';
const freeze=v=>Object.freeze(v); const nonempty=(v,n)=>{const s=String(v??'').trim();if(!s)throw new TypeError(`${n}-required`);return s};
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
export function createTemporalIntelligence({company_id,max_samples=200}={}){
 const cid=assertCanonicalCompanyId(company_id), times=new Map(), durations=new Map();
 const record=(action,time=new Date(),duration_minutes=null)=>{const a=nonempty(action,'action'),d=new Date(time);if(Number.isNaN(d.getTime()))throw new TypeError('time-invalid');const t=times.get(a)??[];t.push({weekday:d.getUTCDay()||7,hour:d.getUTCHours()});times.set(a,t.slice(-max_samples));if(duration_minutes!==null){const n=Number(duration_minutes);if(!Number.isFinite(n)||n<0)throw new TypeError('duration-invalid');const ds=durations.get(a)??[];ds.push(n);durations.set(a,ds.slice(-max_samples));}return api;};
 const suggest=(action,now=new Date())=>{const a=nonempty(action,'action'),rows=times.get(a)??[];if(!rows.length)return freeze({company_id:cid,action:a,confidence:.25,recommended_hour:null,weekday_match:false,evidence:{samples:0},authority_neutral:true});const counts={};for(const r of rows)counts[r.hour]=(counts[r.hour]??0)+1;const ranked=Object.entries(counts).sort((x,y)=>y[1]-x[1]||Number(x[0])-Number(y[0]));const wd=(new Date(now).getUTCDay()||7);return freeze({company_id:cid,action:a,confidence:Number((ranked[0][1]/rows.length).toFixed(4)),recommended_hour:Number(ranked[0][0]),weekday_match:rows.some(r=>r.weekday===wd),evidence:{samples:rows.length},authority_neutral:true});};
 const predictDuration=action=>{const a=nonempty(action,'action'),xs=durations.get(a)??[];if(!xs.length)return freeze({company_id:cid,estimated_minutes:null,confidence:0,range:null,evidence:{samples:0},authority_neutral:true});const avg=xs.reduce((s,x)=>s+x,0)/xs.length,lo=Math.min(...xs),hi=Math.max(...xs),spread=hi-lo;return freeze({company_id:cid,estimated_minutes:Number(avg.toFixed(1)),confidence:Number((1/(1+spread/Math.max(1,avg))).toFixed(4)),range:{min:lo,max:hi},evidence:{samples:xs.length},authority_neutral:true});};
 const api=freeze({record,suggest,predictDuration});return api;
}
export function createPredictiveCompletion({company_id}={}){
 const cid=assertCanonicalCompanyId(company_id), transitions=new Map(), fields=new Map(); const tk=(w,f)=>`${w}::${f}`,fk=(w,f)=>`${w}::${f}`;
 const api={observeTransition:(wizard_id,from_step,to_step)=>{const k=tk(nonempty(wizard_id,'wizard-id'),nonempty(from_step,'from-step')),to=nonempty(to_step,'to-step'),m=transitions.get(k)??new Map();m.set(to,(m.get(to)??0)+1);transitions.set(k,m);return api;},observeField:(wizard_id,field,value)=>{rejectLegacyTenantAuthorityDeep(value,'predictive-completion-field');const k=fk(nonempty(wizard_id,'wizard-id'),nonempty(field,'field')),m=fields.get(k)??new Map(),encoded=JSON.stringify(value);const prev=m.get(encoded)??{value,count:0};m.set(encoded,{value:structuredClone(value),count:prev.count+1});fields.set(k,m);return api;},predictNextStep:(wizard_id,current_step)=>{const m=transitions.get(tk(nonempty(wizard_id,'wizard-id'),nonempty(current_step,'current-step')));if(!m?.size)return freeze({company_id:cid,most_likely:null,confidence:0,alternatives:[],authority_neutral:true});const rows=[...m.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])),total=rows.reduce((s,r)=>s+r[1],0);return freeze({company_id:cid,most_likely:rows[0][0],confidence:Number((rows[0][1]/total).toFixed(4)),alternatives:rows.slice(1,4).map(r=>r[0]),evidence:{observations:total},authority_neutral:true});},prefill:(wizard_id,field_names,minimum_confidence=.7)=>{const out={};for(const field of field_names){const m=fields.get(fk(nonempty(wizard_id,'wizard-id'),nonempty(field,'field')));if(!m?.size)continue;const rows=[...m.values()].sort((a,b)=>b.count-a.count),total=rows.reduce((s,r)=>s+r.count,0),confidence=rows[0].count/total;if(confidence>=minimum_confidence)out[field]={value:structuredClone(rows[0].value),confidence:Number(confidence.toFixed(4)),suggestion_only:true};}return freeze({company_id:cid,values:out,authority_neutral:true,requires_user_or_governed_acceptance:true});}};return freeze(api);
}
export function createAdaptiveReweighting({company_id,minimum_weight=.1,maximum_weight=3}={}){
 const cid=assertCanonicalCompanyId(company_id),weights=new Map(),history=[];
 const api={update:(prediction={},actual={},learning_rate=.1)=>{rejectLegacyTenantAuthorityDeep({prediction,actual},'adaptive-reweighting');const rate=clamp(Number(learning_rate),0,1);for(const [feature,predicted] of Object.entries(prediction)){if(!Number.isFinite(Number(predicted))||!Number.isFinite(Number(actual[feature])))continue;const error=Number(actual[feature])-Number(predicted),current=weights.get(feature)??1,next=clamp(current+rate*error,minimum_weight,maximum_weight);weights.set(feature,next);history.push({feature,error,weight:next});}if(history.length>1000)history.splice(0,history.length-1000);return api.weights();},adjust:scores=>{const out={};for(const [feature,score] of Object.entries(scores))out[feature]=Number.isFinite(Number(score))?Number(score)*(weights.get(feature)??1):score;return freeze({company_id:cid,scores:out,authority_neutral:true});},weights:()=>freeze({company_id:cid,weights:Object.fromEntries([...weights.entries()].sort()),authority_neutral:true}),history:()=>freeze(history.map(x=>freeze({...x})))};return freeze(api);
}
