// @ts-nocheck
import { assertCanonicalCompanyId, rejectLegacyTenantAuthorityDeep } from '../boundary.js';
const freeze=v=>Object.freeze(v); const text=(v,n)=>{const s=String(v??'').trim();if(!s)throw new TypeError(`${n}-required`);return s;};
const pathGet=(value,path)=>{let out=value;for(const segment of String(path).split('.')){if(!out || typeof out!=='object' || !(segment in out))return null;out=out[segment];}return out;};
export function createQuestionResolver({company_id,knowledge_query=null,cache_get=null,now=()=>new Date().toISOString()}={}){
 const cid=assertCanonicalCompanyId(company_id), custom=new Map();
 const answer=(key,value,source,confidence)=>freeze({company_id:cid,key,value,source,confidence,answered_at:now(),authority_neutral:true});
 const api={register:(handling,handler)=>{if(typeof handler!=='function')throw new TypeError('question-handler-required');custom.set(text(handling,'question-handling'),handler);return api;},resolve:async(question={},context={})=>{rejectLegacyTenantAuthorityDeep({question,context},'question-resolver');const key=text(question.key,'question-key'),handling=String(question.handling??'').trim();if(custom.has(handling))return answer(key,await custom.get(handling)(question,context),handling,1);if(cache_get){const v=await cache_get({company_id:cid,key,question,context});if(v!==undefined&&v!==null)return answer(key,v,'cache',.9);}if(question.options_source && knowledge_query){const v=await knowledge_query({company_id:cid,source_id:String(question.options_source),query:String(question.question??key),context});if(v!==undefined&&v!==null)return answer(key,v,'knowledge',.8);}const expression=question?.metadata?.compute;if(typeof expression==='string'&&/^[A-Za-z_][A-Za-z0-9_.]*$/.test(expression)){const v=pathGet(context,expression);if(v!==null)return answer(key,v,'compute',.85);}if(Object.prototype.hasOwnProperty.call(question,'default'))return answer(key,question.default,'default',.7);if(context?.answers && Object.prototype.hasOwnProperty.call(context.answers,key))return answer(key,context.answers[key],'context',.8);return answer(key,null,'user',null);}};return freeze(api);
}
