import test from 'node:test'; import assert from 'node:assert/strict'; import { readFile } from 'node:fs/promises';
import { createTeamAAnalysis } from '../core/intelligence-team-a.mjs'; import { createTeamBAnalysis } from '../core/intelligence-team-b.mjs'; import { assessDivergence } from '../core/divergence-intelligence.mjs';
const manifest=JSON.parse(await readFile(new URL('../../manifest.json',import.meta.url),'utf8'));
const ev=(id,d)=>[{evidence_id:id,kind:'observation',source:id,claim:'observed',confidence:.9,provenance:{independence_domain:d}}];
async function pair(bText='invoice appears forged unsafe and should be held for investigation',ca=.9,cb=.88,da='source:a',db='source:b'){
 const a=await createTeamAAnalysis({company_id:'c1',item_id:'i1',revision_id:'r1',lens:'meaning-context',evidence:ev('a',da),interpretation:'invoice is authentic valid payable and safe to approve',confidence:ca,risk_level:'high'});
 const b=await createTeamBAnalysis({company_id:'c1',item_id:'i1',revision_id:'r1',lens:'provenance-reality',evidence:ev('b',db),interpretation:bText,confidence:cb,risk_level:'high'}); return {a,b};
}
test('pass 14 increments BOS package version',()=>assert.equal(manifest.version,'0.18.2'));
test('disagreement is a first-class signal with separate confidence positions',async()=>{const {a,b}=await pair();const r=await assessDivergence({team_a:a,team_b:b,risk_level:'high'});assert.equal(r.first_class_signal,true);assert.equal(r.confidence_positions.aggregation,'not-averaged');assert.equal(r.confidence_positions.team_a,.9);assert.equal(r.confidence_positions.team_b,.88);assert.ok(r.disagreement_strength>.5);});
test('high-confidence independent disagreement escalates instead of averaging',async()=>{const {a,b}=await pair();const r=await assessDivergence({team_a:a,team_b:b});assert.equal(r.high_confidence_conflict,true);assert.equal(r.escalation.required,true);assert.ok(['high','critical'].includes(r.severity));});
test('shared dependencies remain visible and reduce independence without erasing disagreement',async()=>{const {a,b}=await pair(undefined,.9,.88,'shared:x','shared:x');const r=await assessDivergence({team_a:a,team_b:b});assert.equal(r.independence.score,0);assert.deepEqual(r.independence.shared_domains,['shared:x']);assert.equal(r.first_class_signal,true);});
test('near agreement produces no material divergence',async()=>{const {a,b}=await pair('invoice is authentic valid payable and safe to approve');const r=await assessDivergence({team_a:a,team_b:b,risk_level:'low'});assert.equal(r.severity,'none');assert.equal(r.first_class_signal,false);});
test('divergence preserves both interpretations and contested distinct terms',async()=>{const {a,b}=await pair();const r=await assessDivergence({team_a:a,team_b:b});assert.equal(r.interpretations.team_a,a.interpretation);assert.equal(r.interpretations.team_b,b.interpretation);assert.ok(r.contested.team_a_distinct_terms.length);assert.ok(r.contested.team_b_distinct_terms.length);});
test('divergence requires verified same-revision sealed pair',async()=>{const {a,b}=await pair();const bad=structuredClone(b);bad.revision_id='r2';await assert.rejects(()=>assessDivergence({team_a:a,team_b:bad}),/divergence-revision-id-mismatch/);});
