import test from 'node:test'; import assert from 'node:assert/strict'; import { readFile } from 'node:fs/promises';
import { createTeamAAnalysis } from '../core/intelligence-team-a.mjs'; import { createTeamBAnalysis } from '../core/intelligence-team-b.mjs'; import { assessDivergence } from '../core/divergence-intelligence.mjs'; import { assessDivergenceSeverity, DIVERGENCE_SEVERITY_WEIGHTS } from '../core/divergence-severity.mjs';
const manifest=JSON.parse(await readFile(new URL('../../manifest.json',import.meta.url),'utf8'));
const ev=(id,d,q=.9,prov=true)=>[{evidence_id:id,kind:'observation',source:id,claim:'observed',confidence:q,provenance:prov?{independence_domain:d,origin:id}:undefined}];
async function pair({qa=.92,qb=.9,ca=.92,cb=.88,da='source:a',db='source:b',bText='invoice appears forged unsafe and must be held'}={}){
 const a=await createTeamAAnalysis({company_id:'c1',item_id:'i1',revision_id:'r1',lens:'meaning-context',evidence:ev('a',da,qa),interpretation:'invoice is authentic valid payable and safe to approve',confidence:ca,risk_level:'high'});
 const b=await createTeamBAnalysis({company_id:'c1',item_id:'i1',revision_id:'r1',lens:'provenance-reality',evidence:ev('b',db,qb),interpretation:bText,confidence:cb,risk_level:'high'}); return {a,b};
}
test('pass 15 increments BOS package version',()=>assert.equal(manifest.version,'0.18.2'));
test('severity weights cover required dimensions and sum to one',()=>{assert.deepEqual(Object.keys(DIVERGENCE_SEVERITY_WEIGHTS),['disagreement','evidence_quality','confidence_strength','criticality','independence','provenance_quality','consequence']);assert.ok(Math.abs(Object.values(DIVERGENCE_SEVERITY_WEIGHTS).reduce((a,b)=>a+b,0)-1)<1e-9);});
test('high-confidence independent consequential disagreement scores high or critical',async()=>{const {a,b}=await pair();const r=await assessDivergenceSeverity({team_a:a,team_b:b,risk_level:'high',criticality_score:.95,consequence_score:.95});assert.ok(['high','critical'].includes(r.severity));assert.equal(r.source_positions.confidence_aggregation,'not-averaged');assert.equal(r.factors.confidence_strength,.88);assert.ok(r.factors.independence>=.9);});
test('shared dependencies lower severity independence contribution without erasing disagreement',async()=>{const {a,b}=await pair({da:'shared:x',db:'shared:x'});const d=await assessDivergence({team_a:a,team_b:b});const r=await assessDivergenceSeverity({team_a:a,team_b:b,divergence:d,criticality_score:.7,consequence_score:.7});assert.equal(r.factors.independence,0);assert.ok(r.factors.disagreement>.5);assert.equal(r.weighted_components.independence.contribution,0);});
test('weak evidence and weak confidence conservatively suppress severity',async()=>{const {a,b}=await pair({qa:.2,qb:.25,ca:.35,cb:.3});const r=await assessDivergenceSeverity({team_a:a,team_b:b,risk_level:'low',criticality_score:.2,consequence_score:.2});assert.equal(r.factors.evidence_quality<=.5,true);assert.equal(r.factors.confidence_strength,.3);assert.ok(['minimal','low','medium'].includes(r.severity));});
test('exceptional consequential disagreement forces critical handling',async()=>{const {a,b}=await pair();const r=await assessDivergenceSeverity({team_a:a,team_b:b,risk_level:'exceptional',consequence_score:1});assert.equal(r.severity,'critical');assert.equal(r.escalation.required,true);});
test('severity remains revision bound',async()=>{const {a,b}=await pair();const d=await assessDivergence({team_a:a,team_b:b});const bad={...d,revision_id:'other'};await assert.rejects(()=>assessDivergenceSeverity({team_a:a,team_b:b,divergence:bad}),/divergence-severity-divergence-revision-mismatch/);});
