import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createTeamAAnalysis} from '../core/intelligence-team-a.mjs';import {createTeamBAnalysis} from '../core/intelligence-team-b.mjs';import {createTeamCAssurance,verifyTeamCSeal} from '../core/intelligence-team-c.mjs';
const manifest=JSON.parse(fs.readFileSync(new URL('../../manifest.json',import.meta.url)));test('pass 16 increments BOS package version',()=>assert.equal(manifest.version,'0.18.2'));
async function pair(shared=false){const a=await createTeamAAnalysis({company_id:'c1',item_id:'i1',revision_id:'r1',analysis_id:'a1',lens:'meaning-context',evidence:[{id:'ea',source:'crm',claim:'invoice appears duplicate',confidence:.9}],contributors:[{type:'source',contributor_id:'sa',origin:'crm',independence_domain:shared?'common-ledger':'crm-a',provenance:{ref:'1'}}],interpretation:'invoice appears duplicate and should be held',confidence:.88,unresolved:['payment trace']});const b=await createTeamBAnalysis({company_id:'c1',item_id:'i1',revision_id:'r1',analysis_id:'b1',lens:'provenance-reality',evidence:[{id:'eb',source:'bank-feed',claim:'second debit appears real',confidence:.86}],contributors:[{type:'source',contributor_id:'sb',origin:'bank-feed',independence_domain:shared?'common-ledger':'bank-b',provenance:{ref:'2'}}],interpretation:'second debit appears real and should be investigated',confidence:.85});return {a,b};}
test('Team C runs only after valid sealed A/B and seals its own assurance',async()=>{const {a,b}=await pair();const c=await createTeamCAssurance({team_a:a,team_b:b,risk_level:'high'});assert.equal(c.team,'C');assert.equal(c.post_ab,true);assert.equal(c.authority,'assurance-only');assert.equal(c.synthesis_constraints.zero_synthesis_required,true);assert.equal(c.synthesis_constraints.may_approve,false);assert.equal(await verifyTeamCSeal(c),true);});
test('Team C rejects tampered A or B',async()=>{const {a,b}=await pair();const bad={...a,interpretation:'tampered'};await assert.rejects(()=>createTeamCAssurance({team_a:bad,team_b:b}),/team-c-team-a-seal-invalid/);});
test('Team C binds exact company item and revision',async()=>{const {a,b}=await pair();const bad={...b,revision_id:'r2'};await assert.rejects(()=>createTeamCAssurance({team_a:a,team_b:bad}),/revision-id-mismatch/);});
test('Team C exposes three adversarial challenge roles',async()=>{const {a,b}=await pair(true);const c=await createTeamCAssurance({team_a:a,team_b:b});assert.deepEqual(Object.values(c.challenge_roles).map(x=>x.role).sort(),['assumption-challenger','authenticity-consequence-challenger','specialist-assurance'].sort());assert.ok(c.evidence_assurance.shared_independence_domains.length>0);});
test('Team C seal detects tampering',async()=>{const {a,b}=await pair();const c=await createTeamCAssurance({team_a:a,team_b:b});const bad=structuredClone(c);bad.assessment.divergence_score=.99;assert.equal(await verifyTeamCSeal(bad),false);});
