import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createTeamAAnalysis} from '../core/intelligence-team-a.mjs';import {createTeamBAnalysis} from '../core/intelligence-team-b.mjs';import {createTeamCAssurance} from '../core/intelligence-team-c.mjs';import {assessSharedBlindSpots,verifySharedBlindSpotSeal} from '../core/shared-blind-spot.mjs';
const manifest=JSON.parse(fs.readFileSync(new URL('../../manifest.json',import.meta.url)));test('pass 17 increments BOS package version',()=>assert.equal(manifest.version,'0.18.2'));
async function lineage(opts={}){const a=await createTeamAAnalysis({company_id:'c1',item_id:'i1',revision_id:'r1',analysis_id:'a1',lens:'meaning-context',evidence:[{id:'ea',source:opts.common?'shared-feed':'crm',claim:'claim a',confidence:.9,provenance:opts.aProv||{ref:'root-a'}}],contributors:opts.aCon||[{type:'source',contributor_id:'sa',origin:opts.common?'shared-feed':'crm',independence_domain:opts.common?'common-domain':'a-domain',provenance:{ref:'root-a'}}],interpretation:'payment state appears inconsistent with invoice',confidence:.9,unresolved:opts.aAss||[]});const b=await createTeamBAnalysis({company_id:'c1',item_id:'i1',revision_id:'r1',analysis_id:'b1',lens:'provenance-reality',evidence:[{id:'eb',source:opts.common?'shared-feed':'bank',claim:'claim b',confidence:.88,provenance:opts.bProv||{ref:'root-b'}}],contributors:opts.bCon||[{type:'source',contributor_id:'sb',origin:opts.common?'shared-feed':'bank',independence_domain:opts.common?'common-domain':'b-domain',provenance:{ref:'root-b'}}],interpretation:'payment state appears inconsistent after bank trace',confidence:.87,unresolved:opts.bAss||[]});const c=await createTeamCAssurance({team_a:a,team_b:b});return {a,b,c};}
test('detects common-source contamination',async()=>{const {a,b,c}=await lineage({common:true});const r=await assessSharedBlindSpots({team_a:a,team_b:b,team_c:c});assert.ok(r.by_type['common-source-contamination'].length);assert.equal(r.independence_effect.should_discount_convergence,true);assert.equal(await verifySharedBlindSpotSeal(r),true);});
test('detects shared model weaknesses',async()=>{const {a,b,c}=await lineage({aCon:[{type:'model',contributor_id:'ma',origin:'local-model',independence_domain:'model-family-x',provenance:{model_family:'family-x'}}],bCon:[{type:'model',contributor_id:'mb',origin:'local-model',independence_domain:'model-family-x',provenance:{model_family:'family-x'}}]});const r=await assessSharedBlindSpots({team_a:a,team_b:b,team_c:c,model_weakness_registry:{'family-x':['shared hallucination mode']}});assert.ok(r.by_type['shared-model-weakness'].length);assert.equal(r.by_type['shared-model-weakness'][0].severity,'high');});
test('detects correlated assumptions',async()=>{const {a,b,c}=await lineage();const r=await assessSharedBlindSpots({team_a:a,team_b:b,team_c:c,assumptions:{team_a:['bank timestamp is authoritative and complete'],team_b:['bank timestamp is authoritative and complete']}});assert.ok(r.by_type['correlated-assumption'].length);});
test('detects circular cross-path provenance',async()=>{const {a,b,c}=await lineage({aProv:{depends_on:'eb'},bProv:{depends_on:'ea'}});const r=await assessSharedBlindSpots({team_a:a,team_b:b,team_c:c});assert.ok(r.by_type['circular-evidence'].some(x=>x.code==='cross-path-cycle'));assert.equal(r.severity,'critical');});
test('clean independent lineage can remain blind-spot free',async()=>{const {a,b,c}=await lineage();const r=await assessSharedBlindSpots({team_a:a,team_b:b,team_c:c,assumption_similarity_threshold:.95});assert.equal(r.blind_spot_detected,false);assert.equal(r.severity,'none');});
test('rejects tampered Team C and wrong lineage',async()=>{const {a,b,c}=await lineage();const bad=structuredClone(c);bad.assessment.divergence_score=.99;await assert.rejects(()=>assessSharedBlindSpots({team_a:a,team_b:b,team_c:bad}),/team-c-seal-invalid/);});
test('sealed blind-spot report detects tampering',async()=>{const {a,b,c}=await lineage({common:true});const r=await assessSharedBlindSpots({team_a:a,team_b:b,team_c:c});const bad=structuredClone(r);bad.blind_spot_score=0;assert.equal(await verifySharedBlindSpotSeal(bad),false);});
