import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const root=new URL('../',import.meta.url);const cfg=JSON.parse(fs.readFileSync(new URL('../titan-modules/cleaning-marketplace-decision-readiness.json',import.meta.url),'utf8'));assert.equal(cfg.schema,'titan-cleaning-marketplace-decision-readiness/v1');
const html=fs.readFileSync(new URL('../modules.html',import.meta.url),'utf8');assert.equal((html.match(/cleaning-marketplace-decision-readiness\.js/g)||[]).length,1);assert.match(html,/marketplace-decision-readiness-title/);
const items=[
 {id:'ready',title:'Ready',source:'renewal',recommendation:'review_renewal',status:'in_review',owner:'Sam',evidence_total:2,evidence_completed:2,evidence_complete:true,overdue:false},
 {id:'blocked',title:'Blocked',source:'renewal',recommendation:'review_renewal',status:'waiting_evidence',owner:'Sam',evidence_total:2,evidence_completed:1,evidence_complete:false,overdue:false},
 {id:'owner',title:'Owner',source:'consolidation',recommendation:'candidate_for_consolidation',status:'open',owner:'',evidence_total:1,evidence_completed:1,evidence_complete:true,overdue:false},
 {id:'escalate',title:'Escalate',source:'renewal',recommendation:'review_renewal',status:'open',owner:'Sam',evidence_total:1,evidence_completed:0,evidence_complete:false,overdue:true},
 {id:'done',title:'Done',source:'renewal',recommendation:'review_renewal',status:'decision_recorded',owner:'Sam',decision:'keep',evidence_total:1,evidence_completed:1,evidence_complete:true,overdue:false}
];
const els=new Map();function el(id){if(!els.has(id))els.set(id,{id,innerHTML:'',textContent:'',addEventListener(){}});return els.get(id)}const document={getElementById:el};const window={TitanCleaningMarketplaceActionQueue:{getItems:()=>items},addEventListener(){}};const chrome={runtime:{getURL:p=>p}};const fetch=async()=>({json:async()=>cfg});const sandbox={window,document,chrome,fetch,console};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(new URL('../cleaning-marketplace-decision-readiness.js',import.meta.url),'utf8'),sandbox);await new Promise(r=>setTimeout(r,10));
const rows=window.TitanCleaningMarketplaceDecisionReadiness.getItems();const by=Object.fromEntries(rows.map(r=>[r.id,r]));assert.equal(by.ready.readiness,'ready_for_decision');assert.equal(by.blocked.readiness,'evidence_blocked');assert.equal(by.owner.readiness,'owner_needed');assert.equal(by.escalate.readiness,'escalation_needed');assert.equal(by.done.readiness,'decision_recorded');assert.equal(window.TitanCleaningMarketplaceDecisionReadiness.approvesDecisions,false);assert.equal(window.TitanCleaningMarketplaceDecisionReadiness.executesUnderlyingAction,false);console.log('cleaning marketplace decision readiness: 5/5 PASS');
