import test from 'node:test';
import assert from 'node:assert/strict';
import {certifyDispatchRelease,summarizeDispatchReleaseCertification} from '../titan-workforce/dispatch/dispatch-release-certification-runtime.mjs';

const company_id='co-release';
const graph={schema:'titan.workforce.graph.v1',company_id,nodes:[{node_id:'worker:w1',company_id,kind:'worker',label:'Worker 1',attributes:{actor_type:'human'}}],edges:[{company_id,type:'HAS_CAPABILITY',from:'worker:w1',to:'capability:cleaning'}]};
const work={company_id,work_item_id:'job-final',state:'ready',priority:5,required_capabilities:['cleaning'],required_human:true,demand_units:1,service_window_start_ms:1700000000000,service_window_end_ms:1700003600000,location:{lat:-37.81,lng:144.96}};
const base={company_id,manager_baseline:{merge:39,artifact:'Merge39.zip',sha256:'abc123'},golden_input:{graph,capacity_snapshot:{schema:'titan.workforce.workload-capacity.v1',company_id,worker_capacity:[{worker_id:'w1',available_units:2,utilization:.2,state:'BALANCED'}]},work_item:work,worker_availability:[{company_id,worker_id:'w1',start_ms:1699999000000,end_ms:1700007200000,available:true}],worker_locations:[{company_id,worker_id:'w1',lat:-37.82,lng:144.97}],origin:{company_id,lat:-37.82,lng:144.97},destination:work,now:1700000000000,now_ms:1699999900000,canonical_job_revision:3,confirmed:true,confirmation_refs:['human-confirm'],actor_id:'owner',authority_context:{company_id,worker:{worker_id:'owner'}},events:[{company_id,event_id:'evt-final',source_revision:3,idempotency_key:'evt-final'}]},jobs_handoff:{company_id,worker:'Jobs Agent',canonical_owner:'Titan Field',status:'COMPLETE',execution_permitted:false,authority_granted:false},scheduling_handoff:{company_id,worker:'Scheduling Agent',status:'COMPLETE',execution_permitted:false,authority_granted:false,duplicate_replay_suppression:'PASS',company_isolation:'PASS'},reconstruction:{company_id,exact:true,base_files:2877,target_files:2880},collision:{protected_hotspots_touched:[],unresolved:[]},donor:{direct_source_transplant:false,license_status:'UNRESOLVED'}};

test('final release certification passes only with clean external boundaries',()=>{const r=certifyDispatchRelease(base);assert.equal(r.status,'CERTIFIED');assert.equal(r.ready_for_manager_merge,true);assert.equal(r.recommended_convergence_class,'CLEAN_ADDITIVE_FORWARD_PORT');assert.equal(r.execution_permitted,false);assert.equal(r.grants_authority,false);});
test('Jobs remains canonical owner and cannot grant Dispatch authority',()=>{const r=certifyDispatchRelease(base);assert.equal(r.canonical_jobs_owned_elsewhere,true);assert.equal(r.checks.find(x=>x.name==='jobs-handoff-boundary').status,'PASS');});
test('Scheduling remains external and replay-safe evidence is required',()=>{const r=certifyDispatchRelease({...base,scheduling_handoff:{...base.scheduling_handoff,duplicate_replay_suppression:'FAIL'}});assert.equal(r.status,'REVIEW_REQUIRED');assert.equal(r.ready_for_manager_merge,false);});
test('cross-company Jobs or Scheduling handoff fails closed',()=>{assert.throws(()=>certifyDispatchRelease({...base,jobs_handoff:{...base.jobs_handoff,company_id:'other'}}),/cross-company-jobs/);assert.throws(()=>certifyDispatchRelease({...base,scheduling_handoff:{...base.scheduling_handoff,company_id:'other'}}),/cross-company-scheduling/);});
test('non-exact reconstruction blocks release',()=>{const r=certifyDispatchRelease({...base,reconstruction:{company_id,exact:false}});assert.equal(r.status,'BLOCKED');assert.equal(r.ready_for_manager_merge,false);});
test('protected hotspot collision blocks release',()=>{const r=certifyDispatchRelease({...base,collision:{protected_hotspots_touched:['manifest.json'],unresolved:[]}});assert.equal(r.status,'BLOCKED');});
test('unlicensed direct donor transplant blocks release',()=>{const r=certifyDispatchRelease({...base,donor:{direct_source_transplant:true,license_status:'UNVERIFIED'}});assert.equal(r.status,'BLOCKED');});
test('legacy tenant identifiers fail closed recursively',()=>{assert.throws(()=>certifyDispatchRelease({...base,scheduling_handoff:{...base.scheduling_handoff,nested:{tenant_company_id:'legacy'}}}),/legacy-company-boundary/);});
test('golden review prevents premature READY status',()=>{const r=certifyDispatchRelease({...base,golden_input:{...base.golden_input,confirmed:false}});assert.equal(r.status,'REVIEW_REQUIRED');assert.equal(r.ready_for_manager_merge,false);});
test('summary never grants execution authority',()=>{const s=summarizeDispatchReleaseCertification(certifyDispatchRelease(base));assert.equal(s.status,'CERTIFIED');assert.equal(s.ready_for_manager_merge,true);assert.equal(s.execution_permitted,false);assert.equal(s.grants_authority,false);});
