import test from 'node:test';
import assert from 'node:assert/strict';
import { assessDispatchAdversarialScenario, summarizeDispatchAdversarialAssessment } from '../titan-workforce/dispatch/dispatch-adversarial-runtime.mjs';

const company_id='co-1';
const base={company_id,work_items:[],assignments:[],events:[],canonical_job_revision:4,now:1_000_000};

test('urgent unassigned work escalates but does not auto-dispatch',()=>{const r=assessDispatchAdversarialScenario({...base,work_items:[{company_id,work_item_id:'urgent-1',state:'open',priority:5}]});assert.equal(r.state,'REVIEW_REQUIRED');assert.equal(r.findings[0].type,'URGENT_UNASSIGNED');assert.equal(r.findings[0].severity,'CRITICAL');assert.equal(r.automatic_dispatch,false);assert.equal(r.execution_permitted,false);});

test('multiple active workers on one work item exposes reassignment race and blocks',()=>{const r=assessDispatchAdversarialScenario({...base,work_items:[{company_id,work_item_id:'job-1',state:'open'}],assignments:[{company_id,assignment_id:'a1',work_item_id:'job-1',worker_id:'w1',state:'assigned',revision:4},{company_id,assignment_id:'a2',work_item_id:'job-1',worker_id:'w2',state:'assigned',revision:5}]});assert.equal(r.state,'BLOCKED_CONFLICTING_EVIDENCE');assert.ok(r.findings.some(x=>x.type==='MULTIPLE_ACTIVE_ASSIGNMENTS'));assert.ok(r.findings.some(x=>x.type==='REASSIGNMENT_RACE'));assert.equal(r.automatic_reassignment,false);});

test('cancelled job with active assignment blocks rather than auto-releasing worker',()=>{const r=assessDispatchAdversarialScenario({...base,work_items:[{company_id,work_item_id:'job-c',state:'cancelled'}],assignments:[{company_id,assignment_id:'a1',work_item_id:'job-c',worker_id:'w1',state:'assigned'}]});const f=r.findings.find(x=>x.type==='CANCELLED_WITH_ACTIVE_ASSIGNMENT');assert.ok(f);assert.equal(r.state,'BLOCKED_CONFLICTING_EVIDENCE');assert.equal(r.automatic_cancellation,false);assert.equal(r.direct_mutation,false);});

test('same worker overlap is evidence-only and deferred to Scheduling',()=>{const r=assessDispatchAdversarialScenario({...base,work_items:[{company_id,work_item_id:'j1',state:'open'},{company_id,work_item_id:'j2',state:'open'}],assignments:[{company_id,assignment_id:'a1',work_item_id:'j1',worker_id:'w1',state:'assigned',scheduled_start_ms:100,scheduled_end_ms:300},{company_id,assignment_id:'a2',work_item_id:'j2',worker_id:'w1',state:'assigned',scheduled_start_ms:200,scheduled_end_ms:400}]});const f=r.findings.find(x=>x.type==='WORKER_OVERLAP_EVIDENCE');assert.ok(f);assert.equal(f.evidence_only,true);assert.equal(f.recommended_next_step,'DEFER_TO_SCHEDULING_CONFLICT_REVIEW');assert.equal(r.scheduling_overlap_evidence_advisory_only,true);});

test('duplicate dispatch event is suppressed advisory only',()=>{const ev={company_id,event_id:'e1',work_item_id:'j1',source_revision:4,idempotency_key:'k1',payload:{status:'assigned'}};const r=assessDispatchAdversarialScenario({...base,events:[ev,{...ev}]});assert.ok(r.findings.some(x=>x.type==='DUPLICATE_EVENT'));assert.equal(r.automatic_effect_replay,false);});

test('conflicting duplicate event blocks',()=>{const r=assessDispatchAdversarialScenario({...base,events:[{company_id,event_id:'e1',work_item_id:'j1',source_revision:4,idempotency_key:'k1',payload:{worker_id:'w1'}},{company_id,event_id:'e1',work_item_id:'j1',source_revision:4,idempotency_key:'k1',payload:{worker_id:'w2'}}]});assert.equal(r.state,'BLOCKED_CONFLICTING_EVIDENCE');assert.ok(r.findings.some(x=>x.type==='CONFLICTING_EVENT'));});

test('stale and future job revisions both require authoritative refresh',()=>{const r=assessDispatchAdversarialScenario({...base,events:[{company_id,event_id:'old',work_item_id:'j1',source_revision:3,idempotency_key:'old'},{company_id,event_id:'future',work_item_id:'j1',source_revision:5,idempotency_key:'future'}]});assert.ok(r.findings.some(x=>x.type==='STALE_JOB_REVISION'));assert.ok(r.findings.some(x=>x.type==='FUTURE_JOB_REVISION'));assert.equal(r.canonical_job_state_owned_elsewhere,true);});

test('cross-company work assignment and event fail closed',()=>{assert.throws(()=>assessDispatchAdversarialScenario({...base,work_items:[{company_id:'co-2',work_item_id:'j1'}]}),/cross-company-work-item/);assert.throws(()=>assessDispatchAdversarialScenario({...base,assignments:[{company_id:'co-2',assignment_id:'a1'}]}),/cross-company-assignment/);assert.throws(()=>assessDispatchAdversarialScenario({...base,events:[{company_id:'co-2',event_id:'e1'}]}),/cross-company-event/);});

test('legacy tenant boundary fields are rejected anywhere in scenario evidence',()=>{assert.throws(()=>assessDispatchAdversarialScenario({...base,work_items:[{company_id,work_item_id:'j1',metadata:{tenant_company_id:'legacy'}}]}),/legacy-company-boundary/);});

test('clean multi-worker scenario remains clear and deterministic',()=>{const input={...base,work_items:[{company_id,work_item_id:'j1',state:'open'},{company_id,work_item_id:'j2',state:'open'}],assignments:[{company_id,assignment_id:'a1',work_item_id:'j1',worker_id:'w1',state:'assigned',scheduled_start_ms:100,scheduled_end_ms:200},{company_id,assignment_id:'a2',work_item_id:'j2',worker_id:'w2',state:'assigned',scheduled_start_ms:100,scheduled_end_ms:200}]};const a=assessDispatchAdversarialScenario(input),b=assessDispatchAdversarialScenario(input);assert.deepEqual(a,b);assert.equal(a.state,'CLEAR');assert.deepEqual(a.findings,[]);assert.deepEqual(summarizeDispatchAdversarialAssessment(a),{company_id,state:'CLEAR',total:0,critical:0,high:0,requires_human_review:false,automatic_dispatch:false,automatic_reassignment:false,direct_mutation:false,execution_permitted:false,grants_authority:false});});
