import test from 'node:test';
import assert from 'node:assert/strict';
import { assessDispatchRecovery, buildDispatchRestartRecoveryPlan, summarizeDispatchRecovery } from '../titan-workforce/dispatch/dispatch-recovery-runtime.mjs';
const ev=(x={})=>({company_id:'c1',event_id:'e1',event_type:'job.changed',work_item_id:'j1',source_revision:5,idempotency_key:'e1',payload_hash:'h1',...x});

test('exact duplicate event is suppressed as review evidence, not executed',()=>{const r=assessDispatchRecovery({company_id:'c1',canonical_job_revision:5,events:[ev(),ev()]});assert.deepEqual(r.duplicate_event_ids,['e1']);assert.equal(r.state,'REVIEW_REQUIRED');assert.equal(r.auto_replay,false);});
test('same event id with conflicting payload is blocked',()=>{const r=assessDispatchRecovery({company_id:'c1',canonical_job_revision:5,events:[ev(),ev({payload_hash:'h2'})]});assert.deepEqual(r.conflicting_event_ids,['e1']);assert.equal(r.requires_authoritative_refresh,true);assert.equal(r.state,'BLOCKED_STALE_OR_CONFLICTING_EVIDENCE');});
test('stale job revision blocks propagation and requests authoritative refresh',()=>{const r=assessDispatchRecovery({company_id:'c1',canonical_job_revision:8,events:[ev({source_revision:7})]});assert.deepEqual(r.stale_event_ids,['e1']);assert.equal(r.requires_authoritative_refresh,true);assert.equal(r.automatic_job_state_repair,false);});
test('future revision evidence also fails closed',()=>{const r=assessDispatchRecovery({company_id:'c1',canonical_job_revision:4,events:[ev({source_revision:5})]});assert.deepEqual(r.future_revision_event_ids,['e1']);assert.equal(r.state,'BLOCKED_STALE_OR_CONFLICTING_EVIDENCE');});
test('restart preserves safe queued idempotent work but never auto replays it',()=>{const r=buildDispatchRestartRecoveryPlan({company_id:'c1',now:10000,recovery_entries:[{company_id:'c1',operation_id:'op1',state:'queued',updated_at:9900,idempotent:true,operation_class:'durable_write'}],pending_operations:[{company_id:'c1',operation_id:'op1',idempotent:true,operation_class:'durable_write'}]});assert.deepEqual(r.resume_candidate_ids,['op1']);assert.equal(r.requires_explicit_resume,true);assert.equal(r.auto_replay,false);});
test('stale or authority-sensitive recovery work is quarantined',()=>{const r=assessDispatchRecovery({company_id:'c1',now:10000,stale_after_ms:1000,recovery_entries:[{company_id:'c1',operation_id:'old',state:'executing',updated_at:1,idempotent:true,operation_class:'durable_write'}],pending_operations:[{company_id:'c1',operation_id:'auth',idempotent:false,operation_class:'authority_sensitive'}]});assert.deepEqual(r.recovery_quarantine_ids,['auth','old']);assert.equal(r.execution_permitted,false);});
test('cross-company and legacy tenant evidence fail closed',()=>{assert.throws(()=>assessDispatchRecovery({company_id:'c1',events:[ev({company_id:'c2'})]}),/cross-company/);assert.throws(()=>assessDispatchRecovery({company_id:'c1',tenant_company_id:'bad'}),/legacy-company-boundary/);});
test('clean current evidence remains clear and authority neutral',()=>{const r=assessDispatchRecovery({company_id:'c1',canonical_job_revision:5,events:[ev()]});assert.equal(r.state,'CLEAR');assert.equal(r.canonical_job_state_owned_elsewhere,true);assert.equal(r.grants_authority,false);assert.deepEqual(summarizeDispatchRecovery(r),{company_id:'c1',state:'CLEAR',duplicate_count:0,conflict_count:0,stale_count:0,future_revision_count:0,quarantine_count:0,resume_candidate_count:0,auto_replay:false,execution_permitted:false,grants_authority:false});});
