/**
 * Merge62 UI/runtime reachability inventory, refreshed during Pass 9 regression.
 * Generated by TZ-FINISH-UI-RUNTIME-WIRING-001 Pass 1.
 * This is evidence/read-model data only; importing it grants no navigation or execution authority.
 */
import inventory from "./reachability-inventory.generated.json";

export type ReachabilityInventory = typeof inventory;
export const UI_RUNTIME_REACHABILITY_INVENTORY: ReachabilityInventory = inventory;

export function getUnresolvedStaticNavigationTargets() {
  return inventory.navigationTargets.filter((entry) => !entry.resolved);
}

export function getReachabilityRoute(route: string) {
  return inventory.pageRoutes.find((entry) => entry.route === route)
    ?? inventory.routeHandlers.find((entry) => entry.route === route)
    ?? null;
}

export function summarizeReachabilityInventory() {
  return { ...inventory.counts, managerMerge: inventory.generatedAgainst.managerMerge };
}
