import assert from "node:assert/strict";
import test from "node:test";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createServerNodeRuntime, ControlPlaneStore, CONTROL_PLANE_SCHEMA } from "./runtime.mjs";

async function fixture() { const dir = await fs.mkdtemp(path.join(os.tmpdir(), "titan-server-node-")); const runtime = createServerNodeRuntime({ authToken: "test-token", storePath: path.join(dir, "control.json"), dependencyProbe: async () => [{ name: "workforce", status: "healthy" }, { name: "redis", status: "healthy" }] }); const address = await runtime.start(); return { runtime, base: `http://127.0.0.1:${address.port}`, dir }; }
function headers(extra = {}) { return { authorization: "Bearer test-token", "x-titan-schema-version": "1", "x-titan-caller-id": "directadmin-test", "x-titan-company-id": "company-a", "x-titan-correlation-id": "corr-1", ...extra }; }
async function call(base, route, init = {}) { const response = await fetch(`${base}${route}`, { ...init, headers: { ...headers(), ...(init.headers ?? {}) } }); return { status: response.status, body: await response.json() }; }

test("serves authenticated health, bootstrap identity, and dependency graph projections", async (t) => { const f = await fixture(); t.after(() => f.runtime.close()); const result = await call(f.base, "/v1/health"); assert.equal(result.status, 200); assert.equal(result.body.schema, CONTROL_PLANE_SCHEMA); assert.equal(result.body.dependencies[0].status, "healthy"); const bootstrap = await call(f.base, "/v1/bootstrap"); assert.equal(bootstrap.status, 200); assert.equal(bootstrap.body.control_metadata_only, true); const graph = await call(f.base, "/v1/dependencies"); assert.ok(Array.isArray(graph.body.graph)); assert.deepEqual(graph.body.graph[0].depends_on, []); });
test("rejects missing identity, schema, and unauthorized callers", async (t) => { const f = await fixture(); t.after(() => f.runtime.close()); assert.equal((await fetch(`${f.base}/v1/health`)).status, 401); assert.equal((await call(f.base, "/v1/health", { headers: { "x-titan-schema-version": "9" } })).status, 426); assert.equal((await call(f.base, "/v1/health", { headers: { authorization: "Bearer wrong" } })).status, 401); });
test("accepts governed intents, refuses stale/cross-company calls, and deduplicates replay", async (t) => { const f = await fixture(); t.after(() => f.runtime.close()); const body = { kind: "service.restart", company_id: "company-a", capability_id: "node.lifecycle.request", idempotency_key: "intent-1", governed_execution_ref: "exec-1", authority_decision_ref: "decision-1", evidence_ref: "evidence-1", expires_at: new Date(Date.now() + 60_000).toISOString() }; const first = await call(f.base, "/v1/intents", { method: "POST", body: JSON.stringify(body), headers: { "content-type": "application/json" } }); assert.equal(first.status, 202); assert.equal(first.body.verified, false); assert.equal(first.body.execution_boundary, "canonical-execution-gateway"); const replay = await call(f.base, "/v1/intents", { method: "POST", body: JSON.stringify(body), headers: { "content-type": "application/json" } }); assert.equal(replay.status, 200); assert.equal(replay.body.replay, true); assert.equal((await call(f.base, "/v1/intents", { method: "POST", body: JSON.stringify({ ...body, idempotency_key: "intent-2", company_id: "company-b" }), headers: { "content-type": "application/json" } })).status, 403); assert.equal((await call(f.base, "/v1/intents", { method: "POST", body: JSON.stringify({ ...body, idempotency_key: "intent-3", expires_at: new Date(Date.now() - 1).toISOString() }), headers: { "content-type": "application/json" } })).status, 409); assert.equal((await call(f.base, "/v1/intents", { method: "POST", body: JSON.stringify({ ...body, idempotency_key: "intent-4", token: "do-not-store" }), headers: { "content-type": "application/json" } })).status, 400); assert.equal(f.runtime.store.state.denials.length, 2); });
test("persists control metadata across restart and validates snapshots", async (t) => { const f = await fixture(); const intent = { kind: "service.restart", company_id: "company-a", capability_id: "node.lifecycle.request", idempotency_key: "intent-restart", governed_execution_ref: "exec-2", authority_decision_ref: "decision-2", evidence_ref: "evidence-2", expires_at: new Date(Date.now() + 60_000).toISOString() }; await call(f.base, "/v1/intents", { method: "POST", body: JSON.stringify(intent), headers: { "content-type": "application/json" } }); const snapshot = f.runtime.store.exportSnapshot(); await f.runtime.close(); const restored = createServerNodeRuntime({ authToken: "test-token", storePath: path.join(f.dir, "control.json") }); await restored.start(); t.after(() => restored.close()); const response = await call(`http://127.0.0.1:${restored.server.address().port}`, "/v1/intents", { method: "POST", body: JSON.stringify(intent), headers: { "content-type": "application/json" } }); assert.equal(response.status, 200); const store = new ControlPlaneStore(path.join(f.dir, "restored.json")); await store.open(); await store.restoreSnapshot(snapshot); await assert.rejects(() => store.restoreSnapshot({ ...snapshot, schema_version: "titan.server-node/v0" }), /invalid|incompatible/); });

test("restores only a matching metadata snapshot and fails closed for a bad manifest", async (t) => { const f = await fixture(); t.after(() => f.runtime.close()); const snapshot = f.runtime.store.exportSnapshot(); const response = await call(f.base, "/v1/recovery/restore", { method: "POST", body: JSON.stringify({ snapshot, manifest_digest: "wrong" }), headers: { "content-type": "application/json" } }); assert.equal(response.status, 409); });
