// @ts-nocheck
// Ported from Titan Zero extension (portable-core): titan-onboarding/runtime/import-staging.mjs
import crypto from 'node:crypto';
import { normalizeCompanyContext } from '../../titan-local/kernel/company-context.js';

const LEGACY = new Set(['tenant_id','tenant_company_id','workspace_tenant_id','business_id']);
const DATASETS = new Set(['customers','jobs','history']);
const clean=(v,max=500)=>String(v??'').trim().slice(0,max);
const clone=v=>v==null?v:(globalThis.structuredClone?structuredClone(v):JSON.parse(JSON.stringify(v)));
function rejectLegacy(v,path='input'){if(!v||typeof v!=='object')return;if(Array.isArray(v))return v.forEach((x,i)=>rejectLegacy(x,`${path}[${i}]`));for(const[k,x]of Object.entries(v)){if(LEGACY.has(k))throw new Error(`${path}.${k} is a legacy company boundary; company_id is required`);rejectLegacy(x,`${path}.${k}`);}}
const hash=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object'){return Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])]))}return value;}
function fingerprint(dataset,row){return hash(JSON.stringify(stable({dataset,row})));}
function emailOk(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);}
function customerRow(raw,index){const row=raw&&typeof raw==='object'?raw:{};const display_name=clean(row.display_name||row.name,150);const email=clean(row.email,240).toLowerCase();const phone=clean(row.phone,30);const customer_type=clean(row.customer_type||'individual',24).toLowerCase();const errors=[];if(!['individual','business'].includes(customer_type))errors.push('customer_type_invalid');if(display_name.length<2)errors.push('display_name_required');if(!emailOk(email))errors.push('email_invalid');if(phone.length<8)errors.push('phone_invalid');return {dataset:'customers',index,valid:errors.length===0,errors,normalized:{external_id:clean(row.external_id||row.id,160)||null,customer_type,display_name,email,phone,street:clean(row.street,200)||null,suburb:clean(row.suburb,100)||null,state:clean(row.state,80)||null,postcode:clean(row.postcode,16)||null,communication_preference:clean(row.communication_preference||'email',24).toLowerCase(),marketing_consent:row.marketing_consent===true,notes:clean(row.notes,500)||null},target:{workflow:'titan-business-services/workflows/new_customer.json',capability:'crm.customer.create'}};}
function jobRow(raw,index){const row=raw&&typeof raw==='object'?raw:{};const customer_ref=clean(row.customer_id||row.customer_external_id,160);const service_id=clean(row.service_id,160);const address=clean(row.address,300);const scheduled_start=clean(row.scheduled_start,80);const scheduled_end=clean(row.scheduled_end,80);const price=Number(row.price);const errors=[];if(!customer_ref)errors.push('customer_reference_required');if(!service_id)errors.push('service_id_required');if(!address)errors.push('address_required');if(!scheduled_start)errors.push('scheduled_start_required');if(!scheduled_end)errors.push('scheduled_end_required');if(!Number.isFinite(price)||price<0)errors.push('price_invalid');return {dataset:'jobs',index,valid:errors.length===0,errors,normalized:{external_id:clean(row.external_id||row.id,160)||null,customer_ref,service_id,property_id:clean(row.property_id,160)||null,address,access_instructions:clean(row.access_instructions,500)||null,scheduled_start,scheduled_end,worker_ids:Array.isArray(row.worker_ids)?row.worker_ids.map(x=>clean(x,160)).filter(Boolean):[],checklist_id:clean(row.checklist_id,160)||null,price:Number.isFinite(price)?price:null,notes:clean(row.notes,1000)||null},target:{workflow:'titan-business-services/workflows/create_job.json',capability:'crm.work_order.create'}};}
function historyRow(raw,index){const row=raw&&typeof raw==='object'?raw:{};const occurred_at=clean(row.occurred_at||row.timestamp,80);const event_type=clean(row.event_type||row.type,120);const subject_type=clean(row.subject_type,80);const subject_ref=clean(row.subject_ref||row.subject_id,160);const errors=[];if(!occurred_at)errors.push('occurred_at_required');if(!event_type)errors.push('event_type_required');if(!subject_type)errors.push('subject_type_required');if(!subject_ref)errors.push('subject_ref_required');return {dataset:'history',index,valid:errors.length===0,errors,normalized:{external_id:clean(row.external_id||row.id,160)||null,occurred_at,event_type,subject_type,subject_ref,summary:clean(row.summary,500)||null,payload:clone(row.payload||{})},target:{owner:'historical-evidence-staging',capability:null}};}
function normalize(dataset,row,index){if(dataset==='customers')return customerRow(row,index);if(dataset==='jobs')return jobRow(row,index);return historyRow(row,index);}
function canonicalRows(dataset,rows){const out=[];const seen=new Map();for(let i=0;i<rows.length;i++){const item=normalize(dataset,rows[i],i);const fp=fingerprint(dataset,item.normalized);if(seen.has(fp)){out.push({...item,valid:false,errors:[...item.errors,'duplicate_row'],fingerprint:fp,duplicate_of:seen.get(fp)});continue;}seen.set(fp,i);out.push({...item,fingerprint:fp,duplicate_of:null});}return out;}
function summary(rows){return {total:rows.length,valid:rows.filter(x=>x.valid).length,invalid:rows.filter(x=>!x.valid).length,duplicates:rows.filter(x=>x.errors.includes('duplicate_row')).length};}
export function validateOnboardingImport(input={}){rejectLegacy(input,'import');const company_id=clean(input.company_id,128);if(!company_id)throw new Error('company_id is required');const datasets={};for(const dataset of DATASETS){const rows=Array.isArray(input[dataset])?input[dataset]:[];datasets[dataset]=canonicalRows(dataset,rows);}const summaries=Object.fromEntries([...DATASETS].map(k=>[k,summary(datasets[k])]));const invalid_count=Object.values(summaries).reduce((n,x)=>n+x.invalid,0);return Object.freeze({schema:'titan.onboarding.import-validation.v1',company_id,datasets:Object.freeze(datasets),summary:Object.freeze({customers:summaries.customers,jobs:summaries.jobs,history:summaries.history,invalid_count,ready_to_stage:invalid_count===0}),governance:Object.freeze({staging_only:true,live_mutation_permitted:false,authority_granted:false,execution_permitted:false})});}

export function createOnboardingImportStagingAuthority({database,clock=()=>Date.now()}={}){
 if(!database?.getRecord||!database?.putRecord||!database?.deleteRecord)throw new Error('business database with getRecord/putRecord/deleteRecord is required');
 const locator=id=>({module_id:'titan.onboarding',collection:'import-staging',record_id:id});
 async function stage(contextInput,input={}){rejectLegacy(contextInput,'context');rejectLegacy(input,'import');const context=normalizeCompanyContext(contextInput||{});if(input.company_id!=null&&clean(input.company_id,128)!==context.company_id)throw new Error('Cross-company import payload rejected');const validation=validateOnboardingImport({...input,company_id:context.company_id});if(!validation.summary.ready_to_stage)throw new Error('import validation failed; invalid rows cannot be staged');const import_id=clean(input.import_id,160)||`imp_${hash(`${context.company_id}:${JSON.stringify(stable(validation.datasets))}`).slice(0,24)}`;const prior=await database.getRecord(context,locator(import_id));if(prior?.data?.payload_hash){const candidate=hash(JSON.stringify(stable(validation.datasets)));if(candidate!==prior.data.payload_hash)throw new Error('import id already exists with different payload');return Object.freeze({ok:true,idempotent:true,company_id:context.company_id,import_id,revision:Number(prior.version||0),summary:clone(prior.data.summary),status:prior.data.status});}const payload_hash=hash(JSON.stringify(stable(validation.datasets)));const staged_at=Number(clock());const stored=await database.putRecord(context,{...locator(import_id),updated_at:staged_at,data:{schema:'titan.onboarding.import-staging-record.v1',company_id:context.company_id,import_id,status:'STAGED',payload_hash,summary:validation.summary,datasets:validation.datasets,staged_at,rollback_safe:true,live_mutation_permitted:false,authority_granted:false,execution_permitted:false},provenance:{source:'titan-onboarding-import-staging',customer_target:'crm.customer.create',job_target:'crm.work_order.create',history_target:'historical-evidence-staging',apply_step_included:false}});return Object.freeze({ok:true,idempotent:false,company_id:context.company_id,import_id,revision:Number(stored.version||1),summary:validation.summary,status:'STAGED',rollback_safe:true,live_mutation_permitted:false,authority_granted:false,execution_permitted:false});}
 async function inspect(contextInput,import_id){rejectLegacy(contextInput,'context');const context=normalizeCompanyContext(contextInput||{});const id=clean(import_id,160);if(!id)throw new Error('import_id is required');const rec=await database.getRecord(context,locator(id));if(!rec)return null;const d=rec.data||{};return Object.freeze({schema:'titan.onboarding.import-staging.view.v1',company_id:context.company_id,import_id:id,revision:Number(rec.version||0),status:d.status||'STAGED',summary:clone(d.summary||{}),datasets:clone(d.datasets||{}),rollback_safe:true,live_mutation_permitted:false,authority_granted:false,execution_permitted:false});}
 async function discard(contextInput,import_id){rejectLegacy(contextInput,'context');const context=normalizeCompanyContext(contextInput||{});const id=clean(import_id,160);if(!id)throw new Error('import_id is required');const prior=await database.getRecord(context,locator(id));if(!prior)return Object.freeze({ok:true,company_id:context.company_id,import_id:id,discarded:false,already_absent:true});await database.deleteRecord(context,locator(id));return Object.freeze({ok:true,company_id:context.company_id,import_id:id,discarded:true,rollback_action:'staging_record_deleted_only',live_records_affected:0,authority_granted:false,execution_permitted:false});}
 return Object.freeze({schema:'titan.onboarding.import-staging-authority.v1',company_boundary:'company_id',staging_only:true,apply_live_import_supported:false,authority_granted:false,execution_permitted:false,validate:input=>validateOnboardingImport(input),stage,inspect,discard});
}
