// @ts-nocheck
// Ported from Titan Zero extension (portable-core): titan-onboarding/runtime/payments-communications-setup.mjs
import { normalizeCompanyContext } from '../../titan-local/kernel/company-context.js';
import { projectProviderControlCentre } from '../../titan-settings/control-plane/ai-provider-control-centre.js';
import { projectNotificationEscalationSettings } from '../../titan-settings/control-plane/notification-escalation-settings.js';

const LEGACY = new Set(['tenant_id','tenant_company_id','workspace_tenant_id','business_id']);
const PAYMENT_METHODS = new Set(['payid','bank_transfer','cash','paypal','card_via_paypal']);
const clean=(v,max=240)=>String(v??'').trim().slice(0,max);
const clone=v=>v==null?v:(globalThis.structuredClone?structuredClone(v):JSON.parse(JSON.stringify(v)));
function rejectLegacy(v,path='input'){if(!v||typeof v!=='object')return;if(Array.isArray(v))return v.forEach((x,i)=>rejectLegacy(x,`${path}[${i}]`));for(const[k,x]of Object.entries(v)){if(LEGACY.has(k))throw new Error(`${path}.${k} is a legacy company boundary; company_id is required`);rejectLegacy(x,`${path}.${k}`);}}
function uniq(values,label){const out=[];for(const raw of Array.isArray(values)?values:[]){const v=clean(raw,160);if(!v)continue;if(out.includes(v))throw new Error(`duplicate ${label}: ${v}`);out.push(v);}return out;}
function normalisePayments(input={}){const methods=uniq(input.methods||input.payment_methods,'payment method').map(x=>x.toLowerCase());if(!methods.length)throw new Error('at least one payment method is required');for(const x of methods)if(!PAYMENT_METHODS.has(x))throw new Error(`unsupported payment method: ${x}`);return Object.freeze({methods:Object.freeze(methods),currency:clean(input.currency||'AUD',8).toUpperCase(),invoice_capability:'crm.invoice.create',reconciliation_capability:'finance.payment.reconcile',money_movement_permitted:false,refund_permitted:false,automatic_reconciliation:false,authority_granted:false,execution_permitted:false});}
function capabilityMap(nativeContributions){const entries=Array.isArray(nativeContributions?.entries)?nativeContributions.entries:Array.isArray(nativeContributions)?nativeContributions:[];return new Map(entries.map(x=>[clean(x?.id,160),x]).filter(([id])=>id));}
function normaliseCommunications(input={},nativeContributions){const ids=uniq(input.channel_capability_ids||input.channels,'communication channel');if(!ids.length)throw new Error('at least one communication channel is required');const byId=capabilityMap(nativeContributions);return Object.freeze(ids.map(id=>{const c=byId.get(id);if(!c)throw new Error(`unknown communication capability: ${id}`);if(!id.startsWith('channel.'))throw new Error(`communication capability must use channel.* namespace: ${id}`);return Object.freeze({capability_id:id,title:clean(c.title,180)||id,risk_class:clean(c.risk_class,40)||null,configured_reference_only:true,send_permitted:false,credentials_stored:false,activation_confers_authority:false,authority_granted:false,execution_permitted:false});}));}
function normaliseProviders(input={},company_id){const records=Array.isArray(input.providerConfigs)?input.providerConfigs:[];const projection=projectProviderControlCentre({company_id,providerConfigs:records,fallbackPolicy:input.fallbackPolicy||'manual'});return Object.freeze({fallback_policy:projection.fallback_policy,providers:Object.freeze(projection.providers.map(p=>Object.freeze({provider_id:p.provider_id,name:p.name,enabled:p.enabled,priority:p.priority,has_credentials:p.has_credentials,credential_material_copied:false}))),credential_storage:projection.credential_storage,credentials_exposed:false,credentials_stored_in_onboarding:false,authority_granted:false,execution_permitted:false});}
function normaliseNotifications(input={},company_id,workforceGlobalDefaults){const projection=projectNotificationEscalationSettings({company_id,notificationEscalationSettings:input,workforceGlobalDefaults:workforceGlobalDefaults||{}});return Object.freeze({...projection,settings_owner:'titan-settings/control-plane/notification-escalation-settings.js',dispatch_permitted:false,escalation_execution_permitted:false});}

export function createPaymentsCommunicationsSetupAuthority({database,nativeContributions,clock=()=>Date.now()}={}){
 if(!database?.getRecord||!database?.putRecord)throw new Error('business database is required');
 const locator=()=>({module_id:'titan.onboarding',collection:'payments-communications-setup',record_id:'canonical'});
 async function read(contextInput){rejectLegacy(contextInput,'context');const context=normalizeCompanyContext(contextInput||{});const prior=await database.getRecord(context,locator());const data=prior?.data||{};return Object.freeze({schema:'titan.onboarding.payments-communications-setup.view.v1',company_id:context.company_id,revision:Number(prior?.version||0),payments:clone(data.payments||null),communications:Object.freeze(clone(data.communications||[])),providers:clone(data.providers||null),notifications:clone(data.notifications||null),configuration_only:true,credentials_stored_in_onboarding:false,authority_granted:false,execution_permitted:false});}
 async function save(contextInput,input={}){rejectLegacy(contextInput,'context');rejectLegacy(input,'payments_communications_setup');const context=normalizeCompanyContext(contextInput||{});if(input.company_id!=null&&clean(input.company_id,128)!==context.company_id)throw new Error('Cross-company payments/communications setup payload rejected');const payments=normalisePayments(input.payments||{});const communications=normaliseCommunications(input.communications||{},nativeContributions);const providers=normaliseProviders(input.providers||{},context.company_id);const notifications=normaliseNotifications(input.notifications||{},context.company_id,input.workforceGlobalDefaults||{});const prior=await database.getRecord(context,locator());const priorVersion=Number(prior?.version||0);if(input.expected_revision!=null&&Number(input.expected_revision)!==priorVersion)throw new Error('payments/communications setup revision mismatch');const updated_at=Number(clock());const stored=await database.putRecord(context,{...locator(),updated_at,data:{schema:'titan.onboarding.payments-communications-setup-record.v1',company_id:context.company_id,payments,communications,providers,notifications,configuration_only:true,credentials_stored_in_onboarding:false,money_movement_permitted:false,message_send_permitted:false,provider_execution_permitted:false,notification_dispatch_permitted:false,authority_granted:false,execution_permitted:false,updated_at},provenance:{source:'titan-onboarding-payments-communications-setup',payment_contracts:['crm.invoice.create','finance.payment.reconcile'],communication_catalogue:'titan-capabilities/native-contributions.json',provider_settings_owner:'titan-settings/control-plane/ai-provider-control-centre.js',notification_settings_owner:'titan-settings/control-plane/notification-escalation-settings.js',credentials_copied:false}});return Object.freeze({ok:true,company_id:context.company_id,revision:Number(stored.version||priorVersion+1),payment_methods:payments.methods,channel_capability_ids:Object.freeze(communications.map(x=>x.capability_id)),provider_ids:Object.freeze(providers.providers.map(x=>x.provider_id)),configuration_only:true,credentials_stored_in_onboarding:false,authority_granted:false,execution_permitted:false});}
 return Object.freeze({schema:'titan.onboarding.payments-communications-setup-authority.v1',company_boundary:'company_id',configuration_only:true,authority_granted:false,execution_permitted:false,read,save});
}
