export const TITAN_MAPS_CONTRACT = Object.freeze({schema:"titan.maps-intelligence/v1",route_schema:"titan.maps.route-plan/v1",authority:"signals-and-proposals-only"});
export type MapsUncertainty="NONE"|"LOW"|"MEDIUM"|"HIGH"|"UNAVAILABLE";
export type MapsCoordinate=Readonly<{latitude:number;longitude:number;accuracy_m?:number}>;
export type MapsRouteAlternative=Readonly<{id:string;distance_km:number;duration_minutes:number;traffic_minutes?:number;uncertainty:MapsUncertainty}>;
export type MapsProviderPorts=Readonly<{id:string;health:"healthy"|"degraded"|"offline";route?:(ctx:Readonly<{company_id:string;request_id:string}>,from:MapsCoordinate,to:MapsCoordinate)=>Promise<readonly MapsRouteAlternative[]>;geocode?:(ctx:Readonly<{company_id:string;request_id:string}>,address:string)=>Promise<unknown>;places?:(ctx:Readonly<{company_id:string;request_id:string}>,query:string)=>Promise<readonly unknown[]>;traffic?:(ctx:Readonly<{company_id:string;request_id:string}>,route:MapsRoutePlan)=>Promise<unknown>}>;
export type MapsRoutePlan=Readonly<{schema:string;company_id:string;request_id:string;source:"provider"|"native-estimate";provider_id:string;observed_at:string;expires_at:string;stale:boolean;alternatives:readonly MapsRouteAlternative[];selected_alternative_id:string;distance_km:number;duration_minutes:number;eta:string;constraints:readonly string[];uncertainty:MapsUncertainty;receipt:Readonly<{provider_id:string;request_id:string;observed_at:string;response_digest:string;source:"provider"|"native-estimate";evidence_ref:string}>;authority_effect:false}>;
export type MapsRouteRequest=Readonly<{company_id:string;request_id:string;from:MapsCoordinate;to:MapsCoordinate;observed_at:string;freshness_minutes:number;constraints?:readonly string[]}>;
export type TerritoryShape=Readonly<{kind:"radius";center:MapsCoordinate;radius_km:number}>|Readonly<{kind:"polygon";points:readonly MapsCoordinate[]}>|Readonly<{kind:"postcode"|"suburb";values:readonly string[]}>|Readonly<{kind:"branch";branch_id:string;center:MapsCoordinate;radius_km:number}>;
export type MapsTerritory=Readonly<{id:string;company_id:string;shape:TerritoryShape;inclusions?:readonly TerritoryShape[];exclusions?:readonly TerritoryShape[];priority:number;travel_zone:string;config_version:string;proposal_id?:string}>;
export type TerritoryDecision=Readonly<{territory_id:string|null;travel_zone:string|null;matched:boolean;excluded:boolean;reason:string;config_version?:string;proposal_required:true;authority_effect:false}>;
export type GeofencePolicy=Readonly<{purpose:"dispatch-safety"|"arrival-assurance"|"service-area";consent_required:boolean;consent_granted:boolean;precision_m:number;retention_minutes:number}>;
export type GeofenceDecision=Readonly<{inside:boolean;uncertain:boolean;purpose:GeofencePolicy["purpose"];reason:string;retained_until:string|null;raw_location_persisted:false;authority_effect:false}>;
export type DispatchCandidateScore=Readonly<{worker_id:string;eligible:boolean;hard_failures:readonly string[];soft_score:number|null;signals:readonly Readonly<{kind:"distance"|"duration"|"travel-zone"|"route-risk";value:number|string;uncertainty:MapsUncertainty}>[];authority_effect:false}>;
const text=(v:unknown,c:string)=>{const s=String(v??"").trim();if(!s)throw new Error(c);return s;};
const finite=(c:MapsCoordinate)=>Number.isFinite(c.latitude)&&Number.isFinite(c.longitude)&&c.latitude>=-90&&c.latitude<=90&&c.longitude>=-180&&c.longitude<=180;
const hav=(a:MapsCoordinate,b:MapsCoordinate)=>{const r=(n:number)=>n*Math.PI/180,dl=r(b.latitude-a.latitude),do_=r(b.longitude-a.longitude),x=Math.sin(dl/2)**2+Math.cos(r(a.latitude))*Math.cos(r(b.latitude))*Math.sin(do_/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));};
const add=(v:string,m:number)=>new Date(new Date(v).getTime()+m*60000).toISOString();
const digest=(v:unknown)=>{let h=2166136261;for(const c of JSON.stringify(v)){h=Math.imul(h^c.charCodeAt(0),16777619);}return(h>>>0).toString(16);};
const unc=(d:number):MapsUncertainty=>d<=1?"LOW":d<=5?"MEDIUM":"HIGH";
export function createNativeRoutePlan(r:MapsRouteRequest,alts?:readonly MapsRouteAlternative[]):MapsRoutePlan{text(r.company_id,"maps_company_id_required");text(r.request_id,"maps_request_id_required");if(!finite(r.from)||!finite(r.to)||!Number.isFinite(new Date(r.observed_at).getTime()))throw new Error("maps_coordinates_or_time_required");const d=hav(r.from,r.to),a=alts?.length?alts:[{id:"native-estimate",distance_km:d,duration_minutes:Math.max(1,Math.round(d*2.2)),uncertainty:unc(d)}],s=a[0];return{schema:TITAN_MAPS_CONTRACT.route_schema,company_id:r.company_id,request_id:r.request_id,source:"native-estimate",provider_id:"titan-native-haversine",observed_at:new Date(r.observed_at).toISOString(),expires_at:add(r.observed_at,r.freshness_minutes),stale:false,alternatives:a,selected_alternative_id:s.id,distance_km:s.distance_km,duration_minutes:s.duration_minutes,eta:add(r.observed_at,s.duration_minutes),constraints:[...(r.constraints??[]),"native-estimate-only"],uncertainty:s.uncertainty,receipt:{provider_id:"titan-native-haversine",request_id:r.request_id,observed_at:r.observed_at,response_digest:digest(a),source:"native-estimate",evidence_ref:"maps:receipt:"+digest(r)},authority_effect:false};}
export async function planMapsRoute(r:MapsRouteRequest,ps:readonly MapsProviderPorts[]=[]):Promise<MapsRoutePlan>{const n=createNativeRoutePlan(r),p=ps.find(x=>x.health!=="offline"&&x.route);if(!p?.route)return n;try{const a=await Promise.race([p.route({company_id:r.company_id,request_id:r.request_id},r.from,r.to),new Promise<readonly MapsRouteAlternative[]>((_,rej)=>setTimeout(()=>rej(new Error("maps_provider_timeout")),5000))]);if(!a.length)return n;const s=a[0];return{...n,source:"provider",provider_id:p.id,alternatives:a,selected_alternative_id:s.id,distance_km:s.distance_km,duration_minutes:s.duration_minutes,eta:add(r.observed_at,s.duration_minutes),uncertainty:s.uncertainty,receipt:{provider_id:p.id,request_id:r.request_id,observed_at:r.observed_at,response_digest:digest(a),source:"provider",evidence_ref:"maps:receipt:"+digest(a)}};}catch{return n;}}
export function refreshRouteFreshness(r:MapsRoutePlan,at:string){const stale=new Date(at).getTime()>=new Date(r.expires_at).getTime();return{...r,stale,uncertainty:stale?"HIGH":r.uncertainty};}
const match=(q:{coordinate?:MapsCoordinate;postcode?:string;suburb?:string},s:TerritoryShape)=>s.kind==="radius"||s.kind==="branch"?!!q.coordinate&&finite(q.coordinate)&&hav(q.coordinate,s.center)<=s.radius_km:s.kind==="postcode"?!!q.postcode&&s.values.includes(q.postcode):s.kind==="suburb"?!!q.suburb&&s.values.map(x=>x.toLowerCase()).includes(q.suburb.toLowerCase()):s.kind==="polygon"&&!!q.coordinate&&s.points.length>2&&(()=>{let inside=false;for(let i=0,j=s.points.length-1;i<s.points.length;j=i++){const a=s.points[i],b=s.points[j],hit=(a.longitude>q.coordinate!.longitude)!==(b.longitude>q.coordinate!.longitude)&&q.coordinate!.latitude<((b.latitude-a.latitude)*(q.coordinate!.longitude-a.longitude))/(b.longitude-a.longitude)+a.latitude;if(hit)inside=!inside;}return inside;})();
export function resolveTerritory(q:{company_id:string;coordinate?:MapsCoordinate;postcode?:string;suburb?:string},ts:readonly MapsTerritory[]):TerritoryDecision{text(q.company_id,"maps_company_id_required");const m=ts.filter(t=>t.company_id===q.company_id&&match(q,t.shape)&&!(t.exclusions??[]).some(s=>match(q,s))&&(t.inclusions??[]).every(s=>match(q,s))).sort((a,b)=>b.priority-a.priority)[0];return m?{territory_id:m.id,travel_zone:m.travel_zone,matched:true,excluded:false,reason:"priority-matched",config_version:m.config_version,proposal_required:true,authority_effect:false}:{territory_id:null,travel_zone:null,matched:false,excluded:false,reason:"company-isolated-or-outside-territory",proposal_required:true,authority_effect:false};}
export function evaluateGeofence(i:{coordinate:MapsCoordinate;center:MapsCoordinate;radius_m:number;policy:GeofencePolicy;observed_at:string}):GeofenceDecision{if(!finite(i.coordinate)||!finite(i.center))throw new Error("maps_coordinates_required");if(i.policy.consent_required&&!i.policy.consent_granted)return{inside:false,uncertain:true,purpose:i.policy.purpose,reason:"consent-required",retained_until:null,raw_location_persisted:false,authority_effect:false};const d=hav(i.coordinate,i.center)*1000,a=i.coordinate.accuracy_m??Infinity,u=a>i.radius_m/2||Math.abs(d-i.radius_m)<=a;return{inside:d<=i.radius_m,uncertain:u,purpose:i.policy.purpose,reason:u?"location-precision-uncertain":d<=i.radius_m?"inside-geofence":"outside-geofence",retained_until:add(i.observed_at,i.policy.retention_minutes),raw_location_persisted:false,authority_effect:false};}
export function scoreDispatchCandidate(i:{company_id:string;worker_id:string;available:boolean;skills:readonly string[];qualifications:readonly string[];window:{start:string;end:string};territory:TerritoryDecision;safety_ok:boolean;route:MapsRoutePlan|null;safety_uncertainty:MapsUncertainty}):DispatchCandidateScore{const f:string[]=[];if(!i.company_id||!i.worker_id)f.push("identity-required");if(!i.available)f.push("worker-unavailable");if(!i.skills.length||!i.qualifications.length)f.push("skills-or-qualifications-missing");if(!i.territory.matched||i.territory.excluded)f.push("territory-ineligible");if(!i.safety_ok||i.safety_uncertainty==="HIGH")f.push("safety-ineligible");if(new Date(i.window.end).getTime()<=new Date(i.window.start).getTime())f.push("customer-window-invalid");if(f.length)return{worker_id:i.worker_id,eligible:false,hard_failures:f,soft_score:null,signals:[],authority_effect:false};const d=i.route?.distance_km??Infinity,m=i.route?.duration_minutes??Infinity;return{worker_id:i.worker_id,eligible:true,hard_failures:[],soft_score:Number.isFinite(d+m)?Math.max(0,100-d*2-m*.5):0,signals:[{kind:"distance",value:d,uncertainty:i.route?.uncertainty??"UNAVAILABLE"},{kind:"duration",value:m,uncertainty:i.route?.uncertainty??"UNAVAILABLE"}],authority_effect:false};}
export function createPricingSignals(r:MapsRoutePlan){return[{company_id:r.company_id,kind:"distance" as const,value:r.distance_km,unit:"km",uncertainty:r.uncertainty,observed_at:r.observed_at,authority_effect:false as const},{company_id:r.company_id,kind:"duration" as const,value:r.duration_minutes,unit:"minutes",uncertainty:r.uncertainty,observed_at:r.observed_at,authority_effect:false as const}];}
export function reconcileAcceptedAssignment(i:{assignment_id:string;company_id:string;accepted:MapsRoutePlan;refreshed:MapsRoutePlan}){if(i.company_id!==i.refreshed.company_id||i.company_id!==i.accepted.company_id)throw new Error("maps_cross_company");const changed=i.accepted.distance_km!==i.refreshed.distance_km||i.accepted.duration_minutes!==i.refreshed.duration_minutes;return{assignment_id:i.assignment_id,changed:false as const,reason:changed?"new-route-is-observation-proposal":"route-unchanged",proposal:changed?{type:"ROUTE_REFRESH" as const,route:i.refreshed}:null,authority_effect:false as const};}
export function planMultiVisitDay(i:{company_id:string;visits:readonly {id:string;from:MapsCoordinate;to:MapsCoordinate;worker_id:string;territory:TerritoryDecision}[];outage?:boolean}){text(i.company_id,"maps_company_id_required");const legs:MapsRoutePlan[]=[];const reassignments:string[]=[];for(const v of i.visits){if(v.territory.matched)legs.push(createNativeRoutePlan({company_id:i.company_id,request_id:"day:"+v.id,from:v.from,to:v.to,observed_at:"2026-10-02T00:00:00Z",freshness_minutes:30}));else reassignments.push(v.id);}return{company_id:i.company_id,legs,reassignments,uncertainty:i.outage?"HIGH":legs.length?"MEDIUM":"UNAVAILABLE",authority_effect:false as const};}
