import {buildNativeGovernance,applyNativeGovernanceHeaders} from "./governance";
import type { AuthSession } from "@/lib/auth/middleware";
import { buildTitanJobsPlan, type TitanJobsPlanInput } from "@ai-fsm/titan-platform/workforce-native";
export type JobsNativeRequest = Omit<TitanJobsPlanInput,"companyId"|"actorId"> & {dryRun?:boolean};
const ALLOWED_ROLES=new Set(["owner","admin"]);
function assertRole(session:AuthSession){if(!ALLOWED_ROLES.has(session.role))throw new Error("ROLE_NOT_AUTHORIZED");}
function materializePath(path:string,id:string|null){if(!path.includes(":id"))return path;if(!id)throw new Error("jobs-entity-id-required");return path.replace(":id",encodeURIComponent(id));}
function buildSearch(query:Readonly<Record<string,unknown>>){const s=new URLSearchParams();for(const [k,v] of Object.entries(query))if(v!=null)s.set(k,String(v));const q=s.toString();return q?`?${q}`:"";}
export function buildNativeJobsPlan(session:AuthSession,input:JobsNativeRequest){assertRole(session);return buildTitanJobsPlan({...input,companyId:session.accountId,actorId:session.userId,traceId:input.traceId??session.traceId});}
export async function executeNativeJobsAction(request:Request,session:AuthSession,input:JobsNativeRequest){const plan=buildNativeJobsPlan(session,input);const governance=buildNativeGovernance(session,plan,request);if(input.dryRun||plan.operation===null)return{dryRun:Boolean(input.dryRun),executed:false,plan,governance}as const;const source=new URL(request.url);const target=new URL(`${materializePath(plan.operation.path,plan.entity_id)}${buildSearch(plan.query)}`,source.origin);const headers=applyNativeGovernanceHeaders(new Headers(),governance);const cookie=request.headers.get("cookie");if(cookie)headers.set("cookie",cookie);headers.set("accept","application/json");headers.set("x-titan-workforce-agent","jobs");headers.set("x-titan-workforce-operation",plan.operation.id);headers.set("x-titan-company-id",session.accountId);headers.set("x-titan-trace-id",session.traceId);if(plan.operation.method!=="GET")headers.set("content-type","application/json");const response=await fetch(target,{method:plan.operation.method,headers,body:plan.operation.method==="GET"?undefined:JSON.stringify(plan.body??{}),cache:"no-store",redirect:"manual"});const ct=response.headers.get("content-type")??"";const result=ct.includes("application/json")?await response.json().catch(()=>null):await response.text().catch(()=>"");return{dryRun:false,executed:true,plan,governance,upstream:{status:response.status,ok:response.ok,result}}as const;}
