(function attachRepositoryReceiverAdapter(global){
'use strict';
const REQUIRED=['registerRepositoryCapability','registerPrompts','registerSkills','registerProfiles','registerDiagnosticsSection','registerSettingsSection','registerContextProvider'];
function register(host,options){const missing=REQUIRED.filter(k=>typeof host?.[k]!=='function');if(missing.length)throw new Error(`Repository pack receiver APIs missing: ${missing.join(', ')}`);const descriptor=global.CodeeRepositoryCodingPack.registrationDescriptor();for(const id of descriptor.capabilities)host.registerRepositoryCapability({id,pack:descriptor.id,authority:descriptor.authority});host.registerPrompts(descriptor.prompts);host.registerSkills(descriptor.skills);host.registerProfiles(descriptor.profiles);
host.registerContextProvider({id:'repository-runner-context',surface:'runner',priority:60,provide:(snapshot,input)=>global.CodeeRepositoryCodingPack.analyze(snapshot,input)});
host.registerContextProvider({id:'repository-plan-preflight',surface:'multi_step_plans',priority:60,provide:(snapshot,input)=>global.CodeeRepositoryCodingPack.analyze(snapshot,input)});
host.registerDiagnosticsSection({id:'repository-coding-intelligence',title:'Repository & MCP',build:(snapshot,input)=>global.CodeeRepositoryCodingPack.analyze(snapshot,input)});
host.registerSettingsSection({id:'repository-coding-intelligence',title:'Repository & Coding',defaults:{...descriptor.settings},fields:[{key:'enabled',type:'boolean',label:'Enable repository intelligence'},{key:'includeExtensions',type:'boolean',locked:true,value:true,label:'Include app/Extensions/**'},{key:'maxSearchResults',type:'number',min:20,max:1000,label:'Maximum search results'},{key:'maxRemoteContextChars',type:'number',min:1000,max:100000,label:'Maximum MCP context characters'},{key:'requireVerifiedBackupBeforeMutation',type:'boolean',locked:true,value:true,label:'Require verified backup before every mutation'},{key:'consumeMcpRuntime',type:'boolean',label:'Consume Codee MCP runtime when available'}]});
return {registered:true,createdTopLevelTabs:0,surfaces:['runner','multi_step_plans','prompts','skills','settings','diagnostics'],capabilities:descriptor.capabilities.length,authority:{planAdvance:false,repositoryMutation:'host-owned-only-after-backup',mcpRuntime:false}};}
global.CodeeRepositoryReceiverAdapter=Object.freeze({register,REQUIRED});
})(typeof globalThis!=='undefined'?globalThis:this);
