import assert from 'node:assert/strict';
import { hardenCheckpointForPersistence } from './production-hardening.mjs';
const base={schema:'titan.offline.restart-checkpoint.v1',company_id:'co-a',operation_id:'op-1',state:'recovery_required',terminal:false,recovery_count:2,requires_explicit_resume:true,automatic_effect_replay:false,effect_replay_allowed:false,authority_neutral:true};
const safe=hardenCheckpointForPersistence(base,{company_id:'co-a'});
assert.equal(safe.company_id,'co-a');
assert.equal(safe.operation_id,'op-1');
assert.equal(safe.requires_explicit_resume,true);
assert.equal(safe.automatic_effect_replay,false);
assert.equal(safe.effect_replay_allowed,false);
assert.equal(safe.authority_neutral,true);
await assert.rejects(async()=>hardenCheckpointForPersistence({...base,effect_replay_allowed:true},{company_id:'co-a'}),/effect-replay-allowed-true/);
await assert.rejects(async()=>hardenCheckpointForPersistence({...base,automatic_effect_replay:true},{company_id:'co-a'}),/automatic-effect-replay-true/);
await assert.rejects(async()=>hardenCheckpointForPersistence({...base,authority_neutral:false},{company_id:'co-a'}),/authority-neutral-false/);
await assert.rejects(async()=>hardenCheckpointForPersistence({...base,company_id:'co-b'},{company_id:'co-a'}),/cross-company/);
await assert.rejects(async()=>hardenCheckpointForPersistence({...base,state:'mystery'},{company_id:'co-a'}),/state-invalid/);
await assert.rejects(async()=>hardenCheckpointForPersistence({...base,terminal:true,state:'resumed'},{company_id:'co-a'}),/terminal-state-mismatch/);
await assert.rejects(async()=>hardenCheckpointForPersistence({...base,requires_explicit_resume:false},{company_id:'co-a'}),/recovery-resume-invariant/);
await assert.rejects(async()=>hardenCheckpointForPersistence({...base,nested:{tenant_id:'legacy'}},{company_id:'co-a'}),/legacy-company-boundary/);
console.log('Pass10 production hardening PASS');
