import SectionLabel from '../components/SectionLabel'
import CTASection from '../components/CTASection'
const apps=[
['Command','Owner / manager Zero',['business control','workforce','decisions','communications','systems','approvals','intelligence'],'For an owner or manager, Zero becomes a digital operating counterpart: helping understand the business, coordinating specialist intelligence and handling delegated digital operations.'],
['Go','Staff / field Zero',['digital admin','current work','schedules','communications','procedures','job knowledge','maps','visual guidance','evidence capture'],'For staff, Zero can take over appropriate online and digital work while guiding and assisting physical work with the right job context, knowledge and next actions.'],
['Hub','Customer Zero',['bookings','changes','questions','service history','quotes','support','account information','communication','visual help'],'For a customer, Zero becomes a personal service companion. It helps them manage their relationship with the business without needing to learn the business systems behind it.']
]
export default function Apps(){return <><section className="pt-32 pb-16 px-6 text-center"><div className="max-w-5xl mx-auto"><SectionLabel>Titan Zero Apps</SectionLabel><h1 className="text-4xl sm:text-6xl font-extrabold mb-5">Different person. Different Zero.<br/><span className="text-nx-purple-light">Same connected business.</span></h1><p className="text-lg text-nx-muted max-w-3xl mx-auto">One is whoever owns the account in use. Command, Go and Hub adapt the relationship with Zero to an owner or manager, a staff member or a customer while preserving the appropriate business context and authority boundaries.</p></div></section>
<section className="px-6 pb-16"><div className="max-w-6xl mx-auto grid lg:grid-cols-3 gap-5">{apps.map(([name,who,items,close])=><article key={name} className="bg-nx-surface border border-nx-border rounded-2xl p-7"><div className="text-xs uppercase tracking-widest text-nx-purple-light mb-2">{who}</div><h2 className="text-3xl font-extrabold mb-5">Titan Zero {name}</h2><div className="flex flex-wrap gap-2 mb-6">{items.map(x=><span key={x} className="bg-nx-bg border border-nx-border rounded-lg px-3 py-2 text-xs">{x}</span>)}</div><p className="text-sm text-nx-muted leading-relaxed">{close}</p></article>)}</div></section>
<section className="py-20 px-6 border-y border-nx-border"><div className="max-w-6xl mx-auto grid lg:grid-cols-2 gap-10"><div><SectionLabel>Customer Zero</SectionLabel><h2 className="text-4xl font-extrabold mb-4">Hub is more than a customer portal.</h2><p className="text-nx-muted leading-relaxed mb-4">The customer can ask their Zero to book a service, move an appointment, explain a quote, show service history, ask what happened on the last visit, get support or use the camera to show a problem.</p><p className="text-nx-muted leading-relaxed">Their Zero can translate that intent into the appropriate interaction with the business while keeping the customer in control of decisions that belong to them.</p></div><div className="bg-nx-surface border border-nx-border rounded-2xl p-7"><h3 className="text-xl font-bold mb-4">One account. One personal relationship.</h3><p className="text-sm text-nx-muted leading-relaxed mb-4">The customer's Zero should understand the customer's own service relationship, preferences, history and authorised context — not expose the internal understanding or authority of staff, managers or other customers.</p><p className="text-sm text-nx-muted leading-relaxed">Business Reality can be shared where appropriate. Personal Zero understanding stays personal. Authority follows the account holder, role, relationship and explicit delegation.</p></div></div></section>
<CTASection title="Every person can be One." subtitle="Owner, worker or customer — their Zero adapts to who they are, what they are responsible for and what they are allowed to do."/></>}