import { useState } from 'react'
import { ChevronDown } from 'lucide-react'
import SectionLabel from '../components/SectionLabel'
import CTASection from '../components/CTASection'

const faqs=[
{q:'Who is One?',a:'One is the human account holder whose Titan Zero identity is in use. One is not automatically the owner of the business. One may be an owner, manager, office worker, field worker or customer. Each can have their own Zero shaped around their role, relationship, context and authority.'},
{q:'What is Your Zero?',a:'Your Zero is your personal digital working intelligence — a working shadow, assistant and, where appropriate, digital operator. It can progressively understand how you work, handle appropriate digital work, assist with real-world work and coordinate specialist capabilities around your role.'},
{q:'What does One + Zero + Team mean?',a:'One is the human account holder. Zero is that person’s persistent digital working intelligence. Team is the relevant specialist intelligence, systems and people Zero can coordinate within that person’s role. Different people can therefore have different Zeros inside the same connected business.'},
{q:'What does Zero do for staff?',a:'For staff, Zero can take on appropriate online and digital work such as information retrieval, system updates, communications, forms, documentation and administration. For field staff it can also guide physical jobs with procedures, job context, visual assistance, evidence capture and next actions.'},
{q:'What does Zero do for customers?',a:'For customers, Zero can become a personal service companion. It can help book or change services, explain quotes, show relevant service history, get support, communicate with the business and use camera input to help describe a problem — without requiring the customer to learn the business’s internal systems.'},
{q:'Does Zero get more authority as it learns?',a:'No. Learning, confidence, prediction and previous success do not themselves grant permission to act. Titan Zero separates intelligence from authority. Delegation remains explicit and can be capability-specific, bounded, reduced or revoked.'},
{q:'Can Zero learn from mistakes?',a:'Titan Zero is designed to learn from corrections and measured outcomes, not only repeat habits. It can compare what was known, decided, done, expected and what actually happened, while allowing old learning to be reassessed when circumstances materially change.'},
{q:'Can Titan Zero say it does not know?',a:'Yes. Titan Zero is designed to distinguish known, observed, confirmed, inferred, uncertain and contradicted information. When evidence is insufficient, it can preserve that uncertainty and investigate further rather than treating a guess as a fact.'},
{q:'What does the managed service include?',a:'The managed service helps a cleaning business assess its workflows and current software, plan implementation, connect systems where supported, configure appropriate capabilities and maintain the resulting system. Exact scope depends on the business and the verified release state.'},
{q:'Do I have to replace my existing cleaning software?',a:'No. Titan Zero is designed to keep useful systems where they fit. The Cleaning implementation is designed to connect around the current stack and add Titan Zero software or interfaces when an operational gap remains.'},
{q:'Is Titan Zero just an AI chatbot?',a:'No. Chat, voice and camera are interaction surfaces. Behind them, Titan Zero coordinates authorised workforce capabilities, business knowledge, integrations, software functions, governance and operational workflows.'},
{q:'Is the Cleaning SaaS live?',a:'Not yet. The repository contains a substantial cleaning catalogue, workflow blueprint and dedicated tests, but the marketing release evidence still marks the Cleaning runtime as in development and the public cleaning host as not published.'},
{q:'Can Titan Zero use private or local AI models?',a:'The architecture supports device, customer-hosted, BYO-cloud and Titan-managed approaches where suitable. Private/local LLMs and private retrieval over authorised business knowledge can be used for appropriate workloads.'},
{q:'Can I use my own AI or API keys?',a:'Where a provider or integration supports it, Titan Zero is designed to allow customer-owned provider accounts and keys rather than requiring every usage cost to be hidden inside one bundled subscription.'},
{q:'Which cleaning businesses is Titan Zero being built for?',a:'The current Cleaning service model includes regular, one-off, deep, end-of-lease, short-stay turnover, commercial, office, move-in / move-out, carpet, upholstery, window, pressure, post-construction and custom cleaning variants.'},
{q:'How is authority controlled?',a:'An intelligence result, recommendation or prediction does not automatically grant permission to execute. Trust can progress capability by capability from observe, recommend and prepare through ask-and-execute toward bounded automation where appropriate. A trust increase requires system eligibility, explicit human delegation and current system/Zero acceptance under the applicable conditions.'},
{q:'What are Environmental Systems?',a:'Titan Zero can connect environmental assessment, auditing, evidence, compliance and improvement workflows to business operations. Where professional environmental judgement or sign-off is required, work can be performed or reviewed by appropriately qualified environmental scientists.'},
{q:'How is Titan Zero different from cleaning SaaS?',a:'Titan Zero is being built around the cleaning business and its workflows. The Cleaning vertical models service scope, recurring work, crews, room and site records, quality evidence and follow-up on top of shared platform capabilities. Its production release is still in development.'},
{q:'Does local AI always cost less?',a:'Not necessarily. Cost depends on workload, hardware, provider, model and management requirements. Local models, customer-owned compute and BYO keys can change the cost structure and reduce some third-party usage, but Titan Zero does not promise a fixed saving.'},
]
function FAQItem({q,a}){const[open,setOpen]=useState(false);const id=`faq-${q.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}`;return <div className={`border border-nx-border rounded-xl overflow-hidden ${open?'border-nx-purple/50':''}`}><button className="w-full flex items-center justify-between gap-4 px-6 py-4 text-left" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls={id}><span className="text-sm font-semibold">{q}</span><ChevronDown size={16} aria-hidden="true" className={`text-nx-muted transition-transform ${open?'rotate-180':''}`}/></button>{open&&<div id={id} className="px-6 pb-5"><p className="text-sm text-nx-muted leading-relaxed">{a}</p></div>}</div>}
export default function FAQ(){return <><section className="pt-32 pb-16 px-6 text-center"><div className="max-w-7xl mx-auto"><SectionLabel>FAQ</SectionLabel><h1 className="text-4xl sm:text-5xl font-extrabold mb-4">Understand the <span className="text-nx-purple-light">Titan Zero model.</span></h1><p className="text-lg text-nx-muted max-w-2xl mx-auto">How Your Zero, the managed workforce, learning, authority, existing-system integration, privacy architecture and cost model work.</p></div></section><section className="px-6 pb-24"><div className="max-w-3xl mx-auto space-y-3">{faqs.map(f=><FAQItem key={f.q}{...f}/>)}</div></section><CTASection/></>}