import SectionLabel from '../components/SectionLabel'
import CTASection from '../components/CTASection'
const groups=[
['Your Zero can see',['A customer can show their Zero a problem instead of describing it in a form.','A worker can show their Zero equipment or a job condition.','A cleaner can document completed work.','A technician can show an unfamiliar component.','An environmental specialist can capture site evidence.']],
['Your Zero can understand location',['Routing','Scheduling','Field operations','Service areas','Assets','Travel','Environmental context','Geographically distributed work']],
['Your Zero can communicate',['Phone','Messaging','Email','In-app communication','Context continuity across supported channels']]
]
export default function RealWorldIntelligence(){return <><section className="pt-32 pb-16 px-6 text-center"><div className="max-w-5xl mx-auto"><SectionLabel>Real-World Intelligence</SectionLabel><h1 className="text-4xl sm:text-6xl font-extrabold mb-5">Chat. Voice. <span className="text-nx-purple-light">Camera.</span></h1><p className="text-lg text-nx-muted max-w-3xl mx-auto">Titan Zero isn't intended to make owners, staff or customers live inside administration dashboards. Each person can work naturally with their own Zero: chat with it, talk to it or show it what they mean.</p></div></section>
<section className="px-6 pb-24"><div className="max-w-6xl mx-auto grid lg:grid-cols-3 gap-5">{groups.map(([t,items])=><div key={t} className="bg-nx-surface border border-nx-border rounded-2xl p-7"><h2 className="text-2xl font-bold mb-5">{t}</h2><div className="space-y-3">{items.map(x=><p key={x} className="text-sm text-nx-muted">{x}</p>)}</div></div>)}</div></section>
<section className="py-20 px-6 border-t border-nx-border"><div className="max-w-6xl mx-auto"><SectionLabel>The same senses, different context</SectionLabel><div className="grid md:grid-cols-3 gap-4"><div className="bg-nx-surface border border-nx-border rounded-2xl p-6"><h2 className="font-bold mb-2">Customer</h2><p className="text-sm text-nx-muted">Show Zero a leaking fitting, damaged surface or service concern and use that visual context to communicate with the business.</p></div><div className="bg-nx-surface border border-nx-border rounded-2xl p-6"><h2 className="font-bold mb-2">Field worker</h2><p className="text-sm text-nx-muted">Show Zero the job, equipment or site condition and receive authorised procedures, context, evidence prompts and next actions.</p></div><div className="bg-nx-surface border border-nx-border rounded-2xl p-6"><h2 className="font-bold mb-2">Owner or office staff</h2><p className="text-sm text-nx-muted">Talk through an operational problem, inspect evidence and move between conversation and generated controls without learning another complex interface.</p></div></div></div></section>
<section className="py-20 px-6 border-y border-nx-border"><div className="max-w-5xl mx-auto text-center"><h2 className="text-4xl font-extrabold mb-5">Conversation when conversation is best.<br/><span className="text-nx-purple-light">Interface when interface is best.</span></h2><p className="text-lg text-nx-muted">When a visual interface is useful, Titan can generate the appropriate controls, evidence, choices or workflow rather than forcing every interaction through chat.</p></div></section>
<CTASection title="Bring intelligence closer to the work." subtitle="Ask it, tell it or show it — with the appropriate context, evidence and authority around the interaction."/></>}