// @ts-nocheck
const clean=(v,max=1000)=>String(v??'').trim().slice(0,max);
const norm=v=>clean(v,500).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const tokens=v=>new Set(norm(v).split(/\s+/).filter(x=>x.length>1));
const validCompany=v=>/^[A-Za-z0-9._:-]{2,128}$/.test(clean(v,128));
const QUOTE_CHAIN={orchestrator:'quote',manager:'titan.manager.sales',supervisor:'titan.sales.sales_coordinator',specialist:'titan.sales.quote_coordinator',worker:'titan.worker.create_quote_agent'};
function requireBase(input={}){const company_id=clean(input.company_id,128);if(!validCompany(company_id))throw new Error('service-quote-company_id-required');const evidence_ref=clean(input.evidence_ref,260);if(!evidence_ref)throw new Error('service-quote-evidence-ref-required');const idempotency_key=clean(input.idempotency_key,220);if(!idempotency_key)throw new Error('service-quote-idempotency-key-required');return{company_id,evidence_ref,idempotency_key};}
function scoreNeed(need,svc){const a=tokens(need), labels=[svc.name,svc.service_name,svc.description,...(svc.aliases||[]),...(svc.keywords||[])].filter(Boolean).join(' '),b=tokens(labels);if(!a.size||!b.size)return 0;let hit=0;for(const t of a)if(b.has(t))hit++;const exact=norm(need)===norm(svc.name??svc.service_name);return Math.min(1,(hit/a.size)*.8+(exact?.2:0));}
export function matchQualifiedCallToService(input={}){const b=requireBase(input),need=clean(input.service_need??input.qualification?.service_need,220);if(!need)throw new Error('service-quote-service-need-required');const catalogue=Array.isArray(input.service_catalogue)?input.service_catalogue:[];const candidates=catalogue.filter(s=>s&&String(s.company_id??b.company_id)===b.company_id&&s.active!==false).map(s=>({service:s,score:scoreNeed(need,s)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||clean(a.service.service_id??a.service.id).localeCompare(clean(b.service.service_id??b.service.id)));
const top=candidates[0]??null,second=candidates[1]??null;const ambiguous=!!(top&&second&&top.score>=.55&&second.score>=.55&&top.score-second.score<.25);const matched=!!top&&top.score>=.55&&!ambiguous;return{schema:'titan.workforce.call-service-match.v1',...b,service_need:need,status:matched?'MATCHED':ambiguous?'AMBIGUOUS':'NO_CONFIDENT_MATCH',service_match:matched?{service_id:clean(top.service.service_id??top.service.id,160),variant_id:clean(top.service.variant_id,160)||null,name:clean(top.service.name??top.service.service_name,220),score:Number(top.score.toFixed(3)),fixed_price:top.service.fixed_price===true,price_ref:top.service.price_ref??null,price:Number.isFinite(Number(top.service.price))?Number(top.service.price):null,currency:clean(top.service.currency,20)||null,required_pricing_inputs:Array.isArray(top.service.required_pricing_inputs)?top.service.required_pricing_inputs.map(x=>clean(x,120)).filter(Boolean):[]}:null,candidate_count:candidates.length,ambiguity_requires_human_review:ambiguous,persistence_performed:false,grants_authority:false,execution_permitted:false};}
export function assessQuoteReadiness(input={}){const m=matchQualifiedCallToService(input);if(!m.service_match)return{...m,schema:'titan.workforce.call-quote-readiness.v1',quote_ready:false,missing_pricing_inputs:[],status:m.status==='AMBIGUOUS'?'SERVICE_MATCH_REVIEW_REQUIRED':'SERVICE_MATCH_REQUIRED',quote_creation_performed:false};const provided=input.pricing_inputs&&typeof input.pricing_inputs==='object'?input.pricing_inputs:{};const required=m.service_match.required_pricing_inputs;const missing=required.filter(k=>provided[k]===undefined||provided[k]===null||clean(provided[k],300)==='');const fixedReady=m.service_match.fixed_price&&(m.service_match.price_ref||Number.isFinite(m.service_match.price));const quote_ready=missing.length===0&&(fixedReady||required.length>0||input.pricing_evidence_complete===true);return{...m,schema:'titan.workforce.call-quote-readiness.v1',pricing_inputs:provided,missing_pricing_inputs:missing,quote_ready,status:quote_ready?'READY_FOR_QUOTE_PROPOSAL':missing.length?'PRICING_INPUTS_REQUIRED':'PRICING_REVIEW_REQUIRED',quote_creation_performed:false};}
export function planServiceQuoteHandoff(input={}){const r=assessQuoteReadiness(input);const handoffs=[];if(!r.service_match){handoffs.push({type:'GOVERNED_HANDOFF',intent:'review_service_catalogue_match',company_id:r.company_id,evidence_ref:r.evidence_ref,service_need:r.service_need,requires_human_review:true,execution_permitted:false});return{...r,handoffs,recommended_orchestrator:null};}if(!r.quote_ready){handoffs.push({type:'GOVERNED_HANDOFF',intent:'collect_missing_quote_inputs',...QUOTE_CHAIN,target_worker:QUOTE_CHAIN.worker,company_id:r.company_id,evidence_ref:r.evidence_ref,service_ref:{service_id:r.service_match.service_id,variant_id:r.service_match.variant_id},missing_pricing_inputs:r.missing_pricing_inputs,requires_approval:true,execution_permitted:false});return{...r,handoffs,recommended_orchestrator:'quote'};}handoffs.push({type:'GOVERNED_HANDOFF',intent:'prepare_quote_from_catalogue_match_proposal',...QUOTE_CHAIN,target_worker:QUOTE_CHAIN.worker,company_id:r.company_id,evidence_ref:r.evidence_ref,lead_ref:clean(input.lead_ref,220)||null,customer_ref:clean(input.customer_ref,220)||null,service_ref:{service_id:r.service_match.service_id,variant_id:r.service_match.variant_id},pricing_inputs:r.pricing_inputs,price_ref:r.service_match.price_ref,requires_approval:true,execution_permitted:false});return{...r,handoffs,recommended_orchestrator:'quote'};}
export default{matchQualifiedCallToService,assessQuoteReadiness,planServiceQuoteHandoff};
