import test from 'node:test';
import assert from 'node:assert/strict';
import { buildCleaningExecutionPack } from '../.cleaning-test-dist/verticals/cleaning/execution.js';
import { buildCleaningQaReview } from '../.cleaning-test-dist/verticals/cleaning/qa.js';

const execution=()=>buildCleaningExecutionPack({company_id:'company-a',job_ref:'job:1',booking_ref:'booking:1',site_ref:'site:a',service_id:'regular_clean',areas:[{area_ref:'kitchen',label:'Kitchen',checklist_items:['sink','bench'],evidence_required:['completion_photo']}],equipment_available:['vacuum','mop','microfibre kit','approved general chemicals'],completion:{completed_checklist_item_refs:['sink','bench'],evidence_refs:['photo:complete'],sync_state:'SYNCED'}});
const base=()=>({company_id:'company-a',job_ref:'job:1',execution_pack:execution(),supervisor_ref:'worker:supervisor-1',inspection_ref:'inspection:1',inspection_items:[{item_ref:'qa:sink',area_ref:'kitchen',status:'PASS'}],supervisor_signoff_ref:'signoff:supervisor'});

test('Pass7 clean QA pass stays a projection and preserves shared owners',()=>{const q=buildCleaningQaReview(base());assert.equal(q.outcome,'PASS');assert.equal(q.qa_passed,true);assert.equal(q.quality.quality_score,100);assert.equal(q.job_mutation_emitted,false);assert.equal(q.grants_authority,false);assert.equal(q.owners.customer_care,'shared_customer_care_owner');});
test('missed items create rework proposals without automatic task creation or reassignment',()=>{const q=buildCleaningQaReview({...base(),inspection_items:[{item_ref:'qa:sink',area_ref:'kitchen',status:'MISS',note_ref:'note:miss'}]});assert.equal(q.outcome,'REWORK_REQUIRED');assert.equal(q.requires_rework,true);assert.equal(q.rework_items[0].requires_jobs_owner_task_creation,true);assert.equal(q.rework_items[0].automatic_reassignment,false);assert.equal(q.rework_task_mutation_emitted,false);assert.equal(q.requires_fresh_rework_authority,true);});
test('defects and blocked/high-severity findings require evidence and escalation',()=>{assert.throws(()=>buildCleaningQaReview({...base(),inspection_items:[{item_ref:'qa:defect',area_ref:'kitchen',status:'DEFECT',note_ref:'note:defect'}]}),/inspection evidence required/);const q=buildCleaningQaReview({...base(),inspection_items:[{item_ref:'qa:defect',area_ref:'kitchen',status:'DEFECT',note_ref:'note:defect',evidence_refs:['photo:defect'],severity:'HIGH'}]});assert.equal(q.outcome,'ESCALATION_REQUIRED');assert.equal(q.requires_escalation,true);});
test('customer issues route to Customer Care but authorize no refund credit or remedy',()=>{const q=buildCleaningQaReview({...base(),customer_issues:[{issue_ref:'issue:1',category:'quality_concern',note_ref:'note:customer',customer_requested_followup:true}]});assert.equal(q.outcome,'PASS_WITH_NOTES');assert.equal(q.requires_customer_care,true);assert.equal(q.service_recovery[0].remedy_authorized,false);assert.equal(q.service_recovery[0].refund_authorized,false);assert.equal(q.service_recovery[0].credit_authorized,false);assert.equal(q.customer_remedy_mutation_emitted,false);});
test('damage concerns escalate to Customer Care/service recovery review',()=>{const q=buildCleaningQaReview({...base(),customer_issues:[{issue_ref:'issue:damage',category:'damage_concern',note_ref:'note:damage',evidence_refs:['photo:damage']}]});assert.equal(q.outcome,'ESCALATION_REQUIRED');assert.equal(q.requires_customer_care,true);assert.equal(q.requires_fresh_customer_remedy_authority,true);});
test('quality score is bounded and projection-only',()=>{const q=buildCleaningQaReview({...base(),quality_dimensions:{checklist:90,evidence:80,finish:70,customer_readiness:60}});assert.equal(q.quality.quality_score,75);assert.equal(q.quality_is_projection,true);assert.throws(()=>buildCleaningQaReview({...base(),quality_dimensions:{checklist:101,evidence:80,finish:70,customer_readiness:60}}),/between 0 and 100/);});
test('unfinished/conflicted execution cannot become a QA pass',()=>{const pack=buildCleaningExecutionPack({company_id:'company-a',job_ref:'job:1',site_ref:'site:a',service_id:'regular_clean',areas:[{area_ref:'kitchen',label:'Kitchen',checklist_items:['sink'],evidence_required:['completion_photo']}],equipment_available:[],completion:{completed_checklist_item_refs:[],evidence_refs:[],sync_state:'CONFLICT'}});const q=buildCleaningQaReview({...base(),execution_pack:pack});assert.equal(q.outcome,'ESCALATION_REQUIRED');assert.equal(q.completion_ready_before_qa,false);});
test('company, job, area and duplicate identities fail closed',()=>{assert.throws(()=>buildCleaningQaReview({...base(),company_id:'company-b'}),/cross-company/);assert.throws(()=>buildCleaningQaReview({...base(),job_ref:'job:other'}),/job_ref mismatch/);assert.throws(()=>buildCleaningQaReview({...base(),inspection_items:[{item_ref:'qa:x',area_ref:'garage',status:'PASS'}]}),/unknown cleaning area/);assert.throws(()=>buildCleaningQaReview({...base(),inspection_items:[{item_ref:'qa:x',status:'PASS'},{item_ref:'qa:x',status:'PASS'}]}),/duplicate inspection item_ref/);assert.throws(()=>buildCleaningQaReview({...base(),tenant_id:'legacy'}),/legacy tenant boundary/);});
