import test from 'node:test';
import assert from 'node:assert/strict';
import { buildCleaningExecutionPack } from '../.cleaning-test-dist/verticals/cleaning/execution.js';

const base={company_id:'company-a',job_ref:'job:1',booking_ref:'booking:1',site_ref:'site:a',service_id:'regular_clean',areas:[{area_ref:'kitchen',label:'Kitchen',selected_inclusions:['kitchen surfaces and sink'],checklist_items:['kitchen surfaces and sink'],evidence_required:['completion_photo']}],equipment_available:['vacuum','mop','microfibre kit','approved general chemicals'],supplies_available:['cloths'],supply_requirements:['cloths'],completion:{completed_checklist_item_refs:['kitchen surfaces and sink'],evidence_refs:['photo:1'],completed_at_local:'2026-09-13T08:00:00+10:00',device_ref:'device:go-1',offline_sequence:4,sync_state:'QUEUED'}};

test('Pass6 builds offline-safe room/area execution pack with selected inclusions and evidence',()=>{const p=buildCleaningExecutionPack(base);assert.equal(p.areas[0].area_ref,'kitchen');assert.deepEqual(p.areas[0].selected_inclusions,['kitchen surfaces and sink']);assert.equal(p.completion.completion_ready,true);assert.equal(p.completion.sync_state,'QUEUED');assert.equal(p.offline_safe,true);});
test('missing equipment supplies checklist and evidence block completion without mutating job',()=>{const p=buildCleaningExecutionPack({...base,equipment_available:[],supplies_available:[],completion:{sync_state:'LOCAL_ONLY'}});assert.equal(p.completion.completion_ready,false);assert.ok(p.completion.blockers.some(x=>x.startsWith('EQUIPMENT_MISSING:')));assert.ok(p.completion.blockers.includes('SUPPLY_MISSING:cloths'));assert.ok(p.completion.blockers.includes('EVIDENCE_INCOMPLETE'));assert.equal(p.job_mutation_emitted,false);assert.equal(p.completion_mutation_emitted,false);});
test('offline conflict fails closed while queued/local state remains representable',()=>{const conflict=buildCleaningExecutionPack({...base,completion:{...base.completion,sync_state:'CONFLICT'}});assert.equal(conflict.completion.completion_ready,false);assert.ok(conflict.completion.blockers.includes('OFFLINE_SYNC_CONFLICT'));const local=buildCleaningExecutionPack({...base,completion:{...base.completion,sync_state:'LOCAL_ONLY'}});assert.equal(local.completion.sync_state,'LOCAL_ONLY');});
test('exceptions retain note/evidence references and must target known area',()=>{const p=buildCleaningExecutionPack({...base,exception_notes:[{area_ref:'kitchen',code:'PRE_EXISTING_DAMAGE',note_ref:'note:1',evidence_refs:['photo:damage']}]});assert.equal(p.exceptions[0].note_ref,'note:1');assert.throws(()=>buildCleaningExecutionPack({...base,exception_notes:[{area_ref:'garage',code:'X',note_ref:'n'}]}),/unknown cleaning area/);});
test('company boundary, services and area identity fail closed',()=>{assert.throws(()=>buildCleaningExecutionPack({...base,company_id:''}),/company_id is required/);assert.throws(()=>buildCleaningExecutionPack({...base,tenant_id:'legacy'}),/legacy tenant boundary/);assert.throws(()=>buildCleaningExecutionPack({...base,service_id:'missing'}),/unknown cleaning service/);assert.throws(()=>buildCleaningExecutionPack({...base,areas:[base.areas[0],base.areas[0]]}),/duplicate cleaning area_ref/);});
test('execution pack preserves canonical owners and grants no authority',()=>{const p=buildCleaningExecutionPack(base);assert.equal(p.owners.job,'shared_jobs_owner');assert.equal(p.owners.evidence,'shared_evidence_owner');assert.equal(p.owners.customer_care,'shared_customer_care_owner');assert.equal(p.grants_authority,false);assert.equal(p.execution_permitted,false);assert.equal(p.proposal_only,true);});
