import test from "node:test";
import assert from "node:assert/strict";
import { validateDirectAdminPluginPackage, assertPluginCanBeInstalled, resolveDirectAdminTitanContext, validateDirectAdminCompanyContext, DirectAdminContributionRegistry, DirectAdminTitanApiClient, redactDirectAdminDiagnostics } from "../.test-dist/directadmin-plugin.js";
const base={plugin_id:"titan_sdk",version:"1.0.0",archive_filename:"titan_sdk.tar.gz",manifest_content:"name=Titan SDK\nversion=1.0.0\n",files:["plugin.conf","README.md","AGENTS.md","scripts/install.sh","scripts/uninstall.sh","admin/index.html","reseller/index.html","user/index.html"],executable_files:["scripts/install.sh","scripts/uninstall.sh","admin/index.html","reseller/index.html","user/index.html"],role_entrypoints:{admin:"admin/index.html",reseller:"reseller/index.html",user:"user/index.html"},hooks:["hooks/navigation.php"]};
test("accepts a complete flat plugin package",()=>{const r=validateDirectAdminPluginPackage(base);assert.equal(r.valid,true);assert.equal(assertPluginCanBeInstalled(r),true);});
test("reports missing package contract files and roles",()=>{const r=validateDirectAdminPluginPackage({...base,files:["plugin.conf"],role_entrypoints:{...base.role_entrypoints,admin:"admin/missing.php"}});assert.equal(r.valid,false);assert.ok(r.errors.includes("missing-file:README.md"));assert.ok(r.errors.includes("missing-role-entrypoint:admin"));});
test("rejects traversal paths",()=>{const r=validateDirectAdminPluginPackage({...base,files:[...base.files,"../secrets"],hooks:["hooks/../secret.php"]});assert.equal(r.valid,false);assert.ok(r.errors.some(x=>x.startsWith("unsafe-file-path:")));assert.ok(r.errors.some(x=>x.startsWith("unsafe-hook-path:")));assert.throws(()=>assertPluginCanBeInstalled(r),/plugin-validation-failed/);});
test("requires archive identity, matching manifest version and final archive executable modes",()=>{const r=validateDirectAdminPluginPackage({...base,archive_filename:"titan_sdk-1.0.0.tar.gz",manifest_content:"name=Titan SDK\nversion=2.0.0\n",executable_files:["scripts/install.sh"]});assert.equal(r.valid,false);assert.ok(r.errors.includes("archive-filename-must-match-plugin-id"));assert.ok(r.errors.includes("manifest-version-mismatch"));assert.ok(r.errors.includes("role-entrypoint-not-executable:admin"));assert.ok(r.errors.includes("lifecycle-script-not-executable:scripts/uninstall.sh"));});

const session={authenticated:true,session_id:"session-1",account_id:"da-account-1",role:"admin"};
const identity={actor_id:"actor-1",allowed_company_ids:["company-a","company-b"],active_company_id:"company-a",entitlements:["ops.read"],session_revision:"rev-4",authority_revision:"authority-7",expires_at:10_000};
test("DirectAdmin role is presentation context and identity resolution is server supplied",async()=>{const result=await resolveDirectAdminTitanContext(session,async received=>{assert.equal(received.role,"admin");return identity;},1_000);assert.equal(result.status,"resolved");assert.equal(result.context.company_id,"company-a");assert.equal(result.context.authority,"not-carried");assert.equal(result.context.da_role,"admin");assert.equal(validateDirectAdminCompanyContext(result.context,"company-a","rev-4",1_001),true);});
test("admin, reseller and user roles never change resolved Titan actor/company",async()=>{const results=await Promise.all(["admin","reseller","user"].map(role=>resolveDirectAdminTitanContext({...session,role},async()=>identity,1_000)));assert.deepEqual(results.map(x=>x.status),["resolved","resolved","resolved"]);assert.deepEqual(results.map(x=>x.status==="resolved"?x.context.actor_id:null),["actor-1","actor-1","actor-1"]);assert.deepEqual(results.map(x=>x.status==="resolved"?x.context.company_id:null),["company-a","company-a","company-a"]);});
test("unresolved, expired and cross-company identity contexts fail closed",async()=>{assert.deepEqual(await resolveDirectAdminTitanContext({...session,authenticated:false},async()=>identity),{status:"read-only",reason:"unauthenticated"});assert.deepEqual(await resolveDirectAdminTitanContext(session,async()=>null),{status:"read-only",reason:"unresolved-identity"});assert.deepEqual(await resolveDirectAdminTitanContext(session,async()=>({...identity,active_company_id:"company-c"})),{status:"read-only",reason:"invalid-company-context"});const expired=await resolveDirectAdminTitanContext(session,async()=>({...identity,expires_at:5}),10);assert.equal(expired.status,"read-only");if(expired.status==="read-only")assert.equal(expired.reason,"expired-context");const resolved=await resolveDirectAdminTitanContext(session,async()=>identity,1);assert.equal(resolved.status,"resolved");if(resolved.status==="resolved"){assert.equal(validateDirectAdminCompanyContext(resolved.context,"company-b","rev-4",1),false);assert.equal(validateDirectAdminCompanyContext(resolved.context,"company-a","rev-old",1),false);assert.equal(validateDirectAdminCompanyContext(resolved.context,"company-a","rev-4",10_000),false);}});
test("identity-service failure degrades read-only",async()=>assert.deepEqual(await resolveDirectAdminTitanContext(session,async()=>{throw new Error("offline")}),{status:"read-only",reason:"identity-service-unavailable"}));
test("contribution registry validates routes and isolates a bad plugin",()=>{const registry=new DirectAdminContributionRegistry();registry.register({plugin_id:"titan_zero",plugin_version:"1.0.0",sdk_compatibility:"1.0.0",navigation:[{id:"home",label:"Home",route:"/CMD_PLUGINS_ADMIN/titan_zero",roles:["admin"]}],widgets:[{id:"health",title:"Health",status:"degraded",source:"server-node",freshness:null,deep_link:"/CMD_PLUGINS_ADMIN/titan_zero/health",permitted_actions:[],evidence_refs:[]}]});registry.register({plugin_id:"titan_bad",plugin_version:"1.0.0",sdk_compatibility:"1.0.0",navigation:[{id:"evil",label:"Evil",route:"//attacker.invalid",roles:["admin"]}],widgets:[]});const result=registry.snapshot();assert.equal(result.contributions.length,1);assert.ok(result.degraded_plugins.titan_bad);assert.equal(result.contributions[0].plugin_id,"titan_zero");});
test("contribution registry degrades unsupported SDK majors and recovers a corrected plugin",()=>{
  const registry=new DirectAdminContributionRegistry("1.0.0");
  const contribution=(plugin_id,sdk_compatibility)=>({plugin_id,plugin_version:"1.2.0",sdk_compatibility,navigation:[{id:"home",label:"Home",route:`/CMD_PLUGINS_ADMIN/${plugin_id}`,roles:["admin"]}],widgets:[]});
  registry.register(contribution("titan_zero","1.7.0"));
  registry.register(contribution("titan_future","2.0.0"));
  const degraded=registry.snapshot();
  assert.deepEqual(degraded.contributions.map(item=>item.plugin_id),["titan_zero"]);
  assert.equal(degraded.degraded_plugins.titan_future,"sdk-compatibility-mismatch:required-major-2:supported-major-1");
  registry.register(contribution("titan_future","1.4.0"));
  const recovered=registry.snapshot();
  assert.deepEqual(recovered.contributions.map(item=>item.plugin_id),["titan_future","titan_zero"]);
  assert.equal(Object.hasOwn(recovered.degraded_plugins,"titan_future"),false);
  assert.throws(()=>new DirectAdminContributionRegistry("not-a-version"),/invalid-sdk-compatibility-version/);
});
test("API client sends scoped assertions and governed intents only to same-origin versioned routes",async()=>{const resolved=await resolveDirectAdminTitanContext(session,async()=>identity,1);assert.equal(resolved.status,"resolved");if(resolved.status!=="resolved")return;let seen;const client=new DirectAdminTitanApiClient(resolved.context,async(input,init)=>{seen={input,init};return new Response(JSON.stringify({status:"requested"}),{status:202,headers:{"content-type":"application/json"}});},()=>"request-1");const response=await client.submitIntent("/v1/intents",{company_id:"company-a",actor_id:"actor-1",capability_id:"domain.dns.update",operation_id:"operation-1",correlation_id:"correlation-1",input:{record:"example.test"}},2);assert.deepEqual(response,{status:"requested"});assert.equal(seen.input,"/v1/intents");assert.equal(seen.init.credentials,"same-origin");assert.equal(seen.init.redirect,"error");assert.equal(seen.init.headers["X-Titan-Company-ID"],"company-a");assert.equal(seen.init.headers["X-Titan-Actor-ID"],"actor-1");assert.equal(seen.init.headers["X-Titan-Request-ID"],"request-1");assert.equal(seen.init.headers.Authorization,undefined);await assert.rejects(client.submitIntent("/v1/intents",{company_id:"company-b",actor_id:"actor-1",capability_id:"test",operation_id:"op",correlation_id:"corr",input:{}},2),/context-mismatch/);await assert.rejects(client.projection("https://attacker.test/v1/status",2),/invalid-titan-api-path/);});
test("API client rejects stale context before network access",async()=>{const resolved=await resolveDirectAdminTitanContext(session,async()=>identity,1);if(resolved.status!=="resolved")throw new Error("fixture failed");let calls=0;const client=new DirectAdminTitanApiClient(resolved.context,async()=>{calls++;return new Response("{}")},()=>"id");await assert.rejects(client.projection("/v1/health",10_000),/context-expired/);assert.equal(calls,0);});
test("diagnostics redact sensitive fields and bearer/private-key values",()=>{const safe=redactDirectAdminDiagnostics({actor_id:"actor-1",authorization:"Bearer test-token",nested:{api_key:"key",message:"Rejected Bearer abc.def and -----BEGIN OPENSSH PRIVATE KEY-----private-----END OPENSSH PRIVATE KEY-----"}});assert.deepEqual(safe,{actor_id:"actor-1",authorization:"[REDACTED]",nested:{api_key:"[REDACTED]",message:"Rejected [REDACTED] and [REDACTED]"}});});
test("diagnostics redact inline CSRF headers, csrf assignments and Basic authorization",()=>{
  const safe=redactDirectAdminDiagnostics({message:"Request failed: X-Titan-CSRF: csrfNonce_29-x; Authorization: Basic dGl0YW46c2VjcmV0; csrf=bodyNonce.42"});
  assert.equal(safe.message,"Request failed: [REDACTED]; [REDACTED]; [REDACTED]");
  assert.doesNotMatch(safe.message,/csrfNonce_29-x|dGl0YW46c2VjcmV0|bodyNonce\.42/);
});
