import test from "node:test";import assert from "node:assert/strict";import{createNativeRoutePlan,createPricingSignals,evaluateGeofence,planMapsRoute,planMultiVisitDay,reconcileAcceptedAssignment,resolveTerritory,refreshRouteFreshness,scoreDispatchCandidate}from"../.test-dist/maps-intelligence/runtime.js";
const r=()=>({company_id:"co",request_id:"r",from:{latitude:-33.87,longitude:151.2},to:{latitude:-33.9,longitude:151.25},observed_at:"2026-10-02T00:00:00Z",freshness_minutes:30});
test("native deterministic fallback",()=>{const a=createNativeRoutePlan(r()),b=createNativeRoutePlan(r());assert.deepEqual(a,b);assert.equal(a.source,"native-estimate");});
test("provider alternatives receipts and timeout fallback",async()=>{const p=await planMapsRoute(r(),[{id:"road",health:"healthy",route:async()=>[{id:"fast",distance_km:7,duration_minutes:18,uncertainty:"LOW"},{id:"safe",distance_km:8,duration_minutes:20,uncertainty:"LOW"}]}]);assert.equal(p.source,"provider");assert.equal(p.alternatives.length,2);assert.ok(p.receipt.evidence_ref);assert.equal((await planMapsRoute(r(),[{id:"off",health:"offline",route:async()=>[]}])).source,"native-estimate");assert.equal((await planMapsRoute(r(),[{id:"timeout",health:"healthy",route:async()=>{throw new Error("provider-timeout");}}])).source,"native-estimate");});
test("territory priority exclusion and isolation",()=>{const t=[{id:"o",company_id:"co",shape:{kind:"radius",center:r().from,radius_km:20},priority:1,travel_zone:"o",config_version:"1"},{id:"i",company_id:"co",shape:{kind:"radius",center:r().from,radius_km:5},exclusions:[{kind:"postcode",values:["2000"]}],priority:2,travel_zone:"i",config_version:"2"}];assert.equal(resolveTerritory({company_id:"co",coordinate:r().from,postcode:"2001"},t).territory_id,"i");assert.equal(resolveTerritory({company_id:"other",coordinate:r().from},t).territory_id,null);});
test("geofence consent precision retention and purpose",()=>{const d=evaluateGeofence({coordinate:{...r().from,accuracy_m:5},center:r().from,radius_m:100,policy:{purpose:"arrival-assurance",consent_required:true,consent_granted:false,precision_m:50,retention_minutes:30},observed_at:r().observed_at});assert.equal(d.reason,"consent-required");assert.equal(d.raw_location_persisted,false);});
test("hard eligibility precedes route score",()=>{const t=resolveTerritory({company_id:"co",coordinate:r().from},[{id:"t",company_id:"co",shape:{kind:"radius",center:r().from,radius_km:5},priority:1,travel_zone:"z",config_version:"1"}]);const d=scoreDispatchCandidate({company_id:"co",worker_id:"w",available:false,skills:["s"],qualifications:["q"],window:{start:"2026-10-02T01:00:00Z",end:"2026-10-02T02:00:00Z"},territory:t,safety_ok:true,route:createNativeRoutePlan(r()),safety_uncertainty:"LOW"});assert.equal(d.eligible,false);assert.equal(d.soft_score,null);});
test("pricing neutral, outage uncertainty and replay conflict",()=>{const route=createNativeRoutePlan(r());assert.equal(createPricingSignals(route)[0].authority_effect,false);const day=planMultiVisitDay({company_id:"co",outage:true,visits:[{id:"v",from:r().from,to:r().to,worker_id:"w",territory:resolveTerritory({company_id:"co",coordinate:r().from},[{id:"t",company_id:"co",shape:{kind:"radius",center:r().from,radius_km:5},priority:1,travel_zone:"z",config_version:"1"}])}]});assert.equal(day.uncertainty,"HIGH");assert.throws(()=>reconcileAcceptedAssignment({assignment_id:"a",company_id:"co",accepted:route,refreshed:{...route,company_id:"other"}}),/maps_cross_company/);});
test("provider stale refresh, missing coordinates and timezone-safe timestamps",()=>{const route=createNativeRoutePlan(r());const stale={...route,expires_at:"2026-10-01T00:00:00Z"};const refreshed=refreshRouteFreshness(stale,r().observed_at);assert.equal(refreshed.stale,true);assert.equal(refreshed.uncertainty,"HIGH");assert.throws(()=>createNativeRoutePlan({...r(),from:{latitude:99,longitude:151.2}}),/maps_coordinates_or_time_required/);assert.equal(route.observed_at,"2026-10-02T00:00:00.000Z");const offset=createNativeRoutePlan({...r(),observed_at:"2026-10-02T10:00:00+10:00"});assert.equal(offset.observed_at,route.observed_at);assert.equal(Date.parse(route.observed_at),Date.parse(r().observed_at));});
