import test from "node:test";
import assert from "node:assert/strict";
import {createMemoryStorageAdapter,createCompanyRepository} from "../.test-dist/storage/index.js";
import {createFieldEvidenceSync} from "../.test-dist/offline/index.js";

const ctx=(company_id="company-a")=>({company_id,actor_id:"field",operation_id:"evidence-test"});
function setup(opts={}){let now=1000;const repository=createCompanyRepository({adapter:createMemoryStorageAdapter(),clock:()=>now});const sync=createFieldEvidenceSync({repository,clock:()=>now,chunk_size:4,max_bytes:20,...opts});return{repository,sync,setNow:v=>{now=v}};}
const media=(over={})=>({evidence_id:"ev1",operation_id:"op1",idempotency_key:"idem1",media_kind:"photo",mime_type:"image/jpeg",byte_size:10,checksum:"sha256:file",local_blob_ref:"device://blob/1",metadata:{job_id:"j1"},...over});

test("evidence metadata queues durably without storing media bytes",async()=>{const{sync}=setup();const r=await sync.enqueue(ctx(),media());assert.equal(r.status,"queued");assert.equal(r.item.total_chunks,3);assert.equal(r.item.local_blob_ref,"device://blob/1");assert.equal("bytes" in r.item,false);assert.equal(sync.descriptor.bytes_authority,"caller_device_storage");});
test("duplicate enqueue is idempotent but changed identity conflicts",async()=>{const{sync}=setup();await sync.enqueue(ctx(),media());assert.equal((await sync.enqueue(ctx(),media())).status,"duplicate");await assert.rejects(()=>sync.enqueue(ctx(),media({checksum:"different"})),/identity-conflict/);});
test("max media size fails closed",async()=>{const{sync}=setup();await assert.rejects(()=>sync.enqueue(ctx(),media({byte_size:21})),/max-bytes/);});
test("chunk acknowledgements advance resumable progress in order",async()=>{const{sync}=setup();await sync.enqueue(ctx(),media());await sync.begin(ctx(),{evidence_id:"ev1",remote_upload_id:"up1"});let r=await sync.acknowledgeChunk(ctx(),{evidence_id:"ev1",remote_upload_id:"up1",chunk_index:0,chunk_bytes:4,chunk_checksum:"c0"});assert.equal(r.next_chunk_index,1);r=await sync.acknowledgeChunk(ctx(),{evidence_id:"ev1",remote_upload_id:"up1",chunk_index:1,chunk_bytes:4,chunk_checksum:"c1"});assert.equal(r.uploaded_bytes,8);});
test("duplicate chunk acknowledgement is safe and out-of-order chunk fails closed",async()=>{const{sync}=setup();await sync.enqueue(ctx(),media());await sync.begin(ctx(),{evidence_id:"ev1",remote_upload_id:"up1"});await sync.acknowledgeChunk(ctx(),{evidence_id:"ev1",remote_upload_id:"up1",chunk_index:0,chunk_bytes:4,chunk_checksum:"c0"});assert.equal((await sync.acknowledgeChunk(ctx(),{evidence_id:"ev1",remote_upload_id:"up1",chunk_index:0,chunk_bytes:4,chunk_checksum:"c0"})).duplicate_chunk,true);await assert.rejects(()=>sync.acknowledgeChunk(ctx(),{evidence_id:"ev1",remote_upload_id:"up1",chunk_index:2,chunk_bytes:2,chunk_checksum:"c2"}),/out-of-order/);});
test("interruption and coordinator recreation resume from durable next chunk",async()=>{const adapter=createMemoryStorageAdapter();const repository=createCompanyRepository({adapter,clock:()=>1000});const first=createFieldEvidenceSync({repository,clock:()=>1000,chunk_size:4,max_bytes:20});await first.enqueue(ctx(),media());await first.begin(ctx(),{evidence_id:"ev1",remote_upload_id:"up1"});await first.acknowledgeChunk(ctx(),{evidence_id:"ev1",remote_upload_id:"up1",chunk_index:0,chunk_bytes:4,chunk_checksum:"c0"});await first.markInterrupted(ctx(),{evidence_id:"ev1",error:"network"});const second=createFieldEvidenceSync({repository,clock:()=>2000,chunk_size:4,max_bytes:20});const r=await second.resume(ctx(),{evidence_id:"ev1",remote_upload_id:"up1"});assert.equal(r.next_chunk_index,1);assert.equal(r.uploaded_bytes,4);assert.equal(r.state,"uploading");});
test("completion requires every byte and matching checksum",async()=>{const{sync}=setup();await sync.enqueue(ctx(),media());await sync.begin(ctx(),{evidence_id:"ev1",remote_upload_id:"up1"});await assert.rejects(()=>sync.complete(ctx(),{evidence_id:"ev1",remote_upload_id:"up1",remote_evidence_ref:"remote/1",checksum:"sha256:file"}),/incomplete/);await sync.acknowledgeChunk(ctx(),{evidence_id:"ev1",remote_upload_id:"up1",chunk_index:0,chunk_bytes:4,chunk_checksum:"c0"});await sync.acknowledgeChunk(ctx(),{evidence_id:"ev1",remote_upload_id:"up1",chunk_index:1,chunk_bytes:4,chunk_checksum:"c1"});await sync.acknowledgeChunk(ctx(),{evidence_id:"ev1",remote_upload_id:"up1",chunk_index:2,chunk_bytes:2,chunk_checksum:"c2"});await assert.rejects(()=>sync.complete(ctx(),{evidence_id:"ev1",remote_upload_id:"up1",remote_evidence_ref:"remote/1",checksum:"wrong"}),/checksum/);const done=await sync.complete(ctx(),{evidence_id:"ev1",remote_upload_id:"up1",remote_evidence_ref:"remote/1",checksum:"sha256:file"});assert.equal(done.state,"completed");});
test("remote upload identity cannot switch mid-stream",async()=>{const{sync}=setup();await sync.enqueue(ctx(),media());await sync.begin(ctx(),{evidence_id:"ev1",remote_upload_id:"up1"});await assert.rejects(()=>sync.resume(ctx(),{evidence_id:"ev1",remote_upload_id:"up2"}),/upload-id-mismatch/);});
test("cross-company and legacy metadata fail closed",async()=>{const{sync}=setup();await assert.rejects(()=>sync.enqueue(ctx(),media({metadata:{company_id:"company-b"}})),/cross-company/);await assert.rejects(()=>sync.enqueue(ctx(),media({metadata:{tenant_id:"legacy"}})),/legacy/);});
test("pending lists only non-completed evidence and remains authority neutral",async()=>{const{sync}=setup();await sync.enqueue(ctx(),media());assert.equal((await sync.pending(ctx())).length,1);assert.equal(sync.descriptor.identity_grants_authority,false);assert.equal(sync.descriptor.execution_authority,false);assert.equal(sync.descriptor.automatic_effect_replay,false);});
