import test from "node:test";
import assert from "node:assert/strict";
import {createMemoryStorageAdapter,createCompanyRepository} from "../.test-dist/storage/index.js";
import {createRestartRecoveryCoordinator} from "../.test-dist/offline/index.js";

const ctx=(company_id="company-a")=>({company_id,actor_id:"worker",operation_id:"restart-test"});
function setup(){let now=1000;const repository=createCompanyRepository({adapter:createMemoryStorageAdapter(),clock:()=>now});const recovery=createRestartRecoveryCoordinator({repository,clock:()=>now});return{repository,recovery,setNow:v=>{now=v}};}

test("checkpoint is durable, company scoped and replay neutral",async()=>{const{recovery}=setup();const c=await recovery.checkpoint(ctx(),{operation_id:"op1",idempotency_key:"idem1",phase:"dispatch",payload:{x:1}});assert.equal(c.company_id,"company-a");assert.equal(c.automatic_effect_replay,false);assert.equal(c.grants_authority,false);assert.equal((await recovery.read(ctx(),"op1")).data.phase,"dispatch");});
test("restart moves interrupted work to recovery_required without replay",async()=>{const{recovery}=setup();await recovery.checkpoint(ctx(),{operation_id:"op1",idempotency_key:"idem1"});const r=await recovery.afterStart(ctx());assert.equal(r.status,"recovery-required");assert.equal(r.recovered[0].state,"recovery_required");assert.equal(r.recovered[0].requires_explicit_resume,true);assert.equal(r.automatic_effect_replay,false);});
test("resume requires matching idempotency key and yields deterministic continuation token",async()=>{const{recovery}=setup();await recovery.checkpoint(ctx(),{operation_id:"op1",idempotency_key:"idem1"});await recovery.afterStart(ctx());await assert.rejects(()=>recovery.resume(ctx(),{operation_id:"op1",idempotency_key:"wrong"}),/idempotency/);const a=await recovery.resume(ctx(),{operation_id:"op1",idempotency_key:"idem1"});assert.match(a.continuation_token,/^titan-cont:/);assert.equal(a.continuation_pending,true);});
test("continuation can be claimed exactly once",async()=>{const{recovery}=setup();await recovery.checkpoint(ctx(),{operation_id:"op1",idempotency_key:"idem1"});await recovery.afterStart(ctx());const resumed=await recovery.resume(ctx(),{operation_id:"op1",idempotency_key:"idem1"});const first=await recovery.claimContinuation(ctx(),{operation_id:"op1",idempotency_key:"idem1",continuation_token:resumed.continuation_token});const second=await recovery.claimContinuation(ctx(),{operation_id:"op1",idempotency_key:"idem1",continuation_token:resumed.continuation_token});assert.equal(first.claimed,true);assert.equal(second.claimed,false);assert.equal(second.duplicate,true);});
test("wrong continuation token fails closed",async()=>{const{recovery}=setup();await recovery.checkpoint(ctx(),{operation_id:"op1",idempotency_key:"idem1"});await recovery.afterStart(ctx());await recovery.resume(ctx(),{operation_id:"op1",idempotency_key:"idem1"});await assert.rejects(()=>recovery.claimContinuation(ctx(),{operation_id:"op1",idempotency_key:"idem1",continuation_token:"bad"}),/token-mismatch/);});
test("suspend evidence survives and restart receipt trail is durable",async()=>{const{recovery}=setup();await recovery.checkpoint(ctx(),{operation_id:"op1",idempotency_key:"idem1"});await recovery.beforeSuspend(ctx(),{reason:"worker-stop"});await recovery.afterStart(ctx());const kinds=(await recovery.receipts(ctx(),{operation_id:"op1"})).map(x=>x.kind);assert.deepEqual(kinds,["checkpointed","suspended","recovered"]);});
test("completed operations are not recovered after restart",async()=>{const{recovery}=setup();await recovery.checkpoint(ctx(),{operation_id:"op1",idempotency_key:"idem1"});await recovery.complete(ctx(),{operation_id:"op1"});const r=await recovery.afterStart(ctx());assert.equal(r.status,"ready");assert.equal(r.recovered.length,0);});
test("restart state survives coordinator recreation on same repository",async()=>{const adapter=createMemoryStorageAdapter();const repository=createCompanyRepository({adapter,clock:()=>1000});const first=createRestartRecoveryCoordinator({repository,clock:()=>1000});await first.checkpoint(ctx(),{operation_id:"op1",idempotency_key:"idem1"});const second=createRestartRecoveryCoordinator({repository,clock:()=>2000});const r=await second.afterStart(ctx());assert.equal(r.recovered[0].recovery_count,1);});
test("legacy and cross-company payloads fail closed",async()=>{const{recovery}=setup();await assert.rejects(()=>recovery.checkpoint(ctx(),{operation_id:"op1",idempotency_key:"idem1",payload:{tenant_id:"legacy"}}),/legacy/i);await assert.rejects(()=>recovery.checkpoint(ctx(),{operation_id:"op1",idempotency_key:"idem1",payload:{company_id:"company-b"}}),/cross-company/i);});
test("descriptor requires explicit resume and never grants authority",()=>{const{recovery}=setup();assert.equal(recovery.descriptor.requires_explicit_resume,true);assert.equal(recovery.descriptor.automatic_effect_replay,false);assert.equal(recovery.descriptor.identity_grants_authority,false);assert.equal(recovery.descriptor.execution_authority,false);});
