import test from "node:test";
import assert from "node:assert/strict";
import {createMemoryStorageAdapter,createCompanyRepository} from "../.test-dist/storage/index.js";
import {createOfflineNetworkResilience} from "../.test-dist/offline/index.js";

const ctx=(company_id="company-a")=>({company_id,actor_id:"field",operation_id:"network-test"});
function setup(){let now=1000;const repository=createCompanyRepository({adapter:createMemoryStorageAdapter(),clock:()=>now});const resilience=createOfflineNetworkResilience({repository,clock:()=>now,max_clock_skew_ms:100});return{repository,resilience,setNow:v=>{now=v}};}

test("network transitions persist monotonic epochs while duplicate observations are unchanged",async()=>{const{resilience}=setup();let r=await resilience.observeNetwork(ctx(),{state:"offline",observed_at:1000});assert.equal(r.status,"transition");assert.equal(r.state.epoch,1);r=await resilience.observeNetwork(ctx(),{state:"offline",observed_at:1001});assert.equal(r.status,"unchanged");assert.equal(r.state.epoch,1);r=await resilience.observeNetwork(ctx(),{state:"online",observed_at:1002});assert.equal(r.state.epoch,2);});
test("stale network observations cannot roll back current state",async()=>{const{resilience}=setup();await resilience.observeNetwork(ctx(),{state:"online",observed_at:1000});const r=await resilience.observeNetwork(ctx(),{state:"offline",observed_at:999});assert.equal(r.status,"stale_observation");assert.equal(r.state.state,"online");});
test("network and delivery clock skew fail closed",async()=>{const{resilience}=setup();await assert.rejects(()=>resilience.observeNetwork(ctx(),{state:"online",observed_at:1200}),/clock-skew/);await assert.rejects(()=>resilience.acceptDelivery(ctx(),{delivery_id:"d1",operation_id:"op1",idempotency_key:"i1",delivered_at:1200,payload_fingerprint:"f1"}),/clock-skew/);});
test("duplicate delivery with same binding is idempotent",async()=>{const{resilience}=setup();const d={delivery_id:"d1",operation_id:"op1",idempotency_key:"i1",delivered_at:1000,payload_fingerprint:"f1"};assert.equal((await resilience.acceptDelivery(ctx(),d)).status,"accepted");assert.equal((await resilience.acceptDelivery(ctx(),d)).status,"duplicate");});
test("duplicate delivery with changed intent fails closed",async()=>{const{resilience}=setup();await resilience.acceptDelivery(ctx(),{delivery_id:"d1",operation_id:"op1",idempotency_key:"i1",delivered_at:1000,payload_fingerprint:"f1"});await assert.rejects(()=>resilience.acceptDelivery(ctx(),{delivery_id:"d1",operation_id:"op1",idempotency_key:"i1",delivered_at:1000,payload_fingerprint:"f2"}),/duplicate-delivery-conflict/);});
test("partial sync checkpoints ordered progress and duplicate parts are safe",async()=>{const{resilience}=setup();await resilience.beginPartialSync(ctx(),{sync_id:"s1",generation:1,total_parts:3});let r=await resilience.applyPartialPart(ctx(),{sync_id:"s1",generation:1,part_index:0,part_fingerprint:"p0"});assert.equal(r.state.next_part,1);assert.equal((await resilience.applyPartialPart(ctx(),{sync_id:"s1",generation:1,part_index:0,part_fingerprint:"p0"})).status,"duplicate");await assert.rejects(()=>resilience.applyPartialPart(ctx(),{sync_id:"s1",generation:1,part_index:2,part_fingerprint:"p2"}),/out-of-order/);});
test("partial sync interruption and resume survive service recreation",async()=>{const adapter=createMemoryStorageAdapter();const repository=createCompanyRepository({adapter,clock:()=>1000});const first=createOfflineNetworkResilience({repository,clock:()=>1000,max_clock_skew_ms:100});await first.beginPartialSync(ctx(),{sync_id:"s1",generation:2,total_parts:2});await first.applyPartialPart(ctx(),{sync_id:"s1",generation:2,part_index:0,part_fingerprint:"p0"});await first.interruptPartialSync(ctx(),{sync_id:"s1",error:"offline"});const second=createOfflineNetworkResilience({repository,clock:()=>1050,max_clock_skew_ms:100});const resumed=await second.resumePartialSync(ctx(),{sync_id:"s1",generation:2});assert.equal(resumed.next_part,1);const done=await second.applyPartialPart(ctx(),{sync_id:"s1",generation:2,part_index:1,part_fingerprint:"p1"});assert.equal(done.status,"complete");});
test("partial sync generation cannot silently change",async()=>{const{resilience}=setup();await resilience.beginPartialSync(ctx(),{sync_id:"s1",generation:3,total_parts:2});await assert.rejects(()=>resilience.resumePartialSync(ctx(),{sync_id:"s1",generation:2}),/generation-mismatch/);await assert.rejects(()=>resilience.beginPartialSync(ctx(),{sync_id:"s1",generation:4,total_parts:2}),/identity-conflict/);});
test("cross-company and legacy boundaries remain fail closed",async()=>{const{resilience}=setup();await assert.rejects(()=>resilience.acceptDelivery(ctx(),{delivery_id:"d1",operation_id:"op1",idempotency_key:"i1",delivered_at:1000,payload_fingerprint:"f1",company_id:"company-b"}),/cross-company/);await assert.rejects(()=>resilience.beginPartialSync(ctx(),{sync_id:"s1",generation:1,total_parts:2,tenant_id:"legacy"}),/legacy/);});
test("resilience descriptor never grants replay or execution authority",()=>{const{resilience}=setup();assert.equal(resilience.descriptor.duplicate_delivery_idempotent,true);assert.equal(resilience.descriptor.clock_skew_fail_closed,true);assert.equal(resilience.descriptor.automatic_effect_replay,false);assert.equal(resilience.descriptor.identity_grants_authority,false);assert.equal(resilience.descriptor.execution_authority,false);});
