import test from 'node:test';import assert from 'node:assert/strict';
import {createMemoryStorageAdapter,createCompanyRepository} from '../.test-dist/storage/index.js';
import {createPersonalZeroStateService,createCompanyRelationship,createUnderstandingEvidence} from '../.test-dist/personal-zero/index.js';
const ctx=company_id=>({company_id,actor_id:'actor',operation_id:'op'});
const relationship=(company_id,id)=>createCompanyRelationship({relationship_id:id,one_id:'one-1',zero_id:'zero-1',company_id,role_refs:['worker'],capability_refs:[],authority_refs:['authority-ref'],data_visibility_refs:[],activated_at:1});
const evidence=(company_id,relationship_id,id)=>createUnderstandingEvidence({understanding_evidence_id:id,one_id:'one-1',zero_id:'zero-1',company_id,relationship_id,subject:'preference',value:'concise',evidence:[{evidence_id:'source-'+id,source:'correction',provenance_ref:'prov-'+id}],confidence:.9,observed_at:1,fresh_until:null,privacy_class:'company_restricted',provider_egress_allowed:false,correction_of:null});
const state=(company_id,relationship_id,id,evidence_refs,status='accepted',supersedes_understanding_id=null)=>({understanding_id:id,one_id:'one-1',zero_id:'zero-1',company_id,relationship_id,subject:'preference',value:id,status,evidence_refs,confidence:.9,version:1,supersedes_understanding_id,created_at:1,updated_at:1});

test('state service isolates same Zero across company relationships',async()=>{const repo=createCompanyRepository({adapter:createMemoryStorageAdapter()});const svc=createPersonalZeroStateService({repository:repo});await svc.putRelationship(ctx('a'),relationship('a','rel-a'));await svc.putRelationship(ctx('b'),relationship('b','rel-b'));await svc.putUnderstandingEvidence(ctx('a'),evidence('a','rel-a','ev-a'));await svc.promoteUnderstanding(ctx('a'),state('a','rel-a','u-a',['ev-a']));assert.equal((await svc.listUnderstanding(ctx('a'),'rel-a')).length,1);assert.deepEqual(await svc.listUnderstanding(ctx('b'),'rel-b'),[])});

test('cross-context evidence cannot promote understanding',async()=>{const repo=createCompanyRepository({adapter:createMemoryStorageAdapter()});const svc=createPersonalZeroStateService({repository:repo});await svc.putRelationship(ctx('a'),relationship('a','rel-a'));await svc.putRelationship(ctx('a'),createCompanyRelationship({...relationship('a','rel-a'),relationship_id:'rel-other'}));await svc.putUnderstandingEvidence(ctx('a'),evidence('a','rel-a','ev-a'));await assert.rejects(()=>svc.promoteUnderstanding(ctx('a'),state('a','rel-other','u-x',['ev-a'])),/cross-context/i)});

test('revoked relationship blocks new evidence and hides company understanding',async()=>{let now=10;const repo=createCompanyRepository({adapter:createMemoryStorageAdapter()});const svc=createPersonalZeroStateService({repository:repo,clock:()=>now});await svc.putRelationship(ctx('a'),relationship('a','rel-a'));await svc.putUnderstandingEvidence(ctx('a'),evidence('a','rel-a','ev-a'));await svc.promoteUnderstanding(ctx('a'),state('a','rel-a','u-a',['ev-a']));now=20;await svc.revokeRelationship(ctx('a'),'rel-a');await assert.rejects(()=>svc.putUnderstandingEvidence(ctx('a'),evidence('a','rel-a','ev-b')),/revoked/i);assert.deepEqual(await svc.listUnderstanding(ctx('a'),'rel-a'),[])});

test('correction supersedes prior understanding without erasing lineage',async()=>{const repo=createCompanyRepository({adapter:createMemoryStorageAdapter()});const svc=createPersonalZeroStateService({repository:repo,clock:()=>5});await svc.putRelationship(ctx('a'),relationship('a','rel-a'));await svc.putUnderstandingEvidence(ctx('a'),evidence('a','rel-a','ev-1'));await svc.putUnderstandingEvidence(ctx('a'),evidence('a','rel-a','ev-2'));await svc.promoteUnderstanding(ctx('a'),state('a','rel-a','u-1',['ev-1']));await svc.correctUnderstanding(ctx('a'),'u-1',state('a','rel-a','u-2',['ev-2'],'accepted','u-1'));const visible=await svc.listUnderstanding(ctx('a'),'rel-a');assert.equal(visible.find(x=>x.understanding_id==='u-1').status,'superseded');assert.equal(visible.find(x=>x.understanding_id==='u-2').supersedes_understanding_id,'u-1')});

test('legacy tenant aliases fail closed through canonical repository',async()=>{const repo=createCompanyRepository({adapter:createMemoryStorageAdapter()});const svc=createPersonalZeroStateService({repository:repo});await assert.rejects(()=>svc.putRelationship({tenant_id:'legacy'},relationship('a','rel-a')),/company_id|legacy tenant|company mismatch/i)});
