import test from 'node:test';import assert from 'node:assert/strict';
import {createOneIdentity,createZeroIdentity,createCompanyRelationship,createUnderstandingEvidence,createUnderstandingState,createExperienceRecord,createCognitiveEvent,PERSONAL_ZERO_PROTOCOL} from '../.test-dist/personal-zero/index.js';
const base={one_id:'one-1',zero_id:'zero-1',company_id:'company-a',relationship_id:'rel-a'};
test('One and Zero identities are independent from company relationship',()=>{const one=createOneIdentity({one_id:'one-1',zero_id:'zero-1'});const zero=createZeroIdentity({zero_id:'zero-1',one_id:'one-1',created_at:1});assert.deepEqual(one,{one_id:'one-1',zero_id:'zero-1'});assert.equal(zero.protocol,PERSONAL_ZERO_PROTOCOL);assert.equal('company_id' in zero,false)});
test('company relationship references authority but does not grant it',()=>{const rel=createCompanyRelationship({...base,role_refs:['worker'],capability_refs:['jobs.read'],authority_refs:['authority-current-1'],data_visibility_refs:['scope-1'],activated_at:1});assert.equal(rel.company_id,'company-a');assert.deepEqual(rel.authority_refs,['authority-current-1']);assert.equal(rel.status,'active')});
test('private understanding evidence fails closed for provider egress',()=>{const e=createUnderstandingEvidence({...base,understanding_evidence_id:'ue-1',subject:'communication.preference',value:'concise',evidence:[{evidence_id:'ev-1',source:'correction',provenance_ref:'prov-1'}],confidence:.9,observed_at:1,fresh_until:null,privacy_class:'personal_private',provider_egress_allowed:true,correction_of:null});assert.equal(e.provider_egress_allowed,false)});
test('accepted understanding requires evidence and preserves supersession lineage',()=>{assert.throws(()=>createUnderstandingState({...base,understanding_id:'u-1',subject:'preference',value:'x',status:'accepted',evidence_refs:[],confidence:.8,version:1,supersedes_understanding_id:null,created_at:1,updated_at:1}),/requires evidence/);const s=createUnderstandingState({...base,understanding_id:'u-2',subject:'preference',value:'y',status:'superseded',evidence_refs:['ue-2'],confidence:.95,version:2,supersedes_understanding_id:'u-1',created_at:1,updated_at:2});assert.equal(s.supersedes_understanding_id,'u-1')});
test('actual outcomes require verified outcome references',()=>{assert.throws(()=>createExperienceRecord({...base,experience_id:'exp-1',context_refs:['ctx'],decision_ref:'d1',action_ref:'a1',expected_outcome:'ok',verified_outcome_ref:null,actual_outcome:'ok',unintended_effects:[],lesson:'works',confidence:.8,future_applicability:['same-context'],created_at:1}),/verified_outcome_ref/)});
test('cognitive events are authority neutral',()=>{const e=createCognitiveEvent({...base,event_id:'ce-1',type:'approval',payload:{approved:true},evidence_refs:['ev-1'],confidence:1,privacy_class:'company_restricted',parent_event_id:null,correlation_id:'corr-1',operation_id:'op-1',occurred_at:1});assert.equal(e.authority_neutral,true);assert.equal(e.execution_authority,false)});
