import test from 'node:test';import assert from 'node:assert/strict';
import {createMemoryStorageAdapter,createCompanyRepository} from '../.test-dist/storage/index.js';
import {createPersonalZeroStateService,createCompanyRelationship,createUnderstandingEvidence,createTargetShareAcceptance,shareGrantFingerprint} from '../.test-dist/personal-zero/index.js';
const ctx={company_id:'a',actor_id:'actor',operation_id:'op'};const grantInput={grant_id:'g',one_id:'one',zero_id:'zero',source_company_id:'a',source_relationship_id:'ra',target_company_id:'b',target_relationship_id:'rb',subject_refs:['communication'],purpose:'assist',consent_ref:'consent',expires_at:100,revoked_at:null,created_at:1};
async function setup(){const svc=createPersonalZeroStateService({repository:createCompanyRepository({adapter:createMemoryStorageAdapter()})});await svc.putRelationship(ctx,createCompanyRelationship({relationship_id:'ra',one_id:'one',zero_id:'zero',company_id:'a',role_refs:[],capability_refs:[],authority_refs:[],data_visibility_refs:[],activated_at:1}));await svc.putUnderstandingEvidence(ctx,createUnderstandingEvidence({understanding_evidence_id:'e',one_id:'one',zero_id:'zero',company_id:'a',relationship_id:'ra',subject:'communication',value:'concise',evidence:[{evidence_id:'src',source:'user',provenance_ref:'p'}],confidence:1,observed_at:1,fresh_until:null,privacy_class:'shareable',provider_egress_allowed:false,correction_of:null}));await svc.promoteUnderstanding(ctx,{understanding_id:'u',one_id:'one',zero_id:'zero',company_id:'a',relationship_id:'ra',subject:'communication',value:'concise',status:'accepted',evidence_refs:['e'],confidence:1,version:1,supersedes_understanding_id:null,created_at:1,updated_at:1});const row=await svc.putCrossContextShareGrant(ctx,grantInput);return {svc,grant:row.data}}
const accept=(grant,o={})=>createTargetShareAcceptance({acceptance_id:'accept',grant_id:'g',grant_fingerprint:shareGrantFingerprint(grant),one_id:'one',zero_id:'zero',target_company_id:'b',target_relationship_id:'rb',accepted_subject_refs:['communication'],purpose:'assist',accepted_at:2,expires_at:100,revoked_at:null,...o});
test('shared understanding requires valid target acceptance',async()=>{const {svc,grant}=await setup();assert.equal((await svc.getSharedUnderstanding(ctx,'a','g',accept(grant),50)).length,1);assert.deepEqual(await svc.getSharedUnderstanding(ctx,'a','g',accept(grant,{target_relationship_id:'wrong'}),50),[])});
test('revoked or expired target acceptance closes source retrieval',async()=>{const {svc,grant}=await setup();assert.deepEqual(await svc.getSharedUnderstanding(ctx,'a','g',accept(grant,{revoked_at:10}),50),[]);assert.deepEqual(await svc.getSharedUnderstanding(ctx,'a','g',accept(grant,{expires_at:50}),50),[])});
test('changed grant fingerprint cannot reuse prior acceptance',async()=>{const {svc,grant}=await setup();const a=accept(grant);await svc.revokeCrossContextShareGrant(ctx,'g');assert.deepEqual(await svc.getSharedUnderstanding(ctx,'a','g',a,50),[])});
