import test from 'node:test';import assert from 'node:assert/strict';
import {createMemoryStorageAdapter,createCompanyRepository} from '../.test-dist/storage/index.js';
import {createPersonalZeroStateService,createCompanyRelationship} from '../.test-dist/personal-zero/index.js';
const ctx={company_id:'a',actor_id:'actor',operation_id:'op'};
const rel=createCompanyRelationship({relationship_id:'ra',one_id:'one',zero_id:'zero',company_id:'a',role_refs:[],capability_refs:[],authority_refs:['authority-ref'],data_visibility_refs:[],activated_at:1});
const outcome={company_id:'a',agent_id:'agent',capability_id:'cap',outcome_id:'out',correlation_id:'corr',receipt_refs:['receipt'],expected_state_ref:'expected',verified_state_ref:'verified',verified:true};
async function setup(status='accepted'){const repo=createCompanyRepository({adapter:createMemoryStorageAdapter()});const svc=createPersonalZeroStateService({repository:repo,clock:()=>10});await svc.putRelationship(ctx,rel);await svc.proposeLearningFromVerifiedOutcome(ctx,{one_id:'one',zero_id:'zero',relationship_id:'ra',outcome});if(status)await svc.reviewLearningProposal(ctx,'outcome:out',{status,reviewer_id:'reviewer',review_evidence_refs:['review-evidence'],review_reason:'reviewed'});return svc}
test('accepted learning is readable by each canonical consumer without mutation authority',async()=>{const svc=await setup();for(const consumer of ['interaction','decision','workforce']){const [a]=await svc.getAcceptedLearning(ctx,'ra',consumer);assert.equal(a.consumer,consumer);assert.equal(a.read_only,true);assert.equal(a.authority_neutral,true);assert.equal(a.execution_authority,false);assert.equal(a.mutation_permitted,false);assert.equal('authority_refs' in a,false)}});
test('pending and rejected proposals are not consumable',async()=>{const pending=await setup(null);assert.deepEqual(await pending.getAcceptedLearning(ctx,'ra','decision'),[]);const rejected=await setup('rejected');assert.deepEqual(await rejected.getAcceptedLearning(ctx,'ra','decision'),[])});
test('revocation immediately removes accepted learning projection',async()=>{const svc=await setup();assert.equal((await svc.getAcceptedLearning(ctx,'ra','interaction')).length,1);await svc.revokeRelationship(ctx,'ra');assert.deepEqual(await svc.getAcceptedLearning(ctx,'ra','interaction'),[])});
test('consumer projection carries evidence lineage but cannot directly apply adjustment',async()=>{const svc=await setup();const [a]=await svc.getAcceptedLearning(ctx,'ra','workforce');assert.deepEqual(a.evidence_refs,['out','receipt']);assert.deepEqual(a.review_evidence_refs,['review-evidence']);assert.equal(a.mutation_permitted,false);assert.equal(a.execution_authority,false)});
