import test from 'node:test';import assert from 'node:assert/strict';
import {createMemoryStorageAdapter,createCompanyRepository} from '../.test-dist/storage/index.js';
import {createPersonalZeroStateService,createCompanyRelationship} from '../.test-dist/personal-zero/index.js';
const ctx=company_id=>({company_id,actor_id:'actor',operation_id:'op'});
const rel=company_id=>createCompanyRelationship({relationship_id:'rel-'+company_id,one_id:'one',zero_id:'zero',company_id,role_refs:['worker'],capability_refs:[],authority_refs:['auth-ref'],data_visibility_refs:[],activated_at:1});
const exp=(company_id,actual='done')=>({experience_id:'exp-'+company_id,one_id:'one',zero_id:'zero',company_id,relationship_id:'rel-'+company_id,context_refs:['ctx'],decision_ref:'decision-1',action_ref:'action-1',expected_outcome:'done',verified_outcome_ref:'outcome-1',actual_outcome:actual,unintended_effects:[],lesson:'retain',confidence:.9,future_applicability:['same'],created_at:1});
const event=company_id=>({event_id:'event-'+company_id,one_id:'one',zero_id:'zero',company_id,relationship_id:'rel-'+company_id,type:'outcome',payload:{result:'done'},evidence_refs:['receipt-1'],confidence:1,privacy_class:'company_restricted',parent_event_id:null,correlation_id:'corr',operation_id:'op',occurred_at:2});

test('actual experience requires matching verified receipt-backed outcome',async()=>{const repo=createCompanyRepository({adapter:createMemoryStorageAdapter()});const svc=createPersonalZeroStateService({repository:repo});await svc.putRelationship(ctx('a'),rel('a'));await assert.rejects(()=>svc.putExperience(ctx('a'),exp('a'),{company_id:'a',outcome_id:'outcome-1',verified:false,receipt_refs:['r']}),/verified outcome proof/i);await assert.rejects(()=>svc.putExperience(ctx('a'),exp('a'),{company_id:'b',outcome_id:'outcome-1',verified:true,receipt_refs:['r']}),/verified outcome proof/i);const row=await svc.putExperience(ctx('a'),exp('a'),{company_id:'a',outcome_id:'outcome-1',verified:true,receipt_refs:['r']});assert.equal(row.data.actual_outcome,'done')});

test('cognitive chronology stays authority neutral and relationship scoped',async()=>{const repo=createCompanyRepository({adapter:createMemoryStorageAdapter()});const svc=createPersonalZeroStateService({repository:repo});await svc.putRelationship(ctx('a'),rel('a'));const row=await svc.appendCognitiveEvent(ctx('a'),event('a'));assert.equal(row.data.authority_neutral,true);assert.equal(row.data.execution_authority,false);await svc.revokeRelationship(ctx('a'),'rel-a');await assert.rejects(()=>svc.appendCognitiveEvent(ctx('a'),{...event('a'),event_id:'later'}),/revoked/i)});

test('consumer projections are stable, authority neutral and company isolated',async()=>{const repo=createCompanyRepository({adapter:createMemoryStorageAdapter()});const svc=createPersonalZeroStateService({repository:repo});await svc.putRelationship(ctx('a'),rel('a'));await svc.putRelationship(ctx('b'),rel('b'));await svc.putExperience(ctx('a'),exp('a'),{company_id:'a',outcome_id:'outcome-1',verified:true,receipt_refs:['r']});await svc.appendCognitiveEvent(ctx('a'),event('a'));for(const consumer of ['interaction','decision','workforce']){const p=await svc.getConsumerProjection(ctx('a'),'rel-a',consumer);assert.equal(p.consumer,consumer);assert.equal(p.company_id,'a');assert.equal(p.experiences.length,1);assert.equal(p.cognitive_events.length,1);assert.equal(p.authority_neutral,true);assert.equal(p.execution_authority,false)}const other=await svc.getConsumerProjection(ctx('b'),'rel-b','decision');assert.equal(other.experiences.length,0);assert.equal(other.cognitive_events.length,0)});

test('revocation removes consumer projection without deleting unrelated company context',async()=>{const repo=createCompanyRepository({adapter:createMemoryStorageAdapter()});const svc=createPersonalZeroStateService({repository:repo});await svc.putRelationship(ctx('a'),rel('a'));await svc.putRelationship(ctx('b'),rel('b'));await svc.revokeRelationship(ctx('a'),'rel-a');assert.equal(await svc.getConsumerProjection(ctx('a'),'rel-a','interaction'),null);assert.notEqual(await svc.getConsumerProjection(ctx('b'),'rel-b','interaction'),null)});
