import test from 'node:test';import assert from 'node:assert/strict';
import {createMemoryStorageAdapter,createCompanyRepository} from '../.test-dist/storage/index.js';
import {createPersonalZeroStateService,createCompanyRelationship,createUnderstandingEvidence} from '../.test-dist/personal-zero/index.js';
const ctx={company_id:'a',actor_id:'actor',operation_id:'op'};const rel=createCompanyRelationship({relationship_id:'ra',one_id:'one',zero_id:'zero',company_id:'a',role_refs:[],capability_refs:[],authority_refs:[],data_visibility_refs:[],activated_at:1});
async function setup(privacy='shareable'){const svc=createPersonalZeroStateService({repository:createCompanyRepository({adapter:createMemoryStorageAdapter()})});await svc.putRelationship(ctx,rel);await svc.putUnderstandingEvidence(ctx,createUnderstandingEvidence({understanding_evidence_id:'e',one_id:'one',zero_id:'zero',company_id:'a',relationship_id:'ra',subject:'communication',value:'concise',evidence:[{evidence_id:'src',source:'user',provenance_ref:'p'}],confidence:1,observed_at:1,fresh_until:null,privacy_class:privacy,provider_egress_allowed:false,correction_of:null}));await svc.promoteUnderstanding(ctx,{understanding_id:'u',one_id:'one',zero_id:'zero',company_id:'a',relationship_id:'ra',subject:'communication',value:'concise',status:'accepted',evidence_refs:['e'],confidence:1,version:1,supersedes_understanding_id:null,created_at:1,updated_at:1});return svc}
const grant={grant_id:'g',one_id:'one',zero_id:'zero',source_company_id:'a',source_relationship_id:'ra',target_company_id:'b',target_relationship_id:'rb',subject_refs:['communication'],purpose:'cross context assistance',consent_ref:'consent-1',expires_at:null,revoked_at:null,created_at:1};
test('share grant requires explicit consent reference',async()=>{const svc=await setup();await assert.rejects(()=>svc.putCrossContextShareGrant(ctx,{...grant,consent_ref:''}),/consent_ref/)});
test('personal_private understanding cannot cross contexts under ordinary share grant',async()=>{const svc=await setup('personal_private');await assert.rejects(()=>svc.putCrossContextShareGrant(ctx,grant),/stronger consent contract/i)});
test('grant can only name accepted source subjects',async()=>{const svc=await setup();await assert.rejects(()=>svc.putCrossContextShareGrant(ctx,{...grant,subject_refs:['unknown']}),/not accepted/i)});
test('source relationship revocation immediately stops sharing',async()=>{const svc=await setup();await svc.putCrossContextShareGrant(ctx,grant);assert.equal((await svc.getSharedUnderstanding(ctx,'a','g')).length,1);await svc.revokeRelationship(ctx,'ra');assert.deepEqual(await svc.getSharedUnderstanding(ctx,'a','g'),[])});
test('explicit grant revocation immediately stops sharing',async()=>{const svc=await setup();await svc.putCrossContextShareGrant(ctx,grant);await svc.revokeCrossContextShareGrant(ctx,'g');assert.deepEqual(await svc.getSharedUnderstanding(ctx,'a','g'),[])});
