import fs from 'node:fs'; import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../src/titan-builder/signal-priority.ts',import.meta.url),'utf8');
const planner=fs.readFileSync(new URL('../src/titan-builder/workspace-planner.ts',import.meta.url),'utf8');
assert.match(src,/company_id===context\.company_id/);
assert.match(src,/signal\.surface===surface/);
assert.match(src,/SEVERITY/);
assert.match(src,/freshness/);
assert.match(src,/impact/);
assert.match(src,/critical/);
assert.match(src,/warning/);
assert.match(src,/advisory_only:true/);
assert.match(src,/authority_granted:false/);
assert.match(src,/slice\(0,plan\.max_visible_cards\)/);
assert.match(src,/a\.index-b\.index/);
assert.doesNotMatch(src,/fetch\s*\(/);
assert.doesNotMatch(src,/tenant_id|tenant_company_id/);
assert.doesNotMatch(src,/actions\s*:/);
assert.match(planner,/prioritizeBuilderWorkspace/);
assert.match(planner,/priority\?/);
console.log('Titan Builder Pass22 signal priority: 16/16 PASS');
