import fs from 'node:fs'; import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../src/titan-builder/workspace-planner.ts',import.meta.url),'utf8');
const bridge=fs.readFileSync(new URL('../src/titan-builder/runtime-bridge.ts',import.meta.url),'utf8');
assert.match(src,/max_visible_cards:3/);
assert.match(src,/chat_first:true/);
assert.match(src,/zero:\["operations","finance","approvals"\]/);
assert.match(src,/go:\["jobs","tasks","sites"\]/);
assert.match(src,/hub:\["schedule","jobs","invoices"\]/);
assert.match(src,/COMPLEMENTS/);
assert.match(src,/unique\(/);
assert.match(src,/workspace_role/);
assert.match(src,/mode:"read-only"/);
assert.match(src,/authority_granted:false/);
assert.match(src,/if\(\(document\.root\.children\?\?\[\]\)\.length>0\)return document/);
assert.match(bridge,/applyBuilderWorkspacePlan/);
assert.match(bridge,/applyBuilderSemanticIntentPlan\(applyBuilderWorkspacePlan/);
assert.doesNotMatch(src,/fetch\s*\(/);
assert.doesNotMatch(src,/tenant_id|tenant_company_id/);
console.log('Titan Builder Pass21 workspace planner: 15/15 PASS');
