import test from "node:test"; import assert from "node:assert/strict";
import { TitanBuilderConversationCycle } from "../.test-dist/titan-builder/conversation-cycle.js";
const context={schema:"titan.interface-context.v2",company_id:"co-1",user_id:"u-1",product_surface:"zero",domain:"business",branch_id:null,workspace_id:null,team_id:null,device_id:null,object_ref:null,conversation_id:"c-1",journey_id:null,roles:[],capabilities:[],trace_id:"t",correlation_id:"c",causation_id:null,authority_neutral:true,context_changes_grant_authority:false};
const env={company_id:"co-1",surface:"zero",device:{width:1280,height:800,pixelRatio:1},capabilities:{webgl2:true,webgpu:false},preferences:{reducedMotion:false}};
function cycle(){return TitanBuilderConversationCycle.fromChatRequest({company_id:"co-1",surface:"zero",presentation_id:"p1",message:"Show today's jobs",semantic_components:[{type:"text",id:"headline",props:{text:"Today's jobs"}}]},context)}
test("chat request creates reviewable builder workspace",()=>{const c=cycle();assert.equal(c.snapshot().company_id,"co-1");assert.equal(c.snapshot().status,"draft");});
test("publish requires preview and explicit approval",()=>{const c=cycle();assert.throws(()=>c.publish(),/explicit_approval/);assert.throws(()=>c.requestApproval("u-1"),/preview_required/);c.preview(env);c.requestApproval("u-1");const out=c.publish();assert.equal(out.document.status,"published");assert.equal(out.handoff.builder_grants_authority,false);});
test("edit invalidates approval",()=>{const c=cycle();c.preview(env);c.requestApproval("u-1");c.apply({kind:"patch",node_id:"headline",props:{text:"Changed"}});assert.throws(()=>c.publish(),/explicit_approval/);});
test("company and surface boundaries fail closed",()=>{assert.throws(()=>TitanBuilderConversationCycle.fromChatRequest({company_id:"co-2",surface:"zero",presentation_id:"p",message:"x"},context),/company_mismatch/);assert.throws(()=>TitanBuilderConversationCycle.fromChatRequest({company_id:"co-1",surface:"go",presentation_id:"p",message:"x"},context),/surface_mismatch/);});
