import test from "node:test"; import assert from "node:assert/strict";
const runtime = await import("../.test-dist/ported/titan-runtime/visual-runtime/index.js");
test("package manifest validates canonical ownership boundary",()=>{assert.equal(runtime.validateVisualRuntimePackageManifest(runtime.VISUAL_RUNTIME_PACKAGE_MANIFEST).valid,true);assert.equal(runtime.VISUAL_RUNTIME_PACKAGE_MANIFEST.business_authority,false);});
test("package manifest rejects independent tenant boundary",()=>assert.throws(()=>runtime.validateVisualRuntimePackageManifest({...runtime.VISUAL_RUNTIME_PACKAGE_MANIFEST,tenant_boundary:"tenant_id"}),/company_id/));
test("contribution schema enforces zero go hub",()=>{const c=runtime.validateVisualContributionSchema({id:"job.status",provider:"go",surfaces:["go"],treatment:{state:"success"}});assert.equal(c.id,"job.status");assert.throws(()=>runtime.validateVisualContributionSchema({id:"job.status",provider:"go",surfaces:["admin"],treatment:{}}),/surfaces/);});
test("browser metadata rejects executable payload",()=>assert.throws(()=>runtime.sanitizeVisualBrowserMetadata({treatment:{html:"<script>alert(1)</script>"}}),/Forbidden|Executable/));
test("browser environment honors accessibility preferences",()=>{const e=runtime.detectVisualBrowserEnvironment({devicePixelRatio:2,innerWidth:390,matchMedia:q=>({matches:q.includes("reduced-motion")})});assert.equal(e.reducedMotion,true);assert.equal(e.deviceClass,"compact");});
test("browser plan applies visual-only dataset",()=>{const el={dataset:{}};runtime.applyVisualBrowserPlan(el,{visualTreatment:"success",motionPreset:"reduced",transitionPreset:"crossfade",strategy:"preferred"});assert.deepEqual(el.dataset,{visualTreatment:"success",motionPreset:"reduced",transitionPreset:"crossfade",visualStrategy:"preferred"});});
test("interface bridge requires plan company_id and no authority",()=>{assert.equal(runtime.assertVisualInterfaceBridgeCompatibility({method:"plan",company_boundary:"company_id",business_authority:false,canonical_surfaces:["zero","go","hub"]}).compatible,true);assert.throws(()=>runtime.assertVisualInterfaceBridgeCompatibility({method:"execute",company_boundary:"company_id",business_authority:false,canonical_surfaces:["zero","go","hub"]}),/plan/);});
