import test from "node:test";
import assert from "node:assert/strict";
import { VisualContributionRegistry, snapshotVisualContributions, VisualResourceRegistry, compareVisualContributionVersions, VISUAL_MOTION_PRESETS, VISUAL_TRANSITION_PRESETS, VISUAL_TREATMENTS } from "../.test-dist/runtime.js";

test("contribution registry enforces company ownership and version monotonicity",()=>{const r=new VisualContributionRegistry();r.register({id:"job.card",provider:"core",company_id:"c1",surfaces:["zero"],treatment:{density:"compact"},version:"1.1.0"});assert.equal(r.resolve("job.card","zero","c1")?.provider,"core");assert.throws(()=>r.register({id:"job.card",provider:"other",company_id:"c1",surfaces:["zero"],treatment:{},version:"1.2.0"}));assert.throws(()=>r.register({id:"job.card",provider:"core",company_id:"c1",surfaces:["zero"],treatment:{},version:"1.0.0"}));});
test("contribution snapshot is deterministic and authority free",async()=>{const r=new VisualContributionRegistry();r.register({id:"b",provider:"core",surfaces:["hub"],treatment:{}});r.register({id:"a",provider:"core",surfaces:["go"],treatment:{}});const a=await snapshotVisualContributions(r),b=await snapshotVisualContributions(r);assert.equal(a.sha256,b.sha256);assert.equal(a.business_authority,false);assert.equal(a.tenant_boundary,"company_id");});
test("semantic version policy compares compatible v1 versions",()=>{assert.equal(compareVisualContributionVersions("1.2.0","1.1.9"),1);assert.throws(()=>compareVisualContributionVersions("2.0.0","1.0.0"));});
test("resource registry selects offline and DPR variants deterministically",()=>{const r=new VisualResourceRegistry();r.register("asset","brand.logo",{uri:"/logo.png",offlineUri:"asset://logo",variants:[{uri:"/logo@2x.png",minDpr:2}]});assert.equal(r.resolve("asset","brand.logo",{connectivity:"offline"})?.uri,"asset://logo");assert.equal(r.resolve("asset","brand.logo",{connectivity:"online",devicePixelRatio:2})?.uri,"/logo@2x.png");assert.deepEqual(r.inventory().assets,["brand.logo"]);});
test("resource registry rejects unsafe media autoplay and URIs",()=>{const r=new VisualResourceRegistry();assert.throws(()=>r.register("media","hero.video",{uri:"https://x.test/a.mp4",autoplay:true,muted:false}));assert.throws(()=>r.register("icon","bad.icon",{uri:"javascript:alert(1)"}));});
test("built-in visual resources retain semantic-only authority boundary",()=>{assert.equal(VISUAL_MOTION_PRESETS.reduced.duration_ms,0);assert.equal(VISUAL_TRANSITION_PRESETS.crossfade.business_meaning_unchanged,true);assert.equal(VISUAL_TREATMENTS.error.semantic_state,"error");});
