import test from 'node:test';
import assert from 'node:assert/strict';
import {TITAN_WORKFORCE_MIGRATION_CONTRACT,buildTitanWorkforceMigrationPlan,transitionTitanWorkforceMigration} from '../.lifecycle-test-dist/workforce-lifecycle/index.js';
const step={migration_id:'config-v2',registered:true,data_preserving:true,authority_neutral:true,reversible:true,rollback_ref:'rollback://config-v1'};
const plan=(overrides={})=>buildTitanWorkforceMigrationPlan({company_id:'company-1',agent_key:'booking',source_version:'1.0.0',target_version:'2.0.0',source_configuration_revision:1,target_configuration_revision:2,lifecycle_state:'PAUSED',active_work_count:0,backup_ref:'backup://before-v2',rollback_ref:'checkpoint://v1',migrations:[step],...overrides});

test('migration contract is rollback-safe and authority neutral',()=>{assert.equal(TITAN_WORKFORCE_MIGRATION_CONTRACT.agentMaySelfUpgrade,false);assert.equal(TITAN_WORKFORCE_MIGRATION_CONTRACT.rollbackCheckpointRequired,true);assert.equal(TITAN_WORKFORCE_MIGRATION_CONTRACT.migrationGrantsAuthority,false);});
test('safe upgrade prepares without granting execution authority',()=>{const p=plan();assert.equal(p.phase,'PREPARED');assert.deepEqual(p.blockers,[]);assert.equal(p.execution_permitted,false);assert.equal(p.migration_grants_authority,false);});
test('active work or unsafe lifecycle state blocks upgrade',()=>{assert.match(plan({active_work_count:2,lifecycle_state:'PAUSED'}).blockers.join(','),/active-work/);assert.match(plan({lifecycle_state:'ENABLED'}).blockers.join(','),/lifecycle-state-not-upgrade-safe/);});
test('backup and rollback checkpoint are mandatory',()=>{const p=plan({backup_ref:null,rollback_ref:null});assert.equal(p.phase,'BLOCKED');assert.match(p.blockers.join(','),/backup/);assert.match(p.blockers.join(','),/rollback-checkpoint/);});
test('unregistered destructive or authority-changing migrations fail closed',()=>{assert.match(plan({migrations:[{...step,registered:false}]}).blockers.join(','),/unregistered/);assert.match(plan({migrations:[{...step,data_preserving:false}]}).blockers.join(','),/preserve-data/);assert.match(plan({migrations:[{...step,authority_neutral:false}]}).blockers.join(','),/cannot-change-authority/);});
test('normal transition path requires verification before completion',()=>{const a=transitionTitanWorkforceMigration(plan(),{company_id:'company-1',type:'START'});assert.equal(a.phase,'APPLYING');const v=transitionTitanWorkforceMigration(a,{company_id:'company-1',type:'APPLIED'});assert.equal(v.phase,'VERIFYING');const c=transitionTitanWorkforceMigration(v,{company_id:'company-1',type:'VERIFIED'});assert.equal(c.phase,'COMPLETED');assert.equal(c.effect_state,'VERIFIED');assert.equal(c.execution_permitted,false);});
test('interruption fails closed into recovery and unknown effects require review',()=>{const a=transitionTitanWorkforceMigration(plan(),{company_id:'company-1',type:'START'});const r=transitionTitanWorkforceMigration(a,{company_id:'company-1',type:'INTERRUPT',effect_state:'UNKNOWN'});assert.equal(r.phase,'RECOVERY_REQUIRED');assert.equal(r.requires_manual_review,true);assert.equal(r.automatic_effect_replay,false);});
test('failure routes through rollback-required and explicit rollback evidence state',()=>{const a=transitionTitanWorkforceMigration(plan(),{company_id:'company-1',type:'START'});const f=transitionTitanWorkforceMigration(a,{company_id:'company-1',type:'FAIL',effect_state:'UNKNOWN'});assert.equal(f.phase,'ROLLBACK_REQUIRED');const rb=transitionTitanWorkforceMigration(f,{company_id:'company-1',type:'ROLLED_BACK',checkpoint_id:'checkpoint://rolled-back'});assert.equal(rb.phase,'ROLLED_BACK');assert.equal(rb.effect_state,'ROLLED_BACK');});
test('downgrade and configuration rollback require explicit rollback mode',()=>{assert.match(plan({target_version:'0.9.0'}).blockers.join(','),/older-than-source/);assert.match(plan({target_configuration_revision:0}).blockers.join(','),/older-than-source/);assert.equal(plan({target_version:'0.9.0',target_configuration_revision:0,rollback_mode:true}).phase,'PREPARED');});
test('cross-company checkpoints and transitions fail closed',()=>{assert.throws(()=>plan({previous_checkpoint:{company_id:'company-2'}}),/cross-company/);assert.throws(()=>transitionTitanWorkforceMigration(plan(),{company_id:'company-2',type:'START'}),/cross-company/);});
