import test from "node:test";import assert from "node:assert/strict";import{buildTitanJobsPlan}from"../.test-dist/workforce-native/index.js";
test("Jobs reads canonical project work order and visit truth",()=>{assert.equal(buildTitanJobsPlan({companyId:"c1",action:"get_project",projectId:"j1"}).operation.path,"/api/v1/jobs/:id");assert.equal(buildTitanJobsPlan({companyId:"c1",action:"list_work_orders",projectId:"j1"}).query.job_id,"j1");assert.equal(buildTitanJobsPlan({companyId:"c1",action:"get_visit",visitId:"v1"}).operation.path,"/api/v1/visits/:id");});
test("Jobs lifecycle evaluation never self-authorizes",()=>{const p=buildTitanJobsPlan({companyId:"c1",action:"evaluate_transition",projectId:"j1",payload:{from_state:"planned",to_state:"assigned"}});assert.equal(p.evaluation.allowed,false);assert.equal(p.evaluation.reason,"AUTHORITY_REQUIRED");assert.equal(p.authority.identity_grants_authority,false);});
test("Jobs transitions use canonical Business Ops routes",()=>{assert.equal(buildTitanJobsPlan({companyId:"c1",action:"transition_project",projectId:"j1",payload:{to_status:"scheduled"}}).operation.id,"projects.transition");assert.equal(buildTitanJobsPlan({companyId:"c1",action:"start_visit",workOrderId:"wo1",payload:{}}).operation.id,"work_orders.start_visit");assert.equal(buildTitanJobsPlan({companyId:"c1",action:"transition_visit",visitId:"v1",payload:{status:"arrived"}}).operation.id,"visits.transition");});
test("Jobs evidence evaluation remains proposal only",()=>{const p=buildTitanJobsPlan({companyId:"c1",action:"evaluate_evidence",projectId:"j1",payload:{checklist:[{required:true,completed:false}]}});assert.equal(p.evaluation.ready,false);assert.ok(p.evaluation.blockers.includes("REQUIRED_CHECKLIST_INCOMPLETE"));assert.equal(p.evaluation.execution_permitted,false);});
test("Jobs classifies exceptions and keeps authority external",()=>{const p=buildTitanJobsPlan({companyId:"c1",action:"classify_exception",projectId:"j1",payload:{type:"safety",summary:"hazard"}});assert.equal(p.exception.type,"safety");assert.equal(p.exception.requires_authority_review,true);assert.equal(p.exception.execution_permitted,false);});
test("Jobs offline mutation is idempotent and replay is not automatic",()=>{const p=buildTitanJobsPlan({companyId:"c1",action:"build_offline_mutation",projectId:"j1",traceId:"op1",payload:{mutation_kind:"work_order_update",base_revision:2,payload:{x:1}}});assert.equal(p.offline.idempotency_key,"jobs:c1:j1:op1");assert.equal(p.offline.automatic_effect_replay,false);});
test("Jobs revision conflicts surface stale state",()=>{const p=buildTitanJobsPlan({companyId:"c1",action:"detect_revision_conflict",projectId:"j1",traceId:"op1",payload:{base_revision:1,current_revision:2,current_operation_ids:[]}});assert.equal(p.offline.conflict,true);assert.equal(p.offline.disposition,"STALE_REVISION");});
test("Jobs rejects unsafe ids and legacy tenant aliases",()=>{assert.throws(()=>buildTitanJobsPlan({companyId:"c1",action:"get_project",projectId:"../bad"}),/jobs-project-id-required/);assert.throws(()=>buildTitanJobsPlan({companyId:"c1",action:"classify_exception",projectId:"j1",payload:{tenant_id:"x",type:"blocked"}}),/legacy-company-boundary/);});
