export const TITAN_SIGNAL_CONTRACT={schema:"titan.signal/v1",authority:"observation-and-delivery-only"} as const;
export type SignalPayload=Readonly<Record<string,unknown>>;
export type SignalEnvelope=Readonly<{schema:string;schema_revision:number;signal_id:string;event_type:string;company_id:string;source:string;capability:string;correlation_id:string;causation_id?:string;occurred_at:string;observed_at:string;ingested_at:string;payload:SignalPayload;provenance:Readonly<{producer_id:string;receipt_id:string}>;safe_payload:true;payload_bytes:number}>;
export type SignalProducer=Readonly<{producer_id:string;company_id:string;capability:string;event_types:readonly string[];authorize:(event:string,payload:SignalPayload)=>boolean}>;
export type SignalSubscription=Readonly<{id:string;company_id:string;revision:number;event_types:readonly string[];destination:string;capability:string;active:boolean;paused:boolean;authorize:(e:SignalEnvelope)=>boolean}>;
export type Delivery=Readonly<{delivery_id:string;signal_id:string;subscription_id:string;company_id:string;attempt:number;available_at:string;lease_until:string|null;state:"pending"|"leased"|"delivered"|"quarantined";last_error?:string}>;
export type SignalStore=Readonly<{envelopes:Map<string,SignalEnvelope>;deliveries:Map<string,Delivery>;subscriptions:Map<string,SignalSubscription>;evidence_refs:Set<string>;archive:Set<string>}>;
const text=(v:unknown,e:string)=>{const s=String(v??"").trim();if(!s)throw Error(e);return s};
const time=(v:string)=>{if(!Number.isFinite(new Date(v).getTime()))throw Error("signal_time_invalid");return new Date(v).toISOString()};
const size=(v:unknown)=>new TextEncoder().encode(JSON.stringify(v)).byteLength;
const hash=(v:unknown)=>{let h=2166136261;for(const c of JSON.stringify(v))h=Math.imul(h^c.charCodeAt(0),16777619);return(h>>>0).toString(16)};
const now=()=>new Date().toISOString();
export function createSignalStore():SignalStore{return{envelopes:new Map,deliveries:new Map,subscriptions:new Map,evidence_refs:new Set,archive:new Set}};
export function registerSignalProducer(p:SignalProducer,r:Map<string,SignalProducer>){if(r.has(p.producer_id))throw Error("signal_producer_duplicate");r.set(text(p.producer_id,"signal_producer_required"),p);return p}
export function createSignalEnvelope(i:{signal_id:string;event_type:string;company_id:string;source:string;capability:string;correlation_id:string;causation_id?:string;occurred_at:string;observed_at:string;producer:SignalProducer;payload:SignalPayload;receipt_id?:string},r:Map<string,SignalProducer>,limit=32768):SignalEnvelope{const p=r.get(i.producer.producer_id);if(!p)throw Error("signal_producer_unregistered");if(!p.event_types.includes(i.event_type))throw Error("signal_event_type_unregistered");if(i.company_id!==p.company_id)throw Error("signal_company_mismatch");if(!p.authorize(i.event_type,i.payload))throw Error("signal_producer_unauthorized");if(/password|secret|token|api[_-]?key|credential/i.test(JSON.stringify(i.payload)))throw Error("signal_unsafe_payload");const payload_bytes=size(i.payload);if(payload_bytes>limit)throw Error("signal_payload_too_large");return{schema:TITAN_SIGNAL_CONTRACT.schema,schema_revision:1,signal_id:text(i.signal_id,"signal_id_required"),event_type:i.event_type,company_id:i.company_id,source:text(i.source,"signal_source_required"),capability:text(i.capability,"signal_capability_required"),correlation_id:text(i.correlation_id,"signal_correlation_required"),causation_id:i.causation_id,occurred_at:time(i.occurred_at),observed_at:time(i.observed_at),ingested_at:now(),payload:i.payload,provenance:{producer_id:p.producer_id,receipt_id:i.receipt_id??"receipt:"+hash(i)},safe_payload:true,payload_bytes};}
export function registerSubscription(s:SignalStore,x:SignalSubscription){if(s.subscriptions.has(x.id)||x.revision<1)throw Error("signal_subscription_invalid");s.subscriptions.set(x.id,x);return x}
export function reviseSubscription(s:SignalStore,id:string,patch:Partial<SignalSubscription>){const x=s.subscriptions.get(id);if(!x)throw Error("signal_subscription_missing");const n={...x,...patch,revision:x.revision+1};s.subscriptions.set(id,n);return n}
export function ingestSignal(s:SignalStore,e:SignalEnvelope){if(e.schema!==TITAN_SIGNAL_CONTRACT.schema||e.schema_revision!==1)throw Error("signal_schema_version_rejected");if(s.envelopes.has(e.signal_id))return{accepted:false,deduplicated:true};s.envelopes.set(e.signal_id,e);for(const x of s.subscriptions.values())if(x.company_id===e.company_id&&x.active&&!x.paused&&x.event_types.includes(e.event_type)&&x.authorize(e)){const d:Delivery={delivery_id:e.signal_id+":"+x.id,signal_id:e.signal_id,subscription_id:x.id,company_id:e.company_id,attempt:0,available_at:e.ingested_at,lease_until:null,state:"pending"};s.deliveries.set(d.delivery_id,d)}return{accepted:true,deduplicated:false}}
export function leaseDeliveries(s:SignalStore,at:string,minutes=5){const out:Delivery[]=[];for(const [id,d]of s.deliveries){const expired=d.lease_until&&new Date(d.lease_until)<=new Date(at);if(out.length>=50||(!expired&&d.state!=="pending")||new Date(d.available_at)>new Date(at))continue;const n={...d,state:"leased" as const,attempt:d.attempt+1,lease_until:new Date(new Date(at).getTime()+minutes*60000).toISOString()};s.deliveries.set(id,n);out.push(n)}return out}
export function acknowledgeDelivery(s:SignalStore,id:string,at:string){const d=s.deliveries.get(id);if(!d||d.state!=="leased"||!d.lease_until||new Date(d.lease_until)<new Date(at))throw Error("signal_delivery_lease_invalid");const n={...d,state:"delivered" as const,lease_until:null};s.deliveries.set(id,n);return n}
export function failDelivery(s:SignalStore,id:string,error:string,at:string,max=3){const d=s.deliveries.get(id);if(!d||d.state!=="leased")throw Error("signal_delivery_lease_invalid");const n=d.attempt>=max?{...d,state:"quarantined" as const,lease_until:null,last_error:error}:{...d,state:"pending" as const,lease_until:null,last_error:error,available_at:new Date(new Date(at).getTime()+d.attempt*60000).toISOString()};s.deliveries.set(id,n);return n}
export function redriveDelivery(s:SignalStore,id:string,at:string){const d=s.deliveries.get(id);if(!d||d.state!=="quarantined")throw Error("signal_quarantine_missing");const n={...d,state:"pending" as const,attempt:0,available_at:at,last_error:undefined};s.deliveries.set(id,n);return n}
export function correlateSignals(s:SignalStore,company:string,correlation:string){return[...s.envelopes.values()].filter(x=>x.company_id===company&&x.correlation_id===correlation)}
export function evaluateSignalRule(e:SignalEnvelope,r:{version:string;event_type:string;predicate:(p:SignalPayload)=>boolean}){return e.event_type===r.event_type&&r.predicate(e.payload)?{projection_id:e.signal_id+":"+r.version,company_id:e.company_id,signal_id:e.signal_id,rule_version:r.version,alert:true,authority_effect:false as const}:null}
export function redactSignalForExport(e:SignalEnvelope){const p=Object.fromEntries(Object.entries(e.payload).filter(([k])=>!/password|secret|token|credential|location|phone|email/i.test(k)));return{...e,payload:p,payload_bytes:size(p)}}
export function markEvidenceReference(s:SignalStore,id:string,ref:string){if(!s.envelopes.has(id))throw Error("signal_missing");s.evidence_refs.add(id+":"+ref)}
export function pruneSignals(s:SignalStore,before:string){const out:string[]=[];for(const [id,e]of s.envelopes)if(new Date(e.ingested_at)<new Date(before)&&![...s.evidence_refs].some(x=>x.startsWith(id+":"))){s.envelopes.delete(id);s.archive.add(id);out.push(id)}return out}
export function legacySignalAdapter(i:{company_id:string;event_type:string;payload:SignalPayload;producer:SignalProducer},r:Map<string,SignalProducer>){return createSignalEnvelope({signal_id:"legacy:"+hash(i),event_type:i.event_type,company_id:i.company_id,source:"compatibility-adapter",capability:i.producer.capability,correlation_id:"legacy:"+hash(i),occurred_at:now(),observed_at:now(),producer:i.producer,payload:i.payload},r)}
