const text=(v,n)=>{const s=String(v??'').trim();if(!s)throw new Error(`${n}-required`);return s};
const list=v=>Array.isArray(v)?v:[];
const legacy=new Set(['tenant_id','tenant_company_id','tenant','workspace_tenant_id']);
function rejectLegacy(v,path='scheduling'){if(!v||typeof v!=='object')return;if(Array.isArray(v)){v.forEach((x,i)=>rejectLegacy(x,`${path}[${i}]`));return;}for(const[k,x]of Object.entries(v)){if(legacy.has(k))throw new Error(`legacy-company-boundary:${path}.${k}`);rejectLegacy(x,`${path}.${k}`);}}
const when=v=>{const n=Date.parse(String(v??''));return Number.isFinite(n)?n:null};
const reqCaps=v=>list(v).map(x=>typeof x==='string'?{capability_id:x,min_proficiency:0,require_verified:false}:{capability_id:x?.capability_id??x?.id??x?.name,min_proficiency:Number(x?.min_proficiency??x?.proficiency??x?.level??0)||0,require_verified:x?.require_verified===true}).map(x=>({...x,capability_id:String(x.capability_id??'').trim()})).filter(x=>x.capability_id).sort((a,b)=>a.capability_id.localeCompare(b.capability_id));
function fullWindowMatch(row,requested){const rs=when(requested?.starts_at),re=when(requested?.ends_at);if(rs===null||re===null||re<=rs)return false;return list(row?.windows).some(w=>{const s=when(w?.starts_at),e=when(w?.ends_at);return s!==null&&e!==null&&s<=rs&&e>=re;});}
function hasCapabilities(worker_id,requirements,registry){const rows=list(registry?.worker_capabilities).filter(r=>String(r?.worker_id)===worker_id);return requirements.every(req=>rows.some(r=>String(r?.capability_id)===req.capability_id&&Number(r?.proficiency??0)>=req.min_proficiency&&r?.verification_state!=='REVOKED'&&r?.verification_state!=='EXPIRED'&&(!req.require_verified||r?.verification_state==='VERIFIED')));}
function missingCapabilities(requirements,registry){const known=new Set(list(registry?.worker_capabilities).filter(r=>r?.verification_state!=='REVOKED'&&r?.verification_state!=='EXPIRED').map(r=>String(r?.capability_id)));return requirements.filter(r=>!known.has(r.capability_id)).map(r=>r.capability_id).sort();}
export function classifySchedulingConflict(input={},stages={}){const rs=when(input?.requested_window?.starts_at),re=when(input?.requested_window?.ends_at);const base={schema:'titan.scheduling.conflict.v1',grants_authority:false,execution_permitted:false,automatic_assignment:false};if(rs===null||re===null||re<=rs)return Object.freeze({...base,code:'INVALID_WINDOW',message:'Requested scheduling window is invalid.',missing_capabilities:[]});if(list(stages.capacityEligible).length===0)return Object.freeze({...base,code:'NO_CAPACITY',message:'No worker has enough available capacity.',missing_capabilities:[]});if(list(stages.capabilityEligible).length===0)return Object.freeze({...base,code:'MISSING_CAPABILITY',message:'No capacity-eligible worker satisfies required capabilities.',missing_capabilities:list(stages.missingCapabilities)});if(list(stages.timeEligible).length===0)return Object.freeze({...base,code:'NO_TIME_WINDOW',message:'No capability-eligible worker covers the full requested window.',missing_capabilities:[]});return null;}
export function matchSchedulingCandidates(input={},capacitySnapshot={},skillRegistry={},availability=[]){
 rejectLegacy(input); const company_id=text(input.company_id,'company-id'); const schedule_intent_id=text(input.schedule_intent_id,'schedule-intent-id'); const work_item_id=text(input.work_item_id,'work-item-id');
 if(capacitySnapshot?.schema!=='titan.workforce.workload-capacity.v1'||capacitySnapshot.company_id!==company_id)throw new Error('cross-company-capacity-denied');
 if(skillRegistry?.schema!=='titan.workforce.skill-capability-registry.v1'||skillRegistry.company_id!==company_id)throw new Error('cross-company-capability-registry-denied');
 for(const row of list(availability)){rejectLegacy(row,'availability');if(row?.company_id&&String(row.company_id)!==company_id)throw new Error('cross-company-availability-denied');}
 const requested_window=input.requested_window??null; const required_capacity_units=Math.max(0,Number(input.required_capacity_units??1)||1); const required_capabilities=reqCaps(input.required_capabilities);
 const capacityEligible=list(capacitySnapshot.worker_capacity).filter(w=>w&&Number(w.available_units??0)>=required_capacity_units&&String(w.state)!=='OVERLOADED');
 const capabilityEligible=capacityEligible.filter(w=>hasCapabilities(String(w.worker_id),required_capabilities,skillRegistry));
 const availabilityBy=new Map(list(availability).map(r=>[String(r?.worker_id??''),r]));
 const timeEligible=capabilityEligible.filter(w=>fullWindowMatch(availabilityBy.get(String(w.worker_id)),requested_window));
 const conflict=classifySchedulingConflict({requested_window},{capacityEligible,capabilityEligible,timeEligible,missingCapabilities:missingCapabilities(required_capabilities,skillRegistry)});
 const eligible_workers=timeEligible.map(w=>({worker_id:String(w.worker_id),available_units:Number(w.available_units??0),capacity_units:Number(w.capacity_units??0),utilization:Number(w.utilization??0),matched_capabilities:required_capabilities.map(r=>r.capability_id),window_match:'FULL',grants_authority:false})).sort((a,b)=>a.utilization-b.utilization||b.available_units-a.available_units||a.worker_id.localeCompare(b.worker_id));
 return Object.freeze({schema:'titan.scheduling.match-result.v1',company_id,schedule_intent_id,work_item_id,requested_window,required_capacity_units,required_capabilities,eligible_workers,conflict,requires_governed_assignment:true,requires_fresh_authority_evaluation:true,automatic_assignment:false,direct_mutation:false,execution_permitted:false,grants_authority:false});
}
