import test from 'node:test';
import assert from 'node:assert/strict';
import { ConsumableStockLedger } from '../../titan-inventory/runtime/consumable-stock.mjs';
import { JobInventoryEvidence } from '../../titan-inventory/runtime/job-inventory-evidence.mjs';
const p=(key)=>({source:'test',recorded_at:'2026-09-09T01:25:00.000Z',idempotency_key:key});
const seed=(l)=>l.stockIn({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',quantity:20,provenance:p('seed')});

test('job consumption records stock mutation plus authority-neutral evidence',()=>{const l=new ConsumableStockLedger(); seed(l); const e=new JobInventoryEvidence({ledger:l}); const r=e.recordJobConsumption({company_id:'co-a',job_id:'job-1',consumable_id:'chem-1',stock_location_id:'van-1',quantity:3,provenance:p('job-use-1')}); assert.equal(l.getBalance('co-a','chem-1','van-1'),17); assert.equal(r.evidence.evidence_type,'job_consumption'); assert.equal(r.evidence.stock_event_id,'job-use-1'); assert.ok(Object.values(r.evidence.authority).every(v=>v===false));});
test('replenishment evidence increases stock without purchase authority',()=>{const l=new ConsumableStockLedger(); const e=new JobInventoryEvidence({ledger:l}); const r=e.recordReplenishmentEvidence({company_id:'co-a',job_id:'job-1',consumable_id:'chem-1',stock_location_id:'van-1',quantity:5,provenance:p('replenish-1')}); assert.equal(l.getBalance('co-a','chem-1','van-1'),5); assert.equal(r.evidence.evidence_type,'job_replenishment'); assert.equal(r.evidence.authority.purchasing_authority_granted,false);});
test('replayed job evidence does not double mutate stock',()=>{const l=new ConsumableStockLedger(); seed(l); const e=new JobInventoryEvidence({ledger:l}); const args={company_id:'co-a',job_id:'job-1',consumable_id:'chem-1',stock_location_id:'van-1',quantity:4,provenance:p('offline-1')}; e.recordJobConsumption(args); const two=e.recordJobConsumption({...args,quantity:9}); assert.equal(two.replayed,true); assert.equal(l.getBalance('co-a','chem-1','van-1'),16);});
test('job evidence is company and job scoped',()=>{const l=new ConsumableStockLedger(); seed(l); l.stockIn({company_id:'co-b',consumable_id:'chem-1',stock_location_id:'van-1',quantity:5,provenance:p('seed-b')}); const e=new JobInventoryEvidence({ledger:l}); e.recordJobConsumption({company_id:'co-a',job_id:'job-a',consumable_id:'chem-1',stock_location_id:'van-1',quantity:1,provenance:p('a')}); e.recordJobConsumption({company_id:'co-b',job_id:'job-b',consumable_id:'chem-1',stock_location_id:'van-1',quantity:1,provenance:p('b')}); assert.equal(e.listJobEvidence('co-a','job-a').length,1); assert.equal(e.listJobEvidence('co-a','job-b').length,0);});
test('negative stock failure creates no job evidence',()=>{const l=new ConsumableStockLedger(); const e=new JobInventoryEvidence({ledger:l}); assert.throws(()=>e.recordJobConsumption({company_id:'co-a',job_id:'job-1',consumable_id:'chem-1',stock_location_id:'van-1',quantity:1,provenance:p('fail')}),/negative stock/); assert.equal(e.listJobEvidence('co-a','job-1').length,0);});
test('legacy boundary aliases fail closed',()=>{const l=new ConsumableStockLedger(); const e=new JobInventoryEvidence({ledger:l}); assert.throws(()=>e.recordReplenishmentEvidence({company_id:'co-a',tenant_id:'old',job_id:'job-1',consumable_id:'chem-1',stock_location_id:'van-1',quantity:1,provenance:p('legacy')}),/legacy boundary/);});
test('returned evidence is immutable to callers',()=>{const l=new ConsumableStockLedger(); seed(l); const e=new JobInventoryEvidence({ledger:l}); const r=e.recordJobConsumption({company_id:'co-a',job_id:'job-1',consumable_id:'chem-1',stock_location_id:'van-1',quantity:1,provenance:p('immut')}); r.evidence.authority.job_authority_granted=true; assert.equal(e.listJobEvidence('co-a','job-1')[0].authority.job_authority_granted,false);});
