import test from 'node:test';
import assert from 'node:assert/strict';
import { ConsumableStockLedger } from '../../titan-inventory/runtime/consumable-stock.mjs';
import { EquipmentRegister } from '../../titan-inventory/runtime/equipment-register.mjs';
import { InventoryAuditWorkflows } from '../../titan-inventory/runtime/stocktake-asset-exceptions.mjs';
const p=(key)=>({source:'offline_test',recorded_at:'2026-09-09T02:45:00.000Z',idempotency_key:key,trace_id:`trace-${key}`});

function stock(l,company='co-a',location='van-a',qty=10,key='seed'){l.stockIn({company_id:company,consumable_id:'chem-1',stock_location_id:location,quantity:qty,provenance:p(key)});}

test('duplicate adjustment replay is single-apply under offline retry',()=>{const l=new ConsumableStockLedger(); stock(l); const a=l.adjust({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-a',quantity:-2,provenance:p('adj-offline')}); const b=l.adjust({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-a',quantity:-2,provenance:p('adj-offline')}); assert.equal(a.balance,8); assert.equal(b.replayed,true); assert.equal(b.balance,8); assert.equal(l.getBalance('co-a','chem-1','van-a'),8);});

test('replayed event returns stored balance even if caller later mutates other locations',()=>{const l=new ConsumableStockLedger(); stock(l,'co-a','van-a',10,'a'); const first=l.use({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-a',quantity:2,provenance:p('use-1')}); stock(l,'co-a','van-b',99,'b'); const replay=l.use({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-a',quantity:7,provenance:p('use-1')}); assert.equal(first.balance,8); assert.equal(replay.balance,8);});

test('idempotency key reuse against a different location fails closed',()=>{const l=new ConsumableStockLedger(); stock(l,'co-a','van-a',10,'a'); l.use({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-a',quantity:1,provenance:p('same')}); assert.throws(()=>l.use({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-b',quantity:1,provenance:p('same')}),/idempotency key conflict/);});

test('negative stock use leaves balance and event history unchanged',()=>{const l=new ConsumableStockLedger(); stock(l,'co-a','van-a',3,'seed'); const before=l.listEvents('co-a').length; assert.throws(()=>l.use({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-a',quantity:4,provenance:p('too-much')}),/negative stock/); assert.equal(l.getBalance('co-a','chem-1','van-a'),3); assert.equal(l.listEvents('co-a').length,before);});

test('transfer moves stock atomically within one company',()=>{const l=new ConsumableStockLedger(); stock(l,'co-a','warehouse',10,'seed'); const r=l.transfer({company_id:'co-a',consumable_id:'chem-1',from_stock_location_id:'warehouse',to_stock_location_id:'van-a',quantity:4,provenance:p('transfer-1')}); assert.equal(r.transfer.source_balance_after,6); assert.equal(r.transfer.destination_balance_after,4); assert.equal(l.getBalance('co-a','chem-1','warehouse'),6); assert.equal(l.getBalance('co-a','chem-1','van-a'),4); assert.deepEqual(r.transfer.authority,{purchase_authority_granted:false,transfer_grants_business_authority:false});});

test('duplicate transfer replay does not double-move stock',()=>{const l=new ConsumableStockLedger(); stock(l,'co-a','warehouse',10,'seed'); l.transfer({company_id:'co-a',consumable_id:'chem-1',from_stock_location_id:'warehouse',to_stock_location_id:'van-a',quantity:4,provenance:p('transfer-1')}); const replay=l.transfer({company_id:'co-a',consumable_id:'chem-1',from_stock_location_id:'warehouse',to_stock_location_id:'van-a',quantity:9,provenance:p('transfer-1')}); assert.equal(replay.replayed,true); assert.equal(l.getBalance('co-a','chem-1','warehouse'),6); assert.equal(l.getBalance('co-a','chem-1','van-a'),4);});

test('insufficient transfer fails before either location mutates',()=>{const l=new ConsumableStockLedger(); stock(l,'co-a','warehouse',3,'seed'); assert.throws(()=>l.transfer({company_id:'co-a',consumable_id:'chem-1',from_stock_location_id:'warehouse',to_stock_location_id:'van-a',quantity:4,provenance:p('transfer-bad')}),/negative stock/); assert.equal(l.getBalance('co-a','chem-1','warehouse'),3); assert.equal(l.getBalance('co-a','chem-1','van-a'),0);});

test('transfer identities cannot be replayed to another company or route',()=>{const l=new ConsumableStockLedger(); stock(l,'co-a','warehouse',5,'a'); stock(l,'co-b','warehouse',5,'b'); l.transfer({company_id:'co-a',consumable_id:'chem-1',from_stock_location_id:'warehouse',to_stock_location_id:'van-a',quantity:1,provenance:p('route')}); assert.throws(()=>l.transfer({company_id:'co-a',consumable_id:'chem-1',from_stock_location_id:'warehouse',to_stock_location_id:'van-b',quantity:1,provenance:p('route')}),/idempotency key conflict/); const b=l.transfer({company_id:'co-b',consumable_id:'chem-1',from_stock_location_id:'warehouse',to_stock_location_id:'van-b',quantity:1,provenance:p('route')}); assert.equal(b.replayed,false); assert.equal(l.getBalance('co-b','chem-1','warehouse'),4);});

test('cross-company stocktake cannot read or reconcile another company balance',()=>{const stockLedger=new ConsumableStockLedger(); const equipmentRegister=new EquipmentRegister(); const w=new InventoryAuditWorkflows({stockLedger,equipmentRegister}); stock(stockLedger,'co-a','van-a',10,'a'); const r=w.recordStocktake({company_id:'co-b',consumable_id:'chem-1',stock_location_id:'van-a',counted_quantity:0,provenance:p('cross-count')}); assert.equal(r.record.expected_quantity,0); assert.equal(stockLedger.getBalance('co-a','chem-1','van-a'),10);});

test('stocktake adjustment offline replay stays single-apply',()=>{const stockLedger=new ConsumableStockLedger(); const equipmentRegister=new EquipmentRegister(); const w=new InventoryAuditWorkflows({stockLedger,equipmentRegister}); stock(stockLedger,'co-a','van-a',10,'seed'); w.recordStocktake({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-a',counted_quantity:7,apply_adjustment:true,provenance:p('stocktake-offline')}); const replay=w.recordStocktake({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-a',counted_quantity:1,apply_adjustment:true,provenance:p('stocktake-offline')}); assert.equal(replay.replayed,true); assert.equal(stockLedger.getBalance('co-a','chem-1','van-a'),7);});

test('legacy boundary aliases fail closed on transfer',()=>{const l=new ConsumableStockLedger(); assert.throws(()=>l.transfer({company_id:'co-a',tenant_id:'legacy',consumable_id:'chem-1',from_stock_location_id:'a',to_stock_location_id:'b',quantity:1,provenance:p('legacy')}),/legacy boundary/);});
