import test from 'node:test';
import assert from 'node:assert/strict';
import { ConsumableStockLedger } from '../../titan-inventory/runtime/consumable-stock.mjs';
import { ReorderRecommendationEngine } from '../../titan-inventory/runtime/reorder-recommendations.mjs';
const p=(key)=>({source:'test',recorded_at:'2026-09-09T01:40:00.000Z',idempotency_key:key});
const setup=()=>{const ledger=new ConsumableStockLedger(); const engine=new ReorderRecommendationEngine({ledger}); return {ledger,engine};};

test('reorder recommendation appears at or below threshold and links catalogue product',()=>{const {ledger,engine}=setup(); ledger.stockIn({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',quantity:2,provenance:p('seed')}); engine.setPolicy({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',reorder_threshold:2,target_stock:10,catalog_product_id:'chem-neutral-floor',provenance:p('policy')}); const [r]=engine.recommend('co-a'); assert.equal(r.status,'REORDER_RECOMMENDED'); assert.equal(r.suggested_quantity,8); assert.equal(r.product_ref.catalog_product_id,'chem-neutral-floor');});
test('recommendations never grant automatic purchase or marketplace authority',()=>{const {engine}=setup(); engine.setPolicy({company_id:'co-a',consumable_id:'gloves',stock_location_id:'store',reorder_threshold:5,marketplace_product_id:'ppe-gloves',provenance:p('auth')}); const [r]=engine.recommend('co-a'); assert.deepEqual(r.authority,{purchase_authority_granted:false,automatic_order_authority_granted:false,marketplace_identity_grants_authority:false}); assert.equal(r.action,'REVIEW_REPLENISHMENT');});
test('sufficient stock is omitted by default and can be inspected explicitly',()=>{const {ledger,engine}=setup(); ledger.stockIn({company_id:'co-a',consumable_id:'cloths',stock_location_id:'store',quantity:20,provenance:p('stock')}); engine.setPolicy({company_id:'co-a',consumable_id:'cloths',stock_location_id:'store',reorder_threshold:5,target_stock:15,catalog_product_id:'cons-microfibre-general',provenance:p('policy')}); assert.equal(engine.recommend('co-a').length,0); const [r]=engine.recommend('co-a',{include_sufficient:true}); assert.equal(r.status,'SUFFICIENT_STOCK'); assert.equal(r.suggested_quantity,0);});
test('recommendations are company and location scoped',()=>{const {ledger,engine}=setup(); ledger.stockIn({company_id:'co-b',consumable_id:'chem-1',stock_location_id:'van-1',quantity:50,provenance:p('b-stock')}); engine.setPolicy({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',reorder_threshold:3,target_stock:8,catalog_product_id:'chem-glass',provenance:p('a-policy')}); engine.setPolicy({company_id:'co-b',consumable_id:'chem-1',stock_location_id:'van-1',reorder_threshold:3,target_stock:8,catalog_product_id:'chem-glass',provenance:p('b-policy')}); assert.equal(engine.recommend('co-a').length,1); assert.equal(engine.recommend('co-b').length,0);});
test('policy replay is idempotent and does not let retry mutate threshold',()=>{const {engine}=setup(); const args={company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',reorder_threshold:3,target_stock:9,catalog_product_id:'chem-glass',provenance:p('same')}; engine.setPolicy(args); const replay=engine.setPolicy({...args,reorder_threshold:99}); assert.equal(replay.replayed,true); assert.equal(engine.getPolicy('co-a','chem-1','van-1').reorder_threshold,3);});
test('legacy company boundary aliases fail closed',()=>{const {engine}=setup(); assert.throws(()=>engine.setPolicy({company_id:'co-a',tenant_id:'legacy',consumable_id:'chem-1',stock_location_id:'van-1',reorder_threshold:1,provenance:p('legacy')}),/legacy boundary/);});
test('invalid target below threshold is rejected',()=>{const {engine}=setup(); assert.throws(()=>engine.setPolicy({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',reorder_threshold:5,target_stock:4,provenance:p('bad')}),/target_stock/);});
test('discontinued policy emits no replenishment recommendation',()=>{const {engine}=setup(); engine.setPolicy({company_id:'co-a',consumable_id:'old',stock_location_id:'store',reorder_threshold:2,target_stock:5,catalog_product_id:'old-product',lifecycle_state:'discontinued',provenance:p('old')}); assert.equal(engine.recommend('co-a').length,0);});
