import test from 'node:test';
import assert from 'node:assert/strict';
import { ConsumableStockLedger } from '../../titan-inventory/runtime/consumable-stock.mjs';
import { EquipmentRegister } from '../../titan-inventory/runtime/equipment-register.mjs';
import { InventoryAuditWorkflows } from '../../titan-inventory/runtime/stocktake-asset-exceptions.mjs';
const p=(key)=>({source:'test',recorded_at:'2026-09-09T02:20:00.000Z',idempotency_key:key});
function setup(){const stockLedger=new ConsumableStockLedger(); const equipmentRegister=new EquipmentRegister(); const workflows=new InventoryAuditWorkflows({stockLedger,equipmentRegister}); return {stockLedger,equipmentRegister,workflows};}
function asset(reg,company='co-a',id='vac-1'){reg.register({company_id:company,asset_id:id,asset_type:'equipment',name:'Vacuum',lifecycle_state:'available',condition_state:'good',provenance:p(`asset-${company}-${id}`)});}

test('stocktake records exact match without adjustment',()=>{const {stockLedger,workflows}=setup(); stockLedger.stockIn({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',quantity:10,provenance:p('in')}); const r=workflows.recordStocktake({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',counted_quantity:10,provenance:p('st')}); assert.equal(r.record.discrepancy,0); assert.equal(r.record.discrepancy_state,'MATCH'); assert.equal(r.record.adjustment_applied,false); assert.equal(stockLedger.getBalance('co-a','chem-1','van-1'),10);});
test('shortage can be auditable evidence without mutating stock',()=>{const {stockLedger,workflows}=setup(); stockLedger.stockIn({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',quantity:10,provenance:p('in')}); const r=workflows.recordStocktake({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',counted_quantity:7,reason:'counted short',provenance:p('short')}); assert.equal(r.record.discrepancy,-3); assert.equal(r.record.review_required,true); assert.equal(stockLedger.getBalance('co-a','chem-1','van-1'),10);});
test('explicit stocktake adjustment reconciles shortage through existing ledger',()=>{const {stockLedger,workflows}=setup(); stockLedger.stockIn({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',quantity:10,provenance:p('in')}); const r=workflows.recordStocktake({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',counted_quantity:7,apply_adjustment:true,provenance:p('short-adjust')}); assert.equal(r.record.adjustment_applied,true); assert.equal(stockLedger.getBalance('co-a','chem-1','van-1'),7); assert.equal(stockLedger.listEvents('co-a').at(-1).reason,'stocktake_discrepancy');});
test('surplus adjustment can increase balance but grants no purchase authority',()=>{const {stockLedger,workflows}=setup(); stockLedger.stockIn({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',quantity:5,provenance:p('in')}); const r=workflows.recordStocktake({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',counted_quantity:8,apply_adjustment:true,provenance:p('surplus')}); assert.equal(stockLedger.getBalance('co-a','chem-1','van-1'),8); assert.deepEqual(r.record.authority,{purchase_authority_granted:false,automatic_reorder_authority_granted:false,stocktake_grants_business_authority:false});});
test('duplicate stocktake replay does not apply adjustment twice',()=>{const {stockLedger,workflows}=setup(); stockLedger.stockIn({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',quantity:10,provenance:p('in')}); workflows.recordStocktake({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',counted_quantity:8,apply_adjustment:true,provenance:p('dup')}); const replay=workflows.recordStocktake({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',counted_quantity:1,apply_adjustment:true,provenance:p('dup')}); assert.equal(replay.replayed,true); assert.equal(stockLedger.getBalance('co-a','chem-1','van-1'),8);});
test('damaged equipment is recorded and transitioned to damaged lifecycle',()=>{const {equipmentRegister,workflows}=setup(); asset(equipmentRegister); const r=workflows.reportAssetException({company_id:'co-a',asset_id:'vac-1',exception_type:'damaged',evidence:{photo_ref:'photo-1'},provenance:p('damage')}); assert.equal(r.record.after.lifecycle_state,'damaged'); assert.equal(r.record.after.condition_state,'damaged'); assert.equal(r.record.evidence.photo_ref,'photo-1');});
test('lost equipment clears assignment through existing equipment register semantics',()=>{const {equipmentRegister,workflows}=setup(); asset(equipmentRegister); equipmentRegister.assign({company_id:'co-a',asset_id:'vac-1',assignment_type:'worker',assignment_id:'worker-1',provenance:p('assign')}); const r=workflows.reportAssetException({company_id:'co-a',asset_id:'vac-1',exception_type:'lost',provenance:p('lost')}); assert.equal(r.record.after.lifecycle_state,'lost'); assert.equal(r.record.after.assigned_worker_id,null);});
test('asset exception recommendation never grants replacement purchasing authority',()=>{const {equipmentRegister,workflows}=setup(); asset(equipmentRegister); const r=workflows.reportAssetException({company_id:'co-a',asset_id:'vac-1',exception_type:'lost',replacement_recommended:true,provenance:p('replace')}); assert.equal(r.record.replacement_recommended,true); assert.deepEqual(r.record.authority,{purchase_authority_granted:false,replacement_purchase_authority_granted:false,asset_exception_grants_business_authority:false});});
test('records remain company scoped',()=>{const {stockLedger,equipmentRegister,workflows}=setup(); stockLedger.stockIn({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',quantity:2,provenance:p('in')}); workflows.recordStocktake({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',counted_quantity:2,provenance:p('sta')}); asset(equipmentRegister,'co-b','vac-b'); workflows.reportAssetException({company_id:'co-b',asset_id:'vac-b',exception_type:'damaged',provenance:p('db')}); assert.equal(workflows.listRecords('co-a').length,1); assert.equal(workflows.listRecords('co-b').length,1);});
test('wrong-company asset exception fails closed',()=>{const {equipmentRegister,workflows}=setup(); asset(equipmentRegister,'co-a','vac-1'); assert.throws(()=>workflows.reportAssetException({company_id:'co-b',asset_id:'vac-1',exception_type:'lost',provenance:p('cross')}),/asset not found/);});
test('legacy boundary aliases fail closed',()=>{const {workflows}=setup(); assert.throws(()=>workflows.recordStocktake({company_id:'co-a',tenant_id:'legacy',consumable_id:'chem-1',stock_location_id:'van-1',counted_quantity:0,provenance:p('legacy')}),/legacy boundary/);});
test('returned audit records are immutable to callers',()=>{const {stockLedger,workflows}=setup(); stockLedger.stockIn({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',quantity:1,provenance:p('in')}); workflows.recordStocktake({company_id:'co-a',consumable_id:'chem-1',stock_location_id:'van-1',counted_quantity:1,provenance:p('immut')}); const rows=workflows.listRecords('co-a'); rows[0].authority.purchase_authority_granted=true; assert.equal(workflows.listRecords('co-a')[0].authority.purchase_authority_granted,false);});
