import { randomUUID } from "node:crypto";
import type { StorageClient } from "@titan-zero/storage";
import { requireCompanyId } from "@titan-zero/storage";

export const WORK_STATES = ["CREATED", "READY", "CLAIMED", "IN_PROGRESS", "BLOCKED", "WAITING", "WAITING_APPROVAL", "WAITING_EXTERNAL", "COMPLETED", "FAILED", "CANCELLED"] as const;
export type WorkState = typeof WORK_STATES[number];
export type WorkerKind = "digital" | "human";
export type WorkerRole = "manager" | "supervisor" | "specialist" | "worker" | "field-worker" | string;
export type WorkActor = { type: "human" | "worker" | "system"; id: string };
export type RuntimeOutcome = { outcome: "completed"; result?: unknown; evidenceRefs?: string[] } | { outcome: "waiting"; waitKind?: "generic" | "approval" | "external"; resumeSignal?: string } | { outcome: "failed"; error: string };
export interface AgentRuntimeAdapter { run(input: { companyId: string; workerId: string; work: WorkItem }): Promise<RuntimeOutcome>; }
export interface WorkforceEventSink { emit(event: WorkforceEvent): Promise<void> | void; }

export interface WorkerInput { workerId: string; kind: WorkerKind; role: WorkerRole; teamId?: string; managerWorkerId?: string; capabilities?: string[]; active?: boolean; }
export interface Worker extends Required<Pick<WorkerInput, "workerId" | "kind" | "role">> { companyId: string; teamId: string | null; managerWorkerId: string | null; capabilities: string[]; active: boolean; }
export interface WorkInput { objective: string; description?: string; creator: WorkActor; parentWorkId?: string; assigneeWorkerId?: string; teamId?: string; priority?: number; dependencies?: string[]; requiredCapabilities?: string[]; authorityRequirement?: string; contextRefs?: string[]; evidenceRefs?: string[]; }
export interface WorkItem { companyId: string; workId: string; parentWorkId: string | null; objective: string; description: string | null; creator: WorkActor; assigneeWorkerId: string | null; teamId: string | null; priority: number; state: WorkState; dependencies: string[]; requiredCapabilities: string[]; authorityRequirement: string | null; contextRefs: string[]; evidenceRefs: string[]; result: unknown; waitSignal: string | null; claimOwner: string | null; createdAt: string; updatedAt: string; }
export interface WorkforceEvent { eventId: string; companyId: string; workId: string | null; workerId: string | null; type: string; data: unknown; createdAt: string; }
export interface RecurringWorkInput { recurringId: string; schedule: string; template: WorkInput; enabled?: boolean; }

type Row = Record<string, unknown>;
const terminal = new Set<WorkState>(["COMPLETED", "FAILED", "CANCELLED"]);
const transitions: Record<WorkState, Set<WorkState>> = {
  CREATED: new Set(["READY", "CANCELLED", "FAILED"]), READY: new Set(["CLAIMED", "CANCELLED", "FAILED", "WAITING_APPROVAL"]), CLAIMED: new Set(["IN_PROGRESS", "READY", "CANCELLED", "FAILED"]),
  IN_PROGRESS: new Set(["BLOCKED", "WAITING", "WAITING_APPROVAL", "WAITING_EXTERNAL", "COMPLETED", "FAILED", "CANCELLED", "READY"]), BLOCKED: new Set(["READY", "FAILED", "CANCELLED"]),
  WAITING: new Set(["READY", "FAILED", "CANCELLED"]), WAITING_APPROVAL: new Set(["READY", "FAILED", "CANCELLED"]), WAITING_EXTERNAL: new Set(["READY", "FAILED", "CANCELLED"]),
  COMPLETED: new Set(), FAILED: new Set(), CANCELLED: new Set(),
};

const j = (value: unknown) => JSON.stringify(value ?? null);
const p = <T>(value: unknown, fallback: T): T => { try { return typeof value === "string" ? JSON.parse(value) as T : fallback; } catch { return fallback; } };
const now = () => new Date().toISOString();

export class WorkforceService {
  constructor(private readonly storage: StorageClient, private readonly adapters: { runtime?: AgentRuntimeAdapter; events?: WorkforceEventSink } = {}) {}

  async initialize(): Promise<void> {
    await this.storage.query(`CREATE TABLE IF NOT EXISTS workforce_workers (company_id TEXT NOT NULL, worker_id TEXT NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('digital','human')), role TEXT NOT NULL, team_id TEXT, manager_worker_id TEXT, capabilities_json TEXT NOT NULL DEFAULT '[]', active INTEGER NOT NULL DEFAULT 1, PRIMARY KEY(company_id, worker_id))`);
    await this.storage.query(`CREATE TABLE IF NOT EXISTS workforce_work (company_id TEXT NOT NULL, work_id TEXT NOT NULL, parent_work_id TEXT, objective TEXT NOT NULL, description TEXT, creator_json TEXT NOT NULL, assignee_worker_id TEXT, team_id TEXT, priority INTEGER NOT NULL DEFAULT 50, state TEXT NOT NULL, required_capabilities_json TEXT NOT NULL DEFAULT '[]', authority_requirement TEXT, context_refs_json TEXT NOT NULL DEFAULT '[]', evidence_refs_json TEXT NOT NULL DEFAULT '[]', result_json TEXT, wait_signal TEXT, claim_owner TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(company_id, work_id))`);
    await this.storage.query(`CREATE TABLE IF NOT EXISTS workforce_dependencies (company_id TEXT NOT NULL, work_id TEXT NOT NULL, depends_on_work_id TEXT NOT NULL, PRIMARY KEY(company_id, work_id, depends_on_work_id))`);
    await this.storage.query(`CREATE TABLE IF NOT EXISTS workforce_events (event_id TEXT PRIMARY KEY, company_id TEXT NOT NULL, work_id TEXT, worker_id TEXT, type TEXT NOT NULL, data_json TEXT, created_at TEXT NOT NULL)`);
    await this.storage.query(`CREATE INDEX IF NOT EXISTS idx_workforce_ready ON workforce_work(company_id, state, priority, created_at)`);
    await this.storage.query(`CREATE INDEX IF NOT EXISTS idx_workforce_assignee ON workforce_work(company_id, assignee_worker_id, state)`);
    await this.storage.query(`CREATE TABLE IF NOT EXISTS workforce_recurring (company_id TEXT NOT NULL, recurring_id TEXT NOT NULL, schedule TEXT NOT NULL, template_json TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, PRIMARY KEY(company_id, recurring_id))`);
    await this.storage.query(`CREATE TABLE IF NOT EXISTS workforce_occurrences (company_id TEXT NOT NULL, recurring_id TEXT NOT NULL, occurrence_key TEXT NOT NULL, work_id TEXT NOT NULL, PRIMARY KEY(company_id, recurring_id, occurrence_key))`);
  }

  async registerWorker(companyIdRaw: string, input: WorkerInput): Promise<Worker> {
    const companyId = requireCompanyId(companyIdRaw); if (!input.workerId.trim()) throw new Error("worker_id is required");
    if (input.managerWorkerId) await this.getWorker(companyId, input.managerWorkerId);
    await this.storage.query(`INSERT INTO workforce_workers(company_id,worker_id,kind,role,team_id,manager_worker_id,capabilities_json,active) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(company_id,worker_id) DO UPDATE SET kind=excluded.kind,role=excluded.role,team_id=excluded.team_id,manager_worker_id=excluded.manager_worker_id,capabilities_json=excluded.capabilities_json,active=excluded.active`, [companyId,input.workerId,input.kind,input.role,input.teamId??null,input.managerWorkerId??null,j(input.capabilities??[]),input.active===false?0:1]);
    return this.getWorker(companyId,input.workerId);
  }

  async getWorker(companyIdRaw: string, workerId: string): Promise<Worker> {
    const companyId=requireCompanyId(companyIdRaw); const q=await this.storage.query<Row>(`SELECT * FROM workforce_workers WHERE company_id=? AND worker_id=?`,[companyId,workerId]); if(!q.rows[0]) throw new Error("worker not found"); const r=q.rows[0];
    return { companyId, workerId:String(r.worker_id), kind:r.kind as WorkerKind, role:String(r.role), teamId:r.team_id?String(r.team_id):null, managerWorkerId:r.manager_worker_id?String(r.manager_worker_id):null, capabilities:p<string[]>(r.capabilities_json,[]), active:Boolean(r.active) };
  }

  async createWork(companyIdRaw: string, input: WorkInput): Promise<WorkItem> {
    const companyId=requireCompanyId(companyIdRaw); if(!input.objective.trim()) throw new Error("objective is required"); if(input.assigneeWorkerId) await this.getWorker(companyId,input.assigneeWorkerId); if(input.parentWorkId) await this.getWork(companyId,input.parentWorkId);
    const workId=randomUUID(), stamp=now(); const deps=input.dependencies??[]; for(const dep of deps) await this.getWork(companyId,dep);
    const state:WorkState=deps.length?"CREATED":"READY";
    await this.storage.transaction(async tx=>{ await tx.query(`INSERT INTO workforce_work(company_id,work_id,parent_work_id,objective,description,creator_json,assignee_worker_id,team_id,priority,state,required_capabilities_json,authority_requirement,context_refs_json,evidence_refs_json,result_json,wait_signal,claim_owner,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[companyId,workId,input.parentWorkId??null,input.objective,input.description??null,j(input.creator),input.assigneeWorkerId??null,input.teamId??null,input.priority??50,state,j(input.requiredCapabilities??[]),input.authorityRequirement??null,j(input.contextRefs??[]),j(input.evidenceRefs??[]),null,null,null,stamp,stamp]); for(const dep of deps) await tx.query(`INSERT INTO workforce_dependencies(company_id,work_id,depends_on_work_id) VALUES(?,?,?)`,[companyId,workId,dep]); });
    await this.event(companyId,workId,input.assigneeWorkerId??null,"work.created",{creator:input.creator}); if(state==="READY") await this.event(companyId,workId,input.assigneeWorkerId??null,"work.ready",{}); return this.getWork(companyId,workId);
  }

  async getWork(companyIdRaw:string,workId:string):Promise<WorkItem>{ const companyId=requireCompanyId(companyIdRaw); const q=await this.storage.query<Row>(`SELECT * FROM workforce_work WHERE company_id=? AND work_id=?`,[companyId,workId]); if(!q.rows[0]) throw new Error("work not found"); const r=q.rows[0]; const d=await this.storage.query<Row>(`SELECT depends_on_work_id FROM workforce_dependencies WHERE company_id=? AND work_id=? ORDER BY depends_on_work_id`,[companyId,workId]); return {companyId,workId:String(r.work_id),parentWorkId:r.parent_work_id?String(r.parent_work_id):null,objective:String(r.objective),description:r.description?String(r.description):null,creator:p<WorkActor>(r.creator_json,{type:"system",id:"unknown"}),assigneeWorkerId:r.assignee_worker_id?String(r.assignee_worker_id):null,teamId:r.team_id?String(r.team_id):null,priority:Number(r.priority),state:r.state as WorkState,dependencies:d.rows.map(x=>String(x.depends_on_work_id)),requiredCapabilities:p<string[]>(r.required_capabilities_json,[]),authorityRequirement:r.authority_requirement?String(r.authority_requirement):null,contextRefs:p<string[]>(r.context_refs_json,[]),evidenceRefs:p<string[]>(r.evidence_refs_json,[]),result:p(r.result_json,null),waitSignal:r.wait_signal?String(r.wait_signal):null,claimOwner:r.claim_owner?String(r.claim_owner):null,createdAt:String(r.created_at),updatedAt:String(r.updated_at)}; }

  async addDependency(companyIdRaw:string,workId:string,dependsOn:string):Promise<void>{ const companyId=requireCompanyId(companyIdRaw); await this.getWork(companyId,workId); await this.getWork(companyId,dependsOn); if(workId===dependsOn||await this.reachable(companyId,dependsOn,workId)) throw new Error("circular dependency rejected"); await this.storage.query(`INSERT OR IGNORE INTO workforce_dependencies(company_id,work_id,depends_on_work_id) VALUES(?,?,?)`,[companyId,workId,dependsOn]); const work=await this.getWork(companyId,workId); if(work.state==="READY") await this.transition(companyId,workId,"CREATED",{},true); }
  private async reachable(companyId:string,from:string,target:string,seen=new Set<string>()):Promise<boolean>{ if(from===target)return true;if(seen.has(from))return false;seen.add(from);const q=await this.storage.query<Row>(`SELECT depends_on_work_id FROM workforce_dependencies WHERE company_id=? AND work_id=?`,[companyId,from]);for(const r of q.rows)if(await this.reachable(companyId,String(r.depends_on_work_id),target,seen))return true;return false; }
  private async depsSatisfied(companyId:string,workId:string):Promise<boolean>{ const q=await this.storage.query<Row>(`SELECT w.state FROM workforce_dependencies d JOIN workforce_work w ON w.company_id=d.company_id AND w.work_id=d.depends_on_work_id WHERE d.company_id=? AND d.work_id=?`,[companyId,workId]); return q.rows.every(r=>r.state==="COMPLETED"); }

  async claimWork(companyIdRaw:string,workId:string,workerId:string):Promise<WorkItem>{ const companyId=requireCompanyId(companyIdRaw); const worker=await this.getWorker(companyId,workerId); if(!worker.active)throw new Error("worker inactive"); return this.storage.transaction(async tx=>{ const q=await tx.query<Row>(`SELECT state,assignee_worker_id,required_capabilities_json FROM workforce_work WHERE company_id=? AND work_id=?`,[companyId,workId]);if(!q.rows[0])throw new Error("work not found");const r=q.rows[0];if(r.state!=="READY")throw new Error("work is not claimable");if(r.assignee_worker_id&&r.assignee_worker_id!==workerId)throw new Error("work assigned to another worker");const required=p<string[]>(r.required_capabilities_json,[]);if(required.some(c=>!worker.capabilities.includes(c)))throw new Error("worker lacks required capability");const u=await tx.query(`UPDATE workforce_work SET state='CLAIMED',assignee_worker_id=?,claim_owner=?,updated_at=? WHERE company_id=? AND work_id=? AND state='READY'`,[workerId,workerId,now(),companyId,workId]);if(u.rowCount!==1)throw new Error("work is not claimable");await this.event(companyId,workId,workerId,"work.claimed",{});return this.getWork(companyId,workId);}); }
  async startWork(companyId:string,workId:string,workerId:string){ const work=await this.getWork(companyId,workId);if(work.claimOwner!==workerId)throw new Error("claim owner mismatch");return this.transition(companyId,workId,"IN_PROGRESS",{workerId}); }
  async completeWork(companyId:string,workId:string,result:unknown,evidenceRefs:string[]=[]){ const work=await this.getWork(companyId,workId);if(terminal.has(work.state))throw new Error("work already terminal");const merged=[...new Set([...work.evidenceRefs,...evidenceRefs])];const done=await this.transition(companyId,workId,"COMPLETED",{result,evidenceRefs:merged});await this.storage.query(`UPDATE workforce_work SET result_json=?,evidence_refs_json=? WHERE company_id=? AND work_id=?`,[j(result),j(merged),requireCompanyId(companyId),workId]);await this.releaseDependants(requireCompanyId(companyId),workId);return this.getWork(companyId,workId); }
  async failWork(companyId:string,workId:string,error:string){return this.transition(companyId,workId,"FAILED",{error});}
  async cancelWork(companyId:string,workId:string,reason:string){return this.transition(companyId,workId,"CANCELLED",{reason});}
  async blockWork(companyId:string,workId:string,reason:string){return this.transition(companyId,workId,"BLOCKED",{reason});}
  async waitWork(companyId:string,workId:string,kind:"generic"|"approval"|"external",signal?:string){const target=kind==="approval"?"WAITING_APPROVAL":kind==="external"?"WAITING_EXTERNAL":"WAITING";const w=await this.transition(companyId,workId,target,{signal});await this.storage.query(`UPDATE workforce_work SET wait_signal=? WHERE company_id=? AND work_id=?`,[signal??null,requireCompanyId(companyId),workId]);return this.getWork(companyId,workId);}
  async resumeWork(companyId:string,workId:string,signal?:string){const work=await this.getWork(companyId,workId);if(!["WAITING","WAITING_APPROVAL","WAITING_EXTERNAL","BLOCKED"].includes(work.state))throw new Error("work is not waiting");if(work.waitSignal&&signal!==work.waitSignal)throw new Error("resume signal mismatch");const w=await this.transition(companyId,workId,"READY",{signal});await this.storage.query(`UPDATE workforce_work SET wait_signal=NULL,claim_owner=NULL WHERE company_id=? AND work_id=?`,[requireCompanyId(companyId),workId]);await this.event(requireCompanyId(companyId),workId,w.assigneeWorkerId,"work.resumed",{signal});return this.getWork(companyId,workId);}

  async assignWork(companyId:string,workId:string,workerId:string){await this.getWorker(companyId,workerId);await this.getWork(companyId,workId);await this.storage.query(`UPDATE workforce_work SET assignee_worker_id=?,updated_at=? WHERE company_id=? AND work_id=?`,[workerId,now(),requireCompanyId(companyId),workId]);await this.event(requireCompanyId(companyId),workId,workerId,"work.assigned",{});return this.getWork(companyId,workId);}
  async decomposeWork(companyId:string,parentWorkId:string,managerWorkerId:string,children:Array<Omit<WorkInput,"creator"|"parentWorkId"> & {authorityRequirement?:string}>){const manager=await this.getWorker(companyId,managerWorkerId);if(manager.kind!=="digital"||!manager.capabilities.includes("work.delegate"))throw new Error("worker cannot delegate");await this.getWork(companyId,parentWorkId);const out:WorkItem[]=[];for(const child of children){const created=await this.createWork(companyId,{...child,parentWorkId,creator:{type:"worker",id:managerWorkerId}});await this.event(requireCompanyId(companyId),created.workId,created.assigneeWorkerId,"work.delegated",{from:managerWorkerId,parentWorkId});out.push(created);}return out;}
  async escalateWork(companyId:string,workId:string,workerId:string,reason:string){const worker=await this.getWorker(companyId,workerId);if(!worker.managerWorkerId)throw new Error("no manager configured for escalation");await this.getWorker(companyId,worker.managerWorkerId);await this.storage.query(`UPDATE workforce_work SET assignee_worker_id=?,claim_owner=NULL,state='READY',updated_at=? WHERE company_id=? AND work_id=?`,[worker.managerWorkerId,now(),requireCompanyId(companyId),workId]);await this.event(requireCompanyId(companyId),workId,worker.managerWorkerId,"work.escalated",{from:workerId,reason});return this.getWork(companyId,workId);}

  async listReady(companyId:string):Promise<WorkItem[]>{const q=await this.storage.query<Row>(`SELECT work_id FROM workforce_work WHERE company_id=? AND state='READY' ORDER BY priority DESC,created_at ASC`,[requireCompanyId(companyId)]);const out:WorkItem[]=[];for(const r of q.rows)out.push(await this.getWork(companyId,String(r.work_id)));return out;}
  async routeByCapability(companyId:string,required:string[],teamId?:string):Promise<Worker[]>{const q=await this.storage.query<Row>(`SELECT worker_id FROM workforce_workers WHERE company_id=? AND kind='digital' AND active=1 ${teamId?"AND team_id=?":""} ORDER BY worker_id`,teamId?[requireCompanyId(companyId),teamId]:[requireCompanyId(companyId)]);const out:Worker[]=[];for(const r of q.rows){const w=await this.getWorker(companyId,String(r.worker_id));if(required.every(c=>w.capabilities.includes(c)))out.push(w);}return out;}
  async dispatchReady(companyId:string):Promise<string[]>{if(!this.adapters.runtime)return[];const dispatched:string[]=[];for(const work of await this.listReady(companyId)){let workerId=work.assigneeWorkerId;if(!workerId){const [candidate]=await this.routeByCapability(companyId,work.requiredCapabilities,work.teamId??undefined);workerId=candidate?.workerId??null;}if(!workerId)continue;const worker=await this.getWorker(companyId,workerId);if(worker.kind!=="digital")continue;const claimed=await this.claimWork(companyId,work.workId,workerId);await this.event(requireCompanyId(companyId),work.workId,workerId,"worker.woken",{});await this.startWork(companyId,work.workId,workerId);await this.event(requireCompanyId(companyId),work.workId,workerId,"worker.started",{});try{const outcome=await this.adapters.runtime.run({companyId:requireCompanyId(companyId),workerId,work:claimed});if(outcome.outcome==="completed"){await this.completeWork(companyId,work.workId,outcome.result,outcome.evidenceRefs??[]);await this.event(requireCompanyId(companyId),work.workId,workerId,"worker.completed",{});}else if(outcome.outcome==="waiting"){await this.waitWork(companyId,work.workId,outcome.waitKind??"generic",outcome.resumeSignal);await this.event(requireCompanyId(companyId),work.workId,workerId,"worker.waiting",{});}else await this.failWork(companyId,work.workId,outcome.error);}catch(error){await this.failWork(companyId,work.workId,error instanceof Error?error.message:String(error));}dispatched.push(work.workId);}return dispatched;}

  async createRecurringWork(companyId:string,input:RecurringWorkInput){requireCompanyId(companyId);await this.storage.query(`INSERT INTO workforce_recurring(company_id,recurring_id,schedule,template_json,enabled) VALUES(?,?,?,?,?) ON CONFLICT(company_id,recurring_id) DO UPDATE SET schedule=excluded.schedule,template_json=excluded.template_json,enabled=excluded.enabled`,[companyId,input.recurringId,input.schedule,j(input.template),input.enabled===false?0:1]);return input;}
  async activateRecurring(companyId:string,recurringId:string,occurrenceKey:string):Promise<WorkItem>{const cid=requireCompanyId(companyId);const existing=await this.storage.query<Row>(`SELECT work_id FROM workforce_occurrences WHERE company_id=? AND recurring_id=? AND occurrence_key=?`,[cid,recurringId,occurrenceKey]);if(existing.rows[0])return this.getWork(cid,String(existing.rows[0].work_id));const q=await this.storage.query<Row>(`SELECT template_json,enabled FROM workforce_recurring WHERE company_id=? AND recurring_id=?`,[cid,recurringId]);if(!q.rows[0]||!q.rows[0].enabled)throw new Error("recurring work not found or disabled");const work=await this.createWork(cid,p<WorkInput>(q.rows[0].template_json,{} as WorkInput));await this.storage.query(`INSERT INTO workforce_occurrences(company_id,recurring_id,occurrence_key,work_id) VALUES(?,?,?,?)`,[cid,recurringId,occurrenceKey,work.workId]);return work;}
  async listEvents(companyId:string,workId?:string):Promise<WorkforceEvent[]>{const cid=requireCompanyId(companyId);const q=await this.storage.query<Row>(`SELECT * FROM workforce_events WHERE company_id=? ${workId?"AND work_id=?":""} ORDER BY created_at,event_id`,workId?[cid,workId]:[cid]);return q.rows.map(r=>({eventId:String(r.event_id),companyId:cid,workId:r.work_id?String(r.work_id):null,workerId:r.worker_id?String(r.worker_id):null,type:String(r.type),data:p(r.data_json,null),createdAt:String(r.created_at)}));}

  private async transition(companyIdRaw:string,workId:string,to:WorkState,data:unknown={},force=false):Promise<WorkItem>{const companyId=requireCompanyId(companyIdRaw);const work=await this.getWork(companyId,workId);if(!force&&!transitions[work.state].has(to))throw new Error(`invalid work transition ${work.state} -> ${to}`);await this.storage.query(`UPDATE workforce_work SET state=?,updated_at=? WHERE company_id=? AND work_id=?`,[to,now(),companyId,workId]);const type=to==="READY"?"work.ready":to==="IN_PROGRESS"?"work.started":to==="COMPLETED"?"work.completed":to==="FAILED"?"work.failed":to==="CANCELLED"?"work.cancelled":to==="BLOCKED"?"work.blocked":to.startsWith("WAITING")?(to==="WAITING_APPROVAL"?"work.approval_required":"work.waiting"):"work.state_changed";await this.event(companyId,workId,work.assigneeWorkerId,type,data);return this.getWork(companyId,workId);}
  private async releaseDependants(companyId:string,completedWorkId:string):Promise<void>{const q=await this.storage.query<Row>(`SELECT work_id FROM workforce_dependencies WHERE company_id=? AND depends_on_work_id=?`,[companyId,completedWorkId]);for(const r of q.rows){const id=String(r.work_id),work=await this.getWork(companyId,id);if(work.state==="CREATED"&&await this.depsSatisfied(companyId,id))await this.transition(companyId,id,"READY",{});}}
  private async event(companyId:string,workId:string|null,workerId:string|null,type:string,data:unknown){const event:WorkforceEvent={eventId:randomUUID(),companyId,workId,workerId,type,data,createdAt:now()};await this.storage.query(`INSERT INTO workforce_events(event_id,company_id,work_id,worker_id,type,data_json,created_at) VALUES(?,?,?,?,?,?,?)`,[event.eventId,event.companyId,event.workId,event.workerId,event.type,j(event.data),event.createdAt]);await this.adapters.events?.emit(event);}
}
