import { randomUUID } from "node:crypto";
import type { StorageClient } from "@titan-zero/storage";
import { requireCompanyId } from "@titan-zero/storage";

export const WORK_STATES = ["CREATED","READY","CLAIMED","IN_PROGRESS","BLOCKED","WAITING","WAITING_APPROVAL","WAITING_EXTERNAL","COMPLETED","FAILED","CANCELLED"] as const;
export type WorkState=(typeof WORK_STATES)[number];
export type WorkerKind="digital"|"human";
export type WorkActor={type:"human"|"worker"|"system";id:string};
export interface WorkerInput{workerId:string;kind:WorkerKind;role:string;teamId?:string;managerWorkerId?:string;capabilities?:string[];active?:boolean}
export interface Worker{companyId:string;workerId:string;kind:WorkerKind;role:string;teamId:string|null;managerWorkerId:string|null;capabilities:string[];active:boolean}
export interface WorkInput{objective:string;description?:string;creator:WorkActor;parentWorkId?:string;assigneeWorkerId?:string;teamId?:string;priority?:number;dependencies?:string[];requiredCapabilities?:string[];authorityRequirement?:string;contextRefs?:string[];evidenceRefs?:string[]}
export interface WorkItem{companyId:string;workId:string;parentWorkId:string|null;objective:string;description:string|null;creator:WorkActor;assigneeWorkerId:string|null;teamId:string|null;priority:number;state:WorkState;dependencies:string[];requiredCapabilities:string[];authorityRequirement:string|null;contextRefs:string[];evidenceRefs:string[];result:unknown;waitSignal:string|null;claimOwner:string|null;createdAt:string;updatedAt:string}
export interface WorkforceEvent{eventId:string;companyId:string;workId:string|null;workerId:string|null;type:string;data:unknown;createdAt:string}
export type RuntimeOutcome={outcome:"completed";result?:unknown;evidenceRefs?:string[]}|{outcome:"waiting";waitKind?:"generic"|"approval"|"external";resumeSignal?:string}|{outcome:"failed";error:string};
export interface AgentRuntimeAdapter{run(input:{companyId:string;workerId:string;work:WorkItem}):Promise<RuntimeOutcome>}
export interface WorkforceEventSink{emit(event:WorkforceEvent):Promise<void>|void}
export interface RecurringWorkInput{recurringId:string;schedule:string;template:WorkInput;enabled?:boolean}

type Row=Record<string,unknown>;
const states=(...s:WorkState[])=>new Set<WorkState>(s);
const terminal=states("COMPLETED","FAILED","CANCELLED");
const transitions:Record<WorkState,Set<WorkState>>={
 CREATED:states("READY","CANCELLED","FAILED"), READY:states("CLAIMED","CANCELLED","FAILED","WAITING_APPROVAL"), CLAIMED:states("IN_PROGRESS","READY","CANCELLED","FAILED"),
 IN_PROGRESS:states("BLOCKED","WAITING","WAITING_APPROVAL","WAITING_EXTERNAL","COMPLETED","FAILED","CANCELLED","READY"), BLOCKED:states("READY","FAILED","CANCELLED"),
 WAITING:states("READY","FAILED","CANCELLED"), WAITING_APPROVAL:states("READY","FAILED","CANCELLED"), WAITING_EXTERNAL:states("READY","FAILED","CANCELLED"), COMPLETED:states(),FAILED:states(),CANCELLED:states()
};
const j=(v:unknown)=>JSON.stringify(v??null);
const p=<T>(v:unknown,f:T):T=>{try{return typeof v==="string"?JSON.parse(v) as T:f}catch{return f}};
const stamp=()=>new Date().toISOString();

export class WorkforceService{
 constructor(private readonly storage:StorageClient,private readonly adapters:{runtime?:AgentRuntimeAdapter;events?:WorkforceEventSink}={}){}
 async initialize(){
  await this.storage.query(`CREATE TABLE IF NOT EXISTS workforce_workers(company_id TEXT NOT NULL,worker_id TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN ('digital','human')),role TEXT NOT NULL,team_id TEXT,manager_worker_id TEXT,capabilities_json TEXT NOT NULL DEFAULT '[]',active INTEGER NOT NULL DEFAULT 1,PRIMARY KEY(company_id,worker_id))`);
  await this.storage.query(`CREATE TABLE IF NOT EXISTS workforce_work(company_id TEXT NOT NULL,work_id TEXT NOT NULL,parent_work_id TEXT,objective TEXT NOT NULL,description TEXT,creator_json TEXT NOT NULL,assignee_worker_id TEXT,team_id TEXT,priority INTEGER NOT NULL DEFAULT 50,state TEXT NOT NULL,required_capabilities_json TEXT NOT NULL DEFAULT '[]',authority_requirement TEXT,context_refs_json TEXT NOT NULL DEFAULT '[]',evidence_refs_json TEXT NOT NULL DEFAULT '[]',result_json TEXT,wait_signal TEXT,claim_owner TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(company_id,work_id))`);
  await this.storage.query(`CREATE TABLE IF NOT EXISTS workforce_dependencies(company_id TEXT NOT NULL,work_id TEXT NOT NULL,depends_on_work_id TEXT NOT NULL,PRIMARY KEY(company_id,work_id,depends_on_work_id))`);
  await this.storage.query(`CREATE TABLE IF NOT EXISTS workforce_events(event_id TEXT PRIMARY KEY,company_id TEXT NOT NULL,work_id TEXT,worker_id TEXT,type TEXT NOT NULL,data_json TEXT,created_at TEXT NOT NULL)`);
  await this.storage.query(`CREATE TABLE IF NOT EXISTS workforce_recurring(company_id TEXT NOT NULL,recurring_id TEXT NOT NULL,schedule TEXT NOT NULL,template_json TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,PRIMARY KEY(company_id,recurring_id))`);
  await this.storage.query(`CREATE TABLE IF NOT EXISTS workforce_occurrences(company_id TEXT NOT NULL,recurring_id TEXT NOT NULL,occurrence_key TEXT NOT NULL,work_id TEXT NOT NULL,PRIMARY KEY(company_id,recurring_id,occurrence_key))`);
  await this.storage.query(`CREATE INDEX IF NOT EXISTS idx_workforce_ready ON workforce_work(company_id,state,priority,created_at)`);
 }
 async registerWorker(raw:string,i:WorkerInput):Promise<Worker>{const c=requireCompanyId(raw);if(!i.workerId.trim())throw new Error("worker_id is required");if(i.managerWorkerId)await this.getWorker(c,i.managerWorkerId);await this.storage.query(`INSERT INTO workforce_workers(company_id,worker_id,kind,role,team_id,manager_worker_id,capabilities_json,active) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(company_id,worker_id) DO UPDATE SET kind=excluded.kind,role=excluded.role,team_id=excluded.team_id,manager_worker_id=excluded.manager_worker_id,capabilities_json=excluded.capabilities_json,active=excluded.active`,[c,i.workerId,i.kind,i.role,i.teamId??null,i.managerWorkerId??null,j(i.capabilities??[]),i.active===false?0:1]);return this.getWorker(c,i.workerId)}
 async getWorker(raw:string,id:string):Promise<Worker>{const c=requireCompanyId(raw),q=await this.storage.query<Row>(`SELECT * FROM workforce_workers WHERE company_id=? AND worker_id=?`,[c,id]),r=q.rows[0];if(!r)throw new Error("worker not found");return{companyId:c,workerId:String(r.worker_id),kind:r.kind as WorkerKind,role:String(r.role),teamId:r.team_id?String(r.team_id):null,managerWorkerId:r.manager_worker_id?String(r.manager_worker_id):null,capabilities:p<string[]>(r.capabilities_json,[]),active:Boolean(r.active)}}
 async createWork(raw:string,i:WorkInput):Promise<WorkItem>{const c=requireCompanyId(raw);if(!i.objective?.trim())throw new Error("objective is required");if(i.assigneeWorkerId)await this.getWorker(c,i.assigneeWorkerId);if(i.parentWorkId)await this.getWork(c,i.parentWorkId);const id=randomUUID(),deps=i.dependencies??[],t=stamp();for(const d of deps)await this.getWork(c,d);const state:WorkState=deps.length?"CREATED":"READY";await this.storage.transaction(async tx=>{await tx.query(`INSERT INTO workforce_work(company_id,work_id,parent_work_id,objective,description,creator_json,assignee_worker_id,team_id,priority,state,required_capabilities_json,authority_requirement,context_refs_json,evidence_refs_json,result_json,wait_signal,claim_owner,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[c,id,i.parentWorkId??null,i.objective,i.description??null,j(i.creator),i.assigneeWorkerId??null,i.teamId??null,i.priority??50,state,j(i.requiredCapabilities??[]),i.authorityRequirement??null,j(i.contextRefs??[]),j(i.evidenceRefs??[]),null,null,null,t,t]);for(const d of deps)await tx.query(`INSERT INTO workforce_dependencies(company_id,work_id,depends_on_work_id) VALUES(?,?,?)`,[c,id,d])});await this.event(c,id,i.assigneeWorkerId??null,"work.created",{creator:i.creator});if(state==="READY")await this.event(c,id,i.assigneeWorkerId??null,"work.ready",{});return this.getWork(c,id)}
 async getWork(raw:string,id:string):Promise<WorkItem>{const c=requireCompanyId(raw),q=await this.storage.query<Row>(`SELECT * FROM workforce_work WHERE company_id=? AND work_id=?`,[c,id]),r=q.rows[0];if(!r)throw new Error("work not found");const d=await this.storage.query<Row>(`SELECT depends_on_work_id FROM workforce_dependencies WHERE company_id=? AND work_id=? ORDER BY depends_on_work_id`,[c,id]);return{companyId:c,workId:String(r.work_id),parentWorkId:r.parent_work_id?String(r.parent_work_id):null,objective:String(r.objective),description:r.description?String(r.description):null,creator:p<WorkActor>(r.creator_json,{type:"system",id:"unknown"}),assigneeWorkerId:r.assignee_worker_id?String(r.assignee_worker_id):null,teamId:r.team_id?String(r.team_id):null,priority:Number(r.priority),state:r.state as WorkState,dependencies:d.rows.map(x=>String(x.depends_on_work_id)),requiredCapabilities:p<string[]>(r.required_capabilities_json,[]),authorityRequirement:r.authority_requirement?String(r.authority_requirement):null,contextRefs:p<string[]>(r.context_refs_json,[]),evidenceRefs:p<string[]>(r.evidence_refs_json,[]),result:p(r.result_json,null),waitSignal:r.wait_signal?String(r.wait_signal):null,claimOwner:r.claim_owner?String(r.claim_owner):null,createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
 async addDependency(raw:string,id:string,dep:string){const c=requireCompanyId(raw);await this.getWork(c,id);await this.getWork(c,dep);if(id===dep||await this.reachable(c,dep,id))throw new Error("circular dependency rejected");await this.storage.query(`INSERT OR IGNORE INTO workforce_dependencies(company_id,work_id,depends_on_work_id) VALUES(?,?,?)`,[c,id,dep]);const w=await this.getWork(c,id);if(w.state==="READY")await this.transition(c,id,"CREATED",{},true)}
 private async reachable(c:string,from:string,target:string,seen=new Set<string>()):Promise<boolean>{if(from===target)return true;if(seen.has(from))return false;seen.add(from);const q=await this.storage.query<Row>(`SELECT depends_on_work_id FROM workforce_dependencies WHERE company_id=? AND work_id=?`,[c,from]);for(const r of q.rows)if(await this.reachable(c,String(r.depends_on_work_id),target,seen))return true;return false}
 private async depsSatisfied(c:string,id:string){const q=await this.storage.query<Row>(`SELECT w.state FROM workforce_dependencies d JOIN workforce_work w ON w.company_id=d.company_id AND w.work_id=d.depends_on_work_id WHERE d.company_id=? AND d.work_id=?`,[c,id]);return q.rows.every(r=>r.state==="COMPLETED")}
 async claimWork(raw:string,id:string,workerId:string):Promise<WorkItem>{const c=requireCompanyId(raw),worker=await this.getWorker(c,workerId);if(!worker.active)throw new Error("worker inactive");return this.storage.transaction(async tx=>{const q=await tx.query<Row>(`SELECT state,assignee_worker_id,required_capabilities_json FROM workforce_work WHERE company_id=? AND work_id=?`,[c,id]),r=q.rows[0];if(!r)throw new Error("work not found");if(r.state!=="READY")throw new Error("work is not claimable");if(r.assignee_worker_id&&r.assignee_worker_id!==workerId)throw new Error("work assigned to another worker");const req=p<string[]>(r.required_capabilities_json,[]);if(req.some(x=>!worker.capabilities.includes(x)))throw new Error("worker lacks required capability");const u=await tx.query(`UPDATE workforce_work SET state='CLAIMED',assignee_worker_id=?,claim_owner=?,updated_at=? WHERE company_id=? AND work_id=? AND state='READY'`,[workerId,workerId,stamp(),c,id]);if(u.rowCount!==1)throw new Error("work is not claimable");await this.event(c,id,workerId,"work.claimed",{});return this.getWork(c,id)})}
 async startWork(c:string,id:string,workerId:string){const w=await this.getWork(c,id);if(w.claimOwner!==workerId)throw new Error("claim owner mismatch");return this.transition(c,id,"IN_PROGRESS",{workerId})}
 async completeWork(c:string,id:string,result:unknown,evidence:string[]=[]){const w=await this.getWork(c,id);if(terminal.has(w.state))throw new Error("work already terminal");if(w.state!=="IN_PROGRESS")throw new Error("work must be in progress before completion");const merged=[...new Set([...w.evidenceRefs,...evidence])];await this.transition(c,id,"COMPLETED",{result,evidenceRefs:merged});await this.storage.query(`UPDATE workforce_work SET result_json=?,evidence_refs_json=? WHERE company_id=? AND work_id=?`,[j(result),j(merged),requireCompanyId(c),id]);await this.releaseDependants(requireCompanyId(c),id);return this.getWork(c,id)}
 async failWork(c:string,id:string,error:string){return this.transition(c,id,"FAILED",{error})} async cancelWork(c:string,id:string,reason:string){return this.transition(c,id,"CANCELLED",{reason})} async blockWork(c:string,id:string,reason:string){return this.transition(c,id,"BLOCKED",{reason})}
 async waitWork(c:string,id:string,kind:"generic"|"approval"|"external",signal?:string){const to:WorkState=kind==="approval"?"WAITING_APPROVAL":kind==="external"?"WAITING_EXTERNAL":"WAITING";await this.transition(c,id,to,{signal});await this.storage.query(`UPDATE workforce_work SET wait_signal=? WHERE company_id=? AND work_id=?`,[signal??null,requireCompanyId(c),id]);return this.getWork(c,id)}
 async resumeWork(c:string,id:string,signal?:string){const w=await this.getWork(c,id);if(!["WAITING","WAITING_APPROVAL","WAITING_EXTERNAL","BLOCKED"].includes(w.state))throw new Error("work is not waiting");if(w.waitSignal&&signal!==w.waitSignal)throw new Error("resume signal mismatch");await this.transition(c,id,"READY",{signal});await this.storage.query(`UPDATE workforce_work SET wait_signal=NULL,claim_owner=NULL WHERE company_id=? AND work_id=?`,[requireCompanyId(c),id]);await this.event(requireCompanyId(c),id,w.assigneeWorkerId,"work.resumed",{signal});return this.getWork(c,id)}
 async assignWork(c:string,id:string,workerId:string){await this.getWorker(c,workerId);await this.getWork(c,id);await this.storage.query(`UPDATE workforce_work SET assignee_worker_id=?,updated_at=? WHERE company_id=? AND work_id=?`,[workerId,stamp(),requireCompanyId(c),id]);await this.event(requireCompanyId(c),id,workerId,"work.assigned",{});return this.getWork(c,id)}
 async decomposeWork(c:string,parent:string,managerId:string,children:Array<Omit<WorkInput,"creator"|"parentWorkId">>){const m=await this.getWorker(c,managerId);if(m.kind!=="digital"||!m.capabilities.includes("work.delegate"))throw new Error("worker cannot delegate");await this.getWork(c,parent);const out:WorkItem[]=[];for(const child of children){const w=await this.createWork(c,{...child,parentWorkId:parent,creator:{type:"worker",id:managerId}});await this.event(requireCompanyId(c),w.workId,w.assigneeWorkerId,"work.delegated",{from:managerId,parentWorkId:parent});out.push(w)}return out}
 async escalateWork(c:string,id:string,workerId:string,reason:string){const w=await this.getWorker(c,workerId);if(!w.managerWorkerId)throw new Error("no manager configured for escalation");await this.getWorker(c,w.managerWorkerId);await this.storage.query(`UPDATE workforce_work SET assignee_worker_id=?,claim_owner=NULL,state='READY',updated_at=? WHERE company_id=? AND work_id=?`,[w.managerWorkerId,stamp(),requireCompanyId(c),id]);await this.event(requireCompanyId(c),id,w.managerWorkerId,"work.escalated",{from:workerId,reason});return this.getWork(c,id)}
 async listReady(c:string){const q=await this.storage.query<Row>(`SELECT work_id FROM workforce_work WHERE company_id=? AND state='READY' ORDER BY priority DESC,created_at ASC`,[requireCompanyId(c)]),out:WorkItem[]=[];for(const r of q.rows)out.push(await this.getWork(c,String(r.work_id)));return out}
 async routeByCapability(c:string,required:string[],teamId?:string){const q=await this.storage.query<Row>(`SELECT worker_id FROM workforce_workers WHERE company_id=? AND kind='digital' AND active=1 ${teamId?"AND team_id=?":""} ORDER BY worker_id`,teamId?[requireCompanyId(c),teamId]:[requireCompanyId(c)]),out:Worker[]=[];for(const r of q.rows){const w=await this.getWorker(c,String(r.worker_id));if(required.every(x=>w.capabilities.includes(x)))out.push(w)}return out}
 async dispatchReady(c:string){if(!this.adapters.runtime)return[];const done:string[]=[];for(const work of await this.listReady(c)){let workerId=work.assigneeWorkerId;if(!workerId){const [candidate]=await this.routeByCapability(c,work.requiredCapabilities,work.teamId??undefined);workerId=candidate?.workerId??null}if(!workerId)continue;const worker=await this.getWorker(c,workerId);if(worker.kind!=="digital")continue;await this.claimWork(c,work.workId,workerId);await this.event(requireCompanyId(c),work.workId,workerId,"worker.woken",{});await this.startWork(c,work.workId,workerId);await this.event(requireCompanyId(c),work.workId,workerId,"worker.started",{});try{const current=await this.getWork(c,work.workId),o=await this.adapters.runtime.run({companyId:requireCompanyId(c),workerId,work:current});if(o.outcome==="completed"){await this.completeWork(c,work.workId,o.result,o.evidenceRefs??[]);await this.event(requireCompanyId(c),work.workId,workerId,"worker.completed",{})}else if(o.outcome==="waiting"){await this.waitWork(c,work.workId,o.waitKind??"generic",o.resumeSignal);await this.event(requireCompanyId(c),work.workId,workerId,"worker.waiting",{})}else await this.failWork(c,work.workId,o.error)}catch(e){await this.failWork(c,work.workId,e instanceof Error?e.message:String(e))}done.push(work.workId)}return done}
 async createRecurringWork(c:string,i:RecurringWorkInput){const cid=requireCompanyId(c);await this.storage.query(`INSERT INTO workforce_recurring(company_id,recurring_id,schedule,template_json,enabled) VALUES(?,?,?,?,?) ON CONFLICT(company_id,recurring_id) DO UPDATE SET schedule=excluded.schedule,template_json=excluded.template_json,enabled=excluded.enabled`,[cid,i.recurringId,i.schedule,j(i.template),i.enabled===false?0:1]);return i}
 async activateRecurring(c:string,rid:string,key:string){const cid=requireCompanyId(c),e=await this.storage.query<Row>(`SELECT work_id FROM workforce_occurrences WHERE company_id=? AND recurring_id=? AND occurrence_key=?`,[cid,rid,key]);if(e.rows[0])return this.getWork(cid,String(e.rows[0].work_id));const q=await this.storage.query<Row>(`SELECT template_json,enabled FROM workforce_recurring WHERE company_id=? AND recurring_id=?`,[cid,rid]),r=q.rows[0];if(!r||!r.enabled)throw new Error("recurring work not found or disabled");const w=await this.createWork(cid,p<WorkInput>(r.template_json,{} as WorkInput));await this.storage.query(`INSERT INTO workforce_occurrences(company_id,recurring_id,occurrence_key,work_id) VALUES(?,?,?,?)`,[cid,rid,key,w.workId]);return w}
 async listEvents(c:string,id?:string):Promise<WorkforceEvent[]>{const cid=requireCompanyId(c),q=await this.storage.query<Row>(`SELECT * FROM workforce_events WHERE company_id=? ${id?"AND work_id=?":""} ORDER BY created_at,event_id`,id?[cid,id]:[cid]);return q.rows.map(r=>({eventId:String(r.event_id),companyId:cid,workId:r.work_id?String(r.work_id):null,workerId:r.worker_id?String(r.worker_id):null,type:String(r.type),data:p(r.data_json,null),createdAt:String(r.created_at)}))}
 private async transition(raw:string,id:string,to:WorkState,data:unknown={},force=false){const c=requireCompanyId(raw),w=await this.getWork(c,id);if(!force&&!transitions[w.state].has(to))throw new Error(`invalid work transition ${w.state} -> ${to}`);await this.storage.query(`UPDATE workforce_work SET state=?,updated_at=? WHERE company_id=? AND work_id=?`,[to,stamp(),c,id]);const type=to==="READY"?"work.ready":to==="IN_PROGRESS"?"work.started":to==="COMPLETED"?"work.completed":to==="FAILED"?"work.failed":to==="CANCELLED"?"work.cancelled":to==="BLOCKED"?"work.blocked":to==="WAITING_APPROVAL"?"work.approval_required":to.startsWith("WAITING")?"work.waiting":"work.state_changed";await this.event(c,id,w.assigneeWorkerId,type,data);return this.getWork(c,id)}
 private async releaseDependants(c:string,completed:string){const q=await this.storage.query<Row>(`SELECT work_id FROM workforce_dependencies WHERE company_id=? AND depends_on_work_id=?`,[c,completed]);for(const r of q.rows){const id=String(r.work_id),w=await this.getWork(c,id);if(w.state==="CREATED"&&await this.depsSatisfied(c,id))await this.transition(c,id,"READY",{})}}
 private async event(c:string,id:string|null,workerId:string|null,type:string,data:unknown){const e:WorkforceEvent={eventId:randomUUID(),companyId:c,workId:id,workerId,type,data,createdAt:stamp()};await this.storage.query(`INSERT INTO workforce_events(event_id,company_id,work_id,worker_id,type,data_json,created_at) VALUES(?,?,?,?,?,?,?)`,[e.eventId,e.companyId,e.workId,e.workerId,e.type,j(e.data),e.createdAt]);await this.adapters.events?.emit(e)}
}
