// @ts-nocheck
// Ported from Titan Zero extension (portable-core): titan-workforce/coordination/chief-of-staff-runtime.mjs
const clean=(v,max=180)=>String(v??'').trim().slice(0,max);
const list=v=>Array.isArray(v)?v:[];
const uniq=v=>[...new Set(list(v).map(x=>clean(x)).filter(Boolean))].sort();
const validCompany=v=>/^[A-Za-z0-9._:-]{2,128}$/.test(clean(v,128));
function assertCompany(company_id){if(!validCompany(company_id))throw new Error('chief-of-staff-company_id-required');}
function scoped(records,company_id){return list(records).filter(r=>r?.company_id===company_id);}
function openEscalations(supervisors){const out=[];for(const s of supervisors){for(const e of list(s?.escalations)){if(['closed','resolved'].includes(clean(e?.state,40)))continue;out.push({escalation_id:clean(e?.escalation_id),owner_worker_id:clean(s?.supervisor_worker_id),severity:clean(e?.severity,40)||'normal',target_ref:clean(e?.target_ref)||null,state:clean(e?.state,40)||'open',grants_authority:false});}}return out.sort((a,b)=>a.escalation_id.localeCompare(b.escalation_id));}
function responsibilityMap(supervisors){const map=new Map();for(const s of supervisors){const owner=clean(s?.supervisor_worker_id);for(const id of uniq([...(s?.scope?.subordinate_worker_ids||[]),...(s?.scope?.assignment_ids||[]),...(s?.scope?.mission_teams||[]).map(x=>x.mission_team_id)])){const arr=map.get(id)||[];if(owner&&!arr.includes(owner))arr.push(owner);map.set(id,arr.sort());}}return map;}
export function deriveChiefOfStaffCoordination(input={},graph={},missionTeams=[],supervisorRecords=[]){const company_id=clean(input.company_id,128);assertCompany(company_id);if(graph?.schema!=='titan.workforce.graph.v1'||graph?.company_id!==company_id)throw new Error('chief-of-staff-workforce-graph-required');const supervisors=scoped(supervisorRecords,company_id);const teams=scoped(missionTeams,company_id);const rmap=responsibilityMap(supervisors);const activeTeams=teams.filter(t=>['FORMING','ACTIVE','HANDOVER'].includes(clean(t?.state,40)));
const gaps=[];for(const t of activeTeams){const owners=uniq([t.supervisor_worker_id,t.coordinator_worker_id]);if(!owners.length)gaps.push({kind:'mission_team',ref:clean(t.mission_team_id),reason:'no_supervisor_or_coordinator',grants_authority:false});}
for(const n of list(graph.nodes).filter(n=>['assignment','work_item'].includes(n?.kind))){const ref=clean(String(n.node_id||'').replace(/^(assignment|work_item):/,''));if(ref&&!rmap.has(ref))gaps.push({kind:n.kind,ref,reason:'no_supervisory_owner',grants_authority:false});}
const overlaps=[...rmap.entries()].filter(([,owners])=>owners.length>1).map(([ref,owners])=>({ref,owner_worker_ids:owners,reason:'multiple_supervisory_owners',grants_authority:false})).sort((a,b)=>a.ref.localeCompare(b.ref));
const escalations=openEscalations(supervisors);const priorities=[];for(const e of escalations)priorities.push({kind:'escalation',ref:e.escalation_id,priority:e.severity==='critical'?100:e.severity==='high'?80:60,owner_worker_ids:uniq([e.owner_worker_id]),reason:'open_escalation',grants_authority:false});for(const g of gaps)priorities.push({kind:'responsibility_gap',ref:g.ref,priority:75,owner_worker_ids:[],reason:g.reason,grants_authority:false});for(const o of overlaps)priorities.push({kind:'responsibility_overlap',ref:o.ref,priority:50,owner_worker_ids:o.owner_worker_ids,reason:o.reason,grants_authority:false});priorities.sort((a,b)=>b.priority-a.priority||a.ref.localeCompare(b.ref));
const recommendations=[];for(const g of gaps)recommendations.push({type:'assign_coordination_owner',target_ref:g.ref,rationale:g.reason,requires_governed_proposal:true,grants_authority:false});for(const o of overlaps)recommendations.push({type:'clarify_coordination_owner',target_ref:o.ref,candidate_worker_ids:o.owner_worker_ids,rationale:o.reason,requires_governed_proposal:true,grants_authority:false});
return {schema:'titan.workforce.chief-of-staff.v1',company_id,chief_of_staff_worker_id:clean(input.chief_of_staff_worker_id)||null,supervisor_count:supervisors.length,active_mission_team_count:activeTeams.length,responsibility_gaps:gaps.sort((a,b)=>a.ref.localeCompare(b.ref)),responsibility_overlaps:overlaps,consolidated_escalations:escalations,priorities,recommendations,graph_revision:Number(graph.projection_revision||0),graph_cursor:graph.projection_cursor||null,derived:true,coordination_only:true,chief_of_staff_identity_confers_authority:false,recommendations_execute_automatically:false,grants_authority:false,authority_effect:false};}
export function summarizeChiefOfStaffCoordination(record={}){return {company_id:record.company_id,supervisor_count:Number(record.supervisor_count||0),active_mission_team_count:Number(record.active_mission_team_count||0),gap_count:list(record.responsibility_gaps).length,overlap_count:list(record.responsibility_overlaps).length,open_escalation_count:list(record.consolidated_escalations).length,priority_count:list(record.priorities).length,recommendation_count:list(record.recommendations).length,graph_revision:Number(record.graph_revision||0),grants_authority:false};}
