import assert from 'node:assert/strict'; import test from 'node:test';
import {createCallState,applyCallReceipt,decideCallRetry} from '../../titan-workforce/hierarchy/voice-call-state-runtime.mjs';
const base={company_id:'co-call',call_ref:'call:1',operation_id:'op:1',idempotency_key:'idem:1'};
test('call lifecycle progresses through provider receipts without execution authority',()=>{let s=createCallState(base); for(const [i,state] of ['placing','ringing','connected','ended'].entries()){s=applyCallReceipt(s,{...base,state,provider:'twilio',provider_event_id:`ev:${i}`}); assert.equal(s.state,state); assert.equal(s.execution_permitted,false);} });
test('duplicate provider event is suppressed',()=>{let s=createCallState(base); s=applyCallReceipt(s,{...base,state:'placing',provider_event_id:'ev:1'}); const d=applyCallReceipt(s,{...base,state:'placing',provider_event_id:'ev:1'}); assert.equal(d.receipt_applied,false); assert.equal(d.duplicate_or_stale,true);});
test('uncertain outcome requires reconciliation and blocks redial',()=>{let s=createCallState(base); s=applyCallReceipt(s,{...base,state:'placing',provider_event_id:'ev:1'}); s=applyCallReceipt(s,{...base,state:'uncertain',provider_event_id:'ev:2',reconciliation_required:true}); const r=decideCallRetry({...s,attempts:1,max_attempts:3}); assert.equal(r.retry,false); assert.equal(r.redial_permitted,false); assert.equal(r.reason,'RECONCILIATION_REQUIRED_BEFORE_RETRY');});
test('failed call may retry only with same idempotency key and bounded attempts',()=>{assert.equal(decideCallRetry({state:'failed',idempotency_key:'idem:1',attempts:1,max_attempts:3}).retry,true); assert.equal(decideCallRetry({state:'failed',idempotency_key:'',attempts:1,max_attempts:3}).retry,false); assert.equal(decideCallRetry({state:'failed',idempotency_key:'idem:1',attempts:3,max_attempts:3}).retry,false);});
test('invalid state jump fails closed',()=>{const s=createCallState(base); assert.throws(()=>applyCallReceipt(s,{...base,state:'connected',provider_event_id:'ev:x'}),/transition-invalid/);});
test('terminal call ignores later stale state change',()=>{let s=createCallState(base); s=applyCallReceipt(s,{...base,state:'failed',provider_event_id:'ev:1'}); const late=applyCallReceipt(s,{...base,state:'ringing',provider_event_id:'ev:late'}); assert.equal(late.state,'failed'); assert.equal(late.receipt_applied,false);});
