export type CompanyId = string;
export type WorkId = string;
export type WorkerId = string;

export type WorkerKind = "digital" | "human";
export type WorkState = "CREATED" | "READY" | "CLAIMED" | "IN_PROGRESS" | "BLOCKED" | "WAITING" | "WAITING_APPROVAL" | "WAITING_EXTERNAL" | "COMPLETED" | "FAILED" | "CANCELLED";
export interface WorkforceWorker { company_id: CompanyId; worker_id: WorkerId; kind: WorkerKind; team_id?: string; manager_id?: WorkerId; capabilities: string[]; active: boolean; }
export interface WorkItem { company_id: CompanyId; work_id: WorkId; parent_work_id?: WorkId; objective: string; description?: string; creator: string; assignee?: WorkerId; team_id?: string; priority: number; state: WorkState; dependencies: WorkId[]; required_capabilities: string[]; authority_requirement?: string; context_refs: string[]; evidence_refs: string[]; result?: unknown; escalation?: { reason: string; target?: WorkerId; at: string }; recurrence?: { rule: string; next_at?: string }; lease?: { worker_id: WorkerId; expires_at: string }; created_at: string; updated_at: string; }
export interface WorkforceEvent { company_id: CompanyId; type: `work.${"created"|"ready"|"claimed"|"started"|"delegated"|"blocked"|"waiting"|"escalated"|"approval_required"|"resumed"|"completed"|"failed"|"cancelled"}` | `worker.${"woken"|"started"|"waiting"|"completed"}`; work_id: WorkId; at: string; actor?: string; data?: Record<string, unknown>; }
export interface WorkforceStore { get(companyId: CompanyId, workId: WorkId): Promise<WorkItem | undefined>; put(item: WorkItem): Promise<void>; list(companyId: CompanyId): Promise<WorkItem[]>; appendEvent(event: WorkforceEvent): Promise<void>; }
export interface AgentRuntimeAdapter { wake(input: { company_id: CompanyId; worker_id: WorkerId; work_id: WorkId }): Promise<void>; }
export interface AuthorityAdapter { isSatisfied(input: { company_id: CompanyId; worker_id: WorkerId; requirement: string }): Promise<boolean>; }
const terminal=new Set<WorkState>(["COMPLETED","FAILED","CANCELLED"]);
const transitions:Record<WorkState,ReadonlySet<WorkState>>={CREATED:new Set(["READY","BLOCKED","CANCELLED"]),READY:new Set(["CLAIMED","CANCELLED"]),CLAIMED:new Set(["IN_PROGRESS","READY","CANCELLED"]),IN_PROGRESS:new Set(["BLOCKED","WAITING","WAITING_APPROVAL","WAITING_EXTERNAL","COMPLETED","FAILED","CANCELLED"]),BLOCKED:new Set(["READY","FAILED","CANCELLED"]),WAITING:new Set(["READY","FAILED","CANCELLED"]),WAITING_APPROVAL:new Set(["READY","FAILED","CANCELLED"]),WAITING_EXTERNAL:new Set(["READY","FAILED","CANCELLED"]),COMPLETED:new Set(),FAILED:new Set(),CANCELLED:new Set()};
export class WorkforceService {
 constructor(private store:WorkforceStore,private runtime?:AgentRuntimeAdapter,private authority?:AuthorityAdapter){}
 async create(input:Omit<WorkItem,"state"|"created_at"|"updated_at"|"evidence_refs"|"context_refs">&Partial<Pick<WorkItem,"context_refs"|"evidence_refs">>){const now=new Date().toISOString();const item:WorkItem={...input,state:"CREATED",context_refs:input.context_refs??[],evidence_refs:input.evidence_refs??[],created_at:now,updated_at:now};for(const dep of item.dependencies)await this.assertNoCycle(item.company_id,item.work_id,dep);await this.store.put(item);await this.event(item,"work.created");return this.refreshReadiness(item.company_id,item.work_id);}
 async delegate(companyId:CompanyId,workId:WorkId,assignee:WorkerId,actor:string){const item=await this.require(companyId,workId);if(terminal.has(item.state))throw new Error("terminal work cannot be delegated");item.assignee=assignee;item.updated_at=new Date().toISOString();await this.store.put(item);await this.event(item,"work.delegated",actor,{assignee});return item;}
 async claim(companyId:CompanyId,workId:WorkId,workerId:WorkerId,leaseMs=60000){const item=await this.require(companyId,workId);if(item.state!=="READY")throw new Error(`work is ${item.state}, not READY`);if(item.assignee&&item.assignee!==workerId)throw new Error("work assigned to another worker");if(item.authority_requirement&&this.authority&&!(await this.authority.isSatisfied({company_id:companyId,worker_id:workerId,requirement:item.authority_requirement})))return this.transition(companyId,workId,"WAITING_APPROVAL",workerId);item.assignee=workerId;item.lease={worker_id:workerId,expires_at:new Date(Date.now()+leaseMs).toISOString()};await this.store.put(item);return this.transition(companyId,workId,"CLAIMED",workerId);}
 async start(c:CompanyId,w:WorkId,a:string){return this.transition(c,w,"IN_PROGRESS",a)} async complete(c:CompanyId,w:WorkId,a:string,result?:unknown,evidence:string[]=[]){const i=await this.require(c,w);i.result=result;i.evidence_refs.push(...evidence);await this.store.put(i);const done=await this.transition(c,w,"COMPLETED",a);for(const candidate of await this.store.list(c))if(candidate.dependencies.includes(w))await this.refreshReadiness(c,candidate.work_id);return done} async fail(c:CompanyId,w:WorkId,a:string,result?:unknown){const i=await this.require(c,w);i.result=result;await this.store.put(i);return this.transition(c,w,"FAILED",a)} async cancel(c:CompanyId,w:WorkId,a:string){return this.transition(c,w,"CANCELLED",a)} async wait(c:CompanyId,w:WorkId,a:string,k:"WAITING"|"WAITING_APPROVAL"|"WAITING_EXTERNAL"="WAITING"){return this.transition(c,w,k,a)} async resume(c:CompanyId,w:WorkId,a:string){const i=await this.transition(c,w,"READY",a);await this.event(i,"work.resumed",a);await this.wakeIfDigital(i);return i} async escalate(c:CompanyId,w:WorkId,a:string,reason:string,target?:WorkerId){const i=await this.require(c,w);i.escalation={reason,target,at:new Date().toISOString()};if(target)i.assignee=target;await this.store.put(i);await this.event(i,"work.escalated",a,{reason,target});return i}
 async refreshReadiness(c:CompanyId,w:WorkId){const i=await this.require(c,w);if(terminal.has(i.state)||!["CREATED","BLOCKED"].includes(i.state))return i;const deps=await Promise.all(i.dependencies.map(id=>this.require(c,id)));if(deps.every(d=>d.state==="COMPLETED")){const next=await this.transition(c,w,"READY","system");await this.wakeIfDigital(next);return next}if(i.state==="CREATED")return this.transition(c,w,"BLOCKED","system");return i}
 private async wakeIfDigital(i:WorkItem){if(i.assignee&&this.runtime){await this.runtime.wake({company_id:i.company_id,worker_id:i.assignee,work_id:i.work_id});await this.event(i,"worker.woken","dispatcher")}} private async transition(c:CompanyId,w:WorkId,next:WorkState,a:string){const i=await this.require(c,w);if(!transitions[i.state].has(next))throw new Error(`invalid transition ${i.state} -> ${next}`);i.state=next;i.updated_at=new Date().toISOString();if(next!=="CLAIMED")i.lease=undefined;await this.store.put(i);const suffix:Record<string,string>={READY:"ready",CLAIMED:"claimed",IN_PROGRESS:"started",BLOCKED:"blocked",WAITING:"waiting",WAITING_APPROVAL:"approval_required",WAITING_EXTERNAL:"waiting",COMPLETED:"completed",FAILED:"failed",CANCELLED:"cancelled"};await this.event(i,`work.${suffix[next]}` as WorkforceEvent["type"],a);return i} private async require(c:CompanyId,w:WorkId){const i=await this.store.get(c,w);if(!i)throw new Error("work not found in company");return i} private async assertNoCycle(c:CompanyId,w:WorkId,d:WorkId,seen=new Set<string>()):Promise<void>{if(d===w)throw new Error("circular dependency");if(seen.has(d))return;seen.add(d);const dep=await this.store.get(c,d);if(!dep)throw new Error("dependency not found in company");for(const p of dep.dependencies)await this.assertNoCycle(c,w,p,seen)} private event(i:WorkItem,type:WorkforceEvent["type"],actor?:string,data?:Record<string,unknown>){return this.store.appendEvent({company_id:i.company_id,type,work_id:i.work_id,at:new Date().toISOString(),actor,data})}
}
